INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('BRISTOL','01 Bristol Judge 1','Bristol Judge 1','FEE_PAID');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('BRISTOL','4539 Bristol Judge 2','Bristol Judge 2','SALARIED');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('BRISTOL','54 Bristol Judge 3','Bristol Judge 3','UNKNOWN');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('LEEDS','23 Leeds Judge 2','Leeds Judge 2','SALARIED');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('LEEDS','331 Leeds Judge 1','Leeds Judge 1','FEE_PAID');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('LEEDS','4554 Leeds Judge 3','Leeds Judge 3','UNKNOWN');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('LONDON_CENTRAL','101 LondonCentral Judge 1','LondonCentral Judge 1','FEE_PAID');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('LONDON_CENTRAL','564 LondonCentral Judge 2','LondonCentral Judge 2','SALARIED');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('LONDON_CENTRAL','84 LondonCentral Judge 3','LondonCentral Judge 3','UNKNOWN');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('LONDON_EAST','01 LondonEast Judge 1','LondonEast Judge 1','FEE_PAID');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('LONDON_EAST','4539 LondonEast Judge 2','LondonEast Judge 2','SALARIED');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('LONDON_EAST','54 LondonEast Judge 3','LondonEast Judge 3','UNKNOWN');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('LONDON_SOUTH','01 LondonSouth Judge 1','LondonSouth Judge 1','FEE_PAID');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('LONDON_SOUTH','4539 LondonSouth Judge 2','LondonSouth Judge 2','SALARIED');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('LONDON_SOUTH','54 LondonSouth Judge 3','LondonSouth Judge 3','UNKNOWN');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('MANCHESTER','01 Manchester Judge 1','Manchester Judge 1','FEE_PAID');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('MANCHESTER','4539 Manchester Judge 2','Manchester Judge 2','SALARIED');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('MANCHESTER','54 Manchester Judge 3','Manchester Judge 3','UNKNOWN');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('MIDLANDS_EAST','01 MidlandsEast Judge 1','MidlandsEast Judge 1','FEE_PAID');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('MIDLANDS_EAST','4539 MidlandsEast Judge 2','MidlandsEast Judge 2','SALARIED');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('MIDLANDS_EAST','54 MidlandsEast Judge 3','MidlandsEast Judge 3','UNKNOWN');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('MIDLANDS_WEST','01 MidlandsWest Judge 1','MidlandsWest Judge 1','FEE_PAID');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('MIDLANDS_WEST','4539 MidlandsWest Judge 2','MidlandsWest Judge 2','SALARIED');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('MIDLANDS_WEST','54 MidlandsWest Judge 3','MidlandsWest Judge 3','UNKNOWN');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('NEWCASTLE','01 Newcastle Judge 1','Newcastle Judge 1','FEE_PAID');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('NEWCASTLE','4539 Newcastle Judge 2','Newcastle Judge 2','SALARIED');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('NEWCASTLE','54 Newcastle Judge 3','Newcastle Judge 3','UNKNOWN');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('SCOTLAND','01 Scotland Judge 1','Scotland Judge 1','FEE_PAID');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('SCOTLAND','4539 Scotland Judge 2','Scotland Judge 2','SALARIED');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('SCOTLAND','54 Scotland Judge 3','Scotland Judge 3','UNKNOWN');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('WALES','01 Wales Judge 1','Wales Judge 1','FEE_PAID');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('WALES','4539 Wales Judge 2','Wales Judge 2','SALARIED');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('WALES','54 Wales Judge 3','Wales Judge 3','UNKNOWN');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('WATFORD','01 Watford Judge 1','Watford Judge 1','FEE_PAID');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('WATFORD','4539 Watford Judge 2','Watford Judge 2','SALARIED');
INSERT INTO judge (tribunal_office, code, name, employment_status) VALUES ('WATFORD','54 Watford Judge 3','Watford Judge 3','UNKNOWN');

INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('BRISTOL','CLERK','Bristol Clerk 1','Bristol Clerk 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('BRISTOL','CLERK','Bristol Clerk 2','Bristol Clerk 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('BRISTOL','CLERK','Bristol Clerk 3','Bristol Clerk 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('BRISTOL','EMPLOYEE_MEMBER','Bristol EE Member 1','Bristol EE Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('BRISTOL','EMPLOYEE_MEMBER','Bristol EE Member 2','Bristol EE Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('BRISTOL','EMPLOYEE_MEMBER','Bristol EE Member 3','Bristol EE Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('BRISTOL','EMPLOYER_MEMBER','Bristol ER Member 1','Bristol ER Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('BRISTOL','EMPLOYER_MEMBER','Bristol ER Member 2','Bristol ER Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('BRISTOL','EMPLOYER_MEMBER','Bristol ER Member 3','Bristol ER Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LEEDS','CLERK','Leeds Clerk 1','Leeds Clerk 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LEEDS','CLERK','Leeds Clerk 2','Leeds Clerk 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LEEDS','CLERK','Leeds Clerk 3','Leeds Clerk 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LEEDS','EMPLOYEE_MEMBER','Leeds EE Member 1','Leeds EE Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LEEDS','EMPLOYEE_MEMBER','Leeds EE Member 2','Leeds EE Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LEEDS','EMPLOYEE_MEMBER','Leeds EE Member 3','Leeds EE Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LEEDS','EMPLOYER_MEMBER','Leeds ER Member 1','Leeds ER Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LEEDS','EMPLOYER_MEMBER','Leeds ER Member 2','Leeds ER Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LEEDS','EMPLOYER_MEMBER','Leeds ER Member 3','Leeds ER Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_CENTRAL','CLERK','LondonCentral Clerk 1','LondonCentral Clerk 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_CENTRAL','CLERK','LondonCentral Clerk 2','LondonCentral Clerk 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_CENTRAL','CLERK','LondonCentral Clerk 3','LondonCentral Clerk 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_CENTRAL','EMPLOYEE_MEMBER','LondonCentral EE Member 1','LondonCentral EE Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_CENTRAL','EMPLOYEE_MEMBER','LondonCentral EE Member 2','LondonCentral EE Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_CENTRAL','EMPLOYEE_MEMBER','LondonCentral EE Member 3','LondonCentral EE Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_CENTRAL','EMPLOYER_MEMBER','LondonCentral ER Member 1','LondonCentral ER Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_CENTRAL','EMPLOYER_MEMBER','LondonCentral ER Member 2','LondonCentral ER Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_CENTRAL','EMPLOYER_MEMBER','LondonCentral ER Member 3','LondonCentral ER Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_EAST','CLERK','LondonEast Clerk 1','LondonEast Clerk 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_EAST','CLERK','LondonEast Clerk 2','LondonEast Clerk 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_EAST','CLERK','LondonEast Clerk 3','LondonEast Clerk 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_EAST','EMPLOYEE_MEMBER','LondonEast EE Member 1','LondonEast EE Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_EAST','EMPLOYEE_MEMBER','LondonEast EE Member 2','LondonEast EE Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_EAST','EMPLOYEE_MEMBER','LondonEast EE Member 3','LondonEast EE Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_EAST','EMPLOYER_MEMBER','LondonEast ER Member 1','LondonEast ER Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_EAST','EMPLOYER_MEMBER','LondonEast ER Member 2','LondonEast ER Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_EAST','EMPLOYER_MEMBER','LondonEast ER Member 3','LondonEast ER Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_SOUTH','CLERK','LondonSouth Clerk 1','LondonSouth Clerk 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_SOUTH','CLERK','LondonSouth Clerk 2','LondonSouth Clerk 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_SOUTH','CLERK','LondonSouth Clerk 3','LondonSouth Clerk 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_SOUTH','EMPLOYEE_MEMBER','LondonSouth EE Member 1','LondonSouth EE Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_SOUTH','EMPLOYEE_MEMBER','LondonSouth EE Member 2','LondonSouth EE Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_SOUTH','EMPLOYEE_MEMBER','LondonSouth EE Member 3','LondonSouth EE Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_SOUTH','EMPLOYER_MEMBER','LondonSouth ER Member 1','LondonSouth ER Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_SOUTH','EMPLOYER_MEMBER','LondonSouth ER Member 2','LondonSouth ER Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('LONDON_SOUTH','EMPLOYER_MEMBER','LondonSouth ER Member 3','LondonSouth ER Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MANCHESTER','CLERK','Manchester Clerk 1','Manchester Clerk 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MANCHESTER','CLERK','Manchester Clerk 2','Manchester Clerk 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MANCHESTER','CLERK','Manchester Clerk 3','Manchester Clerk 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MANCHESTER','EMPLOYEE_MEMBER','Manchester EE Member 1','Manchester EE Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MANCHESTER','EMPLOYEE_MEMBER','Manchester EE Member 2','Manchester EE Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MANCHESTER','EMPLOYEE_MEMBER','Manchester EE Member 3','Manchester EE Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MANCHESTER','EMPLOYER_MEMBER','Manchester ER Member 1','Manchester ER Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MANCHESTER','EMPLOYER_MEMBER','Manchester ER Member 2','Manchester ER Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MANCHESTER','EMPLOYER_MEMBER','Manchester ER Member 3','Manchester ER Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_EAST','CLERK','MidlandsEast Clerk 1','MidlandsEast Clerk 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_EAST','CLERK','MidlandsEast Clerk 2','MidlandsEast Clerk 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_EAST','CLERK','MidlandsEast Clerk 3','MidlandsEast Clerk 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_EAST','EMPLOYEE_MEMBER','MidlandsEast EE Member 1','MidlandsEast EE Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_EAST','EMPLOYEE_MEMBER','MidlandsEast EE Member 2','MidlandsEast EE Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_EAST','EMPLOYEE_MEMBER','MidlandsEast EE Member 3','MidlandsEast EE Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_EAST','EMPLOYER_MEMBER','MidlandsEast ER Member 1','MidlandsEast ER Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_EAST','EMPLOYER_MEMBER','MidlandsEast ER Member 2','MidlandsEast ER Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_EAST','EMPLOYER_MEMBER','MidlandsEast ER Member 3','MidlandsEast ER Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_WEST','CLERK','MidlandsWest Clerk 1','MidlandsWest Clerk 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_WEST','CLERK','MidlandsWest Clerk 2','MidlandsWest Clerk 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_WEST','CLERK','MidlandsWest Clerk 3','MidlandsWest Clerk 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_WEST','EMPLOYEE_MEMBER','MidlandsWest EE Member 1','MidlandsWest EE Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_WEST','EMPLOYEE_MEMBER','MidlandsWest EE Member 2','MidlandsWest EE Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_WEST','EMPLOYEE_MEMBER','MidlandsWest EE Member 3','MidlandsWest EE Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_WEST','EMPLOYER_MEMBER','MidlandsWest ER Member 1','MidlandsWest ER Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_WEST','EMPLOYER_MEMBER','MidlandsWest ER Member 2','MidlandsWest ER Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('MIDLANDS_WEST','EMPLOYER_MEMBER','MidlandsWest ER Member 3','MidlandsWest ER Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('NEWCASTLE','CLERK','Newcastle Clerk 1','Newcastle Clerk 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('NEWCASTLE','CLERK','Newcastle Clerk 2','Newcastle Clerk 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('NEWCASTLE','CLERK','Newcastle Clerk 3','Newcastle Clerk 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('NEWCASTLE','EMPLOYEE_MEMBER','Newcastle EE Member 1','Newcastle EE Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('NEWCASTLE','EMPLOYEE_MEMBER','Newcastle EE Member 2','Newcastle EE Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('NEWCASTLE','EMPLOYEE_MEMBER','Newcastle EE Member 3','Newcastle EE Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('NEWCASTLE','EMPLOYER_MEMBER','Newcastle ER Member 1','Newcastle ER Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('NEWCASTLE','EMPLOYER_MEMBER','Newcastle ER Member 2','Newcastle ER Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('NEWCASTLE','EMPLOYER_MEMBER','Newcastle ER Member 3','Newcastle ER Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('SCOTLAND','CLERK','Scotland Clerk 1','Scotland Clerk 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('SCOTLAND','CLERK','Scotland Clerk 2','Scotland Clerk 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('SCOTLAND','CLERK','Scotland Clerk 3','Scotland Clerk 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('SCOTLAND','EMPLOYEE_MEMBER','Scotland EE Member 1','Scotland EE Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('SCOTLAND','EMPLOYEE_MEMBER','Scotland EE Member 2','Scotland EE Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('SCOTLAND','EMPLOYEE_MEMBER','Scotland EE Member 3','Scotland EE Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('SCOTLAND','EMPLOYER_MEMBER','Scotland ER Member 1','Scotland ER Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('SCOTLAND','EMPLOYER_MEMBER','Scotland ER Member 2','Scotland ER Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('SCOTLAND','EMPLOYER_MEMBER','Scotland ER Member 3','Scotland ER Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WALES','CLERK','Wales Clerk 1','Wales Clerk 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WALES','CLERK','Wales Clerk 2','Wales Clerk 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WALES','CLERK','Wales Clerk 3','Wales Clerk 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WALES','EMPLOYEE_MEMBER','Wales EE Member 1','Wales EE Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WALES','EMPLOYEE_MEMBER','Wales EE Member 2','Wales EE Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WALES','EMPLOYEE_MEMBER','Wales EE Member 3','Wales EE Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WALES','EMPLOYER_MEMBER','Wales ER Member 1','Wales ER Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WALES','EMPLOYER_MEMBER','Wales ER Member 2','Wales ER Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WALES','EMPLOYER_MEMBER','Wales ER Member 3','Wales ER Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WATFORD','CLERK','Watford Clerk 1','Watford Clerk 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WATFORD','CLERK','Watford Clerk 2','Watford Clerk 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WATFORD','CLERK','Watford Clerk 3','Watford Clerk 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WATFORD','EMPLOYEE_MEMBER','Watford EE Member 1','Watford EE Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WATFORD','EMPLOYEE_MEMBER','Watford EE Member 2','Watford EE Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WATFORD','EMPLOYEE_MEMBER','Watford EE Member 3','Watford EE Member 3');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WATFORD','EMPLOYER_MEMBER','Watford ER Member 1','Watford ER Member 1');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WATFORD','EMPLOYER_MEMBER','Watford ER Member 2','Watford ER Member 2');
INSERT INTO court_worker (tribunal_office, type, code, name) VALUES ('WATFORD','EMPLOYER_MEMBER','Watford ER Member 3','Watford ER Member 3');

INSERT INTO file_location (tribunal_office, code, name) VALUES ('ABERDEEN','Aberdeen File Location 1','Aberdeen File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('ABERDEEN','Aberdeen File Location 2','Aberdeen File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('ABERDEEN','Aberdeen File Location 3','Aberdeen File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('BRISTOL','Bristol File Location 1','Bristol File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('BRISTOL','Bristol File Location 2','Bristol File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('BRISTOL','Bristol File Location 3','Bristol File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('DUNDEE','Dundee File Location 1','Dundee File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('DUNDEE','Dundee File Location 2','Dundee File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('DUNDEE','Dundee File Location 3','Dundee File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('EDINBURGH','Edinburgh File Location 1','Edinburgh File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('EDINBURGH','Edinburgh File Location 2','Edinburgh File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('EDINBURGH','Edinburgh File Location 3','Edinburgh File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('GLASGOW','Glasgow File Location 1','Glasgow File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('GLASGOW','Glasgow File Location 2','Glasgow File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('GLASGOW','Glasgow File Location 3','Glasgow File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('LEEDS','Leeds File Location 1','Leeds File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('LEEDS','Leeds File Location 2','Leeds File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('LEEDS','Leeds File Location 3','Leeds File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('LONDON_CENTRAL','London Central File Location 1','London Central File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('LONDON_CENTRAL','London Central File Location 2','London Central File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('LONDON_CENTRAL','London Central File Location 3','London Central File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('LONDON_CENTRAL','London Central File Location 1','London Central File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('LONDON_CENTRAL','London Central File Location 2','London Central File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('LONDON_CENTRAL','London Central File Location 3','London Central File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('LONDON_SOUTH','London South File Location 1','London South File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('LONDON_SOUTH','London South File Location 2','London South File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('LONDON_SOUTH','London South File Location 3','London South File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('MANCHESTER','Manchester File Location 1','Manchester File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('MANCHESTER','Manchester File Location 2','Manchester File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('MANCHESTER','Manchester File Location 3','Manchester File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('MIDLANDS_EAST','Midlands East File Location 1','Midlands East File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('MIDLANDS_EAST','Midlands East File Location 2','Midlands East File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('MIDLANDS_EAST','Midlands East File Location 3','Midlands East File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('MIDLANDS_WEST','Midlands West File Location 1','Midlands West File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('MIDLANDS_WEST','Midlands West File Location 2','Midlands West File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('MIDLANDS_WEST','Midlands West File Location 3','Midlands West File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('NEWCASTLE','Newcastle File Location 1','Newcastle File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('NEWCASTLE','Newcastle File Location 2','Newcastle File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('NEWCASTLE','Newcastle File Location 3','Newcastle File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('WALES','Wales File Location 1','Wales File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('WALES','Wales File Location 2','Wales File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('WALES','Wales File Location 3','Wales File Location 3');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('WATFORD','Watford File Location 1','Watford File Location 1');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('WATFORD','Watford File Location 2','Watford File Location 2');
INSERT INTO file_location (tribunal_office, code, name) VALUES ('WATFORD','Watford File Location 3','Watford File Location 3');

INSERT INTO venue (tribunal_office, code, name) VALUES ('ABERDEEN','Aberdeen','Aberdeen');
INSERT INTO venue (tribunal_office, code, name) VALUES ('ABERDEEN','I J C','I J C');
INSERT INTO venue (tribunal_office, code, name) VALUES ('ABERDEEN','Inverness','Inverness');
INSERT INTO venue (tribunal_office, code, name) VALUES ('ABERDEEN','Kirkwall','Kirkwall');
INSERT INTO venue (tribunal_office, code, name) VALUES ('ABERDEEN','Lerwick','Lerwick');
INSERT INTO venue (tribunal_office, code, name) VALUES ('ABERDEEN','Portree','Portree');
INSERT INTO venue (tribunal_office, code, name) VALUES ('ABERDEEN','Shetland','Shetland');
INSERT INTO venue (tribunal_office, code, name) VALUES ('ABERDEEN','Stornoway','Stornoway');
INSERT INTO venue (tribunal_office, code, name) VALUES ('ABERDEEN','Wick','Wick');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Barnstaple','Barnstaple');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bath Law Courts','Bath Law Courts');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bodmin','Bodmin');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bournemouth MC','Bournemouth MC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Brighton','Brighton');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Brighton CC','Brighton CC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bristol','Bristol');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bristol 1','Bristol 1');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bristol 2','Bristol 2');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bristol 3','Bristol 3');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bristol 4','Bristol 4');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bristol 5','Bristol 5');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bristol 6','Bristol 6');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bristol CFJC','Bristol CFJC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','BristolCityHall','BristolCityHall');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bristol Crown','Bristol Crown');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bristol Mags','Bristol Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bristol TBC','Bristol TBC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Bristol Vintry','Bristol Vintry');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Cardiff CFJC','Cardiff CFJC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Exeter','Exeter');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Exeter Combined','Exeter Combined');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Exeter Mags','Exeter Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Floating Case','Floating Case');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Gloucester CCFC','Gloucester CCFC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Havant','Havant');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Plymouth Mags','Plymouth Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Plym St Cath Ho','Plym St Cath Ho');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Queensway House','Queensway House');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Remote Hearing','Remote Hearing');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','ROIT','ROIT');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Southampton','Southampton');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Swindon','Swindon');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Swindon2','Swindon2');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Taunton','Taunton');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Truro','Truro');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Truro Mags','Truro Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','UWE Bristol','UWE Bristol');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Vintry House','Vintry House');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Worle','Worle');
INSERT INTO venue (tribunal_office, code, name) VALUES ('BRISTOL','Yeovil Mags','Yeovil Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('DUNDEE','Dundee','Dundee');
INSERT INTO venue (tribunal_office, code, name) VALUES ('DUNDEE','Tribunal','Tribunal');
INSERT INTO venue (tribunal_office, code, name) VALUES ('EDINBURGH','Edinburgh','Edinburgh');
INSERT INTO venue (tribunal_office, code, name) VALUES ('EDINBURGH','OET Scotland','OET Scotland');
INSERT INTO venue (tribunal_office, code, name) VALUES ('GLASGOW','Cambeltown HC','Cambeltown Sheriff Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('GLASGOW','Dumfries HC','Dumfries Sheriff Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('GLASGOW','Fort William SC','Fort William Sheriff Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('GLASGOW','Glasgow COET','Glasgow COET');
INSERT INTO venue (tribunal_office, code, name) VALUES ('GLASGOW','GTC','GTC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('GLASGOW','Kirkcudbright','Kirkcudbright Sheriff Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('GLASGOW','Lochmaddy HC','Lochmaddy Sheriff Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('GLASGOW','Oban HC','Oban Sheriff court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('GLASGOW','Portree HC','Portree Sheriff Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('GLASGOW','Stirling SC','Stirling Sheriff Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('GLASGOW','Stornoway HC','Stornoway Sheriff Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('GLASGOW','Stranraer HC','Stranraer Sheriff Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LEEDS','Harrogate CJC','Harrogate CJC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LEEDS','Hull','Hull');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LEEDS','Hull Combined Court Centre','Hull Combined Court Centre');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LEEDS','IAC','IAC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LEEDS','Leeds','Leeds');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LEEDS','Scarborough','Scarborough');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LEEDS','Sheffield Combi','Sheffield Combined Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LEEDS','Teesside ET','Teesside ET');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LEEDS','Wakefield Count','Wakefield Civil and Family Justice Centre');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LONDON_CENTRAL','Field House','Field House');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LONDON_CENTRAL','Fox Court rm 1','Fox Court rm 1');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LONDON_CENTRAL','London Central','London Central');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LONDON_CENTRAL','RCJ','RCJ');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LONDON_EAST','Colchester','Colchester');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LONDON_EAST','East London','East London');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LONDON_EAST','Stratford','Stratford');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LONDON_EAST','Woburn Place','Woburn Place');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LONDON_SOUTH','Ashford','Ashford');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LONDON_SOUTH','Croydon','Croydon');
INSERT INTO venue (tribunal_office, code, name) VALUES ('LONDON_SOUTH','London','z London');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Barrow','Barrow');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Blackpool Mags','Blackpool Magistrates'' Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Burnley Court','Burnley Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Carlisle C C','Carlisle Combined Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Carlisle Mags','Carlisle Magistrates'' Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Crown Court','Crown Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Fleetwood','Fleetwood');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Kendal','Kendal');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Lancaster','Lancaster');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Leeds','Leeds');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Liverpool','Liverpool');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Manchester','Manchester');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Manchester IA','Manchester IA');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Manchester Mags','Manchester Magistrates'' Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','Minshull Street','Minshull Street');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','St. Helens','St. Helens');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MANCHESTER','The Lowry','The Lowry');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MIDLANDS_WEST','BCJC','BCJC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MIDLANDS_WEST','Birmingham CCT','Birmingham CCT');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MIDLANDS_WEST','Bury St Edmunds','Bury St Edmunds');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MIDLANDS_WEST','Cambridge','Cambridge');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MIDLANDS_WEST','Hereford Court','Hereford Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MIDLANDS_WEST','Leicester','Leicester');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MIDLANDS_WEST','Stoke','Stoke');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MIDLANDS_WEST','STOKE (Hanley)','Stoke (Hanley)');
INSERT INTO venue (tribunal_office, code, name) VALUES ('MIDLANDS_WEST','Telford','Telford');
INSERT INTO venue (tribunal_office, code, name) VALUES ('NEWCASTLE','Carlisle','Carlisle');
INSERT INTO venue (tribunal_office, code, name) VALUES ('NEWCASTLE','Kendal Mags','Kendal Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('NEWCASTLE','Kings Court','Kings Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('NEWCASTLE','Leeds ET','Leeds ET');
INSERT INTO venue (tribunal_office, code, name) VALUES ('NEWCASTLE','London South ET','London South ET');
INSERT INTO venue (tribunal_office, code, name) VALUES ('NEWCASTLE','Manorview','z Manorview');
INSERT INTO venue (tribunal_office, code, name) VALUES ('NEWCASTLE','Middlesbrough','Middlesbrough');
INSERT INTO venue (tribunal_office, code, name) VALUES ('NEWCASTLE','Newcastle CFT','Newcastle CFT');
INSERT INTO venue (tribunal_office, code, name) VALUES ('NEWCASTLE','Newcastle ET','Newcastle ET');
INSERT INTO venue (tribunal_office, code, name) VALUES ('NEWCASTLE','Teesside Mags','Teesside Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('NEWCASTLE','Whitby','Whitby');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Abergele','Abergele');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Aberystwyth CC','Aberystwyth CC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Aberystwyth JC','Aberystwyth JC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Aberystwyth Mag','Aberystwyth Mag');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Brecon Court','z Brecon Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Caernarfon CC','Caernarfon CC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Caernarfon CJC','Caernarfon CJC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','CARDIFF','z CARDIFF');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Cardiff CJC','Cardiff CJC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Cardiff Crown','Cardiff Crown');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Cardiff Mags','Cardiff Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Cardiff Mag YC1','Cardiff Mag YC1');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Cardiff Mag YC2','Cardiff Mag YC2');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Cardiff Social','z Cardiff Social');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Cardiff SSCS','Cardiff SSCS');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Cardiff SSCSA','Cardiff SSCSA');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Carmarthen','Carmarthen');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Carmarthen CC','Carmarthen CC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','CARMARTHEN DC','CARMARTHEN DC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Carmarthen HH','Carmarthen HH');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Chester County','z Chester County');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Chester Mags','z Chester Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Denbigh Mags','z Denbigh Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Dolgellau Court','z Dolgellau Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Flint Mags','z Flint Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','GOWERTON','z GOWERTON');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Haverfordwest','Haverfordwest');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','HaverfordwestCC','HaverfordwestCC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Haverfordwest M','Haverfordwest M');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Hereford','z Hereford');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Hereford CC','z Hereford CC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Holyhead Mags','z Holyhead Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','LEDBURY','z LEDBURY');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Llandrindod','z Llandrindod');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Llandrindod W','z Llandrindod W');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Llandudno Mags','Llandudno Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Llanelli County','Llanelli County');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Llanelli Mags','Llanelli Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Llangefni Court','Llangefni Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Llangefni Mags','Llangefni Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Manchester ET','Manchester ET');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Mold','Mold');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Mold Court','Mold Court');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Neath','z Neath');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Neath Mags','z Neath Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Newport','Newport');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Newport AIT','Newport AIT');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','ORIEL HOUSE','z ORIEL HOUSE');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Pontypridd','Pontypridd');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Port Talbot','Port Talbot');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Prestatyn JC','Prestatyn JC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Shrewsbury','Shrewsbury');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','SWAN.MAG COURT','z SWAN.MAG COURT');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Swansea','Swansea');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Swansea CJ','Swansea CJ');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','SWANSEA CROWN C','SWANSEA CROWN C');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Swansea Mags','Swansea Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Swansea Sage','z Swansea Sage');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','SW AREA TRAFFIC','z SW AREA TRAFFIC');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Towyn & Kinmel','z Towyn & Kinmel');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Tribunalservice','z Tribunalservice');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Wales','Wales');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Welshpool Mags','Welshpool Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','With Georgia','z With Georgia');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Wrexham Courts','Wrexham Courts');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WALES','Wrexham SSCSA','Wrexham SSCSA');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','Amersham','Amersham');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','Aylesbury Crown','Aylesbury Crown');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','Bedford','Bedford');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','Bedford Mags','Bedford Mags');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','Bury St Edmunds','Bury St Edmunds');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','Cambridge','Cambridge');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','Huntingdon','Huntingdon');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','London Central','London Central');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','Milton Keynes','Milton Keynes');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','Norwich','Norwich');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','Peterborough','Peterborough');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','Reading ET','Reading ET');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','Transfer Team 3','Transfer Team 3');
INSERT INTO venue (tribunal_office, code, name) VALUES ('WATFORD','Watford','Watford');

INSERT INTO room (code, name, venue_code) VALUES ('1','1','Aberdeen');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Aberdeen');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Aberdeen');
INSERT INTO room (code, name, venue_code) VALUES ('Judges Own Room','Judges Own Room','Aberdeen');
INSERT INTO room (code, name, venue_code) VALUES ('Abergele','Abergele','Abergele');
INSERT INTO room (code, name, venue_code) VALUES ('Aberystwyth CC','Aberystwyth CC','Aberystwyth CC');
INSERT INTO room (code, name, venue_code) VALUES ('Aberystwyth JC','Aberystwyth JC','Aberystwyth JC');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Aberystwyth Mag');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','Amersham');
INSERT INTO room (code, name, venue_code) VALUES ('5','5','Amersham');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Ashford');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Ashford');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Ashford');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','Ashford');
INSERT INTO room (code, name, venue_code) VALUES ('5','5','Ashford');
INSERT INTO room (code, name, venue_code) VALUES ('6','6','Ashford');
INSERT INTO room (code, name, venue_code) VALUES ('7','7','Ashford');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Ashford');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Aylesbury Crown');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Barnstaple');
INSERT INTO room (code, name, venue_code) VALUES ('Bath Law Courts','Bath Law Courts','Bath Law Courts');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bath Law Courts');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','BCJC');
INSERT INTO room (code, name, venue_code) VALUES ('11','11','Bedford');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('10 Floor 14th','10 Floor 14th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('11 Floor 14th','11 Floor 14th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('12 Floor 14th','12 Floor 14th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('13 Floor 14th','13 Floor 14th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('14 Floor 14th','14 Floor 14th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('15 Floor 14th','15 Floor 14th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('16 Floor 14th','16 Floor 14th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('1 Floor 13th','1 Floor 13th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('2 Floor 13th','2 Floor 13th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('3 Floor 13th','3 Floor 13th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('4 Floor 13th','4 Floor 13th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('5 Floor 13th','5 Floor 13th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('6 Floor 13th','6 Floor 13th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('7 Floor 13th','7 Floor 13th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('8 Floor 13th','8 Floor 13th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('9 Floor 14th','9 Floor 14th','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('9th Floor','9th Floor','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Birmingham CCT');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Blackpool Mags');
INSERT INTO room (code, name, venue_code) VALUES ('5','5','Blackpool Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Bodmin 2','Bodmin 2','Bodmin');
INSERT INTO room (code, name, venue_code) VALUES ('Bodmin 3','Bodmin 3','Bodmin');
INSERT INTO room (code, name, venue_code) VALUES ('Bodmin NA','Bodmin NA','Bodmin');
INSERT INTO room (code, name, venue_code) VALUES ('Bodmin Office','Bodmin Office','Bodmin');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bodmin');
INSERT INTO room (code, name, venue_code) VALUES ('Bournemouth Mags 1','Bournemouth Mags 1','Bournemouth MC');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bournemouth MC');
INSERT INTO room (code, name, venue_code) VALUES ('Brecon','Brecon','Brecon Court');
INSERT INTO room (code, name, venue_code) VALUES ('Brighton SDFC','Brighton SDFC','Brighton');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Brighton');
INSERT INTO room (code, name, venue_code) VALUES ('Court 2','Court 2','Brighton CC');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Brighton CC');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bristol');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bristol 1');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bristol 2');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bristol 3');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bristol 4');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bristol 5');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bristol 6');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC 1','Bristol CFJC 1','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC 10','Bristol CFJC 10','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC 11','Bristol CFJC 11','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC 12','Bristol CFJC 12','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC 13','Bristol CFJC 13','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC 14','Bristol CFJC 14','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC 15','Bristol CFJC 15','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC 17','Bristol CFJC 17','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC 19','Bristol CFJC 19','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC 6','Bristol CFJC 6','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC 7','Bristol CFJC 7','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC 8','Bristol CFJC 8','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC 9','Bristol CFJC 9','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC NA','Bristol CFJC NA','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC Office','Bristol CFJC Office','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol home','Bristol home','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('CFJC Mediation Rooms','CFJC Mediation Rooms','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('CVP Room','CVP Room','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('CVP + Room','CVP + Room','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('VHS Room','VHS Room','Bristol CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('City Hall 1','City Hall 1','BristolCityHall');
INSERT INTO room (code, name, venue_code) VALUES ('City Hall 2','City Hall 2','BristolCityHall');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','BristolCityHall');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Crown 10','Bristol Crown 10','Bristol Crown');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Crown 2','Bristol Crown 2','Bristol Crown');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Crown 4','Bristol Crown 4','Bristol Crown');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Crown 5','Bristol Crown 5','Bristol Crown');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Crown 8','Bristol Crown 8','Bristol Crown');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Crown Office','Bristol Crown Office','Bristol Crown');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bristol Crown');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Bristol Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Mags 10','Bristol Mags 10','Bristol Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Mags 11','Bristol Mags 11','Bristol Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Mags 12','Bristol Mags 12','Bristol Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Mags 9','Bristol Mags 9','Bristol Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Mags Court 3','Bristol Mags Court 3','Bristol Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Mags Court 6','Bristol Mags Court 6','Bristol Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Mags Court 7','Bristol Mags Court 7','Bristol Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol TBC','Bristol TBC','Bristol TBC');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bristol TBC');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol 2','Bristol 2','Bristol Vintry');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol 3','Bristol 3','Bristol Vintry');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol 4','Bristol 4','Bristol Vintry');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC Court 4','Bristol CFJC Court 4','Bristol Vintry');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol CFJC Court 5','Bristol CFJC Court 5','Bristol Vintry');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol NA','Bristol NA','Bristol Vintry');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Office','Bristol Office','Bristol Vintry');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Vintry 1','Bristol Vintry 1','Bristol Vintry');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Vintry 2','Bristol Vintry 2','Bristol Vintry');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Vintry 3','Bristol Vintry 3','Bristol Vintry');
INSERT INTO room (code, name, venue_code) VALUES ('Bristol Vintry 4','Bristol Vintry 4','Bristol Vintry');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bristol Vintry');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Bury St Edmunds');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bury St Edmunds');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Bury St Edmunds');
INSERT INTO room (code, name, venue_code) VALUES ('Caernarfon CC','Caernarfon CC','Caernarfon CC');
INSERT INTO room (code, name, venue_code) VALUES ('Caernarfon CJC','Caernarfon CJC','Caernarfon CJC');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Cambeltown HC');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Cambridge');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','Cambridge');
INSERT INTO room (code, name, venue_code) VALUES ('5','5','Cambridge');
INSERT INTO room (code, name, venue_code) VALUES ('6','6','Cambridge');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Cambridge');
INSERT INTO room (code, name, venue_code) VALUES ('mags','mags','CARDIFF');
INSERT INTO room (code, name, venue_code) VALUES ('Cardiff CFJC','Cardiff CFJC','Cardiff CFJC');
INSERT INTO room (code, name, venue_code) VALUES ('17','17','Cardiff CJC');
INSERT INTO room (code, name, venue_code) VALUES ('Court','Court','Cardiff CJC');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Cardiff Crown');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','Cardiff Crown');
INSERT INTO room (code, name, venue_code) VALUES ('5','5','Cardiff Crown');
INSERT INTO room (code, name, venue_code) VALUES ('6','6','Cardiff Crown');
INSERT INTO room (code, name, venue_code) VALUES ('8','8','Cardiff Crown');
INSERT INTO room (code, name, venue_code) VALUES ('9','9','Cardiff Crown');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Cardiff Mags');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Cardiff Mags');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Cardiff Mags');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','Cardiff Mags');
INSERT INTO room (code, name, venue_code) VALUES ('6','6','Cardiff Mags');
INSERT INTO room (code, name, venue_code) VALUES ('YC1','YC1','Cardiff Mag YC1');
INSERT INTO room (code, name, venue_code) VALUES ('YC2','YC2','Cardiff Mag YC2');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Cardiff Social');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Cardiff SSCS');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Carlisle');
INSERT INTO room (code, name, venue_code) VALUES ('5','5','Carlisle C C');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Carlisle Mags');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Carlisle Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Flemming','Flemming','Carmarthen');
INSERT INTO room (code, name, venue_code) VALUES ('Taff','Taff','Carmarthen');
INSERT INTO room (code, name, venue_code) VALUES ('Carm CC','Carm CC','CARMARTHEN CC');
INSERT INTO room (code, name, venue_code) VALUES ('Court','Court','CARMARTHEN CC');
INSERT INTO room (code, name, venue_code) VALUES ('10','10','CARMARTHEN DC');
INSERT INTO room (code, name, venue_code) VALUES ('Carmarthen HH','Carmarthen HH','CARMARTHEN HH');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers','Chambers','CARMARTHEN HH');
INSERT INTO room (code, name, venue_code) VALUES ('Chester County','Chester County','Chester County');
INSERT INTO room (code, name, venue_code) VALUES ('Chester Mags','Chester Mags','Chester Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Court 1','Court 1','Colchester');
INSERT INTO room (code, name, venue_code) VALUES ('Court 2','Court 2','Colchester');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Colchester');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Crown Court');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Crown Court');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','Crown Court');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('10','10','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('11','11','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('12','12','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('13','13','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('14','14','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('15','15','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('5','5','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('6','6','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('7','7','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('8','8','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('9','9','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('Chairmans room','Chairmans room','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Croydon');
INSERT INTO room (code, name, venue_code) VALUES ('Denbigh Mags','Denbigh Mags','Denbigh Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Dolgellau','Dolgellau','Dolgellau Court');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Dumfries HC');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Dundee');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Dundee');
INSERT INTO room (code, name, venue_code) VALUES ('Judges Own Room','Judges Own Room','Dundee');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','DUNDEE');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','DUNDEE');
INSERT INTO room (code, name, venue_code) VALUES ('Judges Own Room','Judges Own Room','DUNDEE');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','East London');
INSERT INTO room (code, name, venue_code) VALUES ('10','10','East London');
INSERT INTO room (code, name, venue_code) VALUES ('11','11','East London');
INSERT INTO room (code, name, venue_code) VALUES ('12','12','East London');
INSERT INTO room (code, name, venue_code) VALUES ('13','13','East London');
INSERT INTO room (code, name, venue_code) VALUES ('14','14','East London');
INSERT INTO room (code, name, venue_code) VALUES ('15','15','East London');
INSERT INTO room (code, name, venue_code) VALUES ('16','16','East London');
INSERT INTO room (code, name, venue_code) VALUES ('17','17','East London');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','East London');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','East London');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','East London');
INSERT INTO room (code, name, venue_code) VALUES ('5','5','East London');
INSERT INTO room (code, name, venue_code) VALUES ('6','6','East London');
INSERT INTO room (code, name, venue_code) VALUES ('7','7','East London');
INSERT INTO room (code, name, venue_code) VALUES ('8','8','East London');
INSERT INTO room (code, name, venue_code) VALUES ('9','9','East London');
INSERT INTO room (code, name, venue_code) VALUES ('Judge''s Room','Judge''s Room','East London');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','East London');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Edinburgh');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Edinburgh');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Edinburgh');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','Edinburgh');
INSERT INTO room (code, name, venue_code) VALUES ('EAT Room 1','EAT Room 1','Edinburgh');
INSERT INTO room (code, name, venue_code) VALUES ('EAT Room 2','EAT Room 2','Edinburgh');
INSERT INTO room (code, name, venue_code) VALUES ('Judges own room','Judges own room','Edinburgh');
INSERT INTO room (code, name, venue_code) VALUES ('Judges Own Room','Judges Own Room','EDINBURGH');
INSERT INTO room (code, name, venue_code) VALUES ('CVP Room','CVP Room','Exeter');
INSERT INTO room (code, name, venue_code) VALUES ('Exeter 1','Exeter 1','Exeter');
INSERT INTO room (code, name, venue_code) VALUES ('Exeter 2','Exeter 2','Exeter');
INSERT INTO room (code, name, venue_code) VALUES ('Exeter 3','Exeter 3','Exeter');
INSERT INTO room (code, name, venue_code) VALUES ('Exeter NA','Exeter NA','Exeter');
INSERT INTO room (code, name, venue_code) VALUES ('Exeter Office','Exeter Office','Exeter');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Exeter');
INSERT INTO room (code, name, venue_code) VALUES ('Exeter Combined','Exeter Combined','Exeter Combined');
INSERT INTO room (code, name, venue_code) VALUES ('Exeter Combined 10','Exeter Combined 10','Exeter Combined');
INSERT INTO room (code, name, venue_code) VALUES ('Exeter Combined 6','Exeter Combined 6','Exeter Combined');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Exeter Combined');
INSERT INTO room (code, name, venue_code) VALUES ('Exeter Mags 3','Exeter Mags 3','Exeter Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Exeter Mags 4','Exeter Mags 4','Exeter Mags');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Exeter Mags');
INSERT INTO room (code, name, venue_code) VALUES ('3 - basement','3 - basement','Field House');
INSERT INTO room (code, name, venue_code) VALUES ('Fox Court rm 3','Fox Court rm 3','Field House');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Field House');
INSERT INTO room (code, name, venue_code) VALUES ('Flint Mags','Flint Mags','Flint Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Floating case','Floating case','Floating Case');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Floating Case');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Fort William SC');
INSERT INTO room (code, name, venue_code) VALUES ('fox Court rm3','fox Court rm3','Fox Court rm 1');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Fox Court rm 1');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Glasgow COET');
INSERT INTO room (code, name, venue_code) VALUES ('10 - Judges Own Room','10 - Judges Own Room','Glasgow COET');
INSERT INTO room (code, name, venue_code) VALUES ('11 - Presidents Room','11 - President''s Room','Glasgow COET');
INSERT INTO room (code, name, venue_code) VALUES ('12 - AIT','12 - AIT','Glasgow COET');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Glasgow COET');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Glasgow COET');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','Glasgow COET');
INSERT INTO room (code, name, venue_code) VALUES ('5','5','Glasgow COET');
INSERT INTO room (code, name, venue_code) VALUES ('6','6','Glasgow COET');
INSERT INTO room (code, name, venue_code) VALUES ('7','7','Glasgow COET');
INSERT INTO room (code, name, venue_code) VALUES ('8','8','Glasgow COET');
INSERT INTO room (code, name, venue_code) VALUES ('9','9','Glasgow COET');
INSERT INTO room (code, name, venue_code) VALUES ('Gloucester CCFC','Gloucester CCFC','Gloucester CCFC');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Gloucester CCFC');
INSERT INTO room (code, name, venue_code) VALUES ('201','201','GTC');
INSERT INTO room (code, name, venue_code) VALUES ('202','202','GTC');
INSERT INTO room (code, name, venue_code) VALUES ('203','203','GTC');
INSERT INTO room (code, name, venue_code) VALUES ('204','204','GTC');
INSERT INTO room (code, name, venue_code) VALUES ('205','205','GTC');
INSERT INTO room (code, name, venue_code) VALUES ('206','206','GTC');
INSERT INTO room (code, name, venue_code) VALUES ('207','207','GTC');
INSERT INTO room (code, name, venue_code) VALUES ('208','208','GTC');
INSERT INTO room (code, name, venue_code) VALUES ('209','209','GTC');
INSERT INTO room (code, name, venue_code) VALUES ('AIT','AIT','GTC');
INSERT INTO room (code, name, venue_code) VALUES ('Judges Room','Judges Room','GTC');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Harrogate CJC');
INSERT INTO room (code, name, venue_code) VALUES ('Havant Mediation Rms','Havant Mediation Rms','Havant');
INSERT INTO room (code, name, venue_code) VALUES ('Havant Office','Havant Office','Havant');
INSERT INTO room (code, name, venue_code) VALUES ('Havant Room 1','Havant Room 1','Havant');
INSERT INTO room (code, name, venue_code) VALUES ('Havant Room 2','Havant Room 2','Havant');
INSERT INTO room (code, name, venue_code) VALUES ('Havant Room 3','Havant Room 3','Havant');
INSERT INTO room (code, name, venue_code) VALUES ('Havant Room 4','Havant Room 4','Havant');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Havant');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers','Chambers','HaverfordwestCC');
INSERT INTO room (code, name, venue_code) VALUES ('Haverfordwest CC','Haverfordwest CC','HaverfordwestCC');
INSERT INTO room (code, name, venue_code) VALUES ('Haverfordwest Mags','Haverfordwest Mags','Haverfordwest M');
INSERT INTO room (code, name, venue_code) VALUES ('Committee room 1','Committee room 1','Hereford');
INSERT INTO room (code, name, venue_code) VALUES ('Library','Library','Hereford');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Hereford Court');
INSERT INTO room (code, name, venue_code) VALUES ('Holyhead Mags','Holyhead Mags','Holyhead Mags');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Hull');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Hull');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Hull');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Hull');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Hull Combined Court Centre');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Hull Combined Court Centre');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Huntingdon');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','IAC');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','I J C');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Inverness');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Kendal');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Kendal Mags');
INSERT INTO room (code, name, venue_code) VALUES ('10','10','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('11','11','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('5','5','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('6','6','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('7','7','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('8','8','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers11','Chambers11','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers12','Chambers12','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers13','Chambers13','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers14','Chambers14','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers 8','Chambers 8','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers 9','Chambers 9','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('REJ','REJ','Kings Court');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Kirkcudbright');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Kirkwall');
INSERT INTO room (code, name, venue_code) VALUES ('9','9','LEDBURY');
INSERT INTO room (code, name, venue_code) VALUES ('A','A','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('B','B','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('C','C','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('D','D','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('E','E','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('F','F','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('G','G','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('H','H','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('In Chambers','In Chambers','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('Leeds Magistrates','Leeds Magistrates','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('Teesside Magistrates','Teesside Magistrates','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('Training Room','Training Room','Leeds');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Leeds ET');
INSERT INTO room (code, name, venue_code) VALUES ('E','E','Leeds ET');
INSERT INTO room (code, name, venue_code) VALUES ('F','F','Leeds ET');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Leicester');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Leicester');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Lerwick');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Liverpool');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Liverpool');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Liverpool');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','Liverpool');
INSERT INTO room (code, name, venue_code) VALUES ('5','5','Liverpool');
INSERT INTO room (code, name, venue_code) VALUES ('Court 27','Court 27','Liverpool');
INSERT INTO room (code, name, venue_code) VALUES ('Remote Hearing','Remote Hearing','Liverpool');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers','Chambers','Llandrindod W');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers','Chambers','Llandudno Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Llandudno Mags','Llandudno Mags','Llandudno Mags');
INSERT INTO room (code, name, venue_code) VALUES ('0','0','Llanelli County');
INSERT INTO room (code, name, venue_code) VALUES ('Llanelli','Llanelli','Llanelli Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers','Chambers','Llangefni Court');
INSERT INTO room (code, name, venue_code) VALUES ('Llangefni CC','Llangefni CC','Llangefni Court');
INSERT INTO room (code, name, venue_code) VALUES ('Llangefni Mags','Llangefni Mags','Llangefni Mags');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Lochmaddy HC');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','London');
INSERT INTO room (code, name, venue_code) VALUES ('10 - 2nd Floor','10 - 2nd Floor','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('11 - 2nd Floor','11 - 2nd Floor','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('12 - 2nd Floor','12 - 2nd Floor','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('  1 - Ground Floor','  1 - Ground Floor','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('  2 - Ground Floor','  2 - Ground Floor','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('  3 - Ground Floor','  3 - Ground Floor','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('  4 - Ground Floor','  4 - Ground Floor','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('501/511 5th Flr','501/511 5th Flr','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('508 - 5th Floor Inf','508 - 5th Floor Inf','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('509 - 5th Floor For','509 - 5th Floor For','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('510 - 5th Floor Inf','510 - 5th Floor Inf','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('  5 - 1st Floor','  5 - 1st Floor','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('  6 - 1st Floor','  6 - 1st Floor','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('  7 - 1st Floor','  7 - 1st Floor','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('  8 - 1st Floor','  8 - 1st Floor','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('  9 - 2nd Floor','  9 - 2nd Floor','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('Back Mtg Rm Grd Flr','Back Mtg Rm Grd Flr','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('Front Mtg Rm Grd Flr','Front Mtg Rm Grd Flr','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('Ms Potter''s Mtg Rm','Ms Potter''s Mtg Rm','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('Own Room','Own Room','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('Spare','Spare','London Central');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','London South ET');
INSERT INTO room (code, name, venue_code) VALUES ('2nd Floor  Conf room','2nd Floor  Conf room','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('3rd Floor Q room','3rd Floor Q room','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('3rd Floor Trg room','3rd Floor Trg room','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Accrington Court','Accrington Court','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('A.I.T','A.I.T','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Blackpool C.C.','Blackpool C.C.','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Liverpool ET','Liverpool ET','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Manchester','Manchester','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Remote hearing','Remote hearing','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 10 (6th Floor)','Room 10 (6th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 11 (6th Floor)','Room 11 (6th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 12 (6th Floor)','Room 12 (6th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 14 (7th Floor)','Room 14 (7th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 15 (7th Floor)','Room 15 (7th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 16 (7th Floor)','Room 16 (7th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 1 Ground Floor','Room 1 Ground Floor','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 2 (4th Floor)','Room 2 (4th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 3 (4th Floor)','Room 3 (4th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 405 (4th Floor)','Room 405 (4th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 4 (4th Floor)','Room 4 (4th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 5 (4th Floor)','Room 5 (4th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 6 (5th Floor)','Room 6 (5th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 7 (5th Floor)','Room 7 (5th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 8 (5th Floor)','Room 8 (5th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Room 9 (6th Floor)','Room 9 (6th Floor)','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('Sit Alones','Sit Alones','Manchester');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Manchester Mags');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Manchester Mags');
INSERT INTO room (code, name, venue_code) VALUES ('8','8','Manchester Mags');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Manorview');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Manorview');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','Manorview');
INSERT INTO room (code, name, venue_code) VALUES ('5','5','Manorview');
INSERT INTO room (code, name, venue_code) VALUES ('6','6','Manorview');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Manorview');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Middlesbrough');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Middlesbrough');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Middlesbrough');
INSERT INTO room (code, name, venue_code) VALUES ('SSCSA','SSCSA','Middlesbrough');
INSERT INTO room (code, name, venue_code) VALUES ('9','9','Minshull Street');
INSERT INTO room (code, name, venue_code) VALUES ('Mold CC','Mold CC','Mold Court');
INSERT INTO room (code, name, venue_code) VALUES ('Mold Mags','Mold Mags','Mold Court');
INSERT INTO room (code, name, venue_code) VALUES ('Neath Mags','Neath Mags','Neath Mags');
INSERT INTO room (code, name, venue_code) VALUES ('202','202','Newcastle CFT');
INSERT INTO room (code, name, venue_code) VALUES ('204','204','Newcastle CFT');
INSERT INTO room (code, name, venue_code) VALUES ('205','205','Newcastle CFT');
INSERT INTO room (code, name, venue_code) VALUES ('206','206','Newcastle CFT');
INSERT INTO room (code, name, venue_code) VALUES ('207','207','Newcastle CFT');
INSERT INTO room (code, name, venue_code) VALUES ('CH002','CH002','Newcastle CFT');
INSERT INTO room (code, name, venue_code) VALUES ('CH003','CH003','Newcastle CFT');
INSERT INTO room (code, name, venue_code) VALUES ('CH004','CH004','Newcastle CFT');
INSERT INTO room (code, name, venue_code) VALUES ('CH005','CH005','Newcastle CFT');
INSERT INTO room (code, name, venue_code) VALUES ('CH006','CH006','Newcastle CFT');
INSERT INTO room (code, name, venue_code) VALUES ('CH007','CH007','Newcastle CFT');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Newcastle CFT');
INSERT INTO room (code, name, venue_code) VALUES ('WFH','WFH','Newcastle CFT');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers 3','Chambers 3','Newcastle ET');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers 4','Chambers 4','Newcastle ET');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Newcastle ET');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Newport');
INSERT INTO room (code, name, venue_code) VALUES ('Newport AIT','Newport AIT','Newport AIT');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Oban HC');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Peterborough');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Plymouth Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Plymouth Mags 7','Plymouth Mags 7','Plymouth Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Plymouth Mags NA','Plymouth Mags NA','Plymouth Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Plymouth Mags Office','Plymouth Mags Office','Plymouth Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Plym St Cath Ho Rm 1','Plym St Cath Ho Rm 1','Plym St Cath Ho');
INSERT INTO room (code, name, venue_code) VALUES ('Plym St Cath Ho Rm 2','Plym St Cath Ho Rm 2','Plym St Cath Ho');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Portree HC');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Port Talbot');
INSERT INTO room (code, name, venue_code) VALUES ('Port Talbot','Port Talbot','Port Talbot');
INSERT INTO room (code, name, venue_code) VALUES ('Chambers','Chambers','Prestatyn JC');
INSERT INTO room (code, name, venue_code) VALUES ('Prestatyn','Prestatyn','Prestatyn JC');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Queensway House');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Queensway House');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','RCJ');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Reading ET');
INSERT INTO room (code, name, venue_code) VALUES ('2','2','Reading ET');
INSERT INTO room (code, name, venue_code) VALUES ('3','3','Reading ET');
INSERT INTO room (code, name, venue_code) VALUES ('4','4','Reading ET');
INSERT INTO room (code, name, venue_code) VALUES ('5','5','Reading ET');
INSERT INTO room (code, name, venue_code) VALUES ('6','6','Reading ET');
INSERT INTO room (code, name, venue_code) VALUES ('7','7','Reading ET');
INSERT INTO room (code, name, venue_code) VALUES ('Rhyl CC','Rhyl CC','Rhyl Court');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','ROIT');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Scarborough');
INSERT INTO room (code, name, venue_code) VALUES ('14','14','Sheffield Combi');
INSERT INTO room (code, name, venue_code) VALUES ('15','15','Sheffield Combi');
INSERT INTO room (code, name, venue_code) VALUES ('16','16','Sheffield Combi');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Sheffield Combi');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Shetland');
INSERT INTO room (code, name, venue_code) VALUES ('Shrewsbury','Shrewsbury','Shrewsbury');
INSERT INTO room (code, name, venue_code) VALUES ('Shrewsbury 1','Shrewsbury 1','Shrewsbury');
INSERT INTO room (code, name, venue_code) VALUES ('CVP Room','CVP Room','Southampton');
INSERT INTO room (code, name, venue_code) VALUES ('Mediation Suite','Mediation Suite','Southampton');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Southampton');
INSERT INTO room (code, name, venue_code) VALUES ('Southampton 10','Southampton 10','Southampton');
INSERT INTO room (code, name, venue_code) VALUES ('Southampton 11','Southampton 11','Southampton');
INSERT INTO room (code, name, venue_code) VALUES ('Southampton 12','Southampton 12','Southampton');
INSERT INTO room (code, name, venue_code) VALUES ('Southampton 14','Southampton 14','Southampton');
INSERT INTO room (code, name, venue_code) VALUES ('Southampton 8','Southampton 8','Southampton');
INSERT INTO room (code, name, venue_code) VALUES ('Southampton 9','Southampton 9','Southampton');
INSERT INTO room (code, name, venue_code) VALUES ('Southampton NA','Southampton NA','Southampton');
INSERT INTO room (code, name, venue_code) VALUES ('Southampton Office','Southampton Office','Southampton');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Stirling SC');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Stoke');
INSERT INTO room (code, name, venue_code) VALUES ('6','6','STOKE (Hanley)');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','STOKE (Hanley)');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Stornoway');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Stornoway HC');
INSERT INTO room (code, name, venue_code) VALUES ('1','1','Stranraer HC');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Stratford');
INSERT INTO room (code, name, venue_code) VALUES ('Swansea CJC','Swansea CJC','Swansea CJ');
INSERT INTO room (code, name, venue_code) VALUES ('Swansea Mags','Swansea Mags','Swansea Mags');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Swindon');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Swindon2');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Taunton');
INSERT INTO room (code, name, venue_code) VALUES ('Taunton','Taunton','Taunton');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Teesside ET');
INSERT INTO room (code, name, venue_code) VALUES ('12','12','Teesside Mags');
INSERT INTO room (code, name, venue_code) VALUES ('16','16','Teesside Mags');
INSERT INTO room (code, name, venue_code) VALUES ('8','8','Teesside Mags');
INSERT INTO room (code, name, venue_code) VALUES ('9','9','Teesside Mags');
INSERT INTO room (code, name, venue_code) VALUES ('Chairmans Room','Chairmans Room','Teesside Mags');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Teesside Mags');
INSERT INTO room (code, name, venue_code) VALUES ('* Not Allocated','* Not Allocated','Telford');
