---
version: '3.5'

services:
  dm-store:
    image: "${DM_STORE_USE_LOCAL-hmctspublic.azurecr.io/}dm/store:${DM_STORE_TAG:-latest}"
    healthcheck:
      disable: true
    environment:
      SERVER_PORT: 5005
      IDAM_SUPERUSER_EMAIL:
      IDAM_SECRET_KEY: AAAAAAAAAAAAAAAA
      GOV_NOTIFY_API_KEY:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:6432/evidence
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      ENABLE_AZURE_STORAGE_CONTAINER: "false"
      ENABLE_POSTGRES_BLOB_STORAGE: "false"
      SPRING_PROFILES_ACTIVE: dev
      IDAM_TESTING_SUPPORT_ENABLED: "true"
      LOGGING_LEVEL_UK_GOV_HMCTS_IDAM: WARN
      IDAM_USER_BASE_URI: "${IDAM_STUB_SERVICE_NAME:-http://localhost:5000}"
      IDAM_S2S_BASE_URI: http://localhost:8489
      S2S_NAMES_WHITELIST: em_gw,em_ccd_orchestrator,ccd,document-management-store,ccd_gw,idam-api,em_stitching_api,ccd_data,dg_docassembly_api,xui_webapp,ccd_case_document_am_api,et_cos,et_msg_handler
      http_proxy:
      https_proxy:
      no_proxy:
      REFORM_SERVICE_TYPE: java
      REFORM_SERVICE_NAME: document-management-store
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: docker
      PACKAGES_ENVIRONMENT: docker
      PACKAGES_PROJECT: evidence
      PACKAGES_NAME: document-management-store
      PACKAGES_VERSION: unknown
      ENABLE_DB_MIGRATE: "true"
    ports:
      - 5005:5005
    network_mode: "host"

  azure-storage-emulator-azurite:
    image: arafato/azurite
    ports:
      - 10000:10000
    environment:
      executable: "blob"
    volumes:
      - ccd-docker-azure-blob-data:/opt/azurite/folder
    network_mode: "host"

volumes:
  ccd-docker-azure-blob-data:
