java:
  image: 'hmctspublic.azurecr.io/et/et-ccd-callbacks:latest'
  applicationPort: 8081
  ingressHost: et-ccd-callbacks-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: et
  keyVaults:
    et-ccd-callbacks:
      secrets:
        - tornado-access-key
#        - et-ccd-callbacks-s2s-secret
        - et-ccd-callbacks-POSTGRES-PASS
    et:
      secrets:
        - create-updates-queue-send-connection-string
  environment:
    SERVER_PORT: 8081
    REFORM_TEAM: et
    REFORM_SERVICE_NAME: et-ccd-callbacks
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
    ET_CCD_CALLBACKS_URL: "http://et-ccd-callbacks-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    TORNADO_URL: "https://docmosis.{{ .Values.global.environment }}.platform.hmcts.net/rs/render"
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    IDAM_API_JWK_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/jwks"
    CCD_DATA_STORE_API_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    DOCUMENT_MANAGEMENT_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    SERVICE_AUTH_PROVIDER_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_GATEWAY_BASE_URL: "https://manage-case.{{ .Values.global.environment }}.platform.hmcts.net"
    MICRO_SERVICE: "et_ccd_callbacks"
    ET_CCD_CALLBACKS_DB_CONN_OPTIONS: ?sslmode=require
    ET_CCD_CALLBACKS_DB_HOST: et-ccd-callbacks-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    ET_CCD_CALLBACKS_DB_NAME: et_ccd_callbacks
    ET_CCD_CALLBACKS_DB_PORT: '5432'
    ET_CCD_CALLBACKS_DB_USER_NAME: et_ccd_callbacks@et-ccd-callbacks-postgres-db-{{ .Values.global.environment }}