package uk.gov.hmcts.et.common.ccd;

import java.util.Set;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>AuthorisationComplexType grants for {@code ET_EnglandWales} (part 1).
 */
public final class ETEnglandWalesComplexTypeGrants01 {
    private ETEnglandWalesComplexTypeGrants01() {
    }

    /**
     * @param builder the config builder
     */
    static void apply(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.grantComplexType(CaseData::getHearingCollection, "hearingShowDetails", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingShowDetails", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "Hearing_type", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "Hearing_type", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingNotesDocument", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingNotesDocument", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDates", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDates", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingFormat", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingFormat", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "judicialMediation", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "judicialMediation", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingPublicPrivate", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingPublicPrivate", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingNumber", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingNumber", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "Hearing_venue", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "Hearing_venue", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingEstLengthNum", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingEstLengthNum", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingEstLengthNumType", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingEstLengthNumType", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingSitAlone", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingSitAlone", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "judge", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "judge", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingERMember", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingERMember", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingEEMember", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingEEMember", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "Hearing_stage", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "Hearing_stage", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection", Set.of(Permission.R, Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.listedDate", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.listedDate", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.Hearing_status", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.Hearing_status", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.Postponed_by", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.Postponed_by", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.postponedDate", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.postponedDate", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingVenueDay", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingVenueDay", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingRoom", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingRoom", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingClerk", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingClerk", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingCaseDisposed", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingCaseDisposed", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.Hearing_part_heard", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.Hearing_part_heard", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.Hearing_reserved_judgement", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.Hearing_reserved_judgement", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.attendee_claimant", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.attendee_claimant", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.attendee_non_attendees", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.attendee_non_attendees", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.attendee_resp_no_rep", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.attendee_resp_no_rep", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.attendee_resp_&_rep", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.attendee_resp_&_rep", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.attendee_rep_only", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.attendee_rep_only", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingTimingStart", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingTimingStart", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingTimingBreak", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingTimingBreak", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingTimingResume", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingTimingResume", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingTimingFinish", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingTimingFinish", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingTimingDuration", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT);
        builder.grantComplexType(CaseData::getHearingCollection, "hearingDateCollection.hearingTimingDuration", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsDate", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsStatus", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsPostponedBy", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsCaseDisposed", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsPartHeard", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsReservedJudgment", Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsAttendeeClaimant", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsAttendeeNonAttendees", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsAttendeeRespNoRep", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsAttendeeRespAndRep", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsAttendeeRepOnly", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsTimingStart", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsTimingBreak", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsTimingResume", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsTimingFinish", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsTimingDuration", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getHearingDetailsCollection, "hearingDetailsHearingNotes2", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalCaseInfoType, "additional_live_appeal", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalCaseInfoType, "additional_sensitive", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalCaseInfoType, "doNotPostpone", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalCaseInfoType, "digitalFile", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalCaseInfoType, "reasonableAdjustment", Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalCaseInfoType, "interventionRequired", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3VettingDocument", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3IsThereAnEt3Response", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3NoEt3Response", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3GeneralNotes", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3IsThereACompaniesHouseSearchDocument", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3CompanyHouseDocument", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3GeneralNotesCompanyHouse", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3IsThereAnIndividualSearchDocument", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3IndividualInsolvencyDocument", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3GeneralNotesIndividualInsolvency", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3LegalIssue", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3LegalIssueGiveDetails", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3GeneralNotesLegalEntity", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3ChooseRespondent", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3ResponseInTime", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3ResponseInTimeDetails", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3DoWeHaveRespondentsName", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3GeneralNotesRespondentName", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3DoesRespondentsNameMatch", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3RespondentNameMismatchDetails", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3GeneralNotesRespondentNameMatch", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3DoWeHaveRespondentsAddress", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(CaseData::getRespondentCollection, "et3Vetting.et3GeneralNotesRespondentAddress", Set.of(Permission.D), UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
    }
}
