package uk.gov.hmcts.et.common.ccd;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>The work-basket input and result fields for {@code ET_EnglandWales}.
 */
@Component
public class ETEnglandWalesWorkBasket implements CCDConfig<CaseData, State, UserRole> {
    /**
     * Configures the work-basket input and result fields for {@code ET_EnglandWales}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.workBasketInputFields()
            .field("conciliationTrack", "Track")
            .field("managingOffice", "Tribunal Office")
            .field("ethosCaseReference", "Case Number")
            .field("receiptDate", "Receipt Date")
            .field("feeGroupReference", "Submission Reference")
            .field("claimantIndType", "Claimant Last Name", f -> f.listElementCode("claimant_last_name"))
            .field("claimantIndType", "Claimant First Name", f -> f.listElementCode("claimant_first_names"))
            .field("respondent", "Respondent");
        builder.workBasketResultFields()
            .field("ethosCaseReference", "Case Number")
            .field("receiptDate", "Receipt Date")
            .field("feeGroupReference", "Submission Reference")
            .field("claimant", "Claimant")
            .field("respondent", "Respondent")
            .field("managingOffice", "Tribunal Office")
            .field("positionType", "Current Position");
    }
}
