package uk.gov.hmcts.et.common.ccd;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>The document categories for {@code ET_EnglandWales}.
 */
@Component
public class ETEnglandWalesCategories implements CCDConfig<CaseData, State, UserRole> {
    /**
     * Configures the document categories for {@code ET_EnglandWales}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C1")
            .categoryLabel("Starting a Claim")
            .displayOrder(1);
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C2")
            .categoryLabel("Response to a Claim")
            .displayOrder(2);
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C3")
            .categoryLabel("Initial Consideration")
            .displayOrder(3);
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C4")
            .categoryLabel("Case Management")
            .displayOrder(4);
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C80")
            .categoryLabel("Employer Contract Claim")
            .displayOrder(5);
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C5")
            .categoryLabel("Withdrawal /Settled")
            .displayOrder(6);
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C6")
            .categoryLabel("Hearings")
            .displayOrder(7);
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C7")
            .categoryLabel("Judgment and Reasons")
            .displayOrder(8);
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C8")
            .categoryLabel("Reconsideration")
            .displayOrder(9);
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C9")
            .categoryLabel("Miscellaneous")
            .displayOrder(10);
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C11")
            .categoryLabel("ET1")
            .displayOrder(1)
            .parentCategoryID("C1");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C12")
            .categoryLabel("ET1 Attachment")
            .displayOrder(2)
            .parentCategoryID("C1");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C13")
            .categoryLabel("ACAS Certificate")
            .displayOrder(3)
            .parentCategoryID("C1");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C14")
            .categoryLabel("Notice of claim")
            .displayOrder(4)
            .parentCategoryID("C1");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C15")
            .categoryLabel("Claim accepted")
            .displayOrder(5)
            .parentCategoryID("C1");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C16")
            .categoryLabel("Claim rejected")
            .displayOrder(6)
            .parentCategoryID("C1");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C17")
            .categoryLabel("Claim part rejected")
            .displayOrder(7)
            .parentCategoryID("C1");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C71")
            .categoryLabel("ET1 Vetting")
            .displayOrder(8)
            .parentCategoryID("C1");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C18")
            .categoryLabel("ET3")
            .displayOrder(1)
            .parentCategoryID("C2");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C19")
            .categoryLabel("ET3 Attachment")
            .displayOrder(2)
            .parentCategoryID("C2");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C20")
            .categoryLabel("Response accepted")
            .displayOrder(3)
            .parentCategoryID("C2");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C21")
            .categoryLabel("Response rejected")
            .displayOrder(4)
            .parentCategoryID("C2");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C22")
            .categoryLabel("App to extend time to present a response")
            .displayOrder(5)
            .parentCategoryID("C2");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C72")
            .categoryLabel("ET3 Processing")
            .displayOrder(6)
            .parentCategoryID("C2");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C23")
            .categoryLabel("Initial Consideration")
            .displayOrder(1)
            .parentCategoryID("C3");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C24")
            .categoryLabel("Rule 28 Notice")
            .displayOrder(2)
            .parentCategoryID("C3");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C25")
            .categoryLabel("Rule 29 Notice")
            .displayOrder(3)
            .parentCategoryID("C3");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C26")
            .categoryLabel("Tribunal Order")
            .displayOrder(1)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C27")
            .categoryLabel("Deposit Order")
            .displayOrder(2)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C28")
            .categoryLabel("Unless Order")
            .displayOrder(3)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C29")
            .categoryLabel("Tribunal Notice")
            .displayOrder(4)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C30")
            .categoryLabel("App to vary an order - C")
            .displayOrder(5)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C31")
            .categoryLabel("App to vary an order - R")
            .displayOrder(6)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C32")
            .categoryLabel("App to revoke an order - C")
            .displayOrder(7)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C33")
            .categoryLabel("App to revoke an order - R")
            .displayOrder(8)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C34")
            .categoryLabel("App to extend time to comply to an order/directions - C")
            .displayOrder(9)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C35")
            .categoryLabel("App to extend time to comply to an order/directions - R")
            .displayOrder(10)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C36")
            .categoryLabel("App to Order the R to do something")
            .displayOrder(11)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C37")
            .categoryLabel("App to Order the C to do something")
            .displayOrder(12)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C38")
            .categoryLabel("App to amend claim")
            .displayOrder(13)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C39")
            .categoryLabel("App to amend response")
            .displayOrder(14)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C40")
            .categoryLabel("App for a Witness Order - C")
            .displayOrder(15)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C75")
            .categoryLabel("App for a Witness Order - R")
            .displayOrder(16)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C41")
            .categoryLabel("Disability Impact statement")
            .displayOrder(17)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C42")
            .categoryLabel("R has not complied with an order - C")
            .displayOrder(18)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C43")
            .categoryLabel("C has not complied with an order - R")
            .displayOrder(19)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C44")
            .categoryLabel("App to Strike out all or part of the claim")
            .displayOrder(20)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C45")
            .categoryLabel("App to Strike out all or part of the response")
            .displayOrder(21)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C46")
            .categoryLabel("Referral/Judicial Direction")
            .displayOrder(22)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C47")
            .categoryLabel("Change of party’s details")
            .displayOrder(23)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C73")
            .categoryLabel("App to vary or revoke an order - C")
            .displayOrder(24)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C74")
            .categoryLabel("App to vary or revoke an order - R")
            .displayOrder(25)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C76")
            .categoryLabel("Contact the tribunal about something else - C")
            .displayOrder(26)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C77")
            .categoryLabel("Contact the tribunal about something else - R")
            .displayOrder(27)
            .parentCategoryID("C4");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C48")
            .categoryLabel("Withdrawal of entire claim")
            .displayOrder(1)
            .parentCategoryID("C5");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C49")
            .categoryLabel("Withdrawal of part of claim")
            .displayOrder(2)
            .parentCategoryID("C5");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C78")
            .categoryLabel("Withdrawal of all or part of claim")
            .displayOrder(3)
            .parentCategoryID("C5");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C50")
            .categoryLabel("COT3")
            .displayOrder(4)
            .parentCategoryID("C5");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C51")
            .categoryLabel("App to restrict publicity - C")
            .displayOrder(1)
            .parentCategoryID("C6");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C52")
            .categoryLabel("App to restrict publicity - R")
            .displayOrder(2)
            .parentCategoryID("C6");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C53")
            .categoryLabel("Anonymity Order")
            .displayOrder(3)
            .parentCategoryID("C6");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C54")
            .categoryLabel("Notice of hearing")
            .displayOrder(4)
            .parentCategoryID("C6");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C55")
            .categoryLabel("App to postpone - C")
            .displayOrder(5)
            .parentCategoryID("C6");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C56")
            .categoryLabel("App to postpone - R")
            .displayOrder(6)
            .parentCategoryID("C6");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C57")
            .categoryLabel("Hearing Bundle")
            .displayOrder(7)
            .parentCategoryID("C6");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C58")
            .categoryLabel("Schedule of loss")
            .displayOrder(8)
            .parentCategoryID("C6");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C59")
            .categoryLabel("Counter Schedule of Loss")
            .displayOrder(9)
            .parentCategoryID("C6");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C60")
            .categoryLabel("Judgment")
            .displayOrder(1)
            .parentCategoryID("C7");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C61")
            .categoryLabel("Judgment with Reasons")
            .displayOrder(2)
            .parentCategoryID("C7");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C62")
            .categoryLabel("Reasons")
            .displayOrder(3)
            .parentCategoryID("C7");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C63")
            .categoryLabel("Extract of Judgment")
            .displayOrder(4)
            .parentCategoryID("C7");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C64")
            .categoryLabel("App to have a Legal Officer decision considered afresh - C")
            .displayOrder(1)
            .parentCategoryID("C8");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C65")
            .categoryLabel("App to have a Legal Officer decision considered afresh - R")
            .displayOrder(2)
            .parentCategoryID("C8");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C66")
            .categoryLabel("App for a judgment to be reconsidered - C")
            .displayOrder(3)
            .parentCategoryID("C8");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C67")
            .categoryLabel("App for a judgment to be reconsidered - R")
            .displayOrder(4)
            .parentCategoryID("C8");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C68")
            .categoryLabel("Certificate of Correction")
            .displayOrder(1)
            .parentCategoryID("C9");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C69")
            .categoryLabel("Tribunal Case file")
            .displayOrder(2)
            .parentCategoryID("C9");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C70")
            .categoryLabel("Other")
            .displayOrder(3)
            .parentCategoryID("C9");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C79")
            .categoryLabel("Needs updating")
            .displayOrder(4)
            .parentCategoryID("C9");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C81")
            .categoryLabel("Notice of Employer Contract Claim")
            .displayOrder(1)
            .parentCategoryID("C80");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C82")
            .categoryLabel("Acceptance of ECC response")
            .displayOrder(2)
            .parentCategoryID("C80");
        builder.categories(UserRole.CASEWORKER_RAS_VALIDATION)
            .categoryID("C83")
            .categoryLabel("Rejection of ECC response")
            .displayOrder(3)
            .parentCategoryID("C80");
    }
}
