package uk.gov.hmcts.et.common.ccd;

import java.util.List;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.SearchCriteriaField;
import uk.gov.hmcts.ccd.sdk.api.SearchPartyField;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>The search input/result, search-cases, criteria and parties for {@code ET_EnglandWales}.
 */
@Component
public class ETEnglandWalesSearch implements CCDConfig<CaseData, State, UserRole> {
    /**
     * Configures the search input/result, search-cases, criteria and parties for {@code ET_EnglandWales}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.searchInputFields()
            .field("managingOffice", "Tribunal Office")
            .field("ethosCaseReference", "Case Number")
            .field("feeGroupReference", "Submission Reference")
            .field("claimantIndType", "Claimant Surname", f -> f.listElementCode("claimant_last_name"))
            .field("claimantIndType", "Claimant First Name", f -> f.listElementCode("claimant_first_names"))
            .field("claimant_Company", "Claimant Company Name")
            .field("respondent", "Respondent")
            .field("multipleReference", "Multiple Reference")
            .field("subMultipleName", "Submultiple Reference")
            .field("positionType", "Current Position")
            .field("fileLocation", "Physical Location")
            .field("clerkResponsible", "Clerk")
            .field("claimantType", "Claimant Postcode", f -> f.listElementCode("claimant_addressUK.PostCode"));
        builder.searchResultFields()
            .field("ethosCaseReference", "Case Number")
            .field("claimant", "Claimant")
            .field("respondent", "Respondent")
            .field("positionType", "Current Position")
            .field("fileLocation", "Physical Location")
            .field("multipleReference", "Multiple Reference")
            .field("leadClaimant", "Lead Claimant");
        builder.searchCasesFields()
            .field("[CASE_REFERENCE]", "Case Reference", f -> f.useCase("orgcases"))
            .field("ethosCaseReference", "Case Number", f -> f.useCase("orgcases"))
            .field("claimant", "Claimant", f -> f.useCase("orgcases"))
            .field("respondent", "Respondent", f -> f.useCase("orgcases"))
            .field("[STATE]", "State", f -> f.useCase("orgcases"));
        builder.searchCriteria().fields(List.of(SearchCriteriaField.builder().otherCaseReference("ethosCaseReference").build()));
        builder.searchParty().fields(List.of(SearchPartyField.builder()
            .searchPartyName("claimantIndType.claimant_first_names,claimantIndType.claimant_last_name")
            .searchPartyEmailAddress("claimantType.claimant_email_address")
            .searchPartyAddressLine1("claimantType.claimant_addressUK.AddressLine1")
            .searchPartyPostCode("claimantType.claimant_addressUK.PostCode")
            .searchPartyDOB("claimantIndType.claimant_date_of_birth")
                    .build()));
        builder.searchParty().fields(List.of(SearchPartyField.builder()
            .searchPartyName("respondent_name")
            .searchPartyEmailAddress("respondent_email")
            .searchPartyAddressLine1("respondent_address.AddressLine1")
            .searchPartyPostCode("respondent_address.PostCode")
            .searchPartyCollectionFieldName("respondentCollection")
                    .build()));
        builder.searchParty().fields(List.of(SearchPartyField.builder()
            .searchPartyName("resp_rep_name")
            .searchPartyEmailAddress("representative_email_address")
            .searchPartyAddressLine1("representative_address.AddressLine1")
            .searchPartyPostCode("representative_address.PostCode")
            .searchPartyCollectionFieldName("repCollection")
                    .build()));
    }
}
