'use strict';

const requireDirectory = require('require-directory');
const steps = requireDirectory(module);

module.exports = () => {
    return actor({
        authenticateWithIdam: steps.IDAM.signIn,
        chooseNextStep: steps.nextStep.nextStep,
        acceptTheCase: steps.acceptanceCase.acceptCase,
        rejectTheCase: steps.acceptanceCase.rejectCase,
        executeClaimantDetails: steps.amendClaimantDetails.amendClaimantDet,
        executeClaimantRepresentative: steps.amendClaimantRepresentative.amendClaimantRepresentative,
        executeRespondentDetails: steps.amendRespondentDetails.amendRespondentDetails,
        amendTheCaseDetails: steps.amendCaseDetails.amendCaseDetails,
        amendCaseDetailsWithCaseCurrentPosition: steps.amendCaseDetails.amendCaseDetailsWithCasePosition,
        executeRespondentRepresentative: steps.amendRespondentRepresentative.amendRespondentRepresentative,
        executeAddAmendJurisdiction: steps.amendJurisdiction.addAmendJurisdiction,
        enterDisposalDate: steps.amendJurisdiction.addDisposalDate,
        executeCloseCase: steps.desposeCase.desposeCase,
        executeLettersEvent: steps.generateCorrespondence.generateCorrespondence,
        setRestrictedReporting: steps.restrictedCases.restrictedCases,
        executeFixCaseAPI: steps.fixCaseApi.fixCaseApi,
        executeBFAction: steps.broughtForward.broughtForward,
        executeBFActionsOutstanding: steps.broughtForward.bfActionsOutstandingError,
        executeListHearing: steps.amendHearing.listHearing,
        executeAllocateHearing: steps.allocateHearing.allocateHearing,
        executeHearingDetails: steps.hearingDetails.hearingDetails,
        amendHearingDetails: steps.hearingDetails.updateHearingDetails,
        executePrintHearingLists: steps.printHearingLists.printHearingLists,
        executeCaseTransferEngWales: steps.caseTransfer.caseTransferEngWales,
        executeCaseTransferECM: steps.caseTransfer.caseTransferECM,
        executeCaseTransferScotland: steps.caseTransfer.caseTransferScotland,
        executeJudgment: steps.amendJudgment.addAmendJudgment,
        executeCreateReport: steps.createReport.createReport,
        executeHearingListedInWeekend: steps.amendHearing.hearingListedInWeekend,
        executeUploadDocument: steps.uploadDocument.uploadDocument,
        startInitialConsideration: steps.initialConsideration.initialConsiderationStartPage,
        initialConsiderationRule26: steps.initialConsideration.initialConsiderationRule26Page,
        initialConsiderationCheckYourAnswers: steps.initialConsideration.initialConsiderationCheckYourAnswersPage,
        et1VettingJourney: steps.et1Vetting.et1VettingJourney,
        et3Processing: steps.et3Processing.et3ProcessingPage,
        et3ProcessingWithNoResponse: steps.et3Processing.et3ProcessingPageNoET3Response,
        et1ServingProcess:steps.et1Serving.processEt1Serving,
        et3NotificationProcess:steps.et3Notification.processEt3Notification,
        et3ResponseProcess:steps.et3Response.processEt3Response,
        createAdminReferrals:steps.referrals.createAdminReferrals,
        createJudgeReferrals:steps.referrals.createJudgeReferrals,
        createLegalRepReferrals:steps.referrals.createLegalOfficerReferrals,
        replyReferrals:steps.referrals.replyReferrals,
        closeReferrals:steps.referrals.closeReferrals,
        caseListForCreateCase : steps.createCase.caseList,
        caseJurisdictionForCreateCase : steps.createCase.caseJur,
        caseDateOfReceiptForCreateCase : steps.createCase.caseDate,
        caseTypeOfClaimantForCreateCase : steps.createCase.caseClaimantType,
        caseRespondentsForCreateCase : steps.createCase.caseResp,
        caseClaimantIsWAForCreateCase : steps.createCase.caseClaimantIsWA,
        caseClaimantWAForCreateCase : steps.createCase.caseClaimantWA,
        caseOtherDetailsForCreateCase : steps.createCase.caseOther,
        caseClaimantRepresented : steps.createCase.caseRep,
        caseClaimantHearingPreferences : steps.createCase.caseHearingPref,
        caseApplicationTabs : steps.createCase.caseApplication,
    });
};
