'use strict';
const testConfig = require("../../config");
const commonConfig = require('../../data/commonConfig.json');
module.exports = async function () {

    const I = this;
    I.waitForText('Has a reconsideration application been made? (Optional)', testConfig.TestTimeToWaitForText);
    I.see('Judgment');
    I.see('Case Number:');
    I.see('Non Hearing Judgment?');
    I.see('Judgment Type');
    I.see('Liability (Optional)');
    I.see('Jurisdiction');
    I.see('Date Judgment made');
    I.see('Day');
    I.see('Month');
    I.see('Year');
    I.see('Date Judgment sent');
    I.see('Judgment Notes (Optional)');
    I.see('Upload outcome of Judgment (Optional)');
    I.see('Judgment details');
    I.see('Reasons given (Optional)');
    I.see('Yes');
    I.see('No');
    I.see('Award made? (Optional)');
    I.see('Non-financial award (Optional)');
    I.see('Certificate of Correction Issued? (Optional)');
    I.see('Non-financial award (Optional)');
    I.see('Costs');
    I.see('Have costs been awarded? (Optional)');
    I.see('Reconsideration');
    I.see('Has a reconsideration application been made? (Optional)');

    I.click('#judgementCollection_0_Judgement_costs_costs_question_Yes');
    I.see('Costs/Expenses awarded to (Optional)');
    I.see('Costs/Expenses awarded against (Optional)');
    I.see('Costs/Expenses amount awarded (Optional)');
    I.see('Preparation of time awarded to (Optional)');
    I.see('Preparation of time awarded against (Optional)');
    I.see('Preparation of time amount awarded (Optional)');
    I.see('Wasted cost awarded to (Optional)');
    I.see('Wasted cost awarded against (Optional)');
    I.see('Wasted cost amount awarded (Optional)');
    I.see('Pro Bono costs awarded to (Optional)');
    I.see('Pro Bono costs awarded against (Optional)');
    I.see('Pro Bono costs amount awarded (Optional)');

    I.click('#judgementCollection_0_non_hearing_judgment_Yes');
    I.selectOption('#judgementCollection_0_judgement_type', commonConfig.judgmentType);
    I.selectOption('#judgementCollection_0_liability_optional', 'Liability');
    I.click('//div[@id=\'judgementCollection_0_jurisdictionCodes\']/div/button');
    I.selectOption('#judgementCollection_0_jurisdictionCodes_0_juridictionCodesList', commonConfig.jurisdictionCode);
    I.fillField('#date_judgment_made-day', commonConfig.judgmentMadeDate);
    I.fillField('#date_judgment_made-month', '10');
    I.fillField('#date_judgment_made-year', commonConfig.judgmentMadeYear);
    I.fillField('#date_judgment_sent-day', commonConfig.judgmentSentDate);
    I.fillField('#date_judgment_sent-month', commonConfig.judgmentSentMonth);
    I.fillField('#date_judgment_sent-year', commonConfig.judgmentSentYear);
    I.fillField('#judgementCollection_0_judgment_notes', 'Judgement Notes Optional');
    I.attachFile('#judgementCollection_0_judgement_outcome_doc', 'data/fileUpload.txt');
    I.click('#judgementCollection_0_judgement_details_reasons_given_Yes');
    I.see('Reasons given (Optional)');
    I.see('Date reasons issued (Optional)');
    I.see('Award made? (Optional)');
    I.click('#judgementCollection_0_judgement_details_awardMade_Yes');
    I.see('Financial award made? (Optional)');
    I.click('#judgementCollection_0_judgement_details_financialAwardMade_Yes');
    I.see('Total award £ (Optional)');
    I.see('Adjustment (Old Regs) / ACAS Code Adj (New Regs) (Optional)');
    I.fillField('#judgementCollection_0_judgement_details_total_award', '1000');
    I.selectOption('#judgementCollection_0_judgement_details_adjustment', 'Increase (New regs)');
    I.see('Adjustment % (New Regs) (Optional)');
    I.fillField('#judgementCollection_0_judgement_details_adjustmentPercentage', '25');
    I.see('Non-financial award (Optional)');
    I.click('#judgementCollection_0_judgement_details_non-financial_award_Yes');
    I.see('Remedy left to parties (Optional)');
    I.click('#judgementCollection_0_judgement_details_remedy_left_to_parties_Yes');
    I.see('Reinstate / reengage order (Optional)');
    I.see('Reinstated / reengaged (Optional)');
    I.selectOption('#judgementCollection_0_judgement_details_reinstate_reengage_order', 'Reinstate');
    I.selectOption('#judgementCollection_0_judgement_details_reinstated_reengaged', 'Re-engaged');
    I.see('Certificate of Correction Issued? (Optional)');
    I.click('#judgementCollection_0_judgement_details_certificateOfCorrection_Yes');
    I.see('Cert. of correction date (Optional)');
    I.see('Cert. of correction sent (Optional)');
    I.fillField('#cert_of_correction_date-day', commonConfig.judgmentMadeDate);
    I.fillField('#cert_of_correction_date-month', commonConfig.judgmentSentMonth);
    I.fillField('#cert_of_correction_date-year', commonConfig.judgmentSentYear);
    I.fillField('#cert_of_correction_sent-day', commonConfig.judgmentMadeDate);
    I.fillField('#cert_of_correction_sent-month', commonConfig.judgmentSentMonth);
    I.fillField('#cert_of_correction_sent-year', commonConfig.judgmentSentYear);

    I.selectOption('#judgementCollection_0_Judgement_costs_costs_expenses_awarded_to', 'Claimant');
    I.selectOption('#judgementCollection_0_Judgement_costs_costs_expenses_awarded_against', 'Respondent');
    I.fillField('#judgementCollection_0_Judgement_costs_costs_expenses_awarded_amount', '1000.00');
    I.selectOption('#judgementCollection_0_Judgement_costs_preparation_of_time_awarded_to', 'Claimant');
    I.selectOption('#judgementCollection_0_Judgement_costs_preparation_of_time_awarded_against', 'Respondent');
    I.fillField('#judgementCollection_0_Judgement_costs_preparation_of_time_amount_awarded', '1500.00');
    I.selectOption('#judgementCollection_0_Judgement_costs_wasted_cost_awarded_to', 'Claimant');
    I.selectOption('#judgementCollection_0_Judgement_costs_wasted_cost_awarded_against', 'Respondent');
    I.fillField('#judgementCollection_0_Judgement_costs_wasted_cost_amount_awarded', '2000.00');
    I.selectOption('#judgementCollection_0_Judgement_costs_pro_bono_costs_awarded_to', 'Access to Justice Foundation');
    I.selectOption('#judgementCollection_0_Judgement_costs_pro_bono_costs_awarded_against', 'Respondent\'s Representative');
    I.fillField('#judgementCollection_0_Judgement_costs_pro_bono_costs_amount_awarded', '2500.00');
    I.click('#judgementCollection_0_reconsiderations_reconsideration_Yes');
    I.see('Date of application for reconsideration');
    I.see('Did the Tribunal reconsider the Judgment on its own initiative');
    I.fillField('#reconsiderationDate-day', '01');
    I.fillField('#reconsiderationDate-month', "10");
    I.fillField('#reconsiderationDate-year', "2000");
    I.click('#judgementCollection_0_reconsiderations_reconsiderationOwnInitiative_No');
    I.see('Who applied for reconsideration? (Optional)');
    I.see('Employment Judge\'s direction');
    I.selectOption('#judgementCollection_0_reconsiderations_reconsiderationPartyInitiative', 'Claimant');
    I.selectOption('#judgementCollection_0_reconsiderations_reconsiderationDirection', 'Application refused');
    I.selectOption('#judgementCollection_0_reconsiderations_reconsiderationDecision', 'Judgment confirmed');
    I.click('Submit');
    I.waitForText('has been updated with event: Judgment', testConfig.TestTimeToWaitForText);

    //Verifying the Judgements Tab
    I.click("//div[text()='Judgments']");
    I.see('1');
    I.see('Jurisdiction');
    I.see('Jurisdiction 1');
    I.see('Jurisdiction Code');
    I.see('ADT');
    I.see('Discriminatory terms or rules');
    I.see('Non Hearing Judgment?');
    I.see('Yes');
    I.see('Judgment Type');
    I.see('Judgment');
    I.see('Liability');
    I.see('Date Judgment made');
    I.see('4 Oct 2022');
    I.see('Date Judgment sent');
    I.see('6 Jan 2022');
    I.see('Judgment Notes');
    I.see('Judgement Notes Optional');
    I.see('Upload outcome of Judgment');
    I.see('fileUpload.txt');
    I.see('Judgment details');
    I.see('Reasons given');
    I.see('Award made?');
    I.see('Financial award made?');
    I.see('Remedy left to parties');
    I.see('Reinstate / reengage order');
    I.see('Reinstate');
    I.see('Reinstated / reengaged');
    I.see('Re-engaged');
    I.see('Certificate of Correction Issued?');
    I.see('Cert. of correction date');
    I.see('Cert. of correction date');
    I.see('4 Jan 2022');
    I.see('Cert. of correction sent');
    I.see('Non-financial award');
    I.see('Total award £');
    I.see('£1,000.00');
    I.see('Adjustment (Old Regs) / ACAS Code Adj (New Regs)');
    I.see('Increase (New regs)');
    I.see('Adjustment % (New Regs)');
    I.see('25');
    I.see('Costs');
    I.see('Have costs been awarded?');
    I.see('Costs/Expenses awarded to');
    I.see('Claimant');
    I.see('Costs/Expenses awarded against');
    I.see('Respondent');
    I.see('Costs/Expenses amount awarded');
    I.see('Preparation of time awarded to');
    I.see('Preparation of time awarded against');
    I.see('Preparation of time amount awarded');
    I.see('£1,500.00');
    I.see('Wasted cost awarded to');
    I.see('Wasted cost awarded against');
    I.see('Wasted cost amount awarded');
    I.see('£2,000.00');
    I.see('Pro Bono costs awarded to');
    I.see('Access to Justice Foundation');
    I.see('Pro Bono costs awarded against');
    I.see('Respondent\'s Representative');
    I.see('Pro Bono costs amount awarded');
    I.see('£2,500.00');
    I.see('Reconsideration');
    I.see('Has a reconsideration application been made?');
    I.see('Date of application for reconsideration');
    I.see('1 Oct 2000');
    I.see('Did the Tribunal reconsider the Judgment on its own initiative');
    I.see('No');
    I.see('Who applied for reconsideration?');
    I.see('Claimant');
    I.see('Employment Judge\'s direction');
    I.see('Application refused');
    I.see('Employment Judge\'s decision');
    I.see('Judgment confirmed');
};
