package uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config;

import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.SingleComplexTypes;
import uk.gov.hmcts.et.common.model.ccd.SingleRole;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.ComplexFieldSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.EventFieldSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.EventSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.GrantSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.StandaloneComplexSpec;

@SuppressWarnings({"checkstyle:LineLength", "checkstyle:RightCurlyAlone", "PMD.AvoidDuplicateLiterals"})
final class SingleInitialConsiderationRows {
    private static final int CFTLIB_ENGLAND_WALES = 1;
    private static final int CFTLIB_SCOTLAND = 2;
    private static final int PROD_ENGLAND_WALES = 4;
    private static final int ENGLAND_WALES = 5;
    private static final int PROD_SCOTLAND = 8;
    private static final int SCOTLAND = 10;
    private static final int ALL = 15;
    private static final String LOCALHOST = "http://localhost:8081";
    private static final String PRODUCTION = "http://et-cos-prod.service.core-compute-prod.internal";
    private static final String INITIAL_CONSIDERATION = "initialConsideration";

    static final GrantSpec[] EVENT_GRANTS = {
        new GrantSpec(ALL, INITIAL_CONSIDERATION, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(ENGLAND_WALES, INITIAL_CONSIDERATION, SingleRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, "CRUD"),
        new GrantSpec(ENGLAND_WALES, INITIAL_CONSIDERATION, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES, "CRUD"),
        new GrantSpec(SCOTLAND, INITIAL_CONSIDERATION, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_SCOTLAND, "CRUD"),
        new GrantSpec(SCOTLAND, INITIAL_CONSIDERATION, SingleRole.CASEWORKER_EMPLOYMENT_SCOTLAND, "CRUD"),
        new GrantSpec(ALL, INITIAL_CONSIDERATION, SingleRole.CASEWORKER_WA_TASK_CONFIGURATION, "CRU")
    };

    static final StandaloneComplexSpec[] STANDALONE_COMPLEX_FIELDS = {
        new StandaloneComplexSpec(
                ALL,
                INITIAL_CONSIDERATION,
                CaseData::getIcAllDocumentCollection,
                SingleComplexTypes.IcDocumentUploadType.class)
    };

    static final EventSpec[] EVENTS = {
        event(CFTLIB_ENGLAND_WALES, 20, LOCALHOST),
        event(CFTLIB_SCOTLAND, 44, LOCALHOST),
        event(PROD_ENGLAND_WALES, 20, PRODUCTION),
        event(PROD_SCOTLAND, 44, PRODUCTION)
    };

    static final EventFieldSpec[] EVENT_FIELDS = {
        field(ALL, "initialConsiderationBeforeYouStart", "READONLY", "1", 1, 1, true, "N", "initialConsiderationBeforeYouStartLabel=\"dummy\"", null, null, "Before you start", null),
        field(ALL, "initialConsiderationBeforeYouStartLabel", "READONLY", "1", 1, 2, true, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etInitialConsiderationRespondent", "READONLY", "1", 1, 3, true, "N", "etInitialConsiderationRespondentLabel=\"dummy\"", null, null, null, null),
        field(SCOTLAND, "etInitialConsiderationRespondent", "READONLY", "1", 1, 3, true, "N", "etInitialConsiderationRespondentLabel=\"dummy\"", null, null, "Rule 27", null),
        field(ALL, "etInitialConsiderationRespondentLabel", "READONLY", "1", 1, 4, true, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etInitialConsiderationHearing", "READONLY", "1", 1, 5, true, "N", "etInitialConsiderationHearingLabel=\"dummy\"", null, null, "Before you start", null),
        field(SCOTLAND, "etInitialConsiderationHearing", "READONLY", "1", 1, 5, true, "N", "etInitialConsiderationHearingLabel=\"dummy\"", null, null, null, null),
        field(ALL, "etInitialConsiderationHearingLabel", "READONLY", "1", 1, 6, true, "N", null, null, null, null, null),
        field(ALL, "etIcPartiesHearingPanelPreferenceHeader", "READONLY", "1", null, 7, true, "N", "etIcPartiesHearingPanelPreferenceHeaderLabel=\"dummy\"", null, null, null, null),
        field(ALL, "etIcPartiesHearingPanelPreferenceHeaderLabel", "READONLY", "1", null, 8, true, "N", null, null, null, null, null),
        field(ALL, "etIcPartiesHearingPanelPreference", "READONLY", "1", null, 9, true, "N", "etIcPartiesHearingPanelPreferenceLabel=\"dummy\"", null, null, null, null),
        field(ALL, "etIcPartiesHearingPanelPreferenceLabel", "READONLY", "1", null, 10, true, "N", null, null, null, null, null),
        field(ALL, "etIcPartiesHearingFormat", "READONLY", "1", null, 11, true, "N", "etIcPartiesHearingFormatLabel=\"dummy\"", null, null, null, null),
        field(ALL, "etIcPartiesHearingFormatLabel", "READONLY", "1", null, 12, true, "N", null, null, null, null, null),
        field(SCOTLAND, "etIcHearingPanelPreference", "READONLY", "1", null, 13, true, "N", "etIcHearingPanelPreferenceLabel=\"dummy\"", null, null, null, null),
        field(ENGLAND_WALES, "etInitialConsiderationJurisdictionCodes", "READONLY", "1", 1, 13, true, "N", "etInitialConsiderationJurisdictionCodesLabel=\"dummy\"", null, null, null, null),
        field(SCOTLAND, "etIcHearingPanelPreferenceLabel", "READONLY", "1", 1, 14, true, "N", "etIcPartiesHearingFormatLabel=\"dummy\"", null, null, null, null),
        field(ENGLAND_WALES, "etInitialConsiderationJurisdictionCodesLabel", "READONLY", "1", 1, 14, true, "N", null, null, null, null, null),
        field(ALL, "icRespondentHearingPanelPreference", "READONLY", "1", 1, 15, true, "N", "icRespondentHearingPanelPreferenceLabel=\"dummy\"", null, null, null, null),
        field(SCOTLAND, "etInitialConsiderationJurisdictionCodes", "READONLY", "1", 1, 16, true, "N", "etInitialConsiderationJurisdictionCodesLabel=\"dummy\"", null, null, null, null),
        field(ENGLAND_WALES, "nextListedDate", "OPTIONAL", "1", 1, 16, true, "N", "etICJuridictionCodesInvalid=\"dummy\"", null, null, null, "Y"),
        field(SCOTLAND, "etInitialConsiderationJurisdictionCodesLabel", "READONLY", "1", 1, 17, true, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "icRespondentHearingPanelPreferenceLabel", "READONLY", "1", 1, 17, true, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etICIssuesArisingFromVettingLabel", "READONLY", "1", 1, 18, true, "N", null, null, null, null, null),
        field(SCOTLAND, "nextListedDate", "OPTIONAL", "1", 1, 18, true, "N", "etICJuridictionCodesInvalid=\"dummy\"", null, null, null, "Y"),
        field(ENGLAND_WALES, "icEt1VettingIssuesDetail", "READONLY", "1", 1, 19, true, "N", "icEt1VettingIssuesDetailLabel=\"dummy\"", null, null, null, null),
        field(SCOTLAND, "icRespondentHearingPanelPreferenceLabel", "READONLY", "1", 1, 19, true, "N", null, null, null, null, null),
        field(SCOTLAND, "etICIssuesArisingFromVettingLabel", "READONLY", "1", 1, 20, true, "N", "etICJuridictionCodesInvalid=\"dummy\"", null, null, null, null),
        field(ENGLAND_WALES, "etICMinimumInfoFromVettingLabel", "READONLY", "1", 1, 20, true, "N", null, null, null, null, null),
        field(SCOTLAND, "icEt1VettingIssuesDetail", "READONLY", "1", 1, 21, true, "N", "etICJuridictionCodesInvalid=\"dummy\"", null, null, null, null),
        field(ENGLAND_WALES, "icEt1VettingIssuesDetailLabel", "READONLY", "1", 1, 21, true, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "et3DoWeHaveRespondentsName", "READONLY", "1", 1, 22, true, "N", "etICIssuesArisingFromVettingLabel=\"dummy\"", null, null, null, null),
        field(SCOTLAND, "etICMinimumInfoFromVettingLabel", "READONLY", "1", 1, 22, true, "N", "etICJuridictionCodesInvalid=\"dummy\"", null, null, null, null),
        field(ENGLAND_WALES, "et3DoesRespondentsNameMatch", "READONLY", "1", 1, 23, true, "N", "et3DoWeHaveRespondentsName=\"dummy\"", null, null, null, null),
        field(SCOTLAND, "icEt1VettingIssuesDetailLabel", "READONLY", "1", 1, 23, true, "N", "etICJuridictionCodesInvalid=\"dummy\"", null, null, null, null),
        field(SCOTLAND, "et3DoWeHaveRespondentsName", "READONLY", "1", 1, 24, true, "N", "etICJuridictionCodesInvalid=\"dummy\"", null, null, null, null),
        field(ENGLAND_WALES, "et3RespondentNameMismatchDetails", "READONLY", "1", 1, 24, true, "N", "et3DoesRespondentsNameMatch=\"dummy\"", null, null, null, null),
        field(SCOTLAND, "et3DoesRespondentsNameMatch", "READONLY", "1", 1, 25, true, "N", "et3DoWeHaveRespondentsName=\"Yes\"", null, null, null, null),
        field(ENGLAND_WALES, "icEt3ProcessingIssuesDetailDividerHrLabel", "READONLY", "1", 1, 25, true, "N", null, null, null, null, null),
        field(SCOTLAND, "et3RespondentNameMismatchDetails", "READONLY", "1", 1, 26, true, "N", "et3DoesRespondentsNameMatch=\"No\"", null, null, null, null),
        field(ENGLAND_WALES, "icEt3ProcessingIssuesDetail", "READONLY", "1", 1, 26, true, "N", "icEt3ProcessingIssuesDetailLabel=\"dummy\"", null, null, null, null),
        field(SCOTLAND, "icEt3ProcessingIssuesDetailDividerHrLabel", "READONLY", "1", 1, 27, true, "N", "etICJuridictionCodesInvalid=\"dummy\"", null, null, null, null),
        field(ENGLAND_WALES, "icEt3ProcessingIssuesDetailLabel", "READONLY", "1", 1, 27, true, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "icEt3ProcessingIssuesBottomDividerHrLabel", "READONLY", "1", 1, 28, true, "N", null, null, null, null, null),
        field(SCOTLAND, "icEt3ProcessingIssuesDetail", "READONLY", "1", 1, 28, true, "N", "etICJuridictionCodesInvalid=\"dummy\"", null, null, null, null),
        field(ENGLAND_WALES, "etIcHearingPanelPreferenceLabel", "READONLY", "1", 1, 29, true, "N", "etIcHearingPanelPreference=\"dummy\"", null, null, null, null),
        field(SCOTLAND, "icEt3ProcessingIssuesDetailLabel", "READONLY", "1", 1, 29, true, "N", "etICJuridictionCodesInvalid=\"dummy\"", null, null, null, null),
        field(ENGLAND_WALES, "etIcHearingPanelPreference", "READONLY", "1", null, 30, true, "N", "etIcHearingPanelPreferenceLabel=\"dummy\"", null, null, null, null),
        field(SCOTLAND, "icEt3ProcessingIssuesBottomDividerHrLabel", "READONLY", "1", 1, 30, true, "N", null, null, null, null, null),
        field(ALL, "etICJuridictionCodesInvalid", "MANDATORY", "1", 1, 31, true, "Y", null, null, null, null, null),
        field(ALL, "etICInvalidDetails", "MANDATORY", "1", 1, 32, true, "Y", "etICJuridictionCodesInvalid=\"Yes\"", null, null, null, null),
        field(ENGLAND_WALES, "etICCanProceed", "MANDATORY", "1", 1, 33, true, "Y", null, null, null, null, "Y"),
        field(SCOTLAND, "etICCanProceed", "MANDATORY", "1", 1, 33, true, "Y", null, null, null, "Rule 26", "Y"),
        field(SCOTLAND, "etICHearingNotListedRespondentLabel", "READONLY", "2", 2, 1, true, "N", null, null, "etICCanProceed=\"Yes\" AND etICHearingAlreadyListed=\"No\"", "Rule 27", null),
        field(ENGLAND_WALES, "initialConsiderationBeforeYouStartLabel2", "READONLY", "2", 2, 1, true, "N", null, null, null, "Rule 27", null),
        field(SCOTLAND, "etICHearingNotListedHearingLabel", "READONLY", "2", 2, 2, false, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etICHearingNotListedRespondentLabel", "READONLY", "2", 2, 2, true, "N", null, null, "etICCanProceed=\"Yes\" AND etICHearingAlreadyListed=\"No\"", null, null),
        field(ENGLAND_WALES, "etICHearingNotListedHearingLabel", "READONLY", "2", 2, 3, false, "N", null, null, null, null, null),
        field(SCOTLAND, "notListedHearingPartiesPanelPreferenceLabel", "READONLY", "2", 2, 3, false, "N", null, null, null, null, null),
        field(SCOTLAND, "notListedHearingPartiesHearingFormatLabel", "READONLY", "2", 2, 4, false, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "notListedHearingPartiesPanelPreferenceLabel", "READONLY", "2", 2, 4, false, "N", null, null, null, null, null),
        field(SCOTLAND, "etICHearingNotListedJurCodesLabel", "READONLY", "2", 2, 5, false, "N", null, null, null, null, null),
        field(SCOTLAND, "etICHearingNotListedList", "MANDATORY", "2", 2, 5, false, "Y", "etICCanProceed=\"dummy\"", null, null, null, "Y"),
        field(ENGLAND_WALES, "notListedHearingPartiesHearingFormatLabel", "READONLY", "2", 2, 5, false, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etICHearingNotListedJurCodesLabel", "READONLY", "2", 2, 6, false, "N", null, null, null, null, null),
        field(SCOTLAND, "etICHearingNotListedListUpdated", "MANDATORY", "2", 2, 6, false, "Y", null, null, null, null, "Y"),
        field(ENGLAND_WALES, "etICHearingNotListedList", "MANDATORY", "2", 2, 7, false, "Y", "etICCanProceed=\"dummy\"", null, null, null, "Y"),
        field(SCOTLAND, "etICHearingNotListedListForPrelimHearingUpdated", "COMPLEX", "2", 2, 7, false, "Y", "etICHearingNotListedListUpdated CONTAINS \"List for preliminary hearing\"", null, null, null, null),
        field(SCOTLAND, "etICHearingNotListedListForFinalHearingUpdated", "COMPLEX", "2", 2, 8, false, "Y", "etICHearingNotListedListUpdated CONTAINS \"List for final hearing\"", null, null, null, null),
        field(ENGLAND_WALES, "etICHearingNotListedListUpdatedDividerHrLabel", "READONLY", "2", 2, 8, false, "Y", null, null, null, null, "Y"),
        field(SCOTLAND, "etICHearingNotListedAnyOtherDirections", "OPTIONAL", "2", 2, 9, false, "Y", null, null, null, null, null),
        field(ENGLAND_WALES, "etICHearingNotListedListUpdated", "MANDATORY", "2", 2, 9, false, "Y", null, null, null, null, "Y"),
        field(ENGLAND_WALES, "etICHearingNotListedSeekComments", "COMPLEX", "2", 2, 10, false, "Y", "etICHearingNotListedList=\"dummy\"", null, null, null, null),
        field(SCOTLAND, "icDocumentCollection1", "COMPLEX", "2", 2, 10, false, "Y", null, null, null, null, null),
        field(SCOTLAND, "etICHearingAlreadyListed", "MANDATORY", "2", 2, 11, false, null, "etICCanProceed=\"dummy\"", "Yes", null, null, "Y"),
        field(ENGLAND_WALES, "etICHearingNotListedListForPrelimHearing", "COMPLEX", "2", 2, 11, false, "Y", "etICHearingNotListedList=\"dummy\"", null, null, null, null),
        field(ENGLAND_WALES, "etICHearingNotListedListForPrelimHearingUpdated", "COMPLEX", "2", 2, 11, false, "Y", "etICHearingNotListedListUpdated CONTAINS \"List for preliminary hearing\"", null, null, null, null),
        field(ENGLAND_WALES, "etICHearingNotListedListForFinalHearing", "COMPLEX", "2", 2, 12, false, "Y", "etICHearingNotListedList=\"dummy\"", null, null, null, null),
        field(ENGLAND_WALES, "etICHearingNotListedListForFinalHearingUpdated", "COMPLEX", "2", 2, 12, false, "Y", "etICHearingNotListedListUpdated CONTAINS \"List for final hearing\"", null, null, null, null),
        field(ENGLAND_WALES, "etICHearingNotListedUDLHearing", "COMPLEX", "2", 2, 13, false, "Y", "etICHearingNotListedList=\"dummy\"", null, null, null, null),
        field(ENGLAND_WALES, "etICHearingAlreadyListed", "OPTIONAL", "2", 2, 14, false, null, "etICCanProceed=\"dummy\"", "Yes", null, null, null),
        field(ENGLAND_WALES, "etICAnyOtherDirectionsDividerHrLabel", "READONLY", "2", 2, 15, false, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etICHearingNotListedAnyOtherDirectionsLabel", "READONLY", "2", 2, 16, false, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etICHearingNotListedAnyOtherDirections", "OPTIONAL", "2", 2, 17, false, "Y", null, null, null, null, null),
        field(ENGLAND_WALES, "etICUploadDocDividerHrLabel", "READONLY", "2", 2, 18, false, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "icDocumentCollection1", "COMPLEX", "2", 2, 19, false, "Y", null, null, null, null, null),
        field(ENGLAND_WALES, "etICNavigationButtonsDividerHrLabel", "READONLY", "2", 2, 20, false, "N", null, null, null, null, null),
        field(SCOTLAND, "etICHearingNotListedSeekComments", "COMPLEX", "2", 2, 55, false, "Y", "etICHearingNotListedList CONTAINS \"dummy\"", null, null, null, null),
        field(SCOTLAND, "etICHearingNotListedListForPrelimHearing", "COMPLEX", "2", 2, 56, false, "Y", "etICHearingNotListedList CONTAINS \"dummy\"", null, null, null, null),
        field(SCOTLAND, "etICHearingNotListedListForFinalHearing", "COMPLEX", "2", 2, 57, false, "Y", "etICHearingNotListedList CONTAINS \"dummy\"", null, null, null, null),
        field(SCOTLAND, "etICHearingNotListedUDLHearing", "COMPLEX", "2", 2, 58, false, "Y", "etICHearingNotListedList CONTAINS \"dummy\"", null, null, null, null),
        field(SCOTLAND, "etICRespondentHearingListed", "READONLY", "3", 3, 1, true, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "initialConsiderationBeforeYouStartLabel3", "READONLY", "3", 3, 1, false, "N", null, null, null, null, null),
        field(SCOTLAND, "etICHearingHearingListed", "READONLY", "3", 3, 2, true, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etICHearingListedRespondentLabel", "READONLY", "3", 3, 2, false, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etICHearingListedHearingLabel", "READONLY", "3", 3, 3, true, "N", null, null, null, null, null),
        field(SCOTLAND, "listedHearingPartiesPanelPreferenceLabel", "READONLY", "3", 3, 3, false, "N", null, null, null, null, null),
        field(SCOTLAND, "listedHearingPartiesHearingFormatLabel", "READONLY", "3", 3, 4, false, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "listedHearingPartiesPanelPreferenceLabel", "READONLY", "3", 3, 4, true, "N", null, null, null, null, null),
        field(SCOTLAND, "etICJurisdictionCodesHearingListed", "READONLY", "3", 3, 5, true, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "listedHearingPartiesHearingFormatLabel", "READONLY", "3", 3, 5, true, "N", null, null, null, null, null),
        field(SCOTLAND, "etICHearingListedAnswers", "COMPLEX", "3", 3, 6, false, "Y", null, null, "etICCanProceed=\"Yes\" AND etICHearingAlreadyListed=\"Yes\"", null, null),
        field(ENGLAND_WALES, "etICHearingListedJurisdictionCodesLabel", "READONLY", "3", 3, 6, true, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etICHearingListedAnswers", "COMPLEX", "3", 3, 7, false, "Y", null, null, "etICCanProceed=\"Yes\" AND etICHearingAlreadyListed=\"Yes\"", null, null),
        field(SCOTLAND, "icDocumentCollection2", "COMPLEX", "3", 3, 7, false, "Y", null, null, null, null, null),
        field(ENGLAND_WALES, "etICUploadDocDividerHrLabel3", "READONLY", "3", 3, 8, false, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "icDocumentCollection2", "COMPLEX", "3", 3, 9, false, "Y", null, null, null, null, null),
        field(SCOTLAND, "etICRespondentFurtherInfo", "READONLY", "4", 4, 1, true, "N", null, null, "etICCanProceed=\"No\"", "Rule 27", null),
        field(ENGLAND_WALES, "initialConsiderationBeforeYouStartLabel4", "READONLY", "4", 4, 1, false, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etICFurtherInfoRespondentLabel", "READONLY", "4", 4, 2, false, "N", null, null, "etICCanProceed=\"No\"", null, null),
        field(SCOTLAND, "etICHearingFurtherInfo", "READONLY", "4", 4, 2, true, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etICFurtherInfoHearingLabel", "READONLY", "4", 4, 3, true, "N", null, null, null, null, null),
        field(SCOTLAND, "etICJurisdictionCodesFurtherInfo", "READONLY", "4", 4, 3, true, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etICFurtherInfoJurisdictionCodesLabel", "READONLY", "4", 4, 4, true, "N", null, null, null, null, null),
        field(SCOTLAND, "etICFurtherInformation", "OPTIONAL", "4", 4, 4, true, "Y", null, null, null, null, null),
        field(ENGLAND_WALES, "etICFurtherInformation", "OPTIONAL", "4", 4, 5, false, "Y", null, "No", null, null, null),
        field(SCOTLAND, "etICFurtherInformationGiveDetails", "MANDATORY", "4", 4, 5, true, "Y", "etICFurtherInformation CONTAINS \"furtherInformationRequired\"", null, null, "Rule 27", null),
        field(ENGLAND_WALES, "etICFurtherInfoAnswers", "MANDATORY", "4", 4, 6, false, "Y", "etICFurtherInformation CONTAINS \"Further information required\"", "No", null, null, null),
        field(SCOTLAND, "etICFurtherInformationTimeToComply", "MANDATORY", "4", 4, 6, true, "Y", "etICFurtherInformation CONTAINS \"furtherInformationRequired\"", null, null, "Rule 27", null),
        field(ENGLAND_WALES, "etInitialConsiderationRule27", "MANDATORY", "4", 4, 7, false, "Y", "etICFurtherInformation CONTAINS \"Issue Rule 27 Notice and order\"", "No", null, null, "Y"),
        field(SCOTLAND, "etInitialConsiderationRule27", "COMPLEX", "4", 4, 7, true, "Y", "etICFurtherInformation CONTAINS \"issueRule27\"", null, null, null, null),
        field(ENGLAND_WALES, "etInitialConsiderationRule28", "MANDATORY", "4", 4, 8, false, "Y", "etICFurtherInformation CONTAINS \"Issue Rule 28 Notice and order\"", "No", null, null, "Y"),
        field(SCOTLAND, "etInitialConsiderationRule28", "COMPLEX", "4", 4, 8, true, "Y", "etICFurtherInformation CONTAINS \"issueRule28\"", null, null, null, null),
        field(SCOTLAND, "etICFurtherInformationHearingAnyOtherDirections", "OPTIONAL", "4", 4, 9, true, "Y", null, null, null, "Rule 27", null),
        field(ENGLAND_WALES, "etICFurtherInformationHearingAnyOtherDirectionsLabel", "READONLY", "4", 4, 9, false, "N", null, null, null, null, null),
        field(ENGLAND_WALES, "etICFurtherInformationHearingAnyOtherDirections", "OPTIONAL", "4", 4, 10, false, "Y", null, null, null, null, null),
        field(SCOTLAND, "icDocumentCollection3", "COMPLEX", "4", 4, 10, false, "Y", null, null, null, null, null),
        field(ENGLAND_WALES, "icDocumentCollection3", "COMPLEX", "4", 4, 11, false, "Y", null, null, null, null, null)
    };

    static final ComplexFieldSpec[] COMPLEX_FIELDS = {
        element(ALL, "InitialConsideration", "etICHearingListedAnswers", "etICHearingListed", "MANDATORY", 1, null, null, null),
        element(ALL, "InitialConsideration", "etICHearingListedAnswers", "etICExtendDurationGiveDetails", "MANDATORY", 2, null, null, null),
        element(ALL, "InitialConsideration", "etICHearingListedAnswers", "etICOtherGiveDetails", "MANDATORY", 3, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithJudgeOrMembers", "MANDATORY", 4, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICPostponeGiveDetails", "MANDATORY", 4, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICConvertPreliminaryGiveDetails", "MANDATORY", 5, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithJudgeOrMembersReason", "MANDATORY", 5, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICConvertF2fGiveDetails", "MANDATORY", 6, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICIsFinalHearingWithJudgeOrMembersJsaReason", "MANDATORY", 6, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICExtendDurationGiveDetails", "MANDATORY", 7, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICIsFinalHearingWithJudgeOrMembersReason", "MANDATORY", 7, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithJudgeOrMembersReasonOther", "MANDATORY", 8, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICOtherGiveDetails", "MANDATORY", 8, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithJudgeOrMembers", "MANDATORY", 9, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICJsaFinalHearingReasonOther", "MANDATORY", 9, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithJudgeOrMembersReason", "MANDATORY", 10, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICMembersFinalHearingReasonOther", "MANDATORY", 10, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICIsFinalHearingWithJudgeOrMembersJsaReason", "MANDATORY", 11, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etInitialConsiderationListedHearingType", "READONLY", 11, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICIsFinalHearingWithJudgeOrMembersReason", "MANDATORY", 12, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithJsa", "MANDATORY", 12, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithJsaReasonOther", "MANDATORY", 13, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithJudgeOrMembersReasonOther", "MANDATORY", 13, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICJsaCmPreliminaryHearingReasonOther", "MANDATORY", 14, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICJsaFinalHearingReasonOther", "MANDATORY", 14, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithMembers", "MANDATORY", 15, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICMembersFinalHearingReasonOther", "MANDATORY", 15, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithJudgeOrMembersFurtherDetails", "OPTIONAL", 16, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etInitialConsiderationListedHearingType", "READONLY", 16, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithJsa", "MANDATORY", 17, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "otherDirectionsLabel", "READONLY", 17, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICAnyOtherDirectionsDividerHrLabel3", "OPTIONAL", 18, " ", "No", null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithJsaReasonOther", "MANDATORY", 18, null, null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingListedAnswers", "etICHearingAnyOtherDirections", "OPTIONAL", 19, " ", "No", null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICJsaCmPreliminaryHearingReasonOther", "MANDATORY", 19, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithMembers", "MANDATORY", 20, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICIsHearingWithJudgeOrMembersFurtherDetails", "OPTIONAL", 21, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "otherDirectionsLabel", "READONLY", 22, null, null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingListedAnswers", "etICHearingAnyOtherDirections", "OPTIONAL", 23, " ", "No", null),
        element(ALL, "InitialConsideration", "etICHearingNotListedListForFinalHearing", "etICTypeOfFinalHearing", "MANDATORY", 1, "Type of final hearing", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForFinalHearing", "etICLengthOfFinalHearing", "MANDATORY", 2, "Length of hearing", "No", null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearing", "etICLengthOfFinalHearing", "MANDATORY", 2, "Length of hearing", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForFinalHearing", "finalHearingLengthNumType", "MANDATORY", 3, "Days, Hours or Minutes", "No", null),
        element(ALL, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICTypeOfFinalHearingV2", "MANDATORY", 1, "Type of final hearing", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICHearingOrderBUCompliance", "OPTIONAL", 2, "BU to check compliance with orders?", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICLengthOfFinalHearingV2", "MANDATORY", 2, "Length of hearing", "No", null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICLengthOfFinalHearingV2", "MANDATORY", 2, "Length of hearing", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICTypeOfF2fHearingOrder", "OPTIONAL", 2, "Issue standard orders when listed", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICTypeOfVideoHearingOrder", "OPTIONAL", 2, "Issue standard video orders when listed", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "finalHearingLengthNumTypeV2", "MANDATORY", 3, "Days, Hours or Minutes", "No", null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "finalHearingLengthNumTypeV2", "MANDATORY", 3, "Days, Hours or Minutes", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICFinalHearingIsEJSitAlone", "MANDATORY", 4, "Do you consider this final hearing should be listed judge alone or with members?", "No", null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICFinalHearingPanelComposition", "MANDATORY", 4, "<hr><h3>Panel Composition</h3>", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICFinalHearingIsEJSitAlone", "MANDATORY", 5, "EJ sit alone?", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICFinalHearingIsEJSitAloneReasonYes", "MANDATORY", 5, "Reasons for JSA", "No", null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICFinalHearingIsEJSitAloneReason", "MANDATORY", 6, "Give reason for requesting EJ sit alone:", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICNoLFinalHearingIsEJSitAloneReasonsJsaOther", "MANDATORY", 6, "Reason for JSA - Other", "No", null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICFinalHearingIsEJSitAloneReasonNo", "MANDATORY", 7, "Reasons for Members", "No", null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICNoLFinalHearingIsEJSitAloneReasonsJsaOther", "MANDATORY", 7, "Reasons", "No", null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICNoLFinalHearingIsEJSitAloneReasonsMembersOther", "MANDATORY", 8, "Reason for Members - Other", "No", null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICNoLFinalHearingIsEJSitAloneReasonsMembersOther", "MANDATORY", 8, "Reasons", "No", null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICFinalHearingIsEJSitAloneFurtherDetails", "OPTIONAL", 9, "Further details", "No", null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICFinalHearingIsEJSitAloneReasonYes", "MANDATORY", 9, "Reason for JSA", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICFinalHearingIsEJSitAloneReasonYesOther", "MANDATORY", 10, "Reason for JSA", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICFinalHearingIsEJSitAloneReasonNo", "MANDATORY", 11, "Reason for full Panel", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICFinalHearingIsEJSitAloneReasonNoOther", "MANDATORY", 12, "Other Reason (EJ Sit Alone: No)", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICFinalHearingPanelCompositionBottomDivider", "READONLY", 13, "<hr>", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForFinalHearingUpdated", "etICFinalHearingIsEJSitAloneFurtherDetails", "OPTIONAL", 114, "Further details", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedListForPrelimHearing", "etICTypeOfPreliminaryHearing", "MANDATORY", 1, "Type of preliminary hearing", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedListForPrelimHearing", "etICPurposeOfPreliminaryHearing", "MANDATORY", 2, "Purpose of preliminary hearing", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForPrelimHearing", "etICGiveDetailsOfHearingNotice", "MANDATORY", 3, "Give details of hearing notice", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForPrelimHearing", "etICGiveDetailsOfHearingNotice", "OPTIONAL", 3, "Give details of hearing notice", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForPrelimHearing", "etICLengthOfPrelimHearing", "MANDATORY", 4, "Length of hearing", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForPrelimHearing", "prelimHearingLengthNumType", "MANDATORY", 5, "Days, Hours or Minutes", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedListForPrelimHearingUpdated", "etICTypeOfPreliminaryHearingV2", "MANDATORY", 1, "Type of preliminary hearing", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedListForPrelimHearingUpdated", "etICPurposeOfPreliminaryHearingV2", "MANDATORY", 2, "Purpose of preliminary hearing", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForPrelimHearingUpdated", "etICGiveDetailsOfHearingNoticeV2", "MANDATORY", 3, "Give details of hearing notice", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedListForPrelimHearingUpdated", "etICGiveDetailsOfHearingNoticeV2", "OPTIONAL", 3, "Give details of hearing notice", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedListForPrelimHearingUpdated", "etICLengthOfPrelimHearing", "MANDATORY", 4, "Length of hearing", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedListForPrelimHearingUpdated", "etICLengthOfPrelimHearingV2", "MANDATORY", 4, "Length of hearing", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedListForPrelimHearingUpdated", "prelimHearingLengthNumTypeV2", "MANDATORY", 5, "Days, Hours or Minutes", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedListForPrelimHearingUpdated", "etICIsPreliminaryHearingWithMembersV2", "MANDATORY", 6, "Do you consider this preliminary hearing should be listed with members?", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedListForPrelimHearingUpdated", "etICIsPreliminaryHearingWithMembersReasonV2", "MANDATORY", 7, "Give reasons for requiring members", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedSeekComments", "etICTypeOfCvpHearing", "MANDATORY", 1, "Type of Video hearing", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedSeekComments", "etICTypeOfCvpHearing", "MANDATORY", 1, "Type of CVP hearing", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedSeekComments", "etICFinalHearingDetails", "MANDATORY", 2, "Give details of final hearing", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedSeekComments", "etICPrelimHearingDetails", "MANDATORY", 3, "Give details of preliminary hearing", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedSeekComments", "etICPrelimHearingYesNo", "MANDATORY", 4, "Should the case be listed for a private preliminary hearing?", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICEJSitAlone", "MANDATORY", 1, "EJ sit alone?", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICUDLGiveReasons", "MANDATORY", 2, "Give reasons", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICUDLDisputeOnFacts", "MANDATORY", 3, "Likelihood of dispute on facts makes full tribunal desirable", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICUDLLittleOrNoAgreement", "MANDATORY", 4, "Little or no agreement on facts", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICUDLIssueOfLawArising", "MANDATORY", 5, "Likelihood of issue of law arising makes EJSA desirable", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICUDLViewsOfParties", "MANDATORY", 6, "Views of parties", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICUDLNoViewsExpressedByParties", "MANDATORY", 7, "No views expressed by parties", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICUDLConcurrentProceedings", "MANDATORY", 8, "Concurrent proceedings", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICUDLOther", "MANDATORY", 9, "Other", null, null),
        element(ALL, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICUDLHearFormat", "MANDATORY", 10, "Hearing format", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICUDLCVPIssue", "MANDATORY", 11, "Issue standard Video orders when listed", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICUDLCVPIssue", "MANDATORY", 11, "Issue standard CVP orders when listed", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICUDLFinalF2FIssue", "MANDATORY", 12, "Issue standard orders when listed", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICUDLFinalF2FIssue", "OPTIONAL", 12, "Issue standard orders when listed", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICBUCheckComplianceOrders", "MANDATORY", 13, "BU to check compliance with orders?", null, null),
        element(SCOTLAND, "InitialConsideration", "etICHearingNotListedUDLHearing", "etICBUCheckComplianceOrders", "OPTIONAL", 13, "BU to check compliance with orders?", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etInitialConsiderationRule27", "etICRule27ClaimToBe", "OPTIONAL", 1, null, "No", null),
        element(SCOTLAND, "InitialConsideration", "etInitialConsiderationRule27", "etICRule27ClaimToBe", "MANDATORY", 1, "Claim to be", null, "Y"),
        element(ENGLAND_WALES, "InitialConsideration", "etInitialConsiderationRule27", "etICRule27WhichPart", "OPTIONAL", 2, null, "No", null),
        element(SCOTLAND, "InitialConsideration", "etInitialConsiderationRule27", "etICRule27WhichPart", "MANDATORY", 2, "Which part?", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etInitialConsiderationRule27", "etICRule27Direction", "OPTIONAL", 3, null, "No", null),
        element(SCOTLAND, "InitialConsideration", "etInitialConsiderationRule27", "etICRule27Direction", "MANDATORY", 3, "Employment Judge's direction for Rule 28 Notice", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etInitialConsiderationRule27", "etICRule27DirectionReason", "OPTIONAL", 4, null, "No", null),
        element(SCOTLAND, "InitialConsideration", "etInitialConsiderationRule27", "etICRule27NoJurisdictionReason", "MANDATORY", 4, "No jurisdiction - Set out reason", null, null),
        element(SCOTLAND, "InitialConsideration", "etInitialConsiderationRule27", "etICRule27DirectionReason", "MANDATORY", 5, "No reasonable prospect of success - Set out reason", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etInitialConsiderationRule27", "etICRule27NumberOfDays", "OPTIONAL", 5, null, "No", null),
        element(SCOTLAND, "InitialConsideration", "etInitialConsiderationRule27", "etICRule27NumberOfDays", "MANDATORY", 6, "Number of days for claimant to provide written representations", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etInitialConsiderationRule28", "etICRule28ClaimToBe", "OPTIONAL", 1, null, "No", null),
        element(SCOTLAND, "InitialConsideration", "etInitialConsiderationRule28", "etICRule28ClaimToBe", "MANDATORY", 1, "Response to be", null, "Y"),
        element(ENGLAND_WALES, "InitialConsideration", "etInitialConsiderationRule28", "etICRule28WhichPart", "OPTIONAL", 2, null, "No", null),
        element(SCOTLAND, "InitialConsideration", "etInitialConsiderationRule28", "etICRule28WhichPart", "MANDATORY", 2, "Which part?", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etInitialConsiderationRule28", "etICRule28DirectionReason", "OPTIONAL", 3, null, "No", null),
        element(SCOTLAND, "InitialConsideration", "etInitialConsiderationRule28", "etICRule28DirectionReason", "MANDATORY", 3, "Employment Judge's reasons", null, null),
        element(ENGLAND_WALES, "InitialConsideration", "etInitialConsiderationRule28", "etICRule28NumberOfDays", "OPTIONAL", 4, null, "No", null),
        element(SCOTLAND, "InitialConsideration", "etInitialConsiderationRule28", "etICRule28NumberOfDays", "MANDATORY", 4, "Number of days for respondent to provide written representations", null, null),
        element(ALL, "icDocumentUpload", "icAllDocumentCollection", "shortDescription", "OPTIONAL", 1, null, null, null),
        element(ALL, "icDocumentUpload", "icAllDocumentCollection", "uploadedDocument", "MANDATORY", 1, null, null, null),
        element(ALL, "icDocumentUpload", "icDocumentCollection1", "shortDescription", "OPTIONAL", 1, null, null, null),
        element(ALL, "icDocumentUpload", "icDocumentCollection1", "uploadedDocument", "MANDATORY", 1, null, null, null),
        element(ALL, "icDocumentUpload", "icDocumentCollection2", "shortDescription", "OPTIONAL", 1, null, null, null),
        element(ALL, "icDocumentUpload", "icDocumentCollection2", "uploadedDocument", "MANDATORY", 1, null, null, null),
        element(ALL, "icDocumentUpload", "icDocumentCollection3", "shortDescription", "OPTIONAL", 1, null, null, null),
        element(ALL, "icDocumentUpload", "icDocumentCollection3", "uploadedDocument", "MANDATORY", 1, null, null, null)
    };

    private SingleInitialConsiderationRows() {}

    private static EventSpec event(int mask, int displayOrder, String callbackBase) {
        return new EventSpec(
                mask,
                INITIAL_CONSIDERATION,
                "Initial Consideration",
                "Initial Consideration",
                displayOrder,
                "Accepted",
                "*",
                null,
                "Y",
                "N",
                "Y",
                false,
                null,
                callbackBase + "/startInitialConsideration",
                callbackBase + "/submitInitialConsideration",
                callbackBase + "/completeInitialConsideration");
    }

    private static EventFieldSpec field(
            int mask,
            String fieldId,
            String context,
            String pageId,
            Integer pageOrder,
            Integer fieldOrder,
            boolean pageColumn,
            String showSummary,
            String condition,
            String retainHidden,
            String pageCondition,
            String pageLabel,
            String publish) {
        return new EventFieldSpec(
                mask,
                INITIAL_CONSIDERATION,
                fieldId,
                context,
                pageId,
                pageOrder,
                fieldOrder,
                pageColumn,
                showSummary,
                condition,
                retainHidden,
                pageCondition,
                pageLabel,
                null,
                publish);
    }

    private static ComplexFieldSpec element(
            int mask,
            String rowId,
            String caseFieldId,
            String elementCode,
            String context,
            int order,
            String label,
            String retainHidden,
            String publish) {
        return new ComplexFieldSpec(
                mask,
                rowId,
                INITIAL_CONSIDERATION,
                caseFieldId,
                elementCode,
                context,
                order,
                label,
                null,
                null,
                retainHidden,
                null,
                publish);
    }
}
