package uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config;

import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.SingleRole;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.ComplexFieldSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.EventFieldSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.EventSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.GrantSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.domain.caseview.state.CaseState;

import java.util.Set;

@SuppressWarnings({
    "checkstyle:LineLength",
    "checkstyle:RightCurlyAlone",
    "PMD.AvoidDuplicateLiterals"
})
final class SingleEt3ProcessingRows {
    private static final int CFTLIB_ENGLAND_WALES = 1;
    private static final int CFTLIB_SCOTLAND = 2;
    private static final int CFTLIB = 3;
    private static final int PROD_ENGLAND_WALES = 4;
    private static final int ENGLAND_WALES = 5;
    private static final int PROD_SCOTLAND = 8;
    private static final int SCOTLAND = 10;
    private static final int PROD = 12;
    private static final int ALL = 15;
    private static final String LOCALHOST = "http://localhost:8081";
    private static final String PRODUCTION =
            "http://et-cos-prod.service.core-compute-prod.internal";
    private static final String ET3_VETTING = "et3Vetting";
    private static final String ET3_NOTIFICATION = "et3Notification";

    static final GrantSpec[] EVENT_GRANTS = {
        new GrantSpec(ALL, ET3_VETTING, SingleRole.CASEWORKER_EMPLOYMENT, "R"),
        new GrantSpec(ALL, ET3_VETTING, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(
                ENGLAND_WALES, ET3_VETTING, SingleRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, "CRU"),
        new GrantSpec(ALL, ET3_VETTING, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE, "R"),
        new GrantSpec(
                ENGLAND_WALES,
                ET3_VETTING,
                SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES,
                "CRU"),
        new GrantSpec(
                SCOTLAND, ET3_VETTING, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_SCOTLAND, "CRU"),
        new GrantSpec(SCOTLAND, ET3_VETTING, SingleRole.CASEWORKER_EMPLOYMENT_SCOTLAND, "CRU"),
        new GrantSpec(ALL, ET3_VETTING, SingleRole.CASEWORKER_WA_TASK_CONFIGURATION, "CRU"),
        new GrantSpec(SCOTLAND, ET3_VETTING, SingleRole.ET_ACAS_API, "R"),
        new GrantSpec(ALL, ET3_NOTIFICATION, SingleRole.CASEWORKER_EMPLOYMENT, "R"),
        new GrantSpec(ALL, ET3_NOTIFICATION, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(
                ENGLAND_WALES,
                ET3_NOTIFICATION,
                SingleRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES,
                "CRU"),
        new GrantSpec(ALL, ET3_NOTIFICATION, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE, "R"),
        new GrantSpec(
                ENGLAND_WALES,
                ET3_NOTIFICATION,
                SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES,
                "CRU"),
        new GrantSpec(
                SCOTLAND,
                ET3_NOTIFICATION,
                SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_SCOTLAND,
                "CRU"),
        new GrantSpec(SCOTLAND, ET3_NOTIFICATION, SingleRole.CASEWORKER_EMPLOYMENT_SCOTLAND, "CRU"),
        new GrantSpec(SCOTLAND, ET3_NOTIFICATION, SingleRole.ET_ACAS_API, "R")
    };

    static final EventSpec[] EVENTS = {
        new EventSpec(
                CFTLIB,
                ET3_VETTING,
                "ET3 Processing",
                "ET3 Processing",
                18,
                "Accepted",
                "*",
                "managingOffice !=\"Unassigned\"",
                "Y",
                "N",
                "Y",
                false,
                null,
                LOCALHOST + "/et3Vetting/aboutToStart",
                LOCALHOST + "/et3Vetting/aboutToSubmit",
                LOCALHOST + "/et3Vetting/processingComplete",
                null),
        new EventSpec(
                PROD,
                ET3_VETTING,
                "ET3 Processing",
                "ET3 Processing",
                18,
                "Accepted",
                "*",
                "managingOffice !=\"Unassigned\"",
                "Y",
                "N",
                "Y",
                false,
                null,
                PRODUCTION + "/et3Vetting/aboutToStart",
                PRODUCTION + "/et3Vetting/aboutToSubmit",
                PRODUCTION + "/et3Vetting/processingComplete",
                null),
        new EventSpec(
                CFTLIB,
                ET3_NOTIFICATION,
                "ET3 notification",
                "ET3 notification",
                19,
                "Accepted",
                "*",
                null,
                "N",
                "N",
                null,
                false,
                null,
                LOCALHOST + "/et3Notification/aboutToStart",
                LOCALHOST + "/et3Notification/aboutToSubmit",
                LOCALHOST + "/et3Notification/submitted",
                null),
        new EventSpec(
                PROD,
                ET3_NOTIFICATION,
                "ET3 notification",
                "ET3 notification",
                19,
                "Accepted",
                "*",
                null,
                "N",
                "N",
                null,
                false,
                null,
                PRODUCTION + "/et3Notification/aboutToStart",
                PRODUCTION + "/et3Notification/aboutToSubmit",
                PRODUCTION + "/et3Notification/submitted",
                null)
    };

    static final EventFieldSpec[] EVENT_FIELDS = {
        readOnly(ALL, ET3_VETTING, "horizontalLine", 1, 1, null, null, "Before you start", null),
        readOnly(
                ALL,
                ET3_VETTING,
                "et3VettingBeforeYouStart",
                1,
                2,
                null,
                null,
                "Before you start",
                null),
        field(
                CFTLIB,
                ET3_VETTING,
                "et3ChooseRespondent",
                "MANDATORY",
                2,
                1,
                false,
                null,
                null,
                null,
                null,
                "Select Respondent",
                LOCALHOST + "/et3Vetting/midPopulateRespondentEt3Response",
                null),
        field(
                PROD,
                ET3_VETTING,
                "et3ChooseRespondent",
                "MANDATORY",
                2,
                1,
                false,
                null,
                null,
                null,
                null,
                "Select Respondent",
                PRODUCTION + "/et3Vetting/midPopulateRespondentEt3Response",
                null),
        field(
                ALL,
                ET3_VETTING,
                "respondentCollection",
                "COMPLEX",
                2,
                2,
                true,
                "N",
                "et3ChooseRespondent=\"dummy\"",
                null,
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ET3_VETTING,
                "nextListedDate",
                "OPTIONAL",
                2,
                3,
                true,
                "N",
                "et3ChooseRespondent=\"dummy\"",
                null,
                null,
                null,
                null,
                "Y"),
        field(
                CFTLIB,
                ET3_VETTING,
                "et3Date",
                "READONLY",
                3,
                1,
                true,
                null,
                "et3DateLabel=\"dummy\"",
                null,
                null,
                "Minimum required information",
                LOCALHOST + "/et3Vetting/midCalculateResponseInTime",
                null),
        field(
                PROD,
                ET3_VETTING,
                "et3Date",
                "READONLY",
                3,
                1,
                true,
                null,
                "et3DateLabel=\"dummy\"",
                null,
                null,
                "Minimum required information",
                PRODUCTION + "/et3Vetting/midCalculateResponseInTime",
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3DateLabel",
                "READONLY",
                3,
                2,
                true,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        mandatory(ALL, ET3_VETTING, "et3IsThereAnEt3Response", 3, 3, null, null, null, null),
        field(
                ALL,
                ET3_VETTING,
                "et3NoEt3Response",
                "OPTIONAL",
                3,
                4,
                false,
                null,
                "et3IsThereAnEt3Response=\"No\"",
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3GeneralNotes",
                "OPTIONAL",
                3,
                5,
                false,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ET3_VETTING,
                "nextListedDate",
                "OPTIONAL",
                3,
                6,
                true,
                "N",
                "et3DateLabel=\"dummy\"",
                null,
                null,
                null,
                null,
                "Y"),
        field(
                ALL,
                ET3_VETTING,
                "et3DateCompanyHousePage",
                "READONLY",
                4,
                1,
                true,
                null,
                null,
                null,
                "et3IsThereAnEt3Response=\"No\"",
                "Rule 22 referral",
                null,
                null),
        optional(
                ALL,
                ET3_VETTING,
                "et3IsThereACompaniesHouseSearchDocument",
                4,
                2,
                null,
                null,
                null,
                null),
        mandatory(
                ALL,
                ET3_VETTING,
                "et3CompanyHouseDocument",
                4,
                3,
                "et3IsThereACompaniesHouseSearchDocument=\"Yes\"",
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3GeneralNotesCompanyHouse",
                "OPTIONAL",
                4,
                4,
                false,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        readOnly(
                ALL,
                ET3_VETTING,
                "et3DateIndividualInsolvency",
                5,
                1,
                null,
                "et3IsThereAnEt3Response=\"No\"",
                "Rule 22 referral",
                null),
        optional(
                ALL,
                ET3_VETTING,
                "et3IsThereAnIndividualSearchDocument",
                5,
                2,
                null,
                null,
                null,
                null),
        mandatory(
                ALL,
                ET3_VETTING,
                "et3IndividualInsolvencyDocument",
                5,
                3,
                "et3IsThereAnIndividualSearchDocument=\"Yes\"",
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3GeneralNotesIndividualInsolvency",
                "OPTIONAL",
                5,
                4,
                false,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        optional(
                ALL,
                ET3_VETTING,
                "et3LegalIssue",
                6,
                1,
                null,
                "et3IsThereAnEt3Response=\"No\"",
                "Rule 22 referral",
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3LegalIssueGiveDetails",
                "MANDATORY",
                6,
                2,
                false,
                null,
                "et3LegalIssue=\"Yes\"",
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3GeneralNotesLegalEntity",
                "OPTIONAL",
                6,
                3,
                false,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        readOnly(
                CFTLIB,
                ET3_VETTING,
                "et3ResponseInTimeDateLabel",
                7,
                1,
                null,
                "et3IsThereAnEt3Response=\"Yes\"",
                "Minimum required information",
                LOCALHOST + "/et3Vetting/midRespondentNameAndAddressTable"),
        readOnly(
                PROD,
                ET3_VETTING,
                "et3ResponseInTimeDateLabel",
                7,
                1,
                null,
                "et3IsThereAnEt3Response=\"Yes\"",
                "Minimum required information",
                PRODUCTION + "/et3Vetting/midRespondentNameAndAddressTable"),
        mandatory(ALL, ET3_VETTING, "et3ResponseInTime", 7, 2, null, null, null, null),
        optional(
                ALL,
                ET3_VETTING,
                "et3ResponseInTimeDetails",
                7,
                3,
                "et3ResponseInTime=\"No\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET3_VETTING,
                "et3ContactDetailsLabel",
                8,
                1,
                null,
                "et3IsThereAnEt3Response=\"Yes\"",
                "Minimum required information",
                null),
        readOnly(
                ALL,
                ET3_VETTING,
                "et3NameAddressRespondent",
                8,
                2,
                "et3NameAddressRespondentLabel=\"dummy\"",
                null,
                null,
                null),
        readOnly(ALL, ET3_VETTING, "et3NameAddressRespondentLabel", 8, 3, null, null, null, null),
        field(
                ALL,
                ET3_VETTING,
                "et3DoWeHaveRespondentsName",
                "MANDATORY",
                8,
                4,
                false,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3GeneralNotesRespondentName",
                "OPTIONAL",
                8,
                5,
                false,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        readOnly(
                ALL,
                ET3_VETTING,
                "et3ContactDetailsNameMismatchLabel",
                9,
                1,
                null,
                "et3IsThereAnEt3Response=\"Yes\" AND et3DoWeHaveRespondentsName=\"Yes\"",
                "Minimum required information",
                null),
        readOnly(
                ALL,
                ET3_VETTING,
                "et3NameAddressRespondentNameMismatchLabel",
                9,
                3,
                null,
                null,
                null,
                null),
        mandatory(ALL, ET3_VETTING, "et3DoesRespondentsNameMatch", 9, 4, null, null, null, null),
        field(
                ALL,
                ET3_VETTING,
                "et3RespondentNameMismatchDetails",
                "MANDATORY",
                9,
                5,
                false,
                "Y",
                "et3DoesRespondentsNameMatch=\"No\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3GeneralNotesRespondentNameMatch",
                "OPTIONAL",
                9,
                6,
                false,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        readOnly(
                ALL,
                ET3_VETTING,
                "et3ContactDetailsAddressLabel",
                10,
                1,
                null,
                "et3IsThereAnEt3Response=\"Yes\"",
                "Minimum required information",
                null),
        readOnly(
                ALL,
                ET3_VETTING,
                "et3NameAddressRespondentAddressLabel",
                10,
                3,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3DoWeHaveRespondentsAddress",
                "MANDATORY",
                10,
                4,
                false,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3GeneralNotesRespondentAddress",
                "OPTIONAL",
                10,
                5,
                false,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        readOnly(
                ALL,
                ET3_VETTING,
                "et3ContactDetailsAddressMismatchLabel",
                11,
                1,
                null,
                "et3IsThereAnEt3Response=\"Yes\" AND et3DoWeHaveRespondentsAddress=\"Yes\"",
                "Minimum required information",
                null),
        readOnly(
                ALL,
                ET3_VETTING,
                "et3NameAddressRespondentAddressMismatchLabel",
                11,
                3,
                null,
                null,
                null,
                null),
        mandatory(
                ALL, ET3_VETTING, "et3DoesRespondentsAddressMatch", 11, 4, null, null, null, null),
        field(
                ALL,
                ET3_VETTING,
                "et3RespondentAddressMismatchDetails",
                "MANDATORY",
                11,
                5,
                false,
                "Y",
                "et3DoesRespondentsAddressMatch=\"No\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3GeneralNotesAddressMatch",
                "OPTIONAL",
                11,
                6,
                false,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3ContestClaim",
                "MANDATORY",
                12,
                1,
                true,
                "Y",
                null,
                null,
                "et3IsThereAnEt3Response=\"Yes\"",
                "Minimum required information",
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3ContestClaimGiveDetails",
                "OPTIONAL",
                12,
                2,
                true,
                "Y",
                "et3ContestClaim=\"Yes\" OR et3ContestClaim=\"No\" OR et3ContestClaim=\"Unknown -"
                    + " no answer given\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3GeneralNotesContestClaim",
                "OPTIONAL",
                12,
                3,
                true,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                CFTLIB,
                ET3_VETTING,
                "et3ContractClaimSection7",
                "MANDATORY",
                13,
                1,
                true,
                "Y",
                null,
                null,
                "et3IsThereAnEt3Response=\"Yes\"",
                "Minimum required information",
                LOCALHOST + "/et3Vetting/midHearingListedTable",
                null),
        field(
                PROD,
                ET3_VETTING,
                "et3ContractClaimSection7",
                "MANDATORY",
                13,
                1,
                true,
                "Y",
                null,
                null,
                "et3IsThereAnEt3Response=\"Yes\"",
                "Minimum required information",
                PRODUCTION + "/et3Vetting/midHearingListedTable",
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3ContractClaimSection7Details",
                "OPTIONAL",
                13,
                2,
                true,
                "Y",
                "et3ContractClaimSection7=\"Yes\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3GeneralNotesContractClaimSection7",
                "OPTIONAL",
                13,
                3,
                true,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                CFTLIB,
                ET3_VETTING,
                "et3HearingDetails",
                "READONLY",
                14,
                1,
                true,
                null,
                "et3HearingDetailsLabel=\"dummy\"",
                null,
                "et3IsThereAnEt3Response=\"Yes\"",
                null,
                LOCALHOST + "/et3Vetting/midTransferApplicationTable",
                null),
        field(
                PROD,
                ET3_VETTING,
                "et3HearingDetails",
                "READONLY",
                14,
                1,
                true,
                null,
                "et3HearingDetailsLabel=\"dummy\"",
                null,
                "et3IsThereAnEt3Response=\"Yes\"",
                null,
                PRODUCTION + "/et3Vetting/midTransferApplicationTable",
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3HearingDetailsLabel",
                "READONLY",
                14,
                2,
                true,
                null,
                null,
                null,
                null,
                "Page Title",
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3IsCaseListedForHearing",
                "MANDATORY",
                14,
                3,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3IsCaseListedForHearingDetails",
                "OPTIONAL",
                14,
                4,
                true,
                null,
                "et3IsCaseListedForHearing=\"No\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3GeneralNotesCaseListed",
                "OPTIONAL",
                14,
                5,
                true,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3TribunalLocation",
                "READONLY",
                15,
                1,
                true,
                null,
                "et3TribunalLocationLabel=\"dummy\"",
                "Yes",
                "et3IsThereAnEt3Response=\"Yes\"",
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3TribunalLocationLabel",
                "READONLY",
                15,
                2,
                true,
                null,
                null,
                null,
                null,
                "Page Title",
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3IsThisLocationCorrect",
                "MANDATORY",
                15,
                3,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3RegionalOffice",
                "MANDATORY",
                15,
                4,
                true,
                null,
                "et3IsThisLocationCorrect=\"No - suggest another location\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3WhyWeShouldChangeTheOffice",
                "MANDATORY",
                15,
                5,
                true,
                null,
                "et3IsThisLocationCorrect=\"No - suggest another location\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3GeneralNotesTransferApplication",
                "OPTIONAL",
                15,
                6,
                true,
                null,
                "et3IsThisLocationCorrect=\"Yes\"",
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3Rule26",
                "MANDATORY",
                16,
                1,
                true,
                "Y",
                null,
                null,
                "et3IsThereAnEt3Response=\"Yes\"",
                "Issues identified",
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3Rule26Details",
                "MANDATORY",
                16,
                2,
                true,
                "Y",
                "et3Rule26=\"Yes\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3SuggestedIssues",
                "OPTIONAL",
                16,
                3,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ET3_VETTING,
                "et3SuggestedIssuesStrikeOut",
                "MANDATORY",
                16,
                4,
                true,
                "Y",
                "et3SuggestedIssues CONTAINS \"Applications for strike out or deposit\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ET3_VETTING,
                "et3SuggestedIssuesStrikeOut",
                "MANDATORY",
                16,
                4,
                true,
                "Y",
                "et3SuggestedIssues CONTAINS\"Applications for strike out or deposit\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ET3_VETTING,
                "et3SuggestedIssueInterpreters",
                "MANDATORY",
                16,
                5,
                true,
                "Y",
                "et3SuggestedIssues CONTAINS \"Interpreters\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ET3_VETTING,
                "et3SuggestedIssueInterpreters",
                "MANDATORY",
                16,
                5,
                true,
                "Y",
                "et3SuggestedIssues CONTAINS\"Interpreters\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ET3_VETTING,
                "et3SuggestedIssueJurisdictional",
                "MANDATORY",
                16,
                6,
                true,
                "Y",
                "et3SuggestedIssues CONTAINS \"Jurisdictional issues\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ET3_VETTING,
                "et3SuggestedIssueJurisdictional",
                "MANDATORY",
                16,
                6,
                true,
                "Y",
                "et3SuggestedIssues CONTAINS\"Jurisdictional issues\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ET3_VETTING,
                "et3SuggestedIssueAdjustments",
                "MANDATORY",
                16,
                7,
                true,
                "Y",
                "et3SuggestedIssues CONTAINS \"Request for adjustments\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ET3_VETTING,
                "et3SuggestedIssueAdjustments",
                "MANDATORY",
                16,
                7,
                true,
                "Y",
                "et3SuggestedIssues CONTAINS\"Request for adjustments\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ET3_VETTING,
                "et3SuggestedIssueRule50",
                "MANDATORY",
                16,
                8,
                true,
                "Y",
                "et3SuggestedIssues CONTAINS \"Rule 50\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ET3_VETTING,
                "et3SuggestedIssueRule50",
                "MANDATORY",
                16,
                8,
                true,
                "Y",
                "et3SuggestedIssues CONTAINS\"Rule 50\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ET3_VETTING,
                "et3SuggestedIssueTimePoints",
                "MANDATORY",
                16,
                9,
                true,
                "Y",
                "et3SuggestedIssues CONTAINS \"Time points\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ET3_VETTING,
                "et3SuggestedIssueTimePoints",
                "MANDATORY",
                16,
                9,
                true,
                "Y",
                "et3SuggestedIssues CONTAINS\"Time points\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3GeneralNotesRule26",
                "OPTIONAL",
                16,
                10,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_VETTING,
                "et3AdditionalInformation",
                "OPTIONAL",
                17,
                1,
                true,
                "Y",
                null,
                null,
                null,
                "Final notes",
                null,
                null),
        field(
                CFTLIB,
                ET3_NOTIFICATION,
                "et3NotificationDocCollection",
                "COMPLEX",
                1,
                1,
                true,
                "Y",
                null,
                null,
                null,
                "Upload documents",
                LOCALHOST + "/et3Notification/midUploadDocuments",
                null),
        field(
                PROD,
                ET3_NOTIFICATION,
                "et3NotificationDocCollection",
                "COMPLEX",
                1,
                1,
                true,
                "Y",
                null,
                null,
                null,
                "Upload documents",
                PRODUCTION + "/et3Notification/midUploadDocuments",
                null),
        field(
                ALL,
                ET3_NOTIFICATION,
                "horizontalLine4",
                "READONLY",
                2,
                1,
                true,
                "Y",
                null,
                null,
                "et3OtherTypeDocumentName != \"\"",
                "Who are you sending this document to?",
                null,
                null),
        field(
                ALL,
                ET3_NOTIFICATION,
                "et3OtherTypeDocumentName",
                "MANDATORY",
                2,
                2,
                true,
                null,
                "horizontalLine4=\"dummy\"",
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_NOTIFICATION,
                "et3OtherTypeDocumentNameLabel",
                "READONLY",
                2,
                3,
                true,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_NOTIFICATION,
                "et3SelectAllThatApply",
                "READONLY",
                2,
                4,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_NOTIFICATION,
                "et3NotificationDocRecipient",
                "MANDATORY",
                2,
                5,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_NOTIFICATION,
                "et3EmailDocsToAcasTitle",
                "READONLY",
                3,
                1,
                true,
                null,
                null,
                null,
                null,
                "Email Acas",
                null,
                null),
        field(
                ALL,
                ET3_NOTIFICATION,
                "et3EmailLinkToAcas",
                "MANDATORY",
                3,
                2,
                true,
                null,
                "et3EmailDocsToAcasTitle=\"dummy\"",
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_NOTIFICATION,
                "et3EmailDocsToAcasLink",
                "READONLY",
                3,
                3,
                true,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_NOTIFICATION,
                "et3EmailDocsToAcasInstructions",
                "READONLY",
                3,
                4,
                true,
                null,
                null,
                null,
                null,
                null,
                null,
                null)
    };

    static final ComplexFieldSpec[] COMPLEX_FIELDS = {
        complexField(
                ALL,
                "et3NotificationDoc",
                ET3_NOTIFICATION,
                "et3NotificationDocCollection",
                "typeOfDocument",
                "MANDATORY",
                1,
                "Type of Document",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "et3NotificationDoc",
                ET3_NOTIFICATION,
                "et3NotificationDocCollection",
                "uploadedDocument",
                "MANDATORY",
                2,
                "Document",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "et3NotificationDoc",
                ET3_NOTIFICATION,
                "et3NotificationDocCollection",
                "shortDescription",
                "OPTIONAL",
                3,
                "Short Description",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "rule21",
                ET3_VETTING,
                "respondentCollection",
                "et3Vetting",
                "OPTIONAL",
                1,
                " ",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "rule21",
                ET3_VETTING,
                "respondentCollection",
                "et3Vetting.et3ContractClaimSection7",
                "OPTIONAL",
                2,
                " ",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "rule21",
                ET3_VETTING,
                "respondentCollection",
                "et3Vetting.et3IsThereAnEt3Response",
                "OPTIONAL",
                2,
                " ",
                null,
                null,
                null,
                null,
                "Y")
    };

    private SingleEt3ProcessingRows() {}

    static void configureComplexTypeAccess(ConfigBuilder<CaseData, CaseState, SingleRole> builder) {
        Set<Permission> delete = Set.of(Permission.D);
        builder.grantComplexType(
                CaseData::getRespondentCollection,
                "et3Vetting.et3IsThereAnEt3Response",
                delete,
                SingleRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(
                CaseData::getRespondentCollection,
                "et3Vetting.et3ContractClaimSection7",
                delete,
                SingleRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        builder.grantComplexType(
                CaseData::getRespondentCollection,
                "et3Vetting",
                delete,
                SingleRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR,
                SingleRole.CASEWORKER_EMPLOYMENT);
    }

    private static EventFieldSpec readOnly(
            int mask,
            String eventId,
            String fieldId,
            int page,
            int order,
            String condition,
            String pageCondition,
            String pageLabel,
            String midEvent) {
        return field(
                mask,
                eventId,
                fieldId,
                "READONLY",
                page,
                order,
                false,
                null,
                condition,
                null,
                pageCondition,
                pageLabel,
                midEvent,
                null);
    }

    private static EventFieldSpec mandatory(
            int mask,
            String eventId,
            String fieldId,
            int page,
            int order,
            String condition,
            String pageCondition,
            String pageLabel,
            String midEvent) {
        return field(
                mask,
                eventId,
                fieldId,
                "MANDATORY",
                page,
                order,
                false,
                "Y",
                condition,
                null,
                pageCondition,
                pageLabel,
                midEvent,
                null);
    }

    private static EventFieldSpec optional(
            int mask,
            String eventId,
            String fieldId,
            int page,
            int order,
            String condition,
            String pageCondition,
            String pageLabel,
            String midEvent) {
        return field(
                mask,
                eventId,
                fieldId,
                "OPTIONAL",
                page,
                order,
                false,
                "Y",
                condition,
                null,
                pageCondition,
                pageLabel,
                midEvent,
                null);
    }

    private static EventFieldSpec field(
            int mask,
            String eventId,
            String fieldId,
            String context,
            int page,
            int order,
            boolean pageColumn,
            String showSummary,
            String condition,
            String retainHidden,
            String pageCondition,
            String pageLabel,
            String midEvent,
            String publish) {
        return new EventFieldSpec(
                mask,
                eventId,
                fieldId,
                context,
                Integer.toString(page),
                page,
                order,
                pageColumn,
                showSummary,
                condition,
                retainHidden,
                pageCondition,
                pageLabel,
                midEvent,
                publish);
    }

    private static ComplexFieldSpec complexField(
            int mask,
            String rowId,
            String eventId,
            String caseFieldId,
            String elementCode,
            String context,
            int order,
            String label,
            String hint,
            String condition,
            String retainHidden,
            String defaultValue,
            String publish) {
        return new ComplexFieldSpec(
                mask,
                rowId,
                eventId,
                caseFieldId,
                elementCode,
                context,
                order,
                label,
                hint,
                condition,
                retainHidden,
                defaultValue,
                publish);
    }
}
