package uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config;

import uk.gov.hmcts.et.common.model.ccd.SingleRole;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.ComplexFieldSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.EventFieldSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.EventSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.GrantSpec;

@SuppressWarnings({
    "checkstyle:LineLength",
    "checkstyle:RightCurlyAlone",
    "PMD.AvoidDuplicateLiterals"
})
final class SingleEt3ResponseIntakeRows {
    private static final int CFTLIB_ENGLAND_WALES = 1;
    private static final int CFTLIB_SCOTLAND = 2;
    private static final int CFTLIB = 3;
    private static final int PROD_ENGLAND_WALES = 4;
    private static final int ENGLAND_WALES = 5;
    private static final int PROD_SCOTLAND = 8;
    private static final int SCOTLAND = 10;
    private static final int PROD = 12;
    private static final int ALL = 15;
    private static final String LOCALHOST = "http://localhost:8081";
    private static final String PRODUCTION =
            "http://et-cos-prod.service.core-compute-prod.internal";
    private static final String ET3_RESPONSE = "et3Response";
    private static final String ET3_RESPONSE_EMPLOYMENT_DETAILS = "et3ResponseEmploymentDetails";
    private static final String ET3_RESPONSE_DETAILS = "et3ResponseDetails";
    private static final String DOWNLOAD_DRAFT_ET3 = "downloadDraftEt3";
    private static final String SUBMIT_ET3 = "submitEt3";

    private static final SingleRole[] RESPONDENT_SOLICITORS = {
        SingleRole.SOLICITORA,
        SingleRole.SOLICITORB,
        SingleRole.SOLICITORC,
        SingleRole.SOLICITORD,
        SingleRole.SOLICITORE,
        SingleRole.SOLICITORF,
        SingleRole.SOLICITORG,
        SingleRole.SOLICITORH,
        SingleRole.SOLICITORI,
        SingleRole.SOLICITORJ
    };

    private static final GrantSpec[] EXPLICIT_EVENT_GRANTS = {
        new GrantSpec(ALL, ET3_RESPONSE, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(ALL, ET3_RESPONSE, SingleRole.CASEWORKER_WA_TASK_CONFIGURATION, "CRU"),
        new GrantSpec(ALL, ET3_RESPONSE, SingleRole.CLAIMANTSOLICITOR, "D"),
        new GrantSpec(ALL, ET3_RESPONSE, SingleRole.ET_ACAS_API, "R"),
        new GrantSpec(
                ALL, ET3_RESPONSE_EMPLOYMENT_DETAILS, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(ALL, ET3_RESPONSE_EMPLOYMENT_DETAILS, SingleRole.CLAIMANTSOLICITOR, "D"),
        new GrantSpec(ALL, ET3_RESPONSE_EMPLOYMENT_DETAILS, SingleRole.ET_ACAS_API, "R"),
        new GrantSpec(ALL, ET3_RESPONSE_DETAILS, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(ALL, ET3_RESPONSE_DETAILS, SingleRole.CLAIMANTSOLICITOR, "D"),
        new GrantSpec(ALL, ET3_RESPONSE_DETAILS, SingleRole.ET_ACAS_API, "R"),
        new GrantSpec(ALL, DOWNLOAD_DRAFT_ET3, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRU"),
        new GrantSpec(ALL, SUBMIT_ET3, SingleRole.CASEWORKER_EMPLOYMENT, "R"),
        new GrantSpec(ALL, SUBMIT_ET3, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(
                ENGLAND_WALES, SUBMIT_ET3, SingleRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, "R"),
        new GrantSpec(ALL, SUBMIT_ET3, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE, "R"),
        new GrantSpec(
                ENGLAND_WALES,
                SUBMIT_ET3,
                SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES,
                "R"),
        new GrantSpec(SCOTLAND, SUBMIT_ET3, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_SCOTLAND, "R"),
        new GrantSpec(SCOTLAND, SUBMIT_ET3, SingleRole.CASEWORKER_EMPLOYMENT_SCOTLAND, "R"),
        new GrantSpec(ALL, SUBMIT_ET3, SingleRole.CASEWORKER_WA_TASK_CONFIGURATION, "CRU"),
        new GrantSpec(ALL, SUBMIT_ET3, SingleRole.CLAIMANTSOLICITOR, "D"),
        new GrantSpec(ALL, SUBMIT_ET3, SingleRole.ET_ACAS_API, "R")
    };

    static final GrantSpec[] EVENT_GRANTS = eventGrants();

    static final EventSpec[] EVENTS = {
        section(CFTLIB_ENGLAND_WALES, ET3_RESPONSE, "ET3 - Respondent Details", 43, LOCALHOST, "Y"),
        section(CFTLIB_SCOTLAND, ET3_RESPONSE, "ET3 - Respondent Details", 41, LOCALHOST, "Y"),
        section(PROD_ENGLAND_WALES, ET3_RESPONSE, "ET3 - Respondent Details", 43, PRODUCTION, "Y"),
        section(PROD_SCOTLAND, ET3_RESPONSE, "ET3 - Respondent Details", 41, PRODUCTION, "Y"),
        section(
                CFTLIB_ENGLAND_WALES,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "ET3 - Employment Details",
                44,
                LOCALHOST,
                null),
        section(
                CFTLIB_SCOTLAND,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "ET3 - Employment Details",
                42,
                LOCALHOST,
                null),
        section(
                PROD_ENGLAND_WALES,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "ET3 - Employment Details",
                44,
                PRODUCTION,
                null),
        section(
                PROD_SCOTLAND,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "ET3 - Employment Details",
                42,
                PRODUCTION,
                null),
        section(
                CFTLIB_ENGLAND_WALES,
                ET3_RESPONSE_DETAILS,
                "ET3 - Response Details",
                45,
                LOCALHOST,
                null),
        section(
                CFTLIB_SCOTLAND,
                ET3_RESPONSE_DETAILS,
                "ET3 - Response Details",
                43,
                LOCALHOST,
                null),
        section(
                PROD_ENGLAND_WALES,
                ET3_RESPONSE_DETAILS,
                "ET3 - Response Details",
                45,
                PRODUCTION,
                null),
        section(
                PROD_SCOTLAND,
                ET3_RESPONSE_DETAILS,
                "ET3 - Response Details",
                43,
                PRODUCTION,
                null),
        download(CFTLIB_ENGLAND_WALES, 46, LOCALHOST),
        download(CFTLIB_SCOTLAND, 44, LOCALHOST),
        download(PROD_ENGLAND_WALES, 46, PRODUCTION),
        download(PROD_SCOTLAND, 44, PRODUCTION),
        submit(CFTLIB_ENGLAND_WALES, 46, null, LOCALHOST),
        submit(CFTLIB_SCOTLAND, 44, "managingOffice !=\"Unassigned\"", LOCALHOST),
        submit(PROD_ENGLAND_WALES, 46, null, PRODUCTION),
        submit(PROD_SCOTLAND, 44, "managingOffice !=\"Unassigned\"", PRODUCTION)
    };

    static final EventFieldSpec[] EVENT_FIELDS = {
        field(
                ALL,
                ET3_RESPONSE,
                "et3ResponseShowInset",
                "OPTIONAL",
                1,
                1,
                false,
                null,
                "et3StartPagePreamble=\"dummy\"",
                null,
                null,
                "ET3 - Response to Employment tribunal claim (ET1)",
                null,
                null),
        readOnly(ALL, ET3_RESPONSE, "et3StartPagePreamble", 1, 2, null, null, null, null),
        readOnly(
                ALL,
                ET3_RESPONSE,
                "et3StartPageInset",
                1,
                3,
                "et3ResponseShowInset=\"Yes\"",
                null,
                null,
                null),
        readOnly(ALL, ET3_RESPONSE, "et3StartPageMainBody", 1, 4, null, null, null, null),
        mandatory(
                CFTLIB,
                ET3_RESPONSE,
                "submitEt3Respondent",
                2,
                1,
                null,
                null,
                null,
                LOCALHOST + "/et3Response/validateRespondent"),
        mandatory(
                PROD,
                ET3_RESPONSE,
                "submitEt3Respondent",
                2,
                1,
                null,
                null,
                null,
                PRODUCTION + "/et3Response/validateRespondent"),
        field(
                ALL,
                ET3_RESPONSE,
                "et3ResponseClaimantName",
                "READONLY",
                3,
                1,
                false,
                null,
                "et3ResponseClaimantNameLabel=\"dummy\"",
                "Yes",
                null,
                "Is this the correct claimant for the claim you're responding to?",
                null,
                null),
        readOnly(ALL, ET3_RESPONSE, "et3ResponseClaimantNameLabel", 3, 2, null, null, null, null),
        mandatory(
                ALL,
                ET3_RESPONSE,
                "et3ResponseIsClaimantNameCorrect",
                3,
                3,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_RESPONSE,
                "et3ResponseClaimantNameCorrection",
                "MANDATORY",
                3,
                4,
                false,
                "Y",
                "et3ResponseIsClaimantNameCorrect=\"No\"",
                "Yes",
                null,
                null,
                null,
                null),
        readOnly(
                ALL,
                ET3_RESPONSE,
                "et3ResponseNamePreamble",
                4,
                1,
                null,
                null,
                "What is the respondent's name?",
                null),
        field(
                ALL,
                ET3_RESPONSE,
                "et3ResponseNameInset",
                "READONLY",
                4,
                2,
                false,
                null,
                "et3ResponseNameShowInset=\"Yes\"",
                "Yes",
                null,
                null,
                null,
                null),
        mandatory(
                ALL, ET3_RESPONSE, "et3ResponseRespondentLegalName", 4, 3, null, null, null, null),
        optional(
                ALL,
                ET3_RESPONSE,
                "et3ResponseRespondentCompanyNumber",
                4,
                4,
                null,
                null,
                null,
                null),
        optional(
                ALL,
                ET3_RESPONSE,
                "et3ResponseRespondentEmployerType",
                4,
                5,
                null,
                null,
                null,
                null),
        optional(
                ALL,
                ET3_RESPONSE,
                "et3ResponseRespondentPreferredTitle",
                4,
                6,
                null,
                null,
                null,
                null),
        optional(
                ALL,
                ET3_RESPONSE,
                "et3ResponseRespondentContactName",
                4,
                7,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_RESPONSE,
                "et3ResponseNameShowInset",
                "OPTIONAL",
                4,
                8,
                false,
                null,
                "et3ResponseNamePreamble=\"dummy\"",
                "Yes",
                null,
                null,
                null,
                null),
        mandatory(
                ALL,
                ET3_RESPONSE,
                "et3RespondentAddress",
                5,
                1,
                null,
                null,
                "Respondent address",
                null),
        optional(ALL, ET3_RESPONSE, "et3ResponseDXAddress", 5, 2, null, null, null, null),
        field(
                ALL,
                ET3_RESPONSE,
                "et3RepresentativeInfoFirstWords",
                "READONLY",
                6,
                1,
                false,
                "Y",
                null,
                null,
                null,
                "Your information (as the representative)",
                null,
                null),
        optional(ALL, ET3_RESPONSE, "et3ResponseContactPreference", 6, 2, null, null, null, null),
        field(
                ALL,
                ET3_RESPONSE,
                "et3ResponseContactReason",
                "MANDATORY",
                6,
                3,
                false,
                "Y",
                "et3ResponseContactPreference=\"Post\"",
                "Yes",
                null,
                null,
                null,
                null),
        optional(ALL, ET3_RESPONSE, "et3ResponseContactLanguage", 6, 4, null, null, null, null),
        optional(ALL, ET3_RESPONSE, "et3ResponsePhone", 6, 5, null, null, null, null),
        optional(ALL, ET3_RESPONSE, "et3ResponseAddress", 6, 6, null, null, null, null),
        optional(ALL, ET3_RESPONSE, "et3ResponseReference", 6, 7, null, null, null, null),
        readOnly(
                ALL,
                ET3_RESPONSE,
                "et3ResponseHearingPreamble",
                7,
                1,
                null,
                null,
                "Hearing format",
                null),
        mandatory(
                ALL,
                ET3_RESPONSE,
                "et3ResponseHearingRepresentative",
                7,
                2,
                null,
                null,
                null,
                null),
        mandatory(ALL, ET3_RESPONSE, "et3ResponseHearingRespondent", 7, 3, null, null, null, null),
        readOnly(
                ALL,
                ET3_RESPONSE,
                "et3ResponseHealthInsetPreamble",
                8,
                1,
                null,
                null,
                "In the respondent party - are you aware of any physical, mental or learning"
                    + " disability or health conditions which requires support?",
                null),
        mandatory(
                ALL,
                ET3_RESPONSE,
                "et3ResponseRespondentSupportNeeded",
                8,
                2,
                null,
                null,
                null,
                null),
        readOnly(
                ALL,
                ET3_RESPONSE,
                "et3ResponseHealthDetailsPreamble",
                9,
                1,
                null,
                "et3ResponseRespondentSupportNeeded=\"Yes\"",
                "Give details of the support you require for the parties",
                null),
        mandatory(
                ALL,
                ET3_RESPONSE,
                "et3ResponseRespondentSupportDetails",
                9,
                2,
                null,
                null,
                null,
                null),
        optional(
                ALL,
                ET3_RESPONSE,
                "et3ResponseRespondentSupportDocument",
                9,
                3,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseShowInset",
                "OPTIONAL",
                1,
                1,
                false,
                null,
                "et3StartPagePreamble=\"dummy\"",
                null,
                null,
                "ET3 - Response to Employment tribunal claim (ET1)",
                null,
                null),
        readOnly(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3StartPagePreamble",
                1,
                2,
                null,
                null,
                null,
                null),
        readOnly(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3StartPageInset",
                1,
                3,
                "et3ResponseShowInset=\"Yes\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3StartPageMainBody",
                1,
                4,
                null,
                null,
                null,
                null),
        mandatory(
                CFTLIB,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3RepresentingRespondent",
                2,
                1,
                null,
                null,
                null,
                LOCALHOST + "/et3Response/validateRespondent"),
        mandatory(
                PROD,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3RepresentingRespondent",
                2,
                1,
                null,
                null,
                null,
                PRODUCTION + "/et3Response/validateRespondent"),
        optional(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseEmploymentCount",
                3,
                1,
                null,
                null,
                "Respondent's workforce",
                null),
        optional(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseMultipleSites",
                3,
                2,
                null,
                null,
                null,
                null),
        optional(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseSiteEmploymentCount",
                3,
                3,
                null,
                null,
                null,
                null),
        mandatory(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseAreDatesCorrect",
                4,
                1,
                null,
                null,
                "Are the dates of employment given by the claimant correct?",
                null),
        optional(
                CFTLIB,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseEmploymentStartDate",
                5,
                1,
                null,
                "et3ResponseAreDatesCorrect=\"No\"",
                "What are the claimant's employment dates?",
                LOCALHOST + "/et3Response/midEmploymentDates"),
        optional(
                PROD,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseEmploymentStartDate",
                5,
                1,
                null,
                "et3ResponseAreDatesCorrect=\"No\"",
                "What are the claimant's employment dates?",
                PRODUCTION + "/et3Response/midEmploymentDates"),
        optional(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseEmploymentEndDate",
                5,
                2,
                null,
                null,
                null,
                null),
        optional(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseEmploymentInformation",
                5,
                3,
                null,
                null,
                null,
                null),
        mandatory(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseContinuingEmployment",
                6,
                1,
                null,
                null,
                "Is the claimant's employment with the respondent continuing?",
                null),
        mandatory(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseIsJobTitleCorrect",
                7,
                1,
                null,
                null,
                "Is the claimant's description of their job or job title correct?",
                null),
        field(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseCorrectJobTitle",
                "OPTIONAL",
                7,
                2,
                false,
                "Y",
                "et3ResponseIsJobTitleCorrect=\"No\"",
                "Yes",
                null,
                null,
                null,
                null),
        mandatory(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseClaimantWeeklyHours",
                8,
                1,
                null,
                null,
                "Are the claimant's total weekly work hours correct?",
                null),
        field(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseClaimantCorrectHours",
                "OPTIONAL",
                8,
                2,
                false,
                "Y",
                "et3ResponseClaimantWeeklyHours=\"No\"",
                "Yes",
                null,
                null,
                null,
                null),
        mandatory(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseEarningDetailsCorrect",
                9,
                1,
                null,
                null,
                "Are the earnings details given by the claimant correct?",
                null),
        readOnly(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponsePayDetailsPreamble",
                10,
                1,
                null,
                "et3ResponseEarningDetailsCorrect=\"No\"",
                "What are the claimant's correct pay details?",
                null),
        optional(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponsePayFrequency",
                10,
                2,
                null,
                null,
                null,
                null),
        optional(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponsePayBeforeTax",
                10,
                3,
                null,
                null,
                null,
                null),
        optional(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponsePayTakehome",
                10,
                4,
                null,
                null,
                null,
                null),
        mandatory(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseIsNoticeCorrect",
                11,
                1,
                null,
                null,
                "Is the information given by the claimant correct about their notice?",
                null),
        optional(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseCorrectNoticeDetails",
                11,
                2,
                "et3ResponseIsNoticeCorrect=\"No\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponseIsPensionCorrect",
                12,
                1,
                null,
                null,
                "Are the details about pension and other benefits correct?",
                null),
        field(
                ALL,
                ET3_RESPONSE_EMPLOYMENT_DETAILS,
                "et3ResponsePensionCorrectDetails",
                "OPTIONAL",
                12,
                2,
                false,
                "Y",
                "et3ResponseIsPensionCorrect=\"No\"",
                "Yes",
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET3_RESPONSE_DETAILS,
                "et3ResponseShowInset",
                "OPTIONAL",
                1,
                1,
                false,
                null,
                "et3StartPagePreamble=\"dummy\"",
                null,
                null,
                "ET3 - Response to Employment tribunal claim (ET1)",
                null,
                null),
        readOnly(ALL, ET3_RESPONSE_DETAILS, "et3StartPagePreamble", 1, 2, null, null, null, null),
        readOnly(
                ALL,
                ET3_RESPONSE_DETAILS,
                "et3StartPageInset",
                1,
                3,
                "et3ResponseShowInset=\"Yes\"",
                null,
                null,
                null),
        readOnly(ALL, ET3_RESPONSE_DETAILS, "et3StartPageMainBody", 1, 4, null, null, null, null),
        mandatory(
                CFTLIB,
                ET3_RESPONSE_DETAILS,
                "et3RepresentingRespondent",
                2,
                1,
                null,
                null,
                null,
                LOCALHOST + "/et3Response/validateRespondent"),
        mandatory(
                PROD,
                ET3_RESPONSE_DETAILS,
                "et3RepresentingRespondent",
                2,
                1,
                null,
                null,
                null,
                PRODUCTION + "/et3Response/validateRespondent"),
        mandatory(
                ALL,
                ET3_RESPONSE_DETAILS,
                "et3ResponseAcasAgree",
                3,
                1,
                null,
                null,
                "Do you agree with the details given by the claimant about early conciliation with"
                    + " Acas?",
                null),
        field(
                ALL,
                ET3_RESPONSE_DETAILS,
                "et3ResponseAcasAgreeReason",
                "OPTIONAL",
                3,
                2,
                false,
                "Y",
                "et3ResponseAcasAgree=\"No\"",
                "Yes",
                null,
                null,
                null,
                null),
        mandatory(
                ALL,
                ET3_RESPONSE_DETAILS,
                "et3ResponseRespondentContestClaim",
                4,
                1,
                null,
                null,
                "Does the respondent contest the claim?",
                null),
        readOnly(
                ALL,
                ET3_RESPONSE_DETAILS,
                "et3ResponseContestClaimPreamble",
                5,
                1,
                null,
                "et3ResponseRespondentContestClaim=\"Yes\"",
                "Explain why the respondent contests the claim",
                null),
        field(
                ALL,
                ET3_RESPONSE_DETAILS,
                "et3ResponseContestClaimDocument",
                "COMPLEX",
                5,
                2,
                false,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        optional(
                ALL,
                ET3_RESPONSE_DETAILS,
                "et3ResponseContestClaimDetails",
                5,
                3,
                null,
                null,
                null,
                null),
        mandatory(
                ALL,
                ET3_RESPONSE_DETAILS,
                "et3ResponseEmployerClaim",
                6,
                1,
                null,
                null,
                "Does the respondent wish to make an Employer's Contract Claim?",
                null),
        readOnly(
                ALL,
                ET3_RESPONSE_DETAILS,
                "et3ResponseEmployerClaimDetailsPreamble",
                7,
                1,
                null,
                "et3ResponseEmployerClaim=\"Yes\"",
                "Provide the background and details of your Employer's Contract Claim",
                null),
        mandatory(
                ALL,
                ET3_RESPONSE_DETAILS,
                "et3ResponseEmployerClaimDetails",
                7,
                2,
                null,
                null,
                null,
                null),
        mandatory(
                ALL,
                ET3_RESPONSE_DETAILS,
                "et3ResponseEmployerClaimDocument",
                7,
                3,
                null,
                null,
                null,
                null),
        field(
                ALL,
                DOWNLOAD_DRAFT_ET3,
                "downloadDraftEt3Label",
                "READONLY",
                1,
                1,
                true,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                DOWNLOAD_DRAFT_ET3,
                "submitEt3Respondent",
                "MANDATORY",
                1,
                2,
                true,
                null,
                null,
                null,
                null,
                null,
                null,
                null),
        mandatory(
                CFTLIB,
                SUBMIT_ET3,
                "submitEt3Respondent",
                1,
                1,
                null,
                null,
                null,
                LOCALHOST + "/et3Response/reloadSubmitData"),
        mandatory(
                PROD,
                SUBMIT_ET3,
                "submitEt3Respondent",
                1,
                1,
                null,
                null,
                null,
                PRODUCTION + "/et3Response/reloadSubmitData"),
        field(
                ALL,
                SUBMIT_ET3,
                "nextListedDate",
                "OPTIONAL",
                1,
                2,
                true,
                "N",
                "submitEt3Respondent=\"dummy\"",
                null,
                null,
                null,
                null,
                "Y"),
        mandatory(ALL, SUBMIT_ET3, "confirmEt3Submit", 2, 1, null, null, null, null),
        field(
                SCOTLAND,
                SUBMIT_ET3,
                "et3ResponseEmployerClaimDocument",
                "READONLY",
                2,
                2,
                false,
                "Y",
                "confirmEt3Submit CONTAINS \"dummy\"",
                null,
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                SUBMIT_ET3,
                "et3ResponseContestClaimDocument",
                "READONLY",
                2,
                3,
                false,
                "Y",
                "confirmEt3Submit CONTAINS \"dummy\"",
                null,
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                SUBMIT_ET3,
                "et3ResponseRespondentSupportDocument",
                "READONLY",
                2,
                4,
                false,
                "Y",
                "confirmEt3Submit CONTAINS \"dummy\"",
                null,
                null,
                null,
                null,
                null)
    };

    static final ComplexFieldSpec[] COMPLEX_FIELDS = {
        complexField(
                ALL,
                "et3ResponseForm",
                ET3_RESPONSE_DETAILS,
                "et3ResponseContestClaimDocument",
                "uploadedDocument",
                "OPTIONAL",
                1,
                "Upload a document to your response")
    };

    private SingleEt3ResponseIntakeRows() {}

    private static GrantSpec[] eventGrants() {
        var grants = new java.util.ArrayList<GrantSpec>(java.util.List.of(EXPLICIT_EVENT_GRANTS));
        addRespondentSolicitorGrants(grants, ET3_RESPONSE, "CRUD");
        addRespondentSolicitorGrants(grants, ET3_RESPONSE_EMPLOYMENT_DETAILS, "CRUD");
        addRespondentSolicitorGrants(grants, ET3_RESPONSE_DETAILS, "CRUD");
        addRespondentSolicitorGrants(grants, DOWNLOAD_DRAFT_ET3, "CRU");
        addRespondentSolicitorGrants(grants, SUBMIT_ET3, "CRUD");
        return grants.toArray(GrantSpec[]::new);
    }

    private static void addRespondentSolicitorGrants(
            java.util.List<GrantSpec> grants, String eventId, String crud) {
        for (SingleRole role : RESPONDENT_SOLICITORS) {
            grants.add(new GrantSpec(ALL, eventId, role, crud));
        }
    }

    private static EventSpec section(
            int mask, String eventId, String name, int order, String callbackBase, String publish) {
        return new EventSpec(
                mask,
                eventId,
                name,
                name,
                order,
                "Accepted",
                "*",
                null,
                "Y",
                "N",
                publish,
                false,
                null,
                callbackBase + "/et3Response/aboutToStart",
                callbackBase + "/et3Response/submitSection",
                callbackBase + "/et3Response/sectionComplete",
                "Save ET3 as draft");
    }

    private static EventSpec download(int mask, int order, String callbackBase) {
        return new EventSpec(
                mask,
                DOWNLOAD_DRAFT_ET3,
                "Download draft ET3 Form",
                "Download draft ET3 Form",
                order,
                "Accepted",
                "*",
                null,
                "N",
                "N",
                null,
                false,
                null,
                callbackBase + "/et3Response/downloadDraft/aboutToStart",
                callbackBase + "/et3Response/downloadDraft/aboutToSubmit",
                callbackBase + "/et3Response/downloadDraft/submitted",
                "Download draft ET3 form");
    }

    private static EventSpec submit(int mask, int order, String condition, String callbackBase) {
        return new EventSpec(
                mask,
                SUBMIT_ET3,
                "Submit ET3 Form",
                "Submit ET3 Form",
                order,
                "Accepted",
                "*",
                condition,
                "Y",
                "N",
                "Y",
                false,
                null,
                callbackBase + "/et3Response/startSubmitEt3",
                callbackBase + "/et3Response/aboutToSubmit",
                callbackBase + "/et3Response/processingComplete",
                "Submit ET3 to Tribunal");
    }

    private static EventFieldSpec readOnly(
            int mask,
            String eventId,
            String fieldId,
            int page,
            int order,
            String condition,
            String pageCondition,
            String pageLabel,
            String midEvent) {
        return field(
                mask,
                eventId,
                fieldId,
                "READONLY",
                page,
                order,
                false,
                null,
                condition,
                null,
                pageCondition,
                pageLabel,
                midEvent,
                null);
    }

    private static EventFieldSpec mandatory(
            int mask,
            String eventId,
            String fieldId,
            int page,
            int order,
            String condition,
            String pageCondition,
            String pageLabel,
            String midEvent) {
        return field(
                mask,
                eventId,
                fieldId,
                "MANDATORY",
                page,
                order,
                false,
                "Y",
                condition,
                null,
                pageCondition,
                pageLabel,
                midEvent,
                null);
    }

    private static EventFieldSpec optional(
            int mask,
            String eventId,
            String fieldId,
            int page,
            int order,
            String condition,
            String pageCondition,
            String pageLabel,
            String midEvent) {
        return field(
                mask,
                eventId,
                fieldId,
                "OPTIONAL",
                page,
                order,
                false,
                "Y",
                condition,
                null,
                pageCondition,
                pageLabel,
                midEvent,
                null);
    }

    private static EventFieldSpec field(
            int mask,
            String eventId,
            String fieldId,
            String context,
            int page,
            int order,
            boolean pageColumn,
            String showSummary,
            String condition,
            String retainHidden,
            String pageCondition,
            String pageLabel,
            String midEvent,
            String publish) {
        return new EventFieldSpec(
                mask,
                eventId,
                fieldId,
                context,
                Integer.toString(page),
                page,
                order,
                pageColumn,
                showSummary,
                condition,
                retainHidden,
                pageCondition,
                pageLabel,
                midEvent,
                publish);
    }

    private static ComplexFieldSpec complexField(
            int mask,
            String rowId,
            String eventId,
            String caseFieldId,
            String elementCode,
            String context,
            int order,
            String label) {
        return new ComplexFieldSpec(
                mask,
                rowId,
                eventId,
                caseFieldId,
                elementCode,
                context,
                order,
                label,
                null,
                null,
                null,
                null,
                null);
    }
}
