package uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config;

import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.SingleRole;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.ComplexFieldSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.EventFieldSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.EventSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.GrantSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.domain.caseview.state.CaseState;

import java.util.Set;

@SuppressWarnings({
    "checkstyle:LineLength",
    "checkstyle:RightCurlyAlone",
    "PMD.AvoidDuplicateLiterals"
})
final class SingleHearingManagementRows {
    private static final int CFTLIB_ENGLAND_WALES = 1;
    private static final int CFTLIB_SCOTLAND = 2;
    private static final int CFTLIB = 3;
    private static final int PROD_ENGLAND_WALES = 4;
    private static final int ENGLAND_WALES = 5;
    private static final int PROD_SCOTLAND = 8;
    private static final int SCOTLAND = 10;
    private static final int PROD = 12;
    private static final int ALL = 15;
    private static final String LOCALHOST = "http://localhost:8081";
    private static final String PRODUCTION =
            "http://et-cos-prod.service.core-compute-prod.internal";
    private static final String ALLOCATE_HEARING = "allocateHearing";
    private static final String PRINT_HEARING = "printHearing";
    private static final String ADD_AMEND_HEARING = "addAmendHearing";
    private static final String UPDATE_HEARING = "updateHearing";
    private static final Set<Permission> READ = Set.of(Permission.R);
    private static final Set<Permission> DELETE = Set.of(Permission.D);
    private static final String[] COMMON_HEARING_ELEMENTS = {
        "Hearing_stage",
        "Hearing_type",
        "hearingDateCollection.listedDate",
        "hearingEstLengthNum",
        "hearingEstLengthNumType",
        "hearingFormat",
        "hearingNumber",
        "hearingPublicPrivate",
        "hearingSitAlone",
        "judicialMediation"
    };
    private static final String[] ENGLAND_WALES_HEARING_ELEMENTS = {"Hearing_venue"};
    private static final String[] SCOTLAND_HEARING_ELEMENTS = {
        "Hearing_Aberdeen",
        "Hearing_Dundee",
        "Hearing_Edinburgh",
        "Hearing_Glasgow",
        "Hearing_venue_Scotland",
        "hearingDateCollection.Hearing_typeReadingDeliberation"
    };
    private static final String[] ENGLAND_WALES_HEARING_DETAILS_READ_ELEMENTS = {
        "hearingDetailsCaseDisposed",
        "hearingDetailsDate",
        "hearingDetailsPartHeard",
        "hearingDetailsPostponedBy",
        "hearingDetailsReservedJudgment",
        "hearingDetailsStatus"
    };
    private static final String[] ENGLAND_WALES_HEARING_DETAILS_DELETE_ELEMENTS = {
        "hearingDetailsAttendeeClaimant",
        "hearingDetailsAttendeeNonAttendees",
        "hearingDetailsAttendeeRepOnly",
        "hearingDetailsAttendeeRespAndRep",
        "hearingDetailsAttendeeRespNoRep",
        "hearingDetailsHearingNotes2",
        "hearingDetailsTimingBreak",
        "hearingDetailsTimingDuration",
        "hearingDetailsTimingFinish",
        "hearingDetailsTimingResume",
        "hearingDetailsTimingStart"
    };

    static final GrantSpec[] EVENT_GRANTS = {
        new GrantSpec(ALL, ALLOCATE_HEARING, SingleRole.CASEWORKER_EMPLOYMENT, "R"),
        new GrantSpec(ALL, ALLOCATE_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(
                ENGLAND_WALES,
                ALLOCATE_HEARING,
                SingleRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES,
                "CRU"),
        new GrantSpec(ALL, ALLOCATE_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE, "R"),
        new GrantSpec(
                ENGLAND_WALES,
                ALLOCATE_HEARING,
                SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES,
                "CRU"),
        new GrantSpec(
                SCOTLAND,
                ALLOCATE_HEARING,
                SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_SCOTLAND,
                "CRU"),
        new GrantSpec(SCOTLAND, ALLOCATE_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_SCOTLAND, "CRU"),
        new GrantSpec(ALL, PRINT_HEARING, SingleRole.CASEWORKER_EMPLOYMENT, "R"),
        new GrantSpec(ALL, PRINT_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(
                ENGLAND_WALES, PRINT_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, "CRU"),
        new GrantSpec(ALL, PRINT_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE, "R"),
        new GrantSpec(
                ENGLAND_WALES,
                PRINT_HEARING,
                SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES,
                "CRU"),
        new GrantSpec(
                SCOTLAND, PRINT_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_SCOTLAND, "CRU"),
        new GrantSpec(SCOTLAND, PRINT_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_SCOTLAND, "CRU"),
        new GrantSpec(ALL, ADD_AMEND_HEARING, SingleRole.CASEWORKER_EMPLOYMENT, "R"),
        new GrantSpec(ALL, ADD_AMEND_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(
                ENGLAND_WALES,
                ADD_AMEND_HEARING,
                SingleRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES,
                "CRU"),
        new GrantSpec(ALL, ADD_AMEND_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE, "R"),
        new GrantSpec(
                ENGLAND_WALES,
                ADD_AMEND_HEARING,
                SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES,
                "CRU"),
        new GrantSpec(
                SCOTLAND,
                ADD_AMEND_HEARING,
                SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_SCOTLAND,
                "CRU"),
        new GrantSpec(
                SCOTLAND, ADD_AMEND_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_SCOTLAND, "CRU"),
        new GrantSpec(ALL, UPDATE_HEARING, SingleRole.CASEWORKER_EMPLOYMENT, "R"),
        new GrantSpec(ALL, UPDATE_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(
                ENGLAND_WALES,
                UPDATE_HEARING,
                SingleRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES,
                "CRU"),
        new GrantSpec(ALL, UPDATE_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE, "R"),
        new GrantSpec(
                ENGLAND_WALES,
                UPDATE_HEARING,
                SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES,
                "CRU"),
        new GrantSpec(
                SCOTLAND, UPDATE_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_SCOTLAND, "CRU"),
        new GrantSpec(SCOTLAND, UPDATE_HEARING, SingleRole.CASEWORKER_EMPLOYMENT_SCOTLAND, "CRU"),
        new GrantSpec(ALL, UPDATE_HEARING, SingleRole.CASEWORKER_WA_TASK_CONFIGURATION, "CRU")
    };

    static final EventSpec[] EVENTS = {
        new EventSpec(
                CFTLIB,
                ALLOCATE_HEARING,
                "Allocate Hearing",
                "Allocate a Hearing",
                23,
                "Accepted;Rejected",
                "Accepted(preAcceptCase.caseAccepted=\"Yes\"):1;Rejected",
                "managingOffice !=\"Unassigned\"",
                "N",
                "N",
                null,
                false,
                null,
                LOCALHOST + "/allocatehearing/initialiseHearings",
                LOCALHOST + "/allocatehearing/aboutToSubmit",
                null,
                null),
        new EventSpec(
                PROD,
                ALLOCATE_HEARING,
                "Allocate Hearing",
                "Allocate a Hearing",
                23,
                "Accepted;Rejected",
                "Accepted(preAcceptCase.caseAccepted=\"Yes\"):1;Rejected",
                "managingOffice !=\"Unassigned\"",
                "N",
                "N",
                null,
                false,
                null,
                PRODUCTION + "/allocatehearing/initialiseHearings",
                PRODUCTION + "/allocatehearing/aboutToSubmit",
                null,
                null),
        new EventSpec(
                CFTLIB,
                PRINT_HEARING,
                "Print Hearing lists",
                "Print Hearing documents",
                25,
                "Accepted;Rejected",
                "Accepted(preAcceptCase.caseAccepted=\"Yes\"):1;Rejected",
                "managingOffice !=\"Unassigned\"",
                "N",
                "N",
                null,
                false,
                null,
                LOCALHOST + "/initPrintHearingLists",
                LOCALHOST + "/generateListingsDocSingleCases",
                LOCALHOST + "/generateListingsDocSingleCasesConfirmation",
                "Print List"),
        new EventSpec(
                PROD,
                PRINT_HEARING,
                "Print Hearing lists",
                "Print Hearing documents",
                25,
                "Accepted;Rejected",
                "Accepted(preAcceptCase.caseAccepted=\"Yes\"):1;Rejected",
                "managingOffice !=\"Unassigned\"",
                "N",
                "N",
                null,
                false,
                null,
                PRODUCTION + "/initPrintHearingLists",
                PRODUCTION + "/generateListingsDocSingleCases",
                PRODUCTION + "/generateListingsDocSingleCasesConfirmation",
                "Print List"),
        new EventSpec(
                CFTLIB,
                ADD_AMEND_HEARING,
                "List Hearing",
                "List a Hearing",
                22,
                "Accepted;Rejected",
                "Accepted(preAcceptCase.caseAccepted=\"Yes\"):1;Rejected",
                "managingOffice !=\"Unassigned\"",
                "N",
                "N",
                "Y",
                false,
                null,
                LOCALHOST + "/initialiseHearings",
                LOCALHOST + "/amendHearing",
                null,
                null),
        new EventSpec(
                PROD,
                ADD_AMEND_HEARING,
                "List Hearing",
                "List a Hearing",
                22,
                "Accepted;Rejected",
                "Accepted(preAcceptCase.caseAccepted=\"Yes\"):1;Rejected",
                "managingOffice !=\"Unassigned\"",
                "N",
                "N",
                "Y",
                false,
                null,
                PRODUCTION + "/initialiseHearings",
                PRODUCTION + "/amendHearing",
                null,
                null),
        new EventSpec(
                CFTLIB,
                UPDATE_HEARING,
                "Hearing Details",
                "Update post Hearing details",
                24,
                "Accepted;Rejected",
                "Accepted(preAcceptCase.caseAccepted=\"Yes\"):1;Rejected",
                "managingOffice !=\"Unassigned\"",
                "N",
                "N",
                "Y",
                false,
                null,
                LOCALHOST + "/hearingdetails/initialiseHearings",
                LOCALHOST + "/hearingdetails/aboutToSubmit",
                null,
                null),
        new EventSpec(
                PROD,
                UPDATE_HEARING,
                "Hearing Details",
                "Update post Hearing details",
                24,
                "Accepted;Rejected",
                "Accepted(preAcceptCase.caseAccepted=\"Yes\"):1;Rejected",
                "managingOffice !=\"Unassigned\"",
                "N",
                "N",
                "Y",
                false,
                null,
                PRODUCTION + "/hearingdetails/initialiseHearings",
                PRODUCTION + "/hearingdetails/aboutToSubmit",
                null,
                null)
    };

    static final EventFieldSpec[] EVENT_FIELDS = {
        field(
                CFTLIB,
                ALLOCATE_HEARING,
                "allocateHearingHearing",
                "MANDATORY",
                1,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                LOCALHOST + "/allocatehearing/handleListingSelected",
                null),
        field(
                PROD,
                ALLOCATE_HEARING,
                "allocateHearingHearing",
                "MANDATORY",
                1,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                PRODUCTION + "/allocatehearing/handleListingSelected",
                null),
        field(
                CFTLIB_SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingManagingOffice",
                "MANDATORY",
                2,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                LOCALHOST + "/allocatehearing/handleManagingOfficeSelected",
                null),
        field(
                PROD_SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingManagingOffice",
                "MANDATORY",
                2,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                PRODUCTION + "/allocatehearing/handleManagingOfficeSelected",
                null),
        field(
                ENGLAND_WALES,
                ALLOCATE_HEARING,
                "allocateHearingSitAlone",
                "MANDATORY",
                2,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ALLOCATE_HEARING,
                "allocateHearingJudge",
                "OPTIONAL",
                2,
                2,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ALLOCATE_HEARING,
                "allocateHearingAdditionalJudge",
                "OPTIONAL",
                2,
                3,
                true,
                "Y",
                "allocateHearingSitAlone=\"Two Judges\"",
                null,
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ALLOCATE_HEARING,
                "allocateHearingEmployerMember",
                "OPTIONAL",
                2,
                3,
                true,
                "Y",
                "allocateHearingSitAlone=\"Full Panel\"",
                null,
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ALLOCATE_HEARING,
                "allocateHearingEmployeeMember",
                "OPTIONAL",
                2,
                4,
                true,
                "Y",
                "allocateHearingSitAlone=\"Full Panel\"",
                null,
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ALLOCATE_HEARING,
                "allocateHearingStatus",
                "OPTIONAL",
                2,
                5,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ALLOCATE_HEARING,
                "allocateHearingPostponedBy",
                "MANDATORY",
                2,
                6,
                true,
                "Y",
                "allocateHearingStatus=\"Postponed\"",
                null,
                null,
                null,
                null,
                null),
        field(
                CFTLIB_ENGLAND_WALES,
                ALLOCATE_HEARING,
                "allocateHearingVenue",
                "MANDATORY",
                2,
                7,
                true,
                "Y",
                null,
                null,
                null,
                null,
                LOCALHOST + "/allocatehearing/populateRooms",
                null),
        field(
                PROD_ENGLAND_WALES,
                ALLOCATE_HEARING,
                "allocateHearingVenue",
                "MANDATORY",
                2,
                7,
                true,
                "Y",
                null,
                null,
                null,
                null,
                PRODUCTION + "/allocatehearing/populateRooms",
                null),
        field(
                ENGLAND_WALES,
                ALLOCATE_HEARING,
                "allocateHearingClerk",
                "OPTIONAL",
                2,
                8,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ENGLAND_WALES,
                ALLOCATE_HEARING,
                "allocateHearingRoom",
                "OPTIONAL",
                3,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingSitAlone",
                "MANDATORY",
                3,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingJudge",
                "OPTIONAL",
                3,
                2,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingAdditionalJudge",
                "OPTIONAL",
                3,
                3,
                true,
                "Y",
                "allocateHearingSitAlone=\"Two Judges\"",
                null,
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingReadingDeliberation",
                "OPTIONAL",
                3,
                3,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingEmployerMember",
                "OPTIONAL",
                3,
                4,
                true,
                "Y",
                "allocateHearingSitAlone=\"Full Panel\"",
                null,
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingEmployeeMember",
                "OPTIONAL",
                3,
                5,
                true,
                "Y",
                "allocateHearingSitAlone=\"Full Panel\"",
                null,
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingStatus",
                "OPTIONAL",
                3,
                6,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingPostponedBy",
                "MANDATORY",
                3,
                7,
                true,
                "Y",
                "allocateHearingStatus=\"Postponed\"",
                null,
                null,
                null,
                null,
                null),
        field(
                CFTLIB_SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingVenue",
                "MANDATORY",
                3,
                8,
                true,
                "Y",
                null,
                null,
                null,
                null,
                LOCALHOST + "/allocatehearing/populateRooms",
                null),
        field(
                PROD_SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingVenue",
                "MANDATORY",
                3,
                8,
                true,
                "Y",
                null,
                null,
                null,
                null,
                PRODUCTION + "/allocatehearing/populateRooms",
                null),
        field(
                SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingClerk",
                "OPTIONAL",
                3,
                9,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                SCOTLAND,
                ALLOCATE_HEARING,
                "allocateHearingRoom",
                "OPTIONAL",
                4,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                CFTLIB,
                PRINT_HEARING,
                "printHearingDetails",
                "COMPLEX",
                1,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                LOCALHOST + "/listingSingleCases",
                null),
        field(
                PROD,
                PRINT_HEARING,
                "printHearingDetails",
                "COMPLEX",
                1,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                PRODUCTION + "/listingSingleCases",
                null),
        field(
                ALL,
                PRINT_HEARING,
                "printHearingCollection",
                "COMPLEX",
                2,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                CFTLIB,
                ADD_AMEND_HEARING,
                "hearingCollection",
                "COMPLEX",
                1,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                LOCALHOST + "/midEventAmendHearing",
                null),
        field(
                PROD,
                ADD_AMEND_HEARING,
                "hearingCollection",
                "COMPLEX",
                1,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                PRODUCTION + "/midEventAmendHearing",
                null),
        field(
                ALL,
                ADD_AMEND_HEARING,
                "listedDateInPastWarning",
                "READONLY",
                2,
                1,
                true,
                "Y",
                "hearingCollection=\"dummy\"",
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ADD_AMEND_HEARING,
                "listedDateInPastWarningLabel",
                "READONLY",
                2,
                1,
                true,
                "Y",
                "listedDateInPastWarning=\"Yes\"",
                null,
                "listedDateInPastWarning=\"Yes\"",
                null,
                null,
                null),
        field(
                CFTLIB,
                UPDATE_HEARING,
                "hearingDetailsHearing",
                "MANDATORY",
                1,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                LOCALHOST + "/hearingdetails/handleListingSelected",
                null),
        field(
                PROD,
                UPDATE_HEARING,
                "hearingDetailsHearing",
                "MANDATORY",
                1,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                PRODUCTION + "/hearingdetails/handleListingSelected",
                null),
        field(
                ALL,
                UPDATE_HEARING,
                "nextListedDate",
                "OPTIONAL",
                1,
                2,
                true,
                "N",
                "hearingDetailsHearing=\"dummy\"",
                null,
                null,
                null,
                null,
                "Y"),
        field(
                ALL,
                UPDATE_HEARING,
                "uploadHearingNotesDocument",
                "OPTIONAL",
                2,
                1,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                UPDATE_HEARING,
                "doesHearingNotesDocExist",
                "OPTIONAL",
                2,
                2,
                true,
                "Y",
                "uploadHearingNotesDocument=\"dummy\"",
                null,
                null,
                null,
                null,
                null),
        field(
                ALL,
                UPDATE_HEARING,
                "removeHearingNotesDocument",
                "OPTIONAL",
                2,
                3,
                true,
                "Y",
                "doesHearingNotesDocExist=\"Yes\"",
                null,
                null,
                null,
                null,
                null),
        field(
                CFTLIB_ENGLAND_WALES,
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "COMPLEX",
                2,
                4,
                true,
                "Y",
                null,
                null,
                null,
                null,
                LOCALHOST + "/hearingdetails/hearingMidEventValidation",
                null),
        field(
                PROD_ENGLAND_WALES,
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "COMPLEX",
                2,
                4,
                true,
                "Y",
                null,
                null,
                null,
                null,
                PRODUCTION + "/hearingdetails/hearingMidEventValidation",
                null),
        field(
                SCOTLAND,
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "COMPLEX",
                2,
                4,
                true,
                "Y",
                null,
                null,
                null,
                null,
                null,
                null)
    };

    static final ComplexFieldSpec[] COMPLEX_FIELDS = {
        complexField(
                ALL,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "hearingDateCollection.listedDate",
                "MANDATORY",
                1,
                "Hearing Date",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "hearingNumber",
                "MANDATORY",
                1,
                "Hearing number",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "Hearing_type",
                "MANDATORY",
                2,
                "Hearing type",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "hearingDateCollection.Hearing_typeReadingDeliberation",
                "OPTIONAL",
                2,
                "Reading Day, Deliberation Day, Members Meeting or In Chambers?",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "hearingPublicPrivate",
                "OPTIONAL",
                3,
                "Public or Private?",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "hearingFormat",
                "MANDATORY",
                4,
                "Hearing Format",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "judicialMediation",
                "OPTIONAL",
                5,
                "Judicial Mediation",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "Hearing_venue",
                "MANDATORY",
                6,
                "Hearing Venue",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "Hearing_venue_Scotland",
                "MANDATORY",
                6,
                "Managing Office",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "Hearing_Aberdeen",
                "MANDATORY",
                7,
                "Venue",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "Hearing_Dundee",
                "MANDATORY",
                7,
                "Venue",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "Hearing_Edinburgh",
                "MANDATORY",
                7,
                "Venue",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "Hearing_Glasgow",
                "MANDATORY",
                7,
                "Venue",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "hearingEstLengthNum",
                "MANDATORY",
                7,
                "Estimated hearing length",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "hearingEstLengthNum",
                "MANDATORY",
                8,
                "Estimated hearing length",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "hearingEstLengthNumType",
                "MANDATORY",
                8,
                "Days, Hours or Minutes",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "hearingEstLengthNumType",
                "MANDATORY",
                9,
                "Days, Hours or Minutes",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "hearingSitAlone",
                "MANDATORY",
                9,
                "Panel Type",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "Hearing_stage",
                "OPTIONAL",
                10,
                "EQP Stage Hearing",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "hearingSitAlone",
                "MANDATORY",
                10,
                "Panel Type",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "Hearing_notes",
                "OPTIONAL",
                11,
                "Hearing Notes",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "Hearing_stage",
                "OPTIONAL",
                11,
                "EQP Stage Hearing",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Hearing",
                ADD_AMEND_HEARING,
                "hearingCollection",
                "Hearing_notes",
                "OPTIONAL",
                12,
                "Hearing Notes",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsDate",
                "READONLY",
                1,
                "Hearing Date",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsStatus",
                "MANDATORY",
                2,
                "Hearing Status",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsPostponedBy",
                "MANDATORY",
                3,
                "Postponed by",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsCaseDisposed",
                "MANDATORY",
                4,
                "Has the case or part of the case been disposed?",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsPartHeard",
                "OPTIONAL",
                5,
                "Has the hearing been part heard?",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsReservedJudgment",
                "OPTIONAL",
                6,
                "Is there a reserved Judgment?",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsAttendeeClaimant",
                "OPTIONAL",
                7,
                "Attendees (Claimant)",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsAttendeeNonAttendees",
                "OPTIONAL",
                8,
                "Number of Non Attendees (Respondent) ",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsAttendeeRespNoRep",
                "OPTIONAL",
                9,
                "Respondent Attended - No Representative",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsAttendeeRespAndRep",
                "OPTIONAL",
                10,
                "Respondent and Representative Attended",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsAttendeeRepOnly",
                "OPTIONAL",
                11,
                "Respondent representative only attended",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsTimingStart",
                "OPTIONAL",
                12,
                "Start Time",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsTimingBreak",
                "OPTIONAL",
                13,
                "Break",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsTimingResume",
                "OPTIONAL",
                14,
                "Resume",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsTimingFinish",
                "OPTIONAL",
                15,
                "Finish",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsTimingDuration",
                "OPTIONAL",
                16,
                "Duration",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "HearingDetails",
                UPDATE_HEARING,
                "hearingDetailsCollection",
                "hearingDetailsHearingNotes2",
                "OPTIONAL",
                17,
                "Hearing Notes",
                null,
                null,
                null,
                null,
                "Y"),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection",
                "READONLY",
                1,
                null,
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.causeListDate",
                "READONLY",
                1,
                "Date",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.causeListDate",
                "READONLY",
                2,
                "Date",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.causeListTime",
                "READONLY",
                2,
                "Time",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.causeListTime",
                "READONLY",
                3,
                "Time",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.causeListVenue",
                "READONLY",
                3,
                "Location",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.causeListVenue",
                "READONLY",
                4,
                "Location",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.elmoCaseReference",
                "READONLY",
                4,
                "Case Number",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.elmoCaseReference",
                "READONLY",
                5,
                "Case Number",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.jurisdictionCodesList",
                "READONLY",
                5,
                "Jurisdiction",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.hearingType",
                "READONLY",
                6,
                "Case Type",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.jurisdictionCodesList",
                "READONLY",
                6,
                "Jurisdiction",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.hearingType",
                "READONLY",
                7,
                "Case Type",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.positionType",
                "READONLY",
                7,
                "Position",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.hearingJudgeName",
                "READONLY",
                8,
                "Employment Judge",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.positionType",
                "READONLY",
                8,
                "Position",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.additionalJudge",
                "READONLY",
                9,
                "Employment Judge",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.hearingJudgeName",
                "READONLY",
                9,
                "Employment Judge",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.additionalJudge",
                "READONLY",
                10,
                "Employment Judge",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.hearingEEMember",
                "READONLY",
                10,
                "Employee Member",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.hearingEEMember",
                "READONLY",
                11,
                "Employee Member",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.hearingERMember",
                "READONLY",
                11,
                "Employer Member",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.hearingClerk",
                "READONLY",
                12,
                "Hearing Clerk",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.hearingERMember",
                "READONLY",
                12,
                "Employer Member",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.hearingClerk",
                "READONLY",
                13,
                "Hearing Clerk",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.hearingDay",
                "READONLY",
                13,
                "Hearing Day",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.claimantName",
                "READONLY",
                14,
                "Claimant",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.hearingDay",
                "READONLY",
                14,
                "Hearing Day",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.claimantName",
                "READONLY",
                15,
                "Claimant",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.claimantTown",
                "READONLY",
                15,
                "Claimant Town",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.claimantRepresentative",
                "READONLY",
                16,
                "Representative",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.claimantTown",
                "READONLY",
                16,
                "Claimant Town",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.claimantRepresentative",
                "READONLY",
                17,
                "Representative",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.respondent",
                "READONLY",
                17,
                "Respondent",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.respondent",
                "READONLY",
                18,
                "Respondent",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.respondentTown",
                "READONLY",
                18,
                "Respondent Town",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.respondentRepresentative",
                "READONLY",
                19,
                "Representative",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.respondentTown",
                "READONLY",
                19,
                "Respondent Town",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.estHearingLength",
                "READONLY",
                20,
                "Estimated Duration",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.respondentRepresentative",
                "READONLY",
                20,
                "Representative",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.estHearingLength",
                "READONLY",
                21,
                "Estimated Duration",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.Hearing_panel",
                "READONLY",
                21,
                "Hearing Panel",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.Hearing_panel",
                "READONLY",
                22,
                "Hearing Panel",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.Hearing_room",
                "READONLY",
                22,
                "Room",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.Hearing_notes",
                "READONLY",
                23,
                "Hearing Notes",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.Hearing_room",
                "READONLY",
                23,
                "Room",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.Hearing_notes",
                "READONLY",
                24,
                "Hearing Notes",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.resp_others",
                "READONLY",
                24,
                "Respondent Others",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingCollection",
                "listingCollection.resp_others",
                "READONLY",
                25,
                "Respondent Others",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "hearingDateType",
                "MANDATORY",
                1,
                "Single or Range",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "listingDateFrom",
                "MANDATORY",
                2,
                "Hearing From",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "listingDateTo",
                "MANDATORY",
                3,
                "Hearing To",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ALL,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "listingDate",
                "MANDATORY",
                4,
                "Hearing Date",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "listingVenue",
                "MANDATORY",
                5,
                "Hearing Venue",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "listingVenueScotland",
                "MANDATORY",
                5,
                "Managing Office",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "hearingDocType",
                "MANDATORY",
                6,
                "Hearing Document",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "venueAberdeen",
                "MANDATORY",
                6,
                "Hearing Venue",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "venueDundee",
                "MANDATORY",
                6,
                "Hearing Venue",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "venueEdinburgh",
                "MANDATORY",
                6,
                "Hearing Venue",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "venueGlasgow",
                "MANDATORY",
                6,
                "Hearing Venue",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "hearingDocETCL",
                "MANDATORY",
                7,
                "Type",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "hearingDocType",
                "MANDATORY",
                7,
                "Hearing Document",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "hearingDocETCL",
                "MANDATORY",
                8,
                "Type",
                null,
                null,
                null,
                null,
                null),
        complexField(
                ENGLAND_WALES,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "roomOrNoRoom",
                "MANDATORY",
                8,
                "Split by room",
                null,
                null,
                null,
                null,
                null),
        complexField(
                SCOTLAND,
                "Scheduling",
                PRINT_HEARING,
                "printHearingDetails",
                "roomOrNoRoom",
                "MANDATORY",
                9,
                "Split by room",
                null,
                null,
                null,
                null,
                null)
    };

    private SingleHearingManagementRows() {}

    static void configureComplexTypeAccess(
            ConfigBuilder<CaseData, CaseState, SingleRole> builder,
            SingleDefinitionSupport.Variant variant) {
        if (variant.includes(SCOTLAND)) {
            grantHearingElements(builder, COMMON_HEARING_ELEMENTS, Permission.CRU);
            grantHearingElements(builder, SCOTLAND_HEARING_ELEMENTS, Permission.CRU);
        } else {
            grantHearingElements(builder, COMMON_HEARING_ELEMENTS, READ);
            grantHearingElements(builder, ENGLAND_WALES_HEARING_ELEMENTS, READ);
            grantHearingDetailsElements(builder, ENGLAND_WALES_HEARING_DETAILS_READ_ELEMENTS, READ);
            grantHearingDetailsElements(
                    builder, ENGLAND_WALES_HEARING_DETAILS_DELETE_ELEMENTS, DELETE);
        }
    }

    private static void grantHearingElements(
            ConfigBuilder<CaseData, CaseState, SingleRole> builder,
            String[] elements,
            Set<Permission> solicitorPermissions) {
        for (String element : elements) {
            builder.grantComplexType(
                    CaseData::getHearingCollection,
                    element,
                    Permission.CRU,
                    SingleRole.CASEWORKER_EMPLOYMENT);
            builder.grantComplexType(
                    CaseData::getHearingCollection,
                    element,
                    solicitorPermissions,
                    SingleRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        }
    }

    private static void grantHearingDetailsElements(
            ConfigBuilder<CaseData, CaseState, SingleRole> builder,
            String[] elements,
            Set<Permission> permissions) {
        for (String element : elements) {
            builder.grantComplexType(
                    CaseData::getHearingDetailsCollection,
                    element,
                    permissions,
                    SingleRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR);
        }
    }

    private static EventFieldSpec field(
            int mask,
            String eventId,
            String fieldId,
            String context,
            int page,
            int order,
            boolean pageColumn,
            String showSummary,
            String condition,
            String retainHidden,
            String pageCondition,
            String pageLabel,
            String midEvent,
            String publish) {
        return new EventFieldSpec(
                mask,
                eventId,
                fieldId,
                context,
                Integer.toString(page),
                page,
                order,
                pageColumn,
                showSummary,
                condition,
                retainHidden,
                pageCondition,
                pageLabel,
                midEvent,
                publish);
    }

    private static ComplexFieldSpec complexField(
            int mask,
            String rowId,
            String eventId,
            String caseFieldId,
            String elementCode,
            String context,
            int order,
            String label,
            String hint,
            String condition,
            String retainHidden,
            String defaultValue,
            String publish) {
        return new ComplexFieldSpec(
                mask,
                rowId,
                eventId,
                caseFieldId,
                elementCode,
                context,
                order,
                label,
                hint,
                condition,
                retainHidden,
                defaultValue,
                publish);
    }
}
