package uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config;

import uk.gov.hmcts.et.common.model.ccd.SingleRole;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.ComplexFieldSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.EventFieldSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.EventSpec;
import uk.gov.hmcts.ethos.replacement.docmosis.ccd.migration.config.SingleDefinitionRows.GrantSpec;

@SuppressWarnings({
    "checkstyle:LineLength",
    "checkstyle:RightCurlyAlone",
    "PMD.AvoidDuplicateLiterals"
})
final class SingleEt1ClaimIntakeRows {
    private static final int CFTLIB_ENGLAND_WALES = 1;
    private static final int CFTLIB = 3;
    private static final int PROD_ENGLAND_WALES = 4;
    private static final int ENGLAND_WALES = 5;
    private static final int SCOTLAND = 10;
    private static final int PROD = 12;
    private static final int ALL = 15;
    private static final String LOCALHOST = "http://localhost:8081";
    private static final String PRODUCTION =
            "http://et-cos-prod.service.core-compute-prod.internal";
    private static final String ET1_REPPED_CREATE_CASE = "et1ReppedCreateCase";
    private static final String ET1_SECTION_ONE = "et1SectionOne";
    private static final String ET1_SECTION_TWO = "et1SectionTwo";
    private static final String ET1_SECTION_THREE = "et1SectionThree";
    private static final String CREATE_DRAFT_ET1 = "createDraftEt1";
    private static final String SUBMIT_ET1_DRAFT = "submitEt1Draft";
    private static final String GENERATE_ET1_DOCUMENTS = "generateEt1Documents";
    private static final String ET1_VETTING = "et1Vetting";

    static final GrantSpec[] EVENT_GRANTS = {
        new GrantSpec(ALL, ET1_REPPED_CREATE_CASE, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(
                ALL,
                ET1_REPPED_CREATE_CASE,
                SingleRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR,
                "CRUD"),
        new GrantSpec(ALL, ET1_SECTION_ONE, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(ALL, ET1_SECTION_ONE, SingleRole.CLAIMANTSOLICITOR, "CRU"),
        new GrantSpec(ALL, ET1_SECTION_TWO, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(ALL, ET1_SECTION_TWO, SingleRole.CLAIMANTSOLICITOR, "CRU"),
        new GrantSpec(ALL, ET1_SECTION_THREE, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(ALL, ET1_SECTION_THREE, SingleRole.CLAIMANTSOLICITOR, "CRU"),
        new GrantSpec(ALL, CREATE_DRAFT_ET1, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(ALL, CREATE_DRAFT_ET1, SingleRole.CLAIMANTSOLICITOR, "CRU"),
        new GrantSpec(ALL, SUBMIT_ET1_DRAFT, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(ALL, SUBMIT_ET1_DRAFT, SingleRole.CASEWORKER_WA_TASK_CONFIGURATION, "CRUD"),
        new GrantSpec(ALL, SUBMIT_ET1_DRAFT, SingleRole.CLAIMANTSOLICITOR, "CRU"),
        new GrantSpec(ALL, GENERATE_ET1_DOCUMENTS, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(ALL, ET1_VETTING, SingleRole.CASEWORKER_EMPLOYMENT, "R"),
        new GrantSpec(ALL, ET1_VETTING, SingleRole.CASEWORKER_EMPLOYMENT_API, "CRUD"),
        new GrantSpec(
                ENGLAND_WALES, ET1_VETTING, SingleRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, "CRU"),
        new GrantSpec(ALL, ET1_VETTING, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE, "R"),
        new GrantSpec(
                ENGLAND_WALES,
                ET1_VETTING,
                SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES,
                "CRU"),
        new GrantSpec(
                SCOTLAND, ET1_VETTING, SingleRole.CASEWORKER_EMPLOYMENT_ETJUDGE_SCOTLAND, "CRU"),
        new GrantSpec(SCOTLAND, ET1_VETTING, SingleRole.CASEWORKER_EMPLOYMENT_SCOTLAND, "CRU")
    };

    static final EventSpec[] EVENTS = {
        new EventSpec(
                CFTLIB,
                ET1_REPPED_CREATE_CASE,
                "Create draft claim",
                "Create a new draft claim",
                54,
                null,
                "AWAITING_SUBMISSION_TO_HMCTS",
                null,
                "N",
                "N",
                null,
                true,
                "365",
                null,
                LOCALHOST + "/et1Repped/createCase/aboutToSubmit",
                LOCALHOST + "/et1Repped/createCase/submitted",
                "Create draft claim"),
        new EventSpec(
                PROD,
                ET1_REPPED_CREATE_CASE,
                "Create draft claim",
                "Create a new draft claim",
                54,
                null,
                "AWAITING_SUBMISSION_TO_HMCTS",
                null,
                "N",
                "N",
                null,
                true,
                "365",
                null,
                PRODUCTION + "/et1Repped/createCase/aboutToSubmit",
                PRODUCTION + "/et1Repped/createCase/submitted",
                "Create draft claim"),
        new EventSpec(
                CFTLIB,
                ET1_SECTION_ONE,
                "ET1 - Claimant details",
                "Claimant details",
                55,
                "AWAITING_SUBMISSION_TO_HMCTS",
                "AWAITING_SUBMISSION_TO_HMCTS",
                null,
                "Y",
                "N",
                null,
                false,
                null,
                null,
                LOCALHOST + "/et1Repped/aboutToSubmitSection",
                LOCALHOST + "/et1Repped/sectionCompleted",
                "Save as draft"),
        new EventSpec(
                PROD,
                ET1_SECTION_ONE,
                "ET1 - Claimant details",
                "Claimant details",
                55,
                "AWAITING_SUBMISSION_TO_HMCTS",
                "AWAITING_SUBMISSION_TO_HMCTS",
                null,
                "Y",
                "N",
                null,
                false,
                null,
                null,
                PRODUCTION + "/et1Repped/aboutToSubmitSection",
                PRODUCTION + "/et1Repped/sectionCompleted",
                "Save as draft"),
        new EventSpec(
                CFTLIB,
                ET1_SECTION_TWO,
                "Employment & Respondent Detail",
                "Employment & Respondent Detail",
                56,
                "AWAITING_SUBMISSION_TO_HMCTS",
                "AWAITING_SUBMISSION_TO_HMCTS",
                null,
                "Y",
                "N",
                null,
                false,
                null,
                null,
                LOCALHOST + "/et1Repped/aboutToSubmitSection",
                LOCALHOST + "/et1Repped/sectionCompleted",
                "Save as draft"),
        new EventSpec(
                PROD,
                ET1_SECTION_TWO,
                "Employment & Respondent Detail",
                "Employment & Respondent Detail",
                56,
                "AWAITING_SUBMISSION_TO_HMCTS",
                "AWAITING_SUBMISSION_TO_HMCTS",
                null,
                "Y",
                "N",
                null,
                false,
                null,
                null,
                PRODUCTION + "/et1Repped/aboutToSubmitSection",
                PRODUCTION + "/et1Repped/sectionCompleted",
                "Save as draft"),
        new EventSpec(
                CFTLIB,
                ET1_SECTION_THREE,
                "Claim Details",
                "Claim Details",
                57,
                "AWAITING_SUBMISSION_TO_HMCTS",
                "AWAITING_SUBMISSION_TO_HMCTS",
                null,
                "Y",
                "N",
                null,
                false,
                null,
                null,
                LOCALHOST + "/et1Repped/aboutToSubmitSection",
                LOCALHOST + "/et1Repped/sectionCompleted",
                "Save as draft"),
        new EventSpec(
                PROD,
                ET1_SECTION_THREE,
                "Claim Details",
                "Claim Details",
                57,
                "AWAITING_SUBMISSION_TO_HMCTS",
                "AWAITING_SUBMISSION_TO_HMCTS",
                null,
                "Y",
                "N",
                null,
                false,
                null,
                null,
                PRODUCTION + "/et1Repped/aboutToSubmitSection",
                PRODUCTION + "/et1Repped/sectionCompleted",
                "Save as draft"),
        new EventSpec(
                CFTLIB,
                CREATE_DRAFT_ET1,
                "Download draft ET1 Form",
                "Download draft ET1 form",
                58,
                "AWAITING_SUBMISSION_TO_HMCTS",
                "AWAITING_SUBMISSION_TO_HMCTS",
                "et1ReppedSectionOne = \"Yes\" OR et1ReppedSectionTwo = \"Yes\" OR"
                    + " et1ReppedSectionThree = \"Yes\"",
                "N",
                "N",
                null,
                false,
                null,
                null,
                LOCALHOST + "/et1Repped/createDraftEt1",
                LOCALHOST + "/et1Repped/createDraftEt1Submitted",
                "Download draft ET1"),
        new EventSpec(
                PROD,
                CREATE_DRAFT_ET1,
                "Download draft ET1 Form",
                "Download draft ET1 form",
                58,
                "AWAITING_SUBMISSION_TO_HMCTS",
                "AWAITING_SUBMISSION_TO_HMCTS",
                "et1ReppedSectionOne = \"Yes\" OR et1ReppedSectionTwo = \"Yes\" OR"
                    + " et1ReppedSectionThree = \"Yes\"",
                "N",
                "N",
                null,
                false,
                null,
                null,
                PRODUCTION + "/et1Repped/createDraftEt1",
                PRODUCTION + "/et1Repped/createDraftEt1Submitted",
                "Download draft ET1"),
        new EventSpec(
                CFTLIB,
                SUBMIT_ET1_DRAFT,
                "Submit ET1 Claim",
                "Submit ET1 Claim",
                57,
                "AWAITING_SUBMISSION_TO_HMCTS",
                "Submitted",
                "et1ReppedSectionOne = \"Yes\" AND et1ReppedSectionTwo = \"Yes\" AND"
                    + " et1ReppedSectionThree = \"Yes\"",
                "N",
                "N",
                "Y",
                true,
                "36524",
                null,
                LOCALHOST + "/et1Repped/submitClaim",
                LOCALHOST + "/et1Repped/submitted",
                "Submit ET1"),
        new EventSpec(
                PROD,
                SUBMIT_ET1_DRAFT,
                "Submit ET1 Claim",
                "Submit ET1 Claim",
                57,
                "AWAITING_SUBMISSION_TO_HMCTS",
                "Submitted",
                "et1ReppedSectionOne = \"Yes\" AND et1ReppedSectionTwo = \"Yes\" AND"
                    + " et1ReppedSectionThree = \"Yes\"",
                "N",
                "N",
                "Y",
                true,
                "36524",
                null,
                PRODUCTION + "/et1Repped/submitClaim",
                PRODUCTION + "/et1Repped/submitted",
                "Submit ET1"),
        new EventSpec(
                CFTLIB,
                GENERATE_ET1_DOCUMENTS,
                "generateEt1Documents",
                "Generate ET1 docs in the background",
                58,
                "*",
                "*",
                "caseType = \"dummy\"",
                "N",
                "N",
                null,
                false,
                null,
                null,
                LOCALHOST + "/et1Repped/generateDocuments",
                null,
                null),
        new EventSpec(
                PROD,
                GENERATE_ET1_DOCUMENTS,
                "generateEt1Documents",
                "Generate ET1 docs in the background",
                58,
                "*",
                "*",
                "caseType = \"dummy\"",
                "N",
                "N",
                null,
                false,
                null,
                null,
                PRODUCTION + "/et1Repped/generateDocuments",
                null,
                null),
        new EventSpec(
                CFTLIB,
                ET1_VETTING,
                "ET1 case vetting",
                "Vetting a case",
                8,
                "Submitted;Rejected;Vetted",
                "Vetted",
                "managingOffice !=\"Unassigned\"",
                "Y",
                "N",
                null,
                false,
                null,
                LOCALHOST + "/initialiseEt1Vetting",
                LOCALHOST + "/et1VettingAboutToSubmit",
                LOCALHOST + "/finishEt1Vetting",
                null),
        new EventSpec(
                PROD,
                ET1_VETTING,
                "ET1 case vetting",
                "Vetting a case",
                8,
                "Submitted;Rejected;Vetted",
                "Vetted",
                "managingOffice !=\"Unassigned\"",
                "Y",
                "N",
                null,
                false,
                null,
                PRODUCTION + "/initialiseEt1Vetting",
                PRODUCTION + "/et1VettingAboutToSubmit",
                PRODUCTION + "/finishEt1Vetting",
                null)
    };

    static final EventFieldSpec[] EVENT_FIELDS = {
        readOnly(
                ALL,
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageLabel",
                1,
                1,
                null,
                null,
                "Claimant's work location",
                null),
        complex(
                ALL,
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageAddress",
                1,
                2,
                null,
                null,
                null,
                null),
        readOnly(
                CFTLIB,
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageYesNo",
                1,
                3,
                "et1ReppedTriageAddress=\"dummy\"",
                null,
                null,
                LOCALHOST + "/et1Repped/createCase/validatePostcode"),
        readOnly(
                PROD,
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageYesNo",
                1,
                3,
                "et1ReppedTriageAddress=\"dummy\"",
                null,
                null,
                PRODUCTION + "/et1Repped/createCase/validatePostcode"),
        readOnly(
                CFTLIB_ENGLAND_WALES,
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageError",
                2,
                1,
                null,
                "et1ReppedTriageYesNo=\"No\"",
                "Service not available yet",
                LOCALHOST + "/et1Repped/createCase/officeError"),
        readOnly(
                PROD_ENGLAND_WALES,
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageError",
                2,
                1,
                null,
                "et1ReppedTriageYesNo=\"No\"",
                "Service not available yet",
                PRODUCTION + "/et1Repped/createCase/officeError"),
        readOnly(
                ALL,
                ET1_SECTION_ONE,
                "et1Section1PreambleLabel",
                1,
                1,
                null,
                null,
                "Make a claim to an employment tribunal",
                null),
        field(
                ALL,
                ET1_SECTION_ONE,
                "claimantFirstName",
                "MANDATORY",
                2,
                1,
                true,
                "Y",
                null,
                null,
                "Claimant details",
                null),
        field(
                ALL,
                ET1_SECTION_ONE,
                "claimantLastName",
                "MANDATORY",
                2,
                2,
                true,
                "Y",
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET1_SECTION_ONE,
                "claimantDateOfBirth",
                "OPTIONAL",
                2,
                3,
                true,
                "Y",
                null,
                null,
                null,
                null),
        optional(
                CFTLIB,
                ET1_SECTION_ONE,
                "claimantSex",
                3,
                1,
                null,
                null,
                "Claimant details",
                LOCALHOST + "/et1Repped/sectionOne/validateClaimantSex"),
        optional(
                PROD,
                ET1_SECTION_ONE,
                "claimantSex",
                3,
                1,
                null,
                null,
                "Claimant details",
                PRODUCTION + "/et1Repped/sectionOne/validateClaimantSex"),
        optional(ALL, ET1_SECTION_ONE, "claimantPreferredTitle", 3, 2, null, null, null, null),
        mandatory(
                ALL,
                ET1_SECTION_ONE,
                "claimantContactAddress",
                4,
                1,
                null,
                null,
                "Claimant contact address",
                null),
        readOnly(
                ALL,
                ET1_SECTION_ONE,
                "hearingFormatPreamble",
                5,
                1,
                null,
                null,
                "Hearing format",
                null),
        optional(
                CFTLIB,
                ET1_SECTION_ONE,
                "representativeAttendHearing",
                5,
                2,
                null,
                null,
                null,
                LOCALHOST + "/et1Repped/sectionOne/validateHearingPreferences"),
        optional(
                PROD,
                ET1_SECTION_ONE,
                "representativeAttendHearing",
                5,
                2,
                null,
                null,
                null,
                PRODUCTION + "/et1Repped/sectionOne/validateHearingPreferences"),
        optional(SCOTLAND, ET1_SECTION_ONE, "claimantAttendHearing", 5, 3, null, null, null, null),
        optional(
                ENGLAND_WALES,
                ET1_SECTION_ONE,
                "hearingContactLanguage",
                5,
                3,
                null,
                null,
                null,
                null),
        optional(
                ENGLAND_WALES,
                ET1_SECTION_ONE,
                "claimantAttendHearing",
                5,
                4,
                null,
                null,
                null,
                null),
        optional(
                ENGLAND_WALES,
                ET1_SECTION_ONE,
                "claimantHearingContactLanguage",
                5,
                5,
                null,
                null,
                null,
                null),
        optional(
                CFTLIB,
                ET1_SECTION_ONE,
                "claimantSupportQuestion",
                6,
                1,
                null,
                null,
                "In the claimant party - are you aware of any physical, mental or learning"
                    + " disability or health condition which requires support?",
                LOCALHOST + "/et1Repped/sectionOne/validateClaimantSupport"),
        optional(
                PROD,
                ET1_SECTION_ONE,
                "claimantSupportQuestion",
                6,
                1,
                null,
                null,
                "In the claimant party - are you aware of any physical, mental or learning"
                    + " disability or health condition which requires support?",
                PRODUCTION + "/et1Repped/sectionOne/validateClaimantSupport"),
        optional(
                ALL,
                ET1_SECTION_ONE,
                "claimantSupportQuestionReason",
                6,
                2,
                "claimantSupportQuestion CONTAINS \"Yes\"",
                null,
                null,
                null),
        readOnly(
                CFTLIB,
                ET1_SECTION_ONE,
                "representativeInformationPreamble",
                7,
                1,
                null,
                null,
                "Your information (as the representative)",
                LOCALHOST + "/et1Repped/sectionOne/validateRepresentativeInformation"),
        readOnly(
                PROD,
                ET1_SECTION_ONE,
                "representativeInformationPreamble",
                7,
                1,
                null,
                null,
                "Your information (as the representative)",
                PRODUCTION + "/et1Repped/sectionOne/validateRepresentativeInformation"),
        optional(
                ALL,
                ET1_SECTION_ONE,
                "representativeContactPreference",
                7,
                2,
                null,
                null,
                null,
                null),
        optional(
                ALL,
                ET1_SECTION_ONE,
                "contactPreferencePostReason",
                7,
                3,
                "representativeContactPreference CONTAINS \"Post\"",
                null,
                null,
                null),
        optional(
                ENGLAND_WALES,
                ET1_SECTION_ONE,
                "contactLanguageQuestion",
                7,
                4,
                null,
                null,
                null,
                null),
        optional(ALL, ET1_SECTION_ONE, "representativeAddress", 7, 5, null, null, null, null),
        optional(ALL, ET1_SECTION_ONE, "representativePhoneNumber", 7, 6, null, null, null, null),
        optional(
                ALL,
                ET1_SECTION_ONE,
                "representativeReferenceNumber",
                7,
                7,
                null,
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_SECTION_TWO,
                "et1Section2PreambleLabel",
                1,
                1,
                null,
                null,
                "Section 2 - Employment and respondent details",
                null),
        optional(
                CFTLIB,
                ET1_SECTION_TWO,
                "didClaimantWorkForOrg",
                2,
                1,
                null,
                null,
                "Did the claimant work for the respondent the claim is being made against?"
                    + " (Optional)",
                LOCALHOST + "/et1Repped/sectionTwo/validateClaimantWorked"),
        optional(
                PROD,
                ET1_SECTION_TWO,
                "didClaimantWorkForOrg",
                2,
                1,
                null,
                null,
                "Did the claimant work for the respondent the claim is being made against?"
                    + " (Optional)",
                PRODUCTION + "/et1Repped/sectionTwo/validateClaimantWorked"),
        optional(
                CFTLIB,
                ET1_SECTION_TWO,
                "claimantStillWorking",
                3,
                1,
                null,
                "didClaimantWorkForOrg CONTAINS \"Yes\"",
                "Is the claimant still working for the respondent the claim is being made against?"
                    + " (Optional)",
                LOCALHOST + "/et1Repped/sectionTwo/validateClaimantWorking"),
        optional(
                PROD,
                ET1_SECTION_TWO,
                "claimantStillWorking",
                3,
                1,
                null,
                "didClaimantWorkForOrg CONTAINS \"Yes\"",
                "Is the claimant still working for the respondent the claim is being made against?"
                    + " (Optional)",
                PRODUCTION + "/et1Repped/sectionTwo/validateClaimantWorking"),
        optional(
                ALL,
                ET1_SECTION_TWO,
                "claimantJobTitle",
                4,
                1,
                null,
                "didClaimantWorkForOrg CONTAINS \"Yes\"",
                "Claimant employment details",
                null),
        optional(ALL, ET1_SECTION_TWO, "claimantStartDate", 4, 2, null, null, null, null),
        optional(ALL, ET1_SECTION_TWO, "claimantEndDate", 4, 3, null, null, null, null),
        optional(
                CFTLIB,
                ET1_SECTION_TWO,
                "claimantStillWorkingNoticePeriod",
                5,
                1,
                null,
                "claimantStillWorking CONTAINS \"Working\"",
                "Does the claimant have a written contract with \na notice period? (Optional)",
                LOCALHOST + "/et1Repped/sectionTwo/validateClaimantWrittenNoticePeriod"),
        optional(
                PROD,
                ET1_SECTION_TWO,
                "claimantStillWorkingNoticePeriod",
                5,
                1,
                null,
                "claimantStillWorking CONTAINS \"Working\"",
                "Does the claimant have a written contract with \na notice period? (Optional)",
                PRODUCTION + "/et1Repped/sectionTwo/validateClaimantWrittenNoticePeriod"),
        optional(
                ALL,
                ET1_SECTION_TWO,
                "claimantStillWorkingNoticePeriodMonths",
                5,
                2,
                "claimantStillWorkingNoticePeriod CONTAINS \"Months\"",
                null,
                null,
                null),
        optional(
                ALL,
                ET1_SECTION_TWO,
                "claimantStillWorkingNoticePeriodWeeks",
                5,
                3,
                "claimantStillWorkingNoticePeriod CONTAINS \"Weeks\"",
                null,
                null,
                null),
        optional(
                CFTLIB,
                ET1_SECTION_TWO,
                "claimantWorkingNoticePeriod",
                6,
                1,
                null,
                "claimantStillWorking CONTAINS \"Notice\"",
                "Is the notice period in months or weeks? (Optional)",
                LOCALHOST + "/et1Repped/sectionTwo/validateClaimantWorkingNoticePeriod"),
        optional(
                PROD,
                ET1_SECTION_TWO,
                "claimantWorkingNoticePeriod",
                6,
                1,
                null,
                "claimantStillWorking CONTAINS \"Notice\"",
                "Is the notice period in months or weeks? (Optional)",
                PRODUCTION + "/et1Repped/sectionTwo/validateClaimantWorkingNoticePeriod"),
        optional(
                ALL,
                ET1_SECTION_TWO,
                "claimantWorkingNoticePeriodMonths",
                6,
                2,
                "claimantWorkingNoticePeriod CONTAINS \"Months\"",
                null,
                null,
                null),
        optional(
                ALL,
                ET1_SECTION_TWO,
                "claimantWorkingNoticePeriodWeeks",
                6,
                3,
                "claimantWorkingNoticePeriod CONTAINS \"Weeks\"",
                null,
                null,
                null),
        optional(
                ALL,
                ET1_SECTION_TWO,
                "claimantWorkingNoticePeriodEndDate",
                6,
                4,
                null,
                null,
                null,
                null),
        optional(
                CFTLIB,
                ET1_SECTION_TWO,
                "claimantNoLongerWorkingQuestion",
                7,
                1,
                null,
                "claimantStillWorking CONTAINS \"No longer working\"",
                "Did the claimant work or get paid for a notice period? (Optional)",
                LOCALHOST + "/et1Repped/sectionTwo/validateClaimantNoLongerWorking"),
        optional(
                PROD,
                ET1_SECTION_TWO,
                "claimantNoLongerWorkingQuestion",
                7,
                1,
                null,
                "claimantStillWorking CONTAINS \"No longer working\"",
                "Did the claimant work or get paid for a notice period? (Optional)",
                PRODUCTION + "/et1Repped/sectionTwo/validateClaimantNoLongerWorking"),
        optional(
                ALL,
                ET1_SECTION_TWO,
                "claimantNoLongerWorking",
                7,
                2,
                "claimantNoLongerWorkingQuestion CONTAINS \"Worked\" OR"
                    + " claimantNoLongerWorkingQuestion CONTAINS \"Paid\"",
                null,
                null,
                null),
        optional(
                ALL,
                ET1_SECTION_TWO,
                "claimantNoLongerWorkingMonths",
                7,
                3,
                "claimantNoLongerWorking CONTAINS \"Months\"",
                null,
                null,
                null),
        optional(
                ALL,
                ET1_SECTION_TWO,
                "claimantNoLongerWorkingWeeks",
                7,
                4,
                "claimantNoLongerWorking CONTAINS \"Weeks\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_SECTION_TWO,
                "claimantAverageWeeklyWorkHoursPreamble",
                8,
                1,
                null,
                "didClaimantWorkForOrg CONTAINS \"Yes\"",
                "Average weekly work hours",
                null),
        optional(
                ALL,
                ET1_SECTION_TWO,
                "claimantAverageWeeklyWorkHours",
                8,
                2,
                null,
                null,
                null,
                null),
        readOnly(
                CFTLIB,
                ET1_SECTION_TWO,
                "claimantPayPreamble",
                9,
                1,
                null,
                "didClaimantWorkForOrg CONTAINS \"Yes\"",
                "Pay details",
                LOCALHOST + "/et1Repped/sectionTwo/validateClaimantPay"),
        readOnly(
                PROD,
                ET1_SECTION_TWO,
                "claimantPayPreamble",
                9,
                1,
                null,
                "didClaimantWorkForOrg CONTAINS \"Yes\"",
                "Pay details",
                PRODUCTION + "/et1Repped/sectionTwo/validateClaimantPay"),
        optional(ALL, ET1_SECTION_TWO, "claimantPayBeforeTax", 9, 2, null, null, null, null),
        optional(ALL, ET1_SECTION_TWO, "claimantPayAfterTax", 9, 3, null, null, null, null),
        optional(ALL, ET1_SECTION_TWO, "claimantPayType", 9, 4, null, null, null, null),
        optional(
                CFTLIB,
                ET1_SECTION_TWO,
                "claimantPensionContribution",
                10,
                1,
                null,
                "didClaimantWorkForOrg CONTAINS \"Yes\"",
                "Pensions and benefits",
                LOCALHOST + "/et1Repped/sectionTwo/validateClaimantPensionBenefits"),
        optional(
                PROD,
                ET1_SECTION_TWO,
                "claimantPensionContribution",
                10,
                1,
                null,
                "didClaimantWorkForOrg CONTAINS \"Yes\"",
                "Pensions and benefits",
                PRODUCTION + "/et1Repped/sectionTwo/validateClaimantPensionBenefits"),
        optional(
                ALL,
                ET1_SECTION_TWO,
                "claimantWeeklyPension",
                10,
                2,
                "claimantPensionContribution CONTAINS \"Yes\"",
                null,
                null,
                null),
        optional(ALL, ET1_SECTION_TWO, "claimantEmployeeBenefits", 10, 3, null, null, null, null),
        optional(
                ALL,
                ET1_SECTION_TWO,
                "claimantBenefits",
                10,
                4,
                "claimantEmployeeBenefits CONTAINS \"Yes\"",
                null,
                null,
                null),
        optional(
                CFTLIB,
                ET1_SECTION_TWO,
                "claimantNewJob",
                11,
                1,
                null,
                "didClaimantWorkForOrg CONTAINS \"Yes\" AND claimantStillWorking CONTAINS \"No"
                    + " longer working\"",
                "Claimant new job (Optional)",
                LOCALHOST + "/et1Repped/sectionTwo/validateClaimantNewJob"),
        optional(
                PROD,
                ET1_SECTION_TWO,
                "claimantNewJob",
                11,
                1,
                null,
                "didClaimantWorkForOrg CONTAINS \"Yes\" AND claimantStillWorking CONTAINS \"No"
                    + " longer working\"",
                "Claimant new job (Optional)",
                PRODUCTION + "/et1Repped/sectionTwo/validateClaimantNewJob"),
        optional(
                ALL,
                ET1_SECTION_TWO,
                "claimantNewJobStartDate",
                11,
                2,
                "claimantNewJob CONTAINS \"Yes\"",
                null,
                null,
                null),
        readOnly(
                CFTLIB,
                ET1_SECTION_TWO,
                "claimantNewJobPayPreamble",
                12,
                1,
                null,
                "didClaimantWorkForOrg CONTAINS \"Yes\" AND claimantStillWorking CONTAINS \"No"
                    + " longer working\" AND claimantNewJob CONTAINS \"Yes\"",
                "New job pay details",
                LOCALHOST + "/et1Repped/sectionTwo/validateClaimantNewJobPay"),
        readOnly(
                PROD,
                ET1_SECTION_TWO,
                "claimantNewJobPayPreamble",
                12,
                1,
                null,
                "didClaimantWorkForOrg CONTAINS \"Yes\" AND claimantStillWorking CONTAINS \"No"
                    + " longer working\" AND claimantNewJob CONTAINS \"Yes\"",
                "New job pay details",
                PRODUCTION + "/et1Repped/sectionTwo/validateClaimantNewJobPay"),
        optional(ALL, ET1_SECTION_TWO, "claimantNewJobPayBeforeTax", 12, 2, null, null, null, null),
        optional(ALL, ET1_SECTION_TWO, "claimantNewJobPayPeriod", 12, 3, null, null, null, null),
        readOnly(
                CFTLIB,
                ET1_SECTION_TWO,
                "respondentNamePreamble",
                13,
                1,
                null,
                null,
                "Respondent Name",
                LOCALHOST + "/et1Repped/sectionTwo/generateRespondentPreamble"),
        readOnly(
                PROD,
                ET1_SECTION_TWO,
                "respondentNamePreamble",
                13,
                1,
                null,
                null,
                "Respondent Name",
                PRODUCTION + "/et1Repped/sectionTwo/generateRespondentPreamble"),
        mandatory(ALL, ET1_SECTION_TWO, "respondentType", 13, 2, null, null, null, null),
        mandatory(
                ALL,
                ET1_SECTION_TWO,
                "respondentOrganisationName",
                13,
                3,
                "respondentType = \"Organisation\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_SECTION_TWO,
                "respondentFirstName",
                13,
                4,
                "respondentType = \"Individual\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_SECTION_TWO,
                "respondentLastName",
                13,
                5,
                "respondentType = \"Individual\"",
                null,
                null,
                null),
        readOnly(ALL, ET1_SECTION_TWO, "respondentEndLabel", 13, 6, null, null, null, null),
        mandatory(
                CFTLIB,
                ET1_SECTION_TWO,
                "respondentAddress",
                14,
                1,
                null,
                null,
                "Respondent address",
                LOCALHOST + "/et1Repped/sectionTwo/generateWorkAddressLabel"),
        mandatory(
                PROD,
                ET1_SECTION_TWO,
                "respondentAddress",
                14,
                1,
                null,
                null,
                "Respondent address",
                PRODUCTION + "/et1Repped/sectionTwo/generateWorkAddressLabel"),
        field(
                ALL,
                ET1_SECTION_TWO,
                "didClaimantWorkAtSameAddressPreamble",
                "OPTIONAL",
                15,
                1,
                false,
                null,
                "didClaimantWorkAtSameAddress = \"dummy\"",
                "didClaimantWorkForOrg CONTAINS \"Yes\"",
                "Claimant work address",
                null),
        readOnly(
                ALL,
                ET1_SECTION_TWO,
                "didClaimantWorkAtSameAddressPreambleLabel",
                15,
                2,
                null,
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_SECTION_TWO,
                "didClaimantWorkAtSameAddress",
                15,
                3,
                null,
                null,
                null,
                null),
        field(
                ALL,
                ET1_SECTION_TWO,
                "claimantWorkAddress",
                "COMPLEX",
                16,
                1,
                false,
                "Y",
                null,
                "didClaimantWorkAtSameAddress = \"No\"",
                "What address did the claimant work at? ",
                null),
        mandatory(
                ALL,
                ET1_SECTION_TWO,
                "respondentAcasYesNo",
                17,
                1,
                null,
                null,
                "Acas certificate for the respondent",
                null),
        mandatory(
                ALL,
                ET1_SECTION_TWO,
                "respondentAcasNumber",
                17,
                2,
                "respondentAcasYesNo = \"Yes\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_SECTION_TWO,
                "respondentNoAcasCertificateReason",
                17,
                4,
                "respondentAcasYesNo = \"No\"",
                null,
                null,
                null),
        field(
                ALL,
                ET1_SECTION_TWO,
                "addAdditionalRespondentPreamble",
                "OPTIONAL",
                19,
                1,
                false,
                null,
                "addAdditionalRespondent = \"dummy\"",
                null,
                "Do you want to add another respondent?",
                null),
        readOnly(
                ALL,
                ET1_SECTION_TWO,
                "addAdditionalRespondentPreambleLabel",
                19,
                2,
                null,
                null,
                null,
                null),
        mandatory(ALL, ET1_SECTION_TWO, "addAdditionalRespondent", 19, 3, null, null, null, null),
        mandatory(
                ALL,
                ET1_SECTION_TWO,
                "et1ReppedRespondentCollection",
                19,
                4,
                "addAdditionalRespondent=\"Yes\"",
                null,
                null,
                null),
        field(
                ALL,
                ET1_SECTION_THREE,
                "et1SectionThreePreamble",
                "READONLY",
                1,
                1,
                true,
                null,
                null,
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_SECTION_THREE,
                "et1SectionThreeDetailsPreamble",
                2,
                1,
                null,
                null,
                "Details of the claim",
                null),
        optional(
                ALL,
                ET1_SECTION_THREE,
                "et1SectionThreeDocumentUpload",
                2,
                2,
                null,
                null,
                null,
                null),
        optional(
                CFTLIB,
                ET1_SECTION_THREE,
                "et1SectionThreeClaimDetails",
                2,
                3,
                null,
                null,
                null,
                LOCALHOST + "/et1Repped/validateGrounds"),
        optional(
                PROD,
                ET1_SECTION_THREE,
                "et1SectionThreeClaimDetails",
                2,
                3,
                null,
                null,
                null,
                PRODUCTION + "/et1Repped/validateGrounds"),
        mandatory(
                ALL,
                ET1_SECTION_THREE,
                "et1SectionThreeTypeOfClaim",
                3,
                1,
                null,
                null,
                "What type of claim is this?",
                null),
        mandatory(
                ALL,
                ET1_SECTION_THREE,
                "discriminationTypesOfClaim",
                3,
                2,
                "et1SectionThreeTypeOfClaim CONTAINS \"discrimination\"",
                null,
                "What type of claim is this?",
                null),
        mandatory(
                ALL,
                ET1_SECTION_THREE,
                "payTypesOfClaim",
                3,
                3,
                "et1SectionThreeTypeOfClaim CONTAINS \"payRelated\"",
                null,
                null,
                null),
        optional(
                CFTLIB,
                ET1_SECTION_THREE,
                "whistleblowingYesNo",
                3,
                4,
                "et1SectionThreeTypeOfClaim CONTAINS \"whistleBlowing\"",
                null,
                null,
                LOCALHOST + "/et1Repped/sectionThree/validateWhistleblowing"),
        optional(
                PROD,
                ET1_SECTION_THREE,
                "whistleblowingYesNo",
                3,
                4,
                "et1SectionThreeTypeOfClaim CONTAINS \"whistleBlowing\"",
                null,
                null,
                PRODUCTION + "/et1Repped/sectionThree/validateWhistleblowing"),
        mandatory(
                ALL,
                ET1_SECTION_THREE,
                "whistleblowingRegulator",
                3,
                5,
                "et1SectionThreeTypeOfClaim CONTAINS \"whistleBlowing\" AND whistleblowingYesNo ="
                    + " \"Yes\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_SECTION_THREE,
                "otherTypeOfClaimDetails",
                3,
                6,
                "et1SectionThreeTypeOfClaim CONTAINS \"otherTypesOfClaims\"",
                null,
                null,
                null),
        optional(
                ALL,
                ET1_SECTION_THREE,
                "claimSuccessful",
                4,
                1,
                null,
                null,
                "What does the claimant want if their claim is successful? (Optional)",
                null),
        optional(
                ALL,
                ET1_SECTION_THREE,
                "compensationDetails",
                4,
                2,
                "claimSuccessful CONTAINS \"compensation\"",
                null,
                null,
                null),
        optional(
                ALL,
                ET1_SECTION_THREE,
                "tribunalRecommendationDetails",
                4,
                4,
                "claimSuccessful CONTAINS \"tribunal\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_SECTION_THREE,
                "linkedCasesPreamble",
                5,
                1,
                null,
                null,
                "Linked cases",
                null),
        optional(
                CFTLIB,
                ET1_SECTION_THREE,
                "linkedCasesYesNo",
                5,
                2,
                null,
                null,
                null,
                LOCALHOST + "/et1Repped/sectionThree/validateLinkedCases"),
        optional(
                PROD,
                ET1_SECTION_THREE,
                "linkedCasesYesNo",
                5,
                2,
                null,
                null,
                null,
                PRODUCTION + "/et1Repped/sectionThree/validateLinkedCases"),
        optional(
                ALL,
                ET1_SECTION_THREE,
                "linkedCasesDetails",
                5,
                3,
                "linkedCasesYesNo CONTAINS \"Yes\"",
                null,
                null,
                null),
        readOnly(ALL, CREATE_DRAFT_ET1, "et1DoNotSubmitDraftMessage", 1, 2, null, null, null, null),
        readOnly(ALL, SUBMIT_ET1_DRAFT, "submitEt1Preamble", 1, 1, null, null, null, null),
        field(
                ALL,
                SUBMIT_ET1_DRAFT,
                "submitEt1Confirmation",
                "MANDATORY",
                1,
                2,
                false,
                null,
                null,
                null,
                null,
                null),
        readOnly(ALL, ET1_VETTING, "horizontalLine", 1, 1, null, null, "Before you start", null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingBeforeYouStart",
                1,
                2,
                "et1VettingBeforeYouStartLabel=\"dummy\"",
                null,
                null,
                null),
        readOnly(ALL, ET1_VETTING, "et1VettingBeforeYouStartLabel", 1, 3, null, null, null, null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingContactDetailsLabel",
                2,
                1,
                null,
                null,
                "Minimum required information",
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingClaimantDetailsMarkUp",
                2,
                2,
                "et1VettingContactDetailsLabel=\"dummy\"",
                null,
                null,
                null),
        readOnly(ALL, ET1_VETTING, "et1VettingClaimantDetailsLabel", 2, 3, null, null, null, null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingRespondentDetailsMarkUp",
                2,
                4,
                "et1VettingContactDetailsLabel=\"dummy\"",
                null,
                null,
                null),
        readOnly(
                ALL, ET1_VETTING, "et1VettingRespondentDetailsLabel", 2, 5, null, null, null, null),
        mandatory(ALL, ET1_VETTING, "et1VettingCanServeClaimYesOrNo", 2, 6, null, null, null, null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1VettingCanServeClaimNoReason",
                2,
                7,
                "et1VettingCanServeClaimYesOrNo=\"No\"",
                null,
                null,
                null),
        optional(
                ALL,
                ET1_VETTING,
                "et1VettingCanServeClaimGeneralNote",
                2,
                8,
                null,
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingClaimantDetailsLabel2",
                3,
                1,
                null,
                null,
                "Minimum required information",
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingRespondentAcasDetails1",
                3,
                2,
                "et1VettingContactDetailsLabel=\"dummy\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingRespondentAcasDetailsLabel1",
                3,
                3,
                null,
                null,
                null,
                null),
        mandatory(ALL, ET1_VETTING, "et1VettingAcasCertIsYesOrNo1", 3, 4, null, null, null, null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1VettingAcasCertExemptYesOrNo1",
                3,
                5,
                "et1VettingAcasCertIsYesOrNo1=\"No\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingRespondentAcasDetails2",
                3,
                6,
                "et1VettingContactDetailsLabel=\"dummy\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingRespondentAcasDetailsLabel2",
                3,
                7,
                "et1VettingRespondentAcasDetails2!=\"\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1VettingAcasCertIsYesOrNo2",
                3,
                8,
                "et1VettingRespondentAcasDetails2!=\"\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1VettingAcasCertExemptYesOrNo2",
                3,
                9,
                "et1VettingRespondentAcasDetails2!=\"\" AND et1VettingAcasCertIsYesOrNo2=\"No\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingRespondentAcasDetails3",
                3,
                10,
                "et1VettingContactDetailsLabel=\"dummy\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingRespondentAcasDetailsLabel3",
                3,
                11,
                "et1VettingRespondentAcasDetails3!=\"\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1VettingAcasCertIsYesOrNo3",
                3,
                12,
                "et1VettingRespondentAcasDetails3!=\"\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1VettingAcasCertExemptYesOrNo3",
                3,
                13,
                "et1VettingRespondentAcasDetails3!=\"\" AND et1VettingAcasCertIsYesOrNo3=\"No\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingRespondentAcasDetails4",
                3,
                14,
                "et1VettingContactDetailsLabel=\"dummy\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingRespondentAcasDetailsLabel4",
                3,
                15,
                "et1VettingRespondentAcasDetails4!=\"\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1VettingAcasCertIsYesOrNo4",
                3,
                16,
                "et1VettingRespondentAcasDetails4!=\"\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1VettingAcasCertExemptYesOrNo4",
                3,
                17,
                "et1VettingRespondentAcasDetails4!=\"\" AND et1VettingAcasCertIsYesOrNo4=\"No\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingRespondentAcasDetails5",
                3,
                18,
                "et1VettingContactDetailsLabel=\"dummy\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingRespondentAcasDetailsLabel5",
                3,
                19,
                "et1VettingRespondentAcasDetails5!=\"\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1VettingAcasCertIsYesOrNo5",
                3,
                20,
                "et1VettingRespondentAcasDetails5!=\"\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1VettingAcasCertExemptYesOrNo5",
                3,
                21,
                "et1VettingRespondentAcasDetails5!=\"\" AND et1VettingAcasCertIsYesOrNo5=\"No\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingRespondentAcasDetails6",
                3,
                22,
                "et1VettingContactDetailsLabel=\"dummy\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1VettingRespondentAcasDetailsLabel6",
                3,
                23,
                "et1VettingRespondentAcasDetails6!=\"\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1VettingAcasCertIsYesOrNo6",
                3,
                24,
                "et1VettingRespondentAcasDetails6!=\"\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1VettingAcasCertExemptYesOrNo6",
                3,
                25,
                "et1VettingRespondentAcasDetails6!=\"\" AND et1VettingAcasCertIsYesOrNo6=\"No\"",
                null,
                null,
                null),
        readOnly(ALL, ET1_VETTING, "horizontalLine4", 3, 26, null, null, null, null),
        optional(ALL, ET1_VETTING, "et1VettingAcasCertGeneralNote", 3, 27, null, null, null, null),
        readOnly(ENGLAND_WALES, ET1_VETTING, "horizontalLine2", 4, 1, null, null, null, null),
        readOnly(SCOTLAND, ET1_VETTING, "horizontalLine2", 4, 1, null, null, "Case details", null),
        optional(ALL, ET1_VETTING, "substantiveDefectsList", 4, 2, null, null, null, null),
        mandatory(
                ALL,
                ET1_VETTING,
                "rule121aTextArea",
                4,
                3,
                "substantiveDefectsList CONTAINS \"rule121a\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "rule121bTextArea",
                4,
                4,
                "substantiveDefectsList CONTAINS \"rule121b\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "rule121cTextArea",
                4,
                5,
                "substantiveDefectsList CONTAINS \"rule121c\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "rule121dTextArea",
                4,
                6,
                "substantiveDefectsList CONTAINS \"rule121d\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "rule121daTextArea",
                4,
                7,
                "substantiveDefectsList CONTAINS \"rule121 da\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "rule121eTextArea",
                4,
                8,
                "substantiveDefectsList CONTAINS \"rule121e\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "rule121fTextArea",
                4,
                9,
                "substantiveDefectsList CONTAINS \"rule121f\"",
                null,
                null,
                null),
        readOnly(ALL, ET1_VETTING, "horizontalLine3", 4, 10, null, null, null, null),
        optional(
                ALL,
                ET1_VETTING,
                "et1SubstantiveDefectsGeneralNotes",
                4,
                11,
                null,
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "existingJurisdictionCodes",
                5,
                1,
                "et1SubstantiveDefectsGeneralNotes=\"dummy\"",
                null,
                "Case details",
                null),
        readOnly(ALL, ET1_VETTING, "existingJurisdictionCodesLabel", 5, 2, null, null, null, null),
        mandatory(ALL, ET1_VETTING, "areTheseCodesCorrect", 5, 3, null, null, null, null),
        mandatory(
                ALL,
                ET1_VETTING,
                "codesCorrectGiveDetails",
                5,
                4,
                "areTheseCodesCorrect=\"No\"",
                null,
                null,
                null),
        optional(
                ALL,
                ET1_VETTING,
                "vettingJurisdictionCodeCollection",
                5,
                5,
                null,
                null,
                null,
                null),
        optional(
                CFTLIB,
                ET1_VETTING,
                "et1JurisdictionCodeGeneralNotes",
                5,
                6,
                null,
                null,
                null,
                LOCALHOST + "/jurisdictionCodes"),
        optional(
                PROD,
                ET1_VETTING,
                "et1JurisdictionCodeGeneralNotes",
                5,
                6,
                null,
                null,
                null,
                PRODUCTION + "/jurisdictionCodes"),
        readOnly(
                ALL,
                ET1_VETTING,
                "trackType",
                5,
                7,
                "areTheseCodesCorrect=\"dummy\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "trackAllocation",
                6,
                1,
                "isTrackAllocationCorrect=\"dummy\"",
                null,
                "Case details",
                null),
        readOnly(ALL, ET1_VETTING, "trackAllocationLabel", 6, 2, null, null, null, null),
        mandatory(ALL, ET1_VETTING, "isTrackAllocationCorrect", 6, 3, null, null, null, null),
        mandatory(
                ALL,
                ET1_VETTING,
                "suggestAnotherTrack",
                6,
                4,
                "isTrackAllocationCorrect=\"No\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "whyChangeTrackAllocation",
                6,
                5,
                "suggestAnotherTrack !=\"\" AND isTrackAllocationCorrect=\"No\"",
                null,
                null,
                null),
        optional(ALL, ET1_VETTING, "trackAllocationGeneralNotes", 6, 6, null, null, null, null),
        mandatory(
                ALL,
                ET1_VETTING,
                "tribunalAndOfficeLocation",
                7,
                1,
                "horizontalLine=\"dummy\"",
                null,
                "Case details",
                null),
        readOnly(ALL, ET1_VETTING, "tribunalAndOfficeLocationLabel", 7, 2, null, null, null, null),
        mandatory(ALL, ET1_VETTING, "isLocationCorrect", 7, 3, null, null, null, null),
        mandatory(
                ALL,
                ET1_VETTING,
                "regionalOffice",
                7,
                4,
                "horizontalLine=\"dummy\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "regionalOfficeLabel",
                7,
                5,
                "isLocationCorrect=\"No\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "regionalOfficeList",
                7,
                6,
                "isLocationCorrect=\"No\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "whyChangeOffice",
                7,
                7,
                "isLocationCorrect=\"No\"",
                null,
                null,
                null),
        optional(
                CFTLIB,
                ET1_VETTING,
                "et1LocationGeneralNotes",
                7,
                8,
                null,
                null,
                null,
                LOCALHOST + "/et1HearingVenue"),
        optional(
                PROD,
                ET1_VETTING,
                "et1LocationGeneralNotes",
                7,
                8,
                null,
                null,
                null,
                PRODUCTION + "/et1HearingVenue"),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1AddressDetails",
                8,
                1,
                "horizontalLine=\"dummy\"",
                null,
                "Case details",
                null),
        readOnly(ALL, ET1_VETTING, "et1AddressDetailsLabel", 8, 2, null, null, null, null),
        mandatory(ALL, ET1_VETTING, "et1SuggestHearingVenue", 8, 3, null, null, null, null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1TribunalRegion",
                8,
                4,
                "horizontalLine=\"dummy\"",
                null,
                null,
                null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1TribunalRegionLabel",
                8,
                5,
                "et1SuggestHearingVenue=\"Yes\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1HearingVenues",
                8,
                6,
                "et1SuggestHearingVenue=\"Yes\"",
                null,
                null,
                null),
        optional(ALL, ET1_VETTING, "et1HearingVenueGeneralNotes", 8, 7, null, null, null, null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1GovOrMajorQuestion",
                9,
                1,
                null,
                null,
                "Further questions",
                null),
        mandatory(
                ALL, ET1_VETTING, "et1ReasonableAdjustmentsQuestion", 9, 2, null, null, null, null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1ReasonableAdjustmentsTextArea",
                9,
                3,
                "et1ReasonableAdjustmentsQuestion=\"Yes\"",
                null,
                null,
                null),
        mandatory(ALL, ET1_VETTING, "et1VideoHearingQuestion", 9, 4, null, null, null, null),
        mandatory(
                ALL,
                ET1_VETTING,
                "et1VideoHearingTextArea",
                9,
                5,
                "et1VideoHearingQuestion=\"No\"",
                null,
                null,
                null),
        optional(ALL, ET1_VETTING, "et1FurtherQuestionsGeneralNotes", 9, 6, null, null, null, null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1JudgeReferralLine1",
                10,
                1,
                null,
                null,
                "Possible referral to a judge or legal officer",
                null),
        optional(ALL, ET1_VETTING, "referralToJudgeOrLOList", 10, 2, null, null, null, null),
        mandatory(
                ALL,
                ET1_VETTING,
                "aClaimOfInterimReliefTextArea",
                10,
                3,
                "referralToJudgeOrLOList CONTAINS \"aClaimOfInterimRelief\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "aStatutoryAppealTextArea",
                10,
                4,
                "referralToJudgeOrLOList CONTAINS \"aStatutoryAppeal\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "anAllegationOfCommissionOfSexualOffenceTextArea",
                10,
                5,
                "referralToJudgeOrLOList CONTAINS \"anAllegationOfCommissionOfSexualOffence\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "insolvencyTextArea",
                10,
                6,
                "referralToJudgeOrLOList CONTAINS \"insolvency\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "jurisdictionsUnclearTextArea",
                10,
                7,
                "referralToJudgeOrLOList CONTAINS \"jurisdictionsUnclear\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "lengthOfServiceTextArea",
                10,
                8,
                "referralToJudgeOrLOList CONTAINS \"lengthOfService\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "potentiallyLinkedCasesInTheEcmTextArea",
                10,
                9,
                "referralToJudgeOrLOList CONTAINS \"potentiallyLinkedCasesInTheEcm\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "rule50IssuesTextArea",
                10,
                10,
                "referralToJudgeOrLOList CONTAINS \"rule50Issues\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "anotherReasonForJudicialReferralTextArea",
                10,
                11,
                "referralToJudgeOrLOList CONTAINS \"anotherReasonForJudicialReferral\"",
                null,
                null,
                null),
        readOnly(ALL, ET1_VETTING, "et1JudgeReferralLine2", 10, 12, null, null, null, null),
        optional(ALL, ET1_VETTING, "et1JudgeReferralGeneralNotes", 10, 13, null, null, null, null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1REJOrVPReferralLine1",
                11,
                1,
                null,
                null,
                "Possible referral to Regional Employment Judge or Vice-President",
                null),
        optional(ALL, ET1_VETTING, "referralToREJOrVPList", 11, 2, null, null, null, null),
        mandatory(
                ALL,
                ET1_VETTING,
                "vexatiousLitigantOrderTextArea",
                11,
                3,
                "referralToREJOrVPList CONTAINS \"vexatiousLitigantOrder\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "aNationalSecurityIssueTextArea",
                11,
                4,
                "referralToREJOrVPList CONTAINS \"aNationalSecurityIssue\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "nationalMultipleOrPresidentialOrderTextArea",
                11,
                5,
                "referralToREJOrVPList CONTAINS \"nationalMultipleOrPresidentialOrder\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "transferToOtherRegionTextArea",
                11,
                6,
                "referralToREJOrVPList CONTAINS \"transferToOtherRegion\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "serviceAbroadTextArea",
                11,
                7,
                "referralToREJOrVPList CONTAINS \"serviceAbroad\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "aSensitiveIssueTextArea",
                11,
                8,
                "referralToREJOrVPList CONTAINS \"aSensitiveIssue\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "anyPotentialConflictTextArea",
                11,
                9,
                "referralToREJOrVPList CONTAINS \"anyPotentialConflict\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "anotherReasonREJOrVPTextArea",
                11,
                10,
                "referralToREJOrVPList CONTAINS \"anotherReasonREJOrVP\"",
                null,
                null,
                null),
        readOnly(ALL, ET1_VETTING, "et1REJOrVPReferralLine2", 11, 11, null, null, null, null),
        optional(
                ALL, ET1_VETTING, "et1REJOrVPReferralGeneralNotes", 11, 12, null, null, null, null),
        readOnly(
                ALL,
                ET1_VETTING,
                "et1OtherReferralLine1",
                12,
                1,
                null,
                null,
                "Other factors",
                null),
        optional(ALL, ET1_VETTING, "otherReferralList", 12, 2, null, null, null, null),
        mandatory(
                ALL,
                ET1_VETTING,
                "claimOutOfTimeTextArea",
                12,
                3,
                "otherReferralList CONTAINS \"claimOutOfTime\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "multipleClaimTextArea",
                12,
                4,
                "otherReferralList CONTAINS \"multipleClaim\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "employmentStatusIssuesTextArea",
                12,
                5,
                "otherReferralList CONTAINS \"employmentStatusIssues\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "pidJurisdictionRegulatorTextArea",
                12,
                6,
                "otherReferralList CONTAINS \"pidJurisdictionRegulator\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "videoHearingPreferenceTextArea",
                12,
                7,
                "otherReferralList CONTAINS \"videoHearingPreference\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "rule50IssuesForOtherReferralTextArea",
                12,
                8,
                "otherReferralList CONTAINS \"rule50IssuesOtherFactors\"",
                null,
                null,
                null),
        mandatory(
                ALL,
                ET1_VETTING,
                "anotherReasonForOtherReferralTextArea",
                12,
                9,
                "otherReferralList CONTAINS \"otherRelevantFactors\"",
                null,
                null,
                null),
        readOnly(ALL, ET1_VETTING, "et1OtherReferralLine2", 12, 10, null, null, null, null),
        optional(ALL, ET1_VETTING, "et1OtherReferralGeneralNotes", 12, 11, null, null, null, null),
        optional(
                ALL,
                ET1_VETTING,
                "et1VettingAdditionalInformationTextArea",
                13,
                1,
                null,
                null,
                "Final notes",
                null)
    };

    static final ComplexFieldSpec[] COMPLEX_FIELDS = {
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_ONE,
                "claimantContactAddress",
                "AddressLine1",
                "OPTIONAL",
                2,
                "Building and Street"),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_ONE,
                "claimantContactAddress",
                "AddressLine2",
                "OPTIONAL",
                3,
                null),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_ONE,
                "claimantContactAddress",
                "AddressLine3",
                "OPTIONAL",
                4,
                null),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_ONE,
                "claimantContactAddress",
                "PostTown",
                "OPTIONAL",
                5,
                "Town or City"),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_ONE,
                "claimantContactAddress",
                "County",
                "OPTIONAL",
                6,
                "County"),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_ONE,
                "claimantContactAddress",
                "Country",
                "OPTIONAL",
                7,
                "Country"),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_ONE,
                "claimantContactAddress",
                "PostCode",
                "OPTIONAL",
                8,
                "Postcode"),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_TWO,
                "claimantWorkAddress",
                "claimant_work_address",
                "MANDATORY",
                1,
                null),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_TWO,
                "claimantWorkAddress",
                "claimant_work_address.AddressLine1",
                "MANDATORY",
                2,
                "Building and Street"),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_TWO,
                "claimantWorkAddress",
                "claimant_work_address.AddressLine2",
                "OPTIONAL",
                3,
                null),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_TWO,
                "claimantWorkAddress",
                "claimant_work_address.AddressLine3",
                "OPTIONAL",
                4,
                null),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_TWO,
                "claimantWorkAddress",
                "claimant_work_address.PostTown",
                "OPTIONAL",
                5,
                "Town or City"),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_TWO,
                "claimantWorkAddress",
                "claimant_work_address.County",
                "OPTIONAL",
                6,
                "County"),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_TWO,
                "claimantWorkAddress",
                "claimant_work_address.Country",
                "OPTIONAL",
                7,
                "Country"),
        complexField(
                ALL,
                "Et1ReppedSectionTwo",
                ET1_SECTION_TWO,
                "claimantWorkAddress",
                "claimant_work_address.PostCode",
                "OPTIONAL",
                8,
                "Postcode"),
        complexField(
                ALL,
                "Et1ReppedCreateDraft",
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageAddress",
                "et1ReppedTriageAddress",
                "MANDATORY",
                1,
                null),
        complexField(
                ALL,
                "Et1ReppedCreateDraft",
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageAddress",
                "AddressLine1",
                "OPTIONAL",
                2,
                null),
        complexField(
                ALL,
                "Et1ReppedCreateDraft",
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageAddress",
                "AddressLine2",
                "OPTIONAL",
                3,
                null),
        complexField(
                ALL,
                "Et1ReppedCreateDraft",
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageAddress",
                "AddressLine3",
                "OPTIONAL",
                4,
                null),
        complexField(
                ALL,
                "Et1ReppedCreateDraft",
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageAddress",
                "PostTown",
                "OPTIONAL",
                5,
                null),
        complexField(
                ALL,
                "Et1ReppedCreateDraft",
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageAddress",
                "County",
                "OPTIONAL",
                6,
                null),
        complexField(
                ALL,
                "Et1ReppedCreateDraft",
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageAddress",
                "Country",
                "OPTIONAL",
                7,
                null),
        complexField(
                ALL,
                "Et1ReppedCreateDraft",
                ET1_REPPED_CREATE_CASE,
                "et1ReppedTriageAddress",
                "PostCode",
                "OPTIONAL",
                8,
                null),
        complexField(
                ALL,
                "JurisdictionCode",
                ET1_VETTING,
                "vettingJurisdictionCodeCollection",
                "et1VettingJurCodeList",
                "OPTIONAL",
                1,
                "Jurisdiction code")
    };

    private SingleEt1ClaimIntakeRows() {}

    private static EventFieldSpec readOnly(
            int mask,
            String eventId,
            String fieldId,
            int page,
            int order,
            String condition,
            String pageCondition,
            String pageLabel,
            String midEvent) {
        return field(
                mask,
                eventId,
                fieldId,
                "READONLY",
                page,
                order,
                false,
                null,
                condition,
                pageCondition,
                pageLabel,
                midEvent);
    }

    private static EventFieldSpec mandatory(
            int mask,
            String eventId,
            String fieldId,
            int page,
            int order,
            String condition,
            String pageCondition,
            String pageLabel,
            String midEvent) {
        return field(
                mask,
                eventId,
                fieldId,
                "MANDATORY",
                page,
                order,
                false,
                "Y",
                condition,
                pageCondition,
                pageLabel,
                midEvent);
    }

    private static EventFieldSpec optional(
            int mask,
            String eventId,
            String fieldId,
            int page,
            int order,
            String condition,
            String pageCondition,
            String pageLabel,
            String midEvent) {
        return field(
                mask,
                eventId,
                fieldId,
                "OPTIONAL",
                page,
                order,
                false,
                "Y",
                condition,
                pageCondition,
                pageLabel,
                midEvent);
    }

    private static EventFieldSpec complex(
            int mask,
            String eventId,
            String fieldId,
            int page,
            int order,
            String condition,
            String pageCondition,
            String pageLabel,
            String midEvent) {
        return field(
                mask,
                eventId,
                fieldId,
                "COMPLEX",
                page,
                order,
                false,
                null,
                condition,
                pageCondition,
                pageLabel,
                midEvent);
    }

    private static EventFieldSpec field(
            int mask,
            String eventId,
            String fieldId,
            String context,
            int page,
            int order,
            boolean pageColumn,
            String showSummary,
            String condition,
            String pageCondition,
            String pageLabel,
            String midEvent) {
        return new EventFieldSpec(
                mask,
                eventId,
                fieldId,
                context,
                Integer.toString(page),
                page,
                order,
                pageColumn,
                showSummary,
                condition,
                null,
                pageCondition,
                pageLabel,
                midEvent,
                null);
    }

    private static ComplexFieldSpec complexField(
            int mask,
            String rowId,
            String eventId,
            String caseFieldId,
            String elementCode,
            String context,
            int order,
            String label) {
        return new ComplexFieldSpec(
                mask,
                rowId,
                eventId,
                caseFieldId,
                elementCode,
                context,
                order,
                label,
                null,
                null,
                null,
                null,
                null);
    }
}
