package uk.gov.hmcts.et.common.model.ccd;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "acceptOrRejectCase",
        generate = true
)
public class AcceptOrRejectCase {
    @CCD(
            label = "Case Accepted?"
    )
    private YesOrNo caseAccepted;

    @CCD(
            label = "Date Accepted",
            showCondition = "caseAccepted=\"Yes\"",
            retainHiddenValue = true
    )
    private LocalDate dateAccepted;

    @CCD(
            label = "Date Rejected",
            showCondition = "caseAccepted=\"No\"",
            retainHiddenValue = true
    )
    private LocalDate dateRejected;

    @CCD(
            label = "Reason for the rejection",
            showCondition = "caseAccepted=\"No\"",
            retainHiddenValue = true,
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "msl_PreAcceptanceResponse"
    )
    private String rejectReason;
}
