package uk.gov.hmcts.et.common.model.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class AdditionalCaseDetails {
    @CCD(
            label = "Live appeal?"
    )
    private YesOrNo additional_live_appeal;

    @CCD(
            label = "Sensitive case?"
    )
    private YesOrNo additional_sensitive;

    @CCD(
            label = "Do not postpone"
    )
    private YesOrNo doNotPostpone;

    @CCD(
            label = "Digital File?"
    )
    private YesOrNo digitalFile;

    @CCD(
            label = "Reasonable Adjustment"
    )
    private YesOrNo reasonableAdjustment;

    @CCD(
            label = "Speak to REJ"
    )
    private YesOrNo interventionRequired;

    @CCD(
            label = "Reserved to Judge"
    )
    private YesOrNo reservedToJudge;
}
