package uk.gov.hmcts.et.common.model.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.AddressUK;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "addressLabel",
        generate = true
)
public class AddressLabel {
    @CCD(
            label = "Print label?",
            searchable = false
    )
    private YesOrNo printLabel;

    @CCD(
            label = "Full name",
            searchable = false
    )
    private String fullName;

    @CCD(
            label = "Full address",
            searchable = false
    )
    private String fullAddress;

    @CCD(
            label = "Entity name 1",
            searchable = false
    )
    private String labelEntityName01;

    @CCD(
            label = "Entity name 2",
            searchable = false
    )
    private String labelEntityName02;

    @CCD(
            label = "Address",
            searchable = false
    )
    private AddressUK labelEntityAddress;

    @CCD(
            label = "Telephone",
            searchable = false
    )
    private String labelEntityTelephone;

    @CCD(
            label = "Fax",
            searchable = false
    )
    private String labelEntityFax;

    @CCD(
            label = "Entity Reference",
            searchable = false
    )
    private String labelEntityReference;

    @CCD(
            label = "Case Reference",
            searchable = false
    )
    private String labelCaseReference;
}
