package uk.gov.hmcts.et.common.model.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "addressLabelsAttributes",
        generate = true
)
public class AddressLabelsAttributes {
    @CCD(
            label = "Number of selected labels to print in this run"
    )
    private String numberOfSelectedLabels;

    @CCD(
            label = "Number of copies of each label"
    )
    private Integer numberOfCopies;

    @CCD(
            label = "Select the label to start printing from",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_AddressLabelNumber"
    )
    private String startingLabel;

    @CCD(
            label = "Show Tel / Fax Numbers?"
    )
    private YesOrNo showTelFax;
}
