package uk.gov.hmcts.et.common.model.ccd;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class Bundle {
    @CCD(
            label = "Bundle ID"
    )
    private String id;

    @CCD(
            label = "Name of bundle"
    )
    private String title;

    @CCD(
            label = "Description",
            typeOverride = FieldType.TextArea
    )
    private String description;

    @CCD(
            label = "Is this the bundle you want to stitch?"
    )
    private YesOrNo eligibleForStitching;

    @CCD(
            label = "Is this the bundle you want to clone?"
    )
    private YesOrNo eligibleForCloning;

    @CCD(
            label = "Bundle document"
    )
    private List<ListValue<BundleDocument>> documents;

    @CCD(
            label = "Bundle folder"
    )
    private List<ListValue<BundleFolder>> folders;

    @CCD(
            label = "Stitch Status"
    )
    private String stitchStatus;

    @CCD(
            label = "Stitched Document"
    )
    private Document stitchedDocument;

    @CCD(
            label = "Should this bundle have coversheets separating each document?"
    )
    private YesOrNo hasCoversheets;

    @CCD(
            label = "Should this bundle have a title page with a table of contents?"
    )
    private YesOrNo hasTableOfContents;

    @CCD(
            label = "Should this bundle’s folders have a coversheet?"
    )
    private YesOrNo hasFolderCoversheets;

    @CCD(
            label = "Error from Stitching service"
    )
    private String stitchingFailureMessage;

    @CCD(
            label = "Name of the PDF"
    )
    private String fileName;

    @CCD(
            label = "Unique filename identifier"
    )
    private String fileNameIdentifier;

    @CCD(
            label = "Pagination Style",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "paginationStyle"
    )
    private String paginationStyle;

    @CCD(
            label = "Cover page template"
    )
    private String coverpageTemplate;

    @CCD(
            label = "Page Number Format",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "pageNumberFormat"
    )
    private String pageNumberFormat;

    @CCD(
            label = "Enable Email Notification?"
    )
    private YesOrNo enableEmailNotification;

    @CCD(
            label = "Configure image for stitched PDF?"
    )
    private DocumentImage documentImage;
}
