package uk.gov.hmcts.et.common.model.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.AddressUK;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class ClaimantCorrespondence {
    @CCD(
            label = "Address"
    )
    private AddressUK claimant_addressUK;

    @CCD(
            label = "Phone number",
            searchable = false,
            typeOverride = FieldType.PhoneUK
    )
    private String claimant_phone_number;

    @CCD(
            label = "Alternative number",
            searchable = false,
            typeOverride = FieldType.PhoneUK
    )
    private String claimant_mobile_number;

    @CCD(
            label = "Email address",
            searchable = false,
            typeOverride = FieldType.Email
    )
    private String claimant_email_address;

    @CCD(
            label = "Contact preference",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_ContactPreference"
    )
    private String claimant_contact_preference;

    @CCD(
            label = "Contact language",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_languages"
    )
    private String claimant_contact_language;

    @CCD(
            label = "Hearing language",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_languages"
    )
    private String claimant_hearing_language;
}
