package uk.gov.hmcts.et.common.model.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class ClaimantRequest {
    @CCD(
            label = "What do you want if your claim is successful?",
            searchable = false,
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "msl_claimOutcomes"
    )
    private String claim_outcome;

    @CCD(
            label = "What compensation are you seeking?",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String claimant_compensation_text;

    @CCD(
            label = "Compensation amount requested",
            searchable = false
    )
    private Integer claimant_compensation_amount;

    @CCD(
            label = "Tribunal recommendation request",
            searchable = false
    )
    private String claimant_tribunal_recommendation;

    @CCD(
            label = "Whistleblowing claim",
            searchable = false
    )
    private YesOrNo whistleblowing;

    @CCD(
            label = "Whistleblowing authority",
            searchable = false
    )
    private String whistleblowing_authority;

    @CCD(
            label = "Describe what happened to you",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String claim_description;

    @CCD(
            label = "Describe what happened to you",
            categoryID = "C12",
            searchable = false
    )
    private Document claim_description_document;

    @CCD(
            label = "What type of discrimination are you claiming?",
            searchable = false,
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "msl_discriminationClaims"
    )
    private String discrimination_claims;

    @CCD(
            label = "What type of pay claim are you making?",
            searchable = false,
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "msl_payClaims"
    )
    private String pay_claims;

    @CCD(
            label = " ",
            searchable = false
    )
    private YesOrNo linked_cases;

    @CCD(
            label = " ",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String linked_cases_detail;

    @CCD(
            label = "Please describe what type of claim you want to make",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String other_claim;
}
