package uk.gov.hmcts.et.common.model.ccd;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class Deposit {
    @JsonProperty("Deposit_amount")
    @CCD(
            label = "Deposit amount (£)",
            hint = "Enter a value less than £10,000",
            min = 0,
            max = 999900,
            typeOverride = FieldType.MoneyGBP
    )
    private String deposit_amount;

    @CCD(
            label = "Deposit ordered against",
            showCondition = "deposit_covers=\"dummy\"",
            retainHiddenValue = true,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_ClaimantOrRespondent"
    )
    private String depositOrderAgainst;

    @CCD(
            label = "Deposit ordered against",
            typeOverride = FieldType.DynamicList
    )
    private String dynamicDepositOrderAgainst;

    @CCD(
            label = "Deposit requested by",
            showCondition = "deposit_covers=\"dummy\"",
            retainHiddenValue = true,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_DepositRequestedBy"
    )
    private String deposit_requested_by;

    @CCD(
            label = "Deposit requested by",
            typeOverride = FieldType.DynamicList
    )
    private String dynamicDepositRequestedBy;

    @CCD(
            label = "Deposit covers",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_DepositCovers"
    )
    private String deposit_covers;

    @CCD(
            label = "Deposit order sent"
    )
    private LocalDate deposit_order_sent;

    @CCD(
            label = "Deposit due"
    )
    private LocalDate deposit_due;

    @CCD(
            label = "Deposit time extension"
    )
    private YesOrNo deposit_time_ext;

    @CCD(
            label = "Deposit time extension due",
            showCondition = "deposit_time_ext=\"Yes\"",
            retainHiddenValue = true
    )
    private LocalDate deposit_time_ext_due;

    @CCD(
            label = "Deposit received"
    )
    private YesOrNo depositReceived;

    @CCD(
            label = "Date deposit received",
            showCondition = "depositReceived=\"Yes\"",
            retainHiddenValue = true
    )
    private LocalDate depositReceivedDate;

    @CCD(
            label = "Deposit refund"
    )
    private YesOrNo deposit_refund;

    @CCD(
            label = "Amount Refunded",
            showCondition = "deposit_refund=\"Yes\"",
            retainHiddenValue = true,
            typeOverride = FieldType.MoneyGBP
    )
    private String depositAmountRefunded;

    @CCD(
            label = "Deposit refund date",
            showCondition = "deposit_refund=\"Yes\"",
            retainHiddenValue = true
    )
    private LocalDate deposit_refund_date;

    @CCD(
            label = "Deposit refunded to",
            showCondition = "deposit_covers=\"dummy\"",
            retainHiddenValue = true,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_ClaimantOrRespondent"
    )
    private String depositRefundedTo;

    @CCD(
            label = "Deposit refunded to",
            showCondition = "deposit_refund=\"Yes\"",
            typeOverride = FieldType.DynamicList
    )
    private String dynamicDepositRefundedTo;

    @CCD(
            label = "Notes",
            typeOverride = FieldType.TextArea
    )
    private String depositNotes;

    @CCD(
            label = "Document Upload",
            categoryID = "C27"
    )
    private Document depositDoc;
}
