package uk.gov.hmcts.et.common.model.ccd;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class DigitalCaseFile {
    @CCD(
            label = "Digital Case File",
            categoryID = "C69"
    )
    private Document uploadedDocument;

    @CCD(
            label = "Date Generated"
    )
    private LocalDate dateGenerated;

    @CCD(
            label = "Status"
    )
    private String status;

    @CCD(
            label = "Error"
    )
    private String error;
}
