package uk.gov.hmcts.et.common.model.ccd;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class DocumentUpload {
    @CCD(
            label = "Exclude from Digital Case File",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "msl_Yes"
    )
    private String excludeFromDcf;

    @CCD(
            label = "Document Category",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_DocumentCategories"
    )
    private String topLevelDocuments;

    @CCD(
            label = "Starting a Claim",
            showCondition = "topLevelDocuments=\"Starting a Claim\"",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_StartingAClaim"
    )
    private String startingClaimDocuments;

    @CCD(
            label = "Response to a Claim",
            showCondition = "topLevelDocuments=\"Response to a Claim\"",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_ResponseToAClaim"
    )
    private String responseClaimDocuments;

    @CCD(
            label = "Initial Consideration",
            showCondition = "topLevelDocuments=\"Initial Consideration\"",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_InitialConsideration"
    )
    private String initialConsiderationDocuments;

    @CCD(
            label = "Case Management",
            showCondition = "topLevelDocuments=\"Case Management\"",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_CaseManagement"
    )
    private String caseManagementDocuments;

    @CCD(
            label = "Employer Contract Claim",
            showCondition = "topLevelDocuments=\"Employer Contract Claim\"",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_EmployerContractClaim"
    )
    private String eccDocuments;

    @CCD(
            label = "Withdrawal/Settled",
            showCondition = "topLevelDocuments=\"Withdrawal/Settled\"",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_WithdrawalSettled"
    )
    private String withdrawalSettledDocuments;

    @CCD(
            label = "Hearings",
            showCondition = "topLevelDocuments=\"Hearings\"",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Hearings"
    )
    private String hearingsDocuments;

    @CCD(
            label = "Judgment and Reasons",
            showCondition = "topLevelDocuments=\"Judgment and Reasons\"",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_JudgmentAndReasons"
    )
    private String judgmentAndReasonsDocuments;

    @CCD(
            label = "Reconsideration",
            showCondition = "topLevelDocuments=\"Reconsideration\"",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Reconsideration"
    )
    private String reconsiderationDocuments;

    @CCD(
            label = "Misc",
            showCondition = "topLevelDocuments=\"Misc\"",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Misc"
    )
    private String miscDocuments;

    @CCD(
            label = "Type of Document",
            showCondition = "topLevelDocuments=\"Legacy Document Names\"",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_DocumentType"
    )
    private String typeOfDocument;

    @CCD(
            label = "Document"
    )
    private Document uploadedDocument;

    @CCD(
            label = "Short Description"
    )
    private String shortDescription;

    @CCD(
            label = "Type of Document"
    )
    private String documentType;

    @CCD(
            label = "Date of Correspondence"
    )
    private LocalDate dateOfCorrespondence;

    @CCD(
            label = "Number"
    )
    private Integer docNumber;

    @CCD(
            label = "Document Number"
    )
    private Integer documentIndex;
}
