package uk.gov.hmcts.et.common.model.ccd;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class EmploymentDetails {
    @CCD(
            label = "Employment Details",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String claimantEmploymentDetails;

    @CCD(
            label = "Occupation",
            searchable = false
    )
    private String claimant_occupation;

    @CCD(
            label = "Employed from",
            searchable = false
    )
    private LocalDate claimant_employed_from;

    @CCD(
            label = "Is the employment continuing?",
            searchable = false
    )
    private YesOrNo claimant_employed_currently;

    @CCD(
            label = "Employed to",
            showCondition = "claimant_employed_currently=\"No\"",
            searchable = false
    )
    private LocalDate claimant_employed_to;

    @CCD(
            label = "Notice Period End Date",
            showCondition = "claimant_employed_currently=\"Yes\"",
            searchable = false
    )
    private LocalDate claimant_employed_notice_period;

    @CCD(
            label = "Are there any disabilities or special requirements?",
            searchable = false
    )
    private YesOrNo claimant_disabled;

    @CCD(
            label = "Please provide details",
            showCondition = "claimant_disabled=\"Yes\"",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String claimant_disabled_details;

    @CCD(
            label = "Notice Period",
            searchable = false
    )
    private YesOrNo claimant_notice_period;

    @CCD(
            label = "Notice Weeks or Months",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_notice_period_unit"
    )
    private String claimant_notice_period_unit;

    @CCD(
            label = "Notice Period Duration",
            searchable = false
    )
    private Integer claimant_notice_period_duration;

    @CCD(
            label = "Average weekly hours",
            searchable = false
    )
    private Integer claimant_average_weekly_hours;

    @CCD(
            label = "Pay before tax",
            searchable = false
    )
    private Integer claimant_pay_before_tax;

    @CCD(
            label = "Pay after tax",
            searchable = false
    )
    private Integer claimant_pay_after_tax;

    @CCD(
            label = "Weekly, monthly or annual pay",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_pay_cycle"
    )
    private String claimant_pay_cycle;

    @CCD(
            label = "Pension Scheme",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_pension_contribution"
    )
    private String claimant_pension_contribution;

    @CCD(
            label = "Pension Contribution",
            searchable = false
    )
    private Integer claimant_pension_weekly_contribution;

    @CCD(
            label = "Employee Benefits",
            searchable = false
    )
    private YesOrNo claimant_benefits;

    @CCD(
            label = "Employee Benefits Details",
            searchable = false
    )
    private String claimant_benefits_detail;

    @CCD(
            label = "Did you work for the organisation or person",
            searchable = false
    )
    private YesOrNo pastEmployer;

    @CCD(
            label = "Are you still working for the organisation or person",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_StillWorking"
    )
    private String stillWorking;
}
