package uk.gov.hmcts.et.common.model.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "etICHearingNotListedListForPrelimHearing",
        generate = true
)
public class EtICHearingNotListedListForPrelimHearing {
    @CCD(
            label = "Type of preliminary hearing",
            hint = "Select all that apply",
            searchable = false,
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "msl_etICTypeOfHearing"
    )
    private String etICTypeOfPreliminaryHearing;

    @CCD(
            label = "Purpose of preliminary hearing",
            hint = "Select all that apply",
            searchable = false,
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "msl_etICPurposeOfPrelimHearing"
    )
    private String etICPurposeOfPreliminaryHearing;

    @CCD(
            label = "Give details of hearing notice",
            showCondition = "etICPurposeOfPreliminaryHearing != \"\"",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String etICGiveDetailsOfHearingNotice;

    @CCD(
            label = "Length of hearing",
            showCondition = "etICPurposeOfPreliminaryHearing != \"\"",
            searchable = false
    )
    private Integer etICLengthOfPrelimHearing;

    @CCD(
            label = "Days, Hours or Minutes",
            showCondition = "etICPurposeOfPreliminaryHearing != \"\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_HearingLength"
    )
    private String prelimHearingLengthNumType;
}
