package uk.gov.hmcts.et.common.model.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class HearingPreference {
    @CCD(
            label = "What are the claimant's hearing preferences",
            searchable = false,
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "msl_HearingPreferences"
    )
    private String hearing_preferences;

    @CCD(
            label = "Why is the claimant unable to take part in video or phone hearings",
            showCondition = "hearing_preferences CONTAINS \"Neither\"",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String hearing_assistance;

    @CCD(
            label = "Do you have a physical, mental or learning disability or long term health condition that means you need support during your case?",
            searchable = false
    )
    private YesOrNo reasonable_adjustments;

    @CCD(
            label = "Tell us what support you need to request",
            showCondition = "reasonable_adjustments=\"Yes\"",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String reasonable_adjustments_detail;

    @CCD(
            label = "Contact language",
            searchable = false,
            typeOverride = FieldType.FixedRadioList,
            typeParameterOverride = "fl_languages"
    )
    private String contact_language;

    @CCD(
            label = "If a hearing is required, what language do you want to speak at a hearing?",
            searchable = false,
            typeOverride = FieldType.FixedRadioList,
            typeParameterOverride = "fl_languages"
    )
    private String hearing_language;

    @CCD(
            label = "Hearing panel preference",
            searchable = false,
            typeOverride = FieldType.FixedRadioList,
            typeParameterOverride = "claimant_hearingPanelPreference"
    )
    private String claimant_hearing_panel_preference;

    @CCD(
            label = "Panel preference reason",
            showCondition = "claimant_hearing_panel_preference=\"Judge\" OR claimant_hearing_panel_preference=\"Panel\"",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String claimant_hearing_panel_preference_why;
}
