package uk.gov.hmcts.et.common.model.ccd;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class Hearing {
    @CCD(
            label = "Show Hearing Details"
    )
    private YesOrNo hearingShowDetails;

    @JsonProperty("Hearing_type")
    @CCD(
            label = "Hearing type",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Hearing"
    )
    private String hearing_type;

    @CCD(
            label = "Hearing notes"
    )
    private Document hearingNotesDocument;

    @CCD(
            label = "Hearing Dates"
    )
    private String hearingDates;

    @CCD(
            label = "Hearing Format",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "msl_HearingFormat"
    )
    private String hearingFormat;

    @CCD(
            label = "Judicial Mediation"
    )
    private YesOrNo judicialMediation;

    @CCD(
            label = "Public or Private?",
            showCondition = "Hearing_type=\"Preliminary Hearing\"",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_PublicPrivate"
    )
    private String hearingPublicPrivate;

    @CCD(
            label = "Hearing Number"
    )
    private Integer hearingNumber;

    @JsonProperty("Hearing_venue")
    @CCD(
            label = "Hearing Venue",
            typeOverride = FieldType.DynamicList
    )
    private String hearing_venue;

    @CCD(
            label = "Estimated hearing length"
    )
    private Integer hearingEstLengthNum;

    @CCD(
            label = "Days, Hours or Minutes",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_HearingLength"
    )
    private String hearingEstLengthNumType;

    @CCD(
            label = "Panel Type",
            typeOverride = FieldType.FixedRadioList,
            typeParameterOverride = "frl_SitAlone"
    )
    private String hearingSitAlone;

    @CCD(
            label = "Employment Judge",
            typeOverride = FieldType.DynamicList
    )
    private String judge;

    @CCD(
            label = "Employment Judge",
            showCondition = "hearingSitAlone = \"Two Judges\"",
            typeOverride = FieldType.DynamicList
    )
    private String additionalJudge;

    @CCD(
            label = "Employer Member",
            showCondition = "hearingSitAlone = \"Full Panel\"",
            typeOverride = FieldType.DynamicList
    )
    private String hearingERMember;

    @CCD(
            label = "Employee Member",
            showCondition = "hearingSitAlone = \"Full Panel\"",
            typeOverride = FieldType.DynamicList
    )
    private String hearingEEMember;

    @JsonProperty("Hearing_stage")
    @CCD(
            label = "EQP Stage Hearing",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Stage"
    )
    private String hearing_stage;

    @JsonProperty("Hearing_notes")
    @CCD(
            label = "Hearing Notes",
            typeOverride = FieldType.TextArea
    )
    private String hearing_notes;

    @CCD(
            label = "Day",
            min = 1
    )
    private List<ListValue<DateListed>> hearingDateCollection;
}
