package uk.gov.hmcts.et.common.model.ccd;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class Judgment {
    @CCD(
            label = "Jurisdiction"
    )
    private List<ListValue<Jurisdiction>> jurisdictionCodes;

    @CCD(
            label = "Non Hearing Judgment?"
    )
    private YesOrNo non_hearing_judgment;

    @CCD(
            label = "Date of Hearing",
            showCondition = "non_hearing_judgment=\"No\"",
            retainHiddenValue = true
    )
    private LocalDate judgmentHearingDate;

    @CCD(
            label = "Hearing Details",
            showCondition = "non_hearing_judgment=\"No\"",
            typeOverride = FieldType.DynamicList
    )
    private String dynamicJudgementHearing;

    @CCD(
            label = "Judgment Type",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_JudgementType"
    )
    private String judgement_type;

    @CCD(
            label = "Liability",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Liability"
    )
    private String liability_optional;

    @CCD(
            label = "Date Judgment made"
    )
    private LocalDate date_judgment_made;

    @CCD(
            label = "Date Judgment sent"
    )
    private LocalDate date_judgment_sent;

    @CCD(
            label = "Judgment Notes",
            typeOverride = FieldType.TextArea
    )
    private String judgment_notes;

    @CCD(
            label = "Upload outcome of Judgment",
            categoryID = "C60"
    )
    private Document judgement_outcome_doc;

    @CCD(
            label = "Judgment details",
            hint = " "
    )
    private JudgmentDetails judgement_details;

    @JsonProperty("Judgement_costs")
    @CCD(
            label = "Costs"
    )
    private JudgmentCosts judgement_costs;

    @CCD(
            label = "Reconsideration",
            hint = " "
    )
    private JudgmentReconsideration reconsiderations;
}
