package uk.gov.hmcts.et.common.model.ccd;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "judgmentReconsideration",
        generate = true
)
public class JudgmentReconsideration {
    @CCD(
            label = "Has a reconsideration application been made?"
    )
    private YesOrNo reconsideration;

    @CCD(
            label = "Date of application for reconsideration",
            showCondition = "reconsideration=\"Yes\"",
            retainHiddenValue = true
    )
    private LocalDate reconsiderationDate;

    @CCD(
            label = "Did the Tribunal reconsider the Judgment on its own initiative",
            showCondition = "reconsideration=\"Yes\"",
            retainHiddenValue = true
    )
    private YesOrNo reconsiderationOwnInitiative;

    @CCD(
            label = "Who applied for reconsideration?",
            showCondition = "reconsiderationOwnInitiative=\"No\"",
            retainHiddenValue = true,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_ClaimantOrRespondent"
    )
    private String reconsiderationPartyInitiative;

    @CCD(
            label = "Employment Judge's direction",
            showCondition = "reconsideration=\"Yes\"",
            retainHiddenValue = true,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_JudgeDirection"
    )
    private String reconsiderationDirection;

    @CCD(
            label = "Employment Judge's decision",
            showCondition = "reconsideration=\"Yes\"",
            retainHiddenValue = true,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_JudgeDecision"
    )
    private String reconsiderationDecision;
}
