package uk.gov.hmcts.et.common.model.ccd;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class Letters {
    @CCD(
            label = "Top Level",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_TopLevel"
    )
    private String topLevel_Documents;

    @CCD(
            label = "Part 0",
            showCondition = "topLevel_Documents=\"EM-TRB-LET-ENG-00544\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_0"
    )
    private String part_0_Documents;

    @CCD(
            label = "Part 1",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00026\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_1"
    )
    private String part_1_Documents;

    @CCD(
            label = "Part 2",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00027\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_2"
    )
    private String part_2_Documents;

    @CCD(
            label = "Part 3",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00028\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_3"
    )
    private String part_3_Documents;

    @CCD(
            label = "Part 4",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00029\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_4"
    )
    private String part_4_Documents;

    @CCD(
            label = "Part 5",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00030\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_5"
    )
    private String part_5_Documents;

    @JsonProperty("Part_6_Documents")
    @CCD(
            label = "Part 6",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00031\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_6"
    )
    private String part_6_Documents;

    @JsonProperty("Part_7_Documents")
    @CCD(
            label = "Part 7",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00032\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_7"
    )
    private String part_7_Documents;

    @JsonProperty("Part_8_Documents")
    @CCD(
            label = "Part 8",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00065\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_8"
    )
    private String part_8_Documents;

    @JsonProperty("Part_9_Documents")
    @CCD(
            label = "Part 9",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00033\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_9"
    )
    private String part_9_Documents;

    @JsonProperty("Part_10_Documents")
    @CCD(
            label = "Part 10",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00034\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_10"
    )
    private String part_10_Documents;

    @JsonProperty("Part_11_Documents")
    @CCD(
            label = "Part 11",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00035\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_11"
    )
    private String part_11_Documents;

    @JsonProperty("Part_12_Documents")
    @CCD(
            label = "Part 12",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00036\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_12"
    )
    private String part_12_Documents;

    @JsonProperty("Part_13_Documents")
    @CCD(
            label = "Part 13",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00037\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_13"
    )
    private String part_13_Documents;

    @JsonProperty("Part_14_Documents")
    @CCD(
            label = "Part 14",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00038\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_14"
    )
    private String part_14_Documents;

    @JsonProperty("Part_15_Documents")
    @CCD(
            label = "Part 15",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00039\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_15"
    )
    private String part_15_Documents;

    @JsonProperty("Part_16_Documents")
    @CCD(
            label = "Part 16",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00040\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_16"
    )
    private String part_16_Documents;

    @JsonProperty("Part_17_Documents")
    @CCD(
            label = "Part 17",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00041\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_17"
    )
    private String part_17_Documents;

    @JsonProperty("Part_18_Documents")
    @CCD(
            label = "Part 18",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00066\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_18"
    )
    private String part_18_Documents;

    @CCD(
            label = "Hearing Number",
            showCondition = "topLevel_Documents=\"dummy\"",
            searchable = false
    )
    private Integer hearingNumber;

    @CCD(
            label = "Hearing Number",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00032\" OR topLevel_Documents=\"EM-TRB-EGW-ENG-00065\" OR part_2_Documents = \"2.5\" OR part_2_Documents = \"2.7\" OR part_2_Documents = \"2.7 Reform\" OR part_2_Documents = \"2.7A\" OR part_2_Documents = \"2.7A Reform\" OR part_2_Documents = \"2.8\" OR part_2_Documents = \"2.8 Reform\" OR part_2_Documents = \"2.8A\" OR part_2_Documents = \"2.8A Reform\" OR part_4_Documents = \"4.5\" OR part_4_Documents = \"4.8A\"  OR part_5_Documents=\"5.18\" OR part_5_Documents=\"5.18A\" OR Part_7_Documents=\"7.8A\" OR Part_7_Documents=\"7.9A\" OR Part_8_Documents=\"8.1A\" OR Part_11_Documents = \"11.8\" OR Part_11_Documents = \"11.9\" OR Part_15_Documents = \"15.2\" OR Part_15_Documents = \"15.1\" OR Part_15_Documents = \"15.3\" OR Part_15_Documents = \"15.4\" OR Part_16_Documents = \"16.1\" OR Part_16_Documents = \"16.2\" OR Part_17_Documents = \"17.3\"",
            searchable = false,
            typeOverride = FieldType.DynamicList
    )
    private String dynamicHearingNumber;

    @JsonProperty("Part_20_Documents")
    @CCD(
            label = "Part 20",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00043\"",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_Part_20"
    )
    private String part_20_Documents;

    @CCD(
            label = "Respondents with ECC",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00028\" AND part_3_Documents != \"3.1\" AND part_3_Documents != \"3.2\" AND part_3_Documents != \"3.3\" AND part_3_Documents != \"3.4\" AND part_3_Documents != \"3.5\" AND part_3_Documents != \"3.6\" AND part_3_Documents != \"3.7\" AND part_3_Documents != \"3.22\" AND part_3_Documents != \"3.23\"",
            searchable = false,
            typeOverride = FieldType.DynamicList
    )
    private String dynamicRespondentsWithEcc;

    @CCD(
            label = "Address ECC letter to Claimant?",
            showCondition = "topLevel_Documents=\"EM-TRB-EGW-ENG-00028\" AND dynamicRespondentsWithEcc != \"\" AND dynamicRespondentsWithEcc != \"No respondents with ECC\"",
            searchable = false
    )
    private YesOrNo flipRespondentAndClaimantValues;
}
