package uk.gov.hmcts.et.common.model.ccd;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class NewEmploymentDetails {
    @CCD(
            label = "Have you got a new job",
            searchable = false
    )
    private YesOrNo new_job;

    @CCD(
            label = "Employed from",
            searchable = false
    )
    private LocalDate newly_employed_from;

    @CCD(
            label = "Pay before tax",
            searchable = false
    )
    private Integer new_pay_before_tax;

    @CCD(
            label = "Is this your weekly, monthly or annual pay",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_pay_cycle"
    )
    private String new_job_pay_interval;
}
