package uk.gov.hmcts.et.common.model.ccd;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "pseRespondCollection",
        generate = true
)
public class PseRespondCollection {
    @CCD(
            label = " ",
            showCondition = "copyToOtherParty = \"dummy\"",
            retainHiddenValue = true
    )
    private String dateTime;

    @CCD(
            label = " ",
            showCondition = "copyToOtherParty=\"dummy\"",
            retainHiddenValue = true
    )
    private String isECC;

    @CCD(
            label = "Response date"
    )
    private String date;

    @CCD(
            label = "Response from"
    )
    private String from;

    @CCD(
            label = "What's your response to the tribunal?",
            typeOverride = FieldType.TextArea
    )
    private String response;

    @CCD(
            label = "Response from Idam id",
            showCondition = "date=\"dummy\""
    )
    private String fromIdamId;

    @CCD(
            label = "Has supporting material",
            showCondition = "date=\"dummy\""
    )
    private String hasSupportingMaterial;

    @CCD(
            label = "Supporting material"
    )
    private List<ListValue<DocumentUpload>> supportingMaterial;

    @CCD(
            label = "Do you want to copy this correspondence to the other party to satisfy the Rules of Procedure?"
    )
    private String copyToOtherParty;

    @CCD(
            label = " ",
            showCondition = "copyToOtherParty=\"dummy\"",
            typeOverride = FieldType.TextArea
    )
    private String copyNoGiveDetails;

    @CCD(
            label = " ",
            showCondition = "date=\"dummy\""
    )
    private String responseState;

    @CCD(
            label = " ",
            showCondition = "date=\"dummy\""
    )
    private String author;
}
