package uk.gov.hmcts.et.common.model.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "pseStatus",
        generate = true
)
public class PseStatus {
    @CCD(
            label = "User Idam Id"
    )
    private String userIdamId;

    @CCD(
            label = "Notification state"
    )
    private String notificationState;

    @CCD(
            label = "Updated date time"
    )
    private String dateTime;
}
