package uk.gov.hmcts.et.common.model.ccd;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "referralReply",
        generate = true
)
public class ReferralReply {
    @CCD(
            label = " ",
            showCondition = "replyDateTime = \"dummy\""
    )
    private String replyDateTime;

    @CCD(
            label = " ",
            showCondition = "replyDateTime = \"dummy\""
    )
    private String referralSubject;

    @CCD(
            label = " ",
            showCondition = "replyDateTime = \"dummy\""
    )
    private String referralNumber;

    @CCD(
            label = "Reply by"
    )
    private String replyBy;

    @CCD(
            label = "Reply to"
    )
    private String directionTo;

    @CCD(
            label = "Email address"
    )
    private String replyToEmailAddress;

    @CCD(
            label = "Date"
    )
    private String replyDate;

    @CCD(
            label = "Urgent"
    )
    private String isUrgentReply;

    @CCD(
            label = "Directions",
            typeOverride = FieldType.TextArea
    )
    private String directionDetails;

    @CCD(
            label = "Documents"
    )
    private List<ListValue<DocumentUpload>> replyDocument;

    @CCD(
            label = "General notes",
            typeOverride = FieldType.TextArea
    )
    private String replyGeneralNotes;
}
