package uk.gov.hmcts.et.common.model.ccd;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "respondNotificationTypeCollection",
        generate = true
)
public class RespondNotificationTypeCollection {
    @CCD(
            label = "Is this a case management order or request?"
    )
    private String respondNotificationCmoOrRequest;

    @CCD(
            label = "Date"
    )
    private String respondNotificationDate;

    @CCD(
            label = "Request made by"
    )
    private String respondNotificationRequestMadeBy;

    @CCD(
            label = " ",
            showCondition = "respondNotificationDate=\"dummy\""
    )
    private String state;

    @CCD(
            label = " ",
            showCondition = "state=\"dummy\""
    )
    private String isClaimantResponseDue;

    @CCD(
            label = "Updated date time"
    )
    private String dateTime;

    @CCD(
            label = "Response title"
    )
    private String respondNotificationTitle;

    @CCD(
            label = "Additional information",
            typeOverride = FieldType.TextArea
    )
    private String respondNotificationAdditionalInfo;

    @CCD(
            label = "Documents"
    )
    private List<ListValue<DocumentUpload>> respondNotificationUploadDocument;

    @CCD(
            label = "Response due"
    )
    private String respondNotificationResponseRequired;

    @CCD(
            label = "Party or parties to respoond"
    )
    private String respondNotificationWhoRespond;

    @CCD(
            label = "Case management order made by"
    )
    private String respondNotificationCaseManagementMadeBy;

    @CCD(
            label = "Full name"
    )
    private String respondNotificationFullName;

    @CCD(
            label = "Sent to"
    )
    private String respondNotificationPartyToNotify;
}
