package uk.gov.hmcts.et.common.model.ccd;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class RestrictedCase {
    @CCD(
            label = "Requested By",
            typeOverride = FieldType.DynamicList
    )
    private String dynamicRequestedBy;

    @CCD(
            label = "Requested By",
            showCondition = "excludedRegister=\"dummy\" OR dynamicRequestedBy!=\"*\"",
            retainHiddenValue = true,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_RestrictedRequestedBy"
    )
    private String requestedBy;

    @CCD(
            label = "Date Ceased"
    )
    private LocalDate dateCeased;

    @CCD(
            label = "Rule 49(3)(d) Applies"
    )
    private YesOrNo imposed;

    @CCD(
            label = "Rule 49(3)(b) Applies"
    )
    private YesOrNo rule503b;

    @CCD(
            label = "Excluded from Register",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "fl_RestrictedExcludedRegister"
    )
    private String excludedRegister;

    @CCD(
            label = "Start Date"
    )
    private LocalDate startDate;

    @CCD(
            label = "Deleted from Physical Register"
    )
    private YesOrNo deletedPhyRegister;

    @CCD(
            label = "Names not for public release",
            typeOverride = FieldType.TextArea
    )
    private String excludedNames;
}
