package uk.gov.hmcts.et.common.model.ccd;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "tseReply",
        generate = true
)
public class TseReply {
    @CCD(
            label = " ",
            showCondition = "dateTime = \"dummy\""
    )
    private String dateTime;

    @CCD(
            label = " ",
            showCondition = "applicationType = \"dummy\""
    )
    private String applicationType;

    @CCD(
            label = "Response from"
    )
    private String from;

    @CCD(
            label = "Response date"
    )
    private String date;

    @CCD(
            label = "Response from Idam id"
    )
    private String fromIdamId;

    @CCD(
            label = "What's your response to the claimant's application",
            typeOverride = FieldType.TextArea
    )
    private String response;

    @CCD(
            label = " ",
            showCondition = "date=\"dummy\""
    )
    private String hasSupportingMaterial;

    @CCD(
            label = "Supporting material"
    )
    private List<ListValue<DocumentUpload>> supportingMaterial;

    @CCD(
            label = "Do you want to copy this correspondence to the other party to satisfy the Rules of Procedure?"
    )
    private String copyToOtherParty;

    @CCD(
            label = "Give details",
            typeOverride = FieldType.TextArea
    )
    private String copyNoGiveDetails;

    @CCD(
            label = " ",
            showCondition = "from=\"dummy\"",
            categoryID = "C4"
    )
    private Document summaryPdf;

    @CCD(
            label = "Enter response title"
    )
    private String enterResponseTitle;

    @CCD(
            label = "Additional information",
            typeOverride = FieldType.TextArea
    )
    private String additionalInformation;

    @CCD(
            label = "Add document"
    )
    private List<ListValue<DocumentUpload>> addDocument;

    @CCD(
            label = "Is this a case management order or request?"
    )
    private String isCmoOrRequest;

    @CCD(
            label = "Case management order made by"
    )
    private String cmoMadeBy;

    @CCD(
            label = "Request made by"
    )
    private String requestMadeBy;

    @CCD(
            label = "Enter their full name"
    )
    private String madeByFullName;

    @CCD(
            label = "Is a response to the tribunal required?"
    )
    private String isResponseRequired;

    @CCD(
            label = "Select the party or parties who must respond"
    )
    private String selectPartyRespond;

    @CCD(
            label = "Select the party or parties to notify"
    )
    private String selectPartyNotify;

    @CCD(
            label = "Viewed by the claimant"
    )
    private String viewedByClaimant;
}
