package uk.gov.hmcts.et.common.model.ccd;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "updateReferralDetails",
        generate = true
)
public class UpdateReferralDetails {
    @CCD(
            label = "No"
    )
    private String updateReferralNumber;

    @CCD(
            label = "Hearing date"
    )
    private String updateReferralHearingDate;

    @CCD(
            label = "Referred to"
    )
    private String updateReferCaseTo;

    @CCD(
            label = "Email address"
    )
    private String updateReferentEmail;

    @CCD(
            label = "Details of the referral",
            typeOverride = FieldType.TextArea
    )
    private String updateReferralDetails;

    @CCD(
            label = "Urgent"
    )
    private String updateIsUrgent;

    @CCD(
            label = "Subject"
    )
    private String updateReferralSubject;

    @CCD(
            label = "Referral subject"
    )
    private String updateReferralSubjectSpecify;

    @CCD(
            label = "Documents"
    )
    private List<ListValue<DocumentUpload>> updateReferralDocument;

    @CCD(
            label = "Recommended instructions",
            typeOverride = FieldType.TextArea
    )
    private String updateReferralInstruction;

    @CCD(
            label = "Updated by"
    )
    private String updateReferredBy;

    @CCD(
            label = "Updated date"
    )
    private String updateReferralDate;

    @CCD(
            label = "Update Referral DateTime"
    )
    private String updateReferralDateTime;
}
