package uk.gov.hmcts.et.common.model.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.AddressUK;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class WorkAddressDetails {
    @CCD(
            label = "Claimant Work Address",
            searchable = false
    )
    private AddressUK claimant_work_address;

    @CCD(
            label = "Work phone number",
            searchable = false,
            typeOverride = FieldType.PhoneUK
    )
    private String claimant_work_phone_number;
}
