package uk.gov.hmcts.ethos.replacement.docmosis.domain.documents;

import lombok.Data;
import lombok.experimental.SuperBuilder;

import java.util.List;

/**
 * Stores data to populate the ET3 Response form template.
 */
@Data
@SuperBuilder
public class Et3ResponseData {
    private String ethosCaseReference;
    private String et3ResponseClaimantName;
    private String et3ResponseRespondentLegalName;
    private String et3ResponseRespondentCompanyNumber;
    private String et3ResponseRespondentEmployerType;
    private String et3ResponseRespondentPreferredTitle;
    private String et3ResponseRespondentContactName;
    private String respondentAddressLine1;
    private String respondentAddressLine2;
    private String respondentCity;
    private String respondentCounty;
    private String respondentPostcode;
    private String et3ResponseDXAddress;
    private String et3ResponsePhone;
    private String et3ResponseContactPreference;
    private List<String> et3ResponseHearingRepresentative;
    private List<String> et3ResponseHearingRespondent;
    private String et3ResponseEmploymentCount;
    private String et3ResponseMultipleSites;
    private String et3ResponseSiteEmploymentCount;
    private String et3ResponseAcasAgree;
    private String et3ResponseAcasAgreeReason;
    private String et3ResponseAreDatesCorrect;
    private String et3ResponseEmploymentStartDate;
    private String et3ResponseEmploymentEndDate;
    private String et3ResponseEmploymentInformation;
    private String et3ResponseContinuingEmployment;
    private String et3ResponseIsJobTitleCorrect;
    private String et3ResponseCorrectJobTitle;
    private String et3ResponseClaimantWeeklyHours;
    private String et3ResponseClaimantCorrectHours;
    private String et3ResponseEarningDetailsCorrect;
    private String et3ResponsePayFrequency;
    private String et3ResponsePayBeforeTax;
    private String et3ResponsePayTakehome;
    private String et3ResponseIsNoticeCorrect;
    private String et3ResponseCorrectNoticeDetails;
    private String et3ResponseIsPensionCorrect;
    private String et3ResponsePensionCorrectDetails;
    private String et3ResponseRespondentContestClaim;
    private String et3ResponseContestClaimDetails;
    private String et3ResponseEmployerClaim;
    private String et3ResponseEmployerClaimDetails;
    private String et3ResponseRespondentSupportNeeded;
    private String et3ResponseRespondentSupportDetails;
    private String titleMr;
    private String titleMrs;
    private String titleMiss;
    private String titleMs;
    private String titleOther;
    private String titleText;
    private String contactPost;
    private String contactEmail;
    private String hearingVideo;
    private String hearingPhone;
    private String siteYes;
    private String siteNo;
    private String acasYes;
    private String acasNo;
    private String datesYes;
    private String datesNo;
    private String datesNA;
    private String continueYes;
    private String continueNo;
    private String continueNA;
    private String jobYes;
    private String jobNo;
    private String jobNA;
    private String hoursYes;
    private String hoursNo;
    private String hoursNA;
    private String earnYes;
    private String earnNo;
    private String earnNA;
    private String beforeWeekly;
    private String beforeMonthly;
    private String beforeAnnually;
    private String takehomeWeekly;
    private String takehomeMonthly;
    private String takehomeAnnually;
    private String noticeYes;
    private String noticeNo;
    private String noticeNA;
    private String pensionYes;
    private String pensionNo;
    private String pensionNA;
    private String contestYes;
    private String contestNo;
    private String eccYes;
    private String helpYes;
    private String helpNo;
    private String helpNA;
    private String repName;
    private String repOrgName;
    private String repAddressLine1;
    private String repAddressLine2;
    private String repTown;
    private String repCounty;
    private String repPostcode;
    private String repDXNumber;
    private String repPhoneNumber;
    private String repMobileNumber;
    private String repContactEmail;
    private String repContactPost;
    private String repEmailAddress;
    private String repHearingVideo;
    private String repHearingPhone;
    private String et3ResponseRespondentMobile;
    private String et3ResponseRespondentEmailAddress;
}
