fortify.client.releaseId=98695
fortify.exclude.pattern=*.jar|*.zip|*.tar|*.key|*.lock|*.html|/build|/.gradle|/.git|/node_modules|/test|/src/test|/dist|/functionalTest|/integrationTest|/ccd-definitions|/test-results|/playwright-report
