---
version: '3.5'

services:
  wiremock:
    container_name: wiremock
    image: wiremock/wiremock
    volumes:
      - ./mocks/wiremock:/home/wiremock:rw
    ports:
      - "8765:8080"
    command:
      - -global-response-templating

networks:
  default:
    name: cftlib_default
    external: true
