package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.Address;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;
import uk.gov.hmcts.et.common.model.ccd.types.ClaimantWorkAddressType;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code amendClaimantDetails}.
 */
public final class AmendClaimantDetailsPage3 {
    private AmendClaimantDetailsPage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("3");
        fields.showCondition("claimant_TypeOfClaimant=\"Individual\"");
        fields.complex(CaseData::getClaimantWorkAddress)
                    .complex(ClaimantWorkAddressType::getClaimantWorkAddress)
                    .optional(Address::getAddressLine1)
                    .eventLabel("Building and Street").done()
                    .complex(ClaimantWorkAddressType::getClaimantWorkAddress)
                    .optional(Address::getAddressLine2).done()
                    .complex(ClaimantWorkAddressType::getClaimantWorkAddress)
                    .optional(Address::getAddressLine3).done()
                    .complex(ClaimantWorkAddressType::getClaimantWorkAddress)
                    .optional(Address::getPostTown)
                    .eventLabel("Town or City").done()
                    .complex(ClaimantWorkAddressType::getClaimantWorkAddress)
                    .optional(Address::getCounty)
                    .eventLabel("County").done()
                    .complex(ClaimantWorkAddressType::getClaimantWorkAddress)
                    .optional(Address::getCountry)
                    .eventLabel("Country").done()
                    .complex(ClaimantWorkAddressType::getClaimantWorkAddress)
                    .mandatory(Address::getPostCode)
                    .eventLabel("Postcode").done()
                    .optional(ClaimantWorkAddressType::getClaimantWorkPhoneNumber)
                    .eventLabel("Work phone number").done();
    }
}
