package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;
import uk.gov.hmcts.et.common.model.ccd.types.ClaimantIndType;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code amendClaimantDetails}.
 */
public final class AmendClaimantDetailsPage1 {
    private AmendClaimantDetailsPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.mandatory(CaseData::getClaimantTypeOfClaimant)
                    .publish(false);
        fields.mandatory(CaseData::getClaimantCompany)
                    .fieldShowCondition("claimant_TypeOfClaimant=\"Company\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.complex(CaseData::getClaimantIndType)
                    .optional(ClaimantIndType::getClaimantPreferredTitle)
                    .eventLabel("Title")
                    .retainHiddenValue()
                    .optional(ClaimantIndType::getClaimantTitleOther)
                    .eventLabel("Other title")
                    .retainHiddenValue()
                    .mandatory(ClaimantIndType::getClaimantFirstNames)
                    .eventLabel("First Name")
                    .retainHiddenValue()
                    .mandatory(ClaimantIndType::getClaimantLastName)
                    .eventLabel("Last Name")
                    .retainHiddenValue()
                    .optional(ClaimantIndType::getClaimantDateOfBirth)
                    .eventLabel("Date of birth")
                    .retainHiddenValue()
                    .optional(ClaimantIndType::getClaimantSex)
                    .eventLabel("Sex")
                    .retainHiddenValue()
                    .optional(ClaimantIndType::getClaimantGenderIdentitySame)
                    .eventLabel("Gender Identity")
                    .retainHiddenValue()
                    .optional(ClaimantIndType::getClaimantGenderIdentity)
                    .eventLabel("Gender Identity description")
                    .retainHiddenValue().done()
                    .fieldShowCondition("claimant_TypeOfClaimant=\"Individual\"");
    }
}
