package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.types.ClaimantOtherType;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 5} of event {@code amendClaimantDetails}.
 */
public final class AmendClaimantDetailsPage5 {
    private AmendClaimantDetailsPage5() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("5");
        fields.complex(CaseData::getClaimantOtherType)
                    .optional(ClaimantOtherType::getClaimantOccupation)
                    .eventLabel("Occupation")
                    .optional(ClaimantOtherType::getClaimantEmployedFrom)
                    .eventLabel("Employed from")
                    .optional(ClaimantOtherType::getClaimantEmployedCurrently)
                    .eventLabel("Is the employment continuing?")
                    .optional(ClaimantOtherType::getClaimantEmployedTo)
                    .eventLabel("Employed to")
                    .optional(ClaimantOtherType::getClaimantEmployedNoticePeriod)
                    .eventLabel("Enter the notice period end date if given")
                    .optional(ClaimantOtherType::getClaimantDisabled)
                    .eventLabel("Are there any disabilities or special requirements?")
                    .mandatory(ClaimantOtherType::getClaimantDisabledDetails)
                    .eventLabel("Please provide details")
                    .optional(ClaimantOtherType::getClaimantNoticePeriod)
                    .eventLabel("Notice Period")
                    .optional(ClaimantOtherType::getClaimantNoticePeriodUnit)
                    .eventLabel("Notice Weeks or Months")
                    .optional(ClaimantOtherType::getClaimantNoticePeriodDuration)
                    .eventLabel("Notice Period Duration")
                    .optional(ClaimantOtherType::getClaimantAverageWeeklyHours)
                    .eventLabel("Average weekly hours")
                    .optional(ClaimantOtherType::getClaimantPayBeforeTax)
                    .eventLabel("Pay before tax")
                    .optional(ClaimantOtherType::getClaimantPayAfterTax)
                    .eventLabel("Pay after tax")
                    .optional(ClaimantOtherType::getClaimantPayCycle)
                    .eventLabel("Weekly, monthly or annual pay")
                    .optional(ClaimantOtherType::getClaimantPensionContribution)
                    .eventLabel("Pension Scheme")
                    .optional(ClaimantOtherType::getClaimantPensionWeeklyContribution)
                    .eventLabel("Pension Contribution")
                    .optional(ClaimantOtherType::getClaimantBenefits)
                    .eventLabel("Employee Benefits")
                    .optional(ClaimantOtherType::getClaimantBenefitsDetail)
                    .eventLabel("Employee Benefits Details").done();
    }
}
