package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.types.ClaimantHearingPreference;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 6} of event {@code amendClaimantDetails}.
 */
public final class AmendClaimantDetailsPage6 {
    private AmendClaimantDetailsPage6() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("6");
        fields.complex(CaseData::getClaimantHearingPreference)
                    .optional(ClaimantHearingPreference::getHearingPreferences)
                    .eventLabel("What are the claimant's hearing preferences")
                    .mandatory(ClaimantHearingPreference::getHearingAssistance)
                    .eventLabel("Why is the claimant unable to take part in video or phone hearings")
                    .optional(ClaimantHearingPreference::getClaimantHearingPanelPreference)
                    .eventLabel("Hearing panel preference")
                    .mandatory(ClaimantHearingPreference::getClaimantHearingPanelPreferenceWhy)
                    .eventLabel("Reason for hearing panel preference")
                    .optional(ClaimantHearingPreference::getReasonableAdjustments)
                    .eventLabel("Is there a physical, mental or learning disability or long term health condition which means support during the case is needed?")
                    .mandatory(ClaimantHearingPreference::getReasonableAdjustmentsDetail)
                    .eventLabel("Support requested")
                    .optional(ClaimantHearingPreference::getContactLanguage)
                    .eventLabel("Contact Language")
                    .optional(ClaimantHearingPreference::getHearingLanguage)
                    .eventLabel("Hearing Language").done();
    }
}
