package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 14} of event {@code claimantTSE}.
 */
public final class ClaimantTSEPage14 {
    private ClaimantTSEPage14() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("14");
        fields.pageLabel("Withdraw all or part of claim");
        fields.showCondition("claimantTseSelectApplication=\"Withdraw all or part of claim\"");
        fields.readonly(CaseData::getClaimantTseGuidanceLabel13)
                    .publish(false);
        fields.optional(CaseData::getClaimantTseDocument13)
                    .publish(false);
        fields.optional(CaseData::getClaimantTseTextBox13)
                    .publish(false);
    }
}
