package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 8} of event {@code claimantTSE}.
 */
public final class ClaimantTSEPage8 {
    private ClaimantTSEPage8() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("8");
        fields.pageLabel("Postpone a hearing");
        fields.showCondition("claimantTseSelectApplication=\"Postpone a hearing\"");
        fields.readonly(CaseData::getClaimantTseGuidanceLabel7)
                    .publish(false);
        fields.optional(CaseData::getClaimantTseDocument7)
                    .publish(false);
        fields.optional(CaseData::getClaimantTseTextBox7)
                    .publish(false);
    }
}
