package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 12} of event {@code claimantTSE}.
 */
public final class ClaimantTSEPage12 {
    private ClaimantTSEPage12() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("12");
        fields.pageLabel("Strike out all or part of the response");
        fields.showCondition("claimantTseSelectApplication=\"Strike out all or part of the response\"");
        fields.readonly(CaseData::getClaimantTseGuidanceLabel11)
                    .publish(false);
        fields.optional(CaseData::getClaimantTseDocument11)
                    .publish(false);
        fields.optional(CaseData::getClaimantTseTextBox11)
                    .publish(false);
    }
}
