package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 10} of event {@code claimantTSE}.
 */
public final class ClaimantTSEPage10 {
    private ClaimantTSEPage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("10");
        fields.pageLabel("Respondent not complied");
        fields.showCondition("claimantTseSelectApplication=\"Respondent not complied\"");
        fields.readonly(CaseData::getClaimantTseGuidanceLabel9)
                    .publish(false);
        fields.optional(CaseData::getClaimantTseDocument9)
                    .publish(false);
        fields.optional(CaseData::getClaimantTseTextBox9)
                    .publish(false);
    }
}
