package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code closeReferral}.
 */
public final class CloseReferralPage2 {
    private CloseReferralPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.pageLabel("Close referral");
        fields.readonly(CaseData::getCloseReferralHearingDetails)
                    .fieldShowCondition("closeReferralHearingDetailsLabel=\"dummy\"")
                    .publish(false);
        fields.readonly(CaseData::getCloseReferralHearingDetailsLabel)
                    .publish(false);
        fields.mandatory(CaseData::getConfirmCloseReferral)
                    .publish(false);
        fields.optional(CaseData::getCloseReferralGeneralNotes)
                    .publish(false);
    }
}
