package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code et1ReppedCreateCase}.
 */
public final class Et1ReppedCreateCasePage1 {
    private Et1ReppedCreateCasePage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.pageLabel("Claimant's work location");
        fields.readonly(CaseData::getEt1ReppedTriageLabel);
        fields.complex(CaseData::getEt1ReppedTriageAddress).done();
        fields.readonly(CaseData::getEt1ReppedTriageYesNo)
                    .fieldShowCondition("et1ReppedTriageAddress=\"dummy\"");
    }
}
