package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 13} of event {@code et1SectionTwo}.
 */
public final class Et1SectionTwoPage13 {
    private Et1SectionTwoPage13() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("13");
        fields.pageLabel("Respondent Name");
        fields.readonly(CaseData::getRespondentNamePreamble);
        fields.mandatory(CaseData::getRespondentType);
        fields.mandatory(CaseData::getRespondentOrganisationName)
                    .fieldShowCondition("respondentType = \"Organisation\"");
        fields.mandatory(CaseData::getRespondentFirstName)
                    .fieldShowCondition("respondentType = \"Individual\"");
        fields.mandatory(CaseData::getRespondentLastName)
                    .fieldShowCondition("respondentType = \"Individual\"");
        fields.readonly(CaseData::getRespondentEndLabel);
    }
}
