package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 4} of event {@code et1SectionThree}.
 */
public final class Et1SectionThreePage4 {
    private Et1SectionThreePage4() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("4");
        fields.pageLabel("What does the claimant want if their claim is successful? (Optional)");
        fields.optional(CaseData::getClaimSuccessful);
        fields.optional(CaseData::getCompensationDetails)
                    .fieldShowCondition("claimSuccessful CONTAINS \"compensation\"");
        fields.optional(CaseData::getTribunalRecommendationDetails)
                    .fieldShowCondition("claimSuccessful CONTAINS \"tribunal\"");
    }
}
