package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code et1SectionTwo}.
 */
public final class Et1SectionTwoPage1 {
    private Et1SectionTwoPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.pageLabel("Section 2 - Employment and respondent details");
        fields.readonly(CaseData::getEt1Section2PreambleLabel);
    }
}
