package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 7} of event {@code et1SectionTwo}.
 */
public final class Et1SectionTwoPage7 {
    private Et1SectionTwoPage7() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("7");
        fields.pageLabel("Did the claimant work or get paid for a notice period? (Optional)");
        fields.showCondition("claimantStillWorking CONTAINS \"No longer working\"");
        fields.optional(CaseData::getClaimantNoLongerWorkingQuestion);
        fields.optional(CaseData::getClaimantNoLongerWorking)
                    .fieldShowCondition("claimantNoLongerWorkingQuestion CONTAINS \"Worked\" OR claimantNoLongerWorkingQuestion CONTAINS \"Paid\"");
        fields.optional(CaseData::getClaimantNoLongerWorkingMonths)
                    .fieldShowCondition("claimantNoLongerWorking CONTAINS \"Months\"");
        fields.optional(CaseData::getClaimantNoLongerWorkingWeeks)
                    .fieldShowCondition("claimantNoLongerWorking CONTAINS \"Weeks\"");
    }
}
