package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 11} of event {@code et1Vetting}.
 */
public final class Et1VettingPage11 {
    private Et1VettingPage11() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("11");
        fields.pageLabel("Possible referral to Regional Employment Judge or Vice-President");
        fields.readonly(CaseData::getEt1REJOrVPReferralLine1);
        fields.optional(CaseData::getReferralToREJOrVPList);
        fields.mandatory(CaseData::getVexatiousLitigantOrderTextArea)
                    .fieldShowCondition("referralToREJOrVPList CONTAINS \"vexatiousLitigantOrder\"");
        fields.mandatory(CaseData::getAnationalSecurityIssueTextArea)
                    .fieldShowCondition("referralToREJOrVPList CONTAINS \"aNationalSecurityIssue\"");
        fields.mandatory(CaseData::getNationalMultipleOrPresidentialOrderTextArea)
                    .fieldShowCondition("referralToREJOrVPList CONTAINS \"nationalMultipleOrPresidentialOrder\"");
        fields.mandatory(CaseData::getTransferToOtherRegionTextArea)
                    .fieldShowCondition("referralToREJOrVPList CONTAINS \"transferToOtherRegion\"");
        fields.mandatory(CaseData::getServiceAbroadTextArea)
                    .fieldShowCondition("referralToREJOrVPList CONTAINS \"serviceAbroad\"");
        fields.mandatory(CaseData::getAsensitiveIssueTextArea)
                    .fieldShowCondition("referralToREJOrVPList CONTAINS \"aSensitiveIssue\"");
        fields.mandatory(CaseData::getAnyPotentialConflictTextArea)
                    .fieldShowCondition("referralToREJOrVPList CONTAINS \"anyPotentialConflict\"");
        fields.mandatory(CaseData::getAnotherReasonREJOrVPTextArea)
                    .fieldShowCondition("referralToREJOrVPList CONTAINS \"anotherReasonREJOrVP\"");
        fields.readonly(CaseData::getEt1REJOrVPReferralLine2);
        fields.optional(CaseData::getEt1REJOrVPReferralGeneralNotes);
    }
}
