package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code et1Vetting}.
 */
public final class Et1VettingPage2 {
    private Et1VettingPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.pageLabel("Minimum required information");
        fields.readonly(CaseData::getEt1VettingContactDetailsLabel);
        fields.readonly(CaseData::getEt1VettingClaimantDetailsMarkUp)
                    .fieldShowCondition("et1VettingContactDetailsLabel=\"dummy\"");
        fields.readonly(CaseData::getEt1VettingClaimantDetailsLabel);
        fields.readonly(CaseData::getEt1VettingRespondentDetailsMarkUp)
                    .fieldShowCondition("et1VettingContactDetailsLabel=\"dummy\"");
        fields.readonly(CaseData::getEt1VettingRespondentDetailsLabel);
        fields.mandatory(CaseData::getEt1VettingCanServeClaimYesOrNo);
        fields.mandatory(CaseData::getEt1VettingCanServeClaimNoReason)
                    .fieldShowCondition("et1VettingCanServeClaimYesOrNo=\"No\"");
        fields.optional(CaseData::getEt1VettingCanServeClaimGeneralNote);
    }
}
