package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 8} of event {@code et1Vetting}.
 */
public final class Et1VettingPage8 {
    private Et1VettingPage8() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("8");
        fields.pageLabel("Case details");
        fields.readonly(CaseData::getEt1AddressDetails)
                    .fieldShowCondition("horizontalLine=\"dummy\"");
        fields.readonly(CaseData::getEt1AddressDetailsLabel);
        fields.mandatory(CaseData::getEt1SuggestHearingVenue);
        fields.readonly(CaseData::getEt1TribunalRegion)
                    .fieldShowCondition("horizontalLine=\"dummy\"");
        fields.readonly(CaseData::getEt1TribunalRegionLabel)
                    .fieldShowCondition("et1SuggestHearingVenue=\"Yes\"");
        fields.mandatory(CaseData::getEt1HearingVenues)
                    .fieldShowCondition("et1SuggestHearingVenue=\"Yes\"");
        fields.optional(CaseData::getEt1HearingVenueGeneralNotes);
    }
}
