package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 4} of event {@code et1Vetting}.
 */
public final class Et1VettingPage4 {
    private Et1VettingPage4() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("4");
        fields.readonly(CaseData::getHorizontalLine2);
        fields.optional(CaseData::getSubstantiveDefectsList);
        fields.mandatory(CaseData::getRule121aTextArea)
                    .fieldShowCondition("substantiveDefectsList CONTAINS \"rule121a\"");
        fields.mandatory(CaseData::getRule121bTextArea)
                    .fieldShowCondition("substantiveDefectsList CONTAINS \"rule121b\"");
        fields.mandatory(CaseData::getRule121cTextArea)
                    .fieldShowCondition("substantiveDefectsList CONTAINS \"rule121c\"");
        fields.mandatory(CaseData::getRule121dTextArea)
                    .fieldShowCondition("substantiveDefectsList CONTAINS \"rule121d\"");
        fields.mandatory(CaseData::getRule121daTextArea)
                    .fieldShowCondition("substantiveDefectsList CONTAINS \"rule121 da\"");
        fields.mandatory(CaseData::getRule121eTextArea)
                    .fieldShowCondition("substantiveDefectsList CONTAINS \"rule121e\"");
        fields.mandatory(CaseData::getRule121fTextArea)
                    .fieldShowCondition("substantiveDefectsList CONTAINS \"rule121f\"");
        fields.readonly(CaseData::getHorizontalLine3);
        fields.optional(CaseData::getEt1SubstantiveDefectsGeneralNotes);
    }
}
