package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 10} of event {@code et1Vetting}.
 */
public final class Et1VettingPage10 {
    private Et1VettingPage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("10");
        fields.pageLabel("Possible referral to a judge or legal officer");
        fields.readonly(CaseData::getEt1JudgeReferralLine1);
        fields.optional(CaseData::getReferralToJudgeOrLOList);
        fields.mandatory(CaseData::getAclaimOfInterimReliefTextArea)
                    .fieldShowCondition("referralToJudgeOrLOList CONTAINS \"aClaimOfInterimRelief\"");
        fields.mandatory(CaseData::getAstatutoryAppealTextArea)
                    .fieldShowCondition("referralToJudgeOrLOList CONTAINS \"aStatutoryAppeal\"");
        fields.mandatory(CaseData::getAnAllegationOfCommissionOfSexualOffenceTextArea)
                    .fieldShowCondition("referralToJudgeOrLOList CONTAINS \"anAllegationOfCommissionOfSexualOffence\"");
        fields.mandatory(CaseData::getInsolvencyTextArea)
                    .fieldShowCondition("referralToJudgeOrLOList CONTAINS \"insolvency\"");
        fields.mandatory(CaseData::getJurisdictionsUnclearTextArea)
                    .fieldShowCondition("referralToJudgeOrLOList CONTAINS \"jurisdictionsUnclear\"");
        fields.mandatory(CaseData::getLengthOfServiceTextArea)
                    .fieldShowCondition("referralToJudgeOrLOList CONTAINS \"lengthOfService\"");
        fields.mandatory(CaseData::getPotentiallyLinkedCasesInTheEcmTextArea)
                    .fieldShowCondition("referralToJudgeOrLOList CONTAINS \"potentiallyLinkedCasesInTheEcm\"");
        fields.mandatory(CaseData::getRule50IssuesTextArea)
                    .fieldShowCondition("referralToJudgeOrLOList CONTAINS \"rule50Issues\"");
        fields.mandatory(CaseData::getAnotherReasonForJudicialReferralTextArea)
                    .fieldShowCondition("referralToJudgeOrLOList CONTAINS \"anotherReasonForJudicialReferral\"");
        fields.readonly(CaseData::getEt1JudgeReferralLine2);
        fields.optional(CaseData::getEt1JudgeReferralGeneralNotes);
    }
}
