package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 5} of event {@code et1Vetting}.
 */
public final class Et1VettingPage5 {
    private Et1VettingPage5() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("5");
        fields.pageLabel("Case details");
        fields.readonly(CaseData::getExistingJurisdictionCodes)
                    .fieldShowCondition("et1SubstantiveDefectsGeneralNotes=\"dummy\"");
        fields.readonly(CaseData::getExistingJurisdictionCodesLabel);
        fields.mandatory(CaseData::getAreTheseCodesCorrect);
        fields.mandatory(CaseData::getCodesCorrectGiveDetails)
                    .fieldShowCondition("areTheseCodesCorrect=\"No\"");
        fields.optional(CaseData::getVettingJurisdictionCodeCollection);
        fields.optional(CaseData::getEt1JurisdictionCodeGeneralNotes);
        fields.readonly(CaseData::getTrackType)
                    .fieldShowCondition("areTheseCodesCorrect=\"dummy\"");
    }
}
