package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 7} of event {@code et1Vetting}.
 */
public final class Et1VettingPage7 {
    private Et1VettingPage7() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("7");
        fields.pageLabel("Case details");
        fields.mandatory(CaseData::getTribunalAndOfficeLocation)
                    .fieldShowCondition("horizontalLine=\"dummy\"");
        fields.readonly(CaseData::getTribunalAndOfficeLocationLabel);
        fields.mandatory(CaseData::getIsLocationCorrect);
        fields.mandatory(CaseData::getRegionalOffice)
                    .fieldShowCondition("horizontalLine=\"dummy\"");
        fields.readonly(CaseData::getRegionalOfficeLabel)
                    .fieldShowCondition("isLocationCorrect=\"No\"");
        fields.mandatory(CaseData::getRegionalOfficeList)
                    .fieldShowCondition("isLocationCorrect=\"No\"");
        fields.mandatory(CaseData::getWhyChangeOffice)
                    .fieldShowCondition("isLocationCorrect=\"No\"");
        fields.optional(CaseData::getEt1LocationGeneralNotes);
    }
}
