package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 12} of event {@code et1Vetting}.
 */
public final class Et1VettingPage12 {
    private Et1VettingPage12() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("12");
        fields.pageLabel("Other factors");
        fields.readonly(CaseData::getEt1OtherReferralLine1);
        fields.optional(CaseData::getOtherReferralList);
        fields.mandatory(CaseData::getClaimOutOfTimeTextArea)
                    .fieldShowCondition("otherReferralList CONTAINS \"claimOutOfTime\"");
        fields.mandatory(CaseData::getMultipleClaimTextArea)
                    .fieldShowCondition("otherReferralList CONTAINS \"multipleClaim\"");
        fields.mandatory(CaseData::getEmploymentStatusIssuesTextArea)
                    .fieldShowCondition("otherReferralList CONTAINS \"employmentStatusIssues\"");
        fields.mandatory(CaseData::getPidJurisdictionRegulatorTextArea)
                    .fieldShowCondition("otherReferralList CONTAINS \"pidJurisdictionRegulator\"");
        fields.mandatory(CaseData::getVideoHearingPreferenceTextArea)
                    .fieldShowCondition("otherReferralList CONTAINS \"videoHearingPreference\"");
        fields.mandatory(CaseData::getRule50IssuesForOtherReferralTextArea)
                    .fieldShowCondition("otherReferralList CONTAINS \"rule50IssuesOtherFactors\"");
        fields.mandatory(CaseData::getAnotherReasonForOtherReferralTextArea)
                    .fieldShowCondition("otherReferralList CONTAINS \"otherRelevantFactors\"");
        fields.readonly(CaseData::getEt1OtherReferralLine2);
        fields.optional(CaseData::getEt1OtherReferralGeneralNotes);
    }
}
