package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code et3Notification}.
 */
public final class Et3NotificationPage2 {
    private Et3NotificationPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.pageLabel("Who are you sending this document to?");
        fields.showCondition("et3OtherTypeDocumentName != \"\"");
        fields.readonly(CaseData::getHorizontalLine4);
        fields.mandatory(CaseData::getEt3OtherTypeDocumentName)
                    .fieldShowCondition("horizontalLine4=\"dummy\"");
        fields.readonly(CaseData::getEt3OtherTypeDocumentNameLabel);
        fields.readonly(CaseData::getEt3SelectAllThatApply);
        fields.mandatory(CaseData::getEt3NotificationDocRecipient);
    }
}
