package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 7} of event {@code et3Response}.
 */
public final class Et3ResponsePage7 {
    private Et3ResponsePage7() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("7");
        fields.pageLabel("Hearing format");
        fields.readonly(CaseData::getEt3ResponseHearingPreamble)
                    .publish(false);
        fields.mandatory(CaseData::getEt3ResponseHearingRepresentative)
                    .publish(false);
        fields.mandatory(CaseData::getEt3ResponseHearingRespondent)
                    .publish(false);
    }
}
