package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 7} of event {@code et3ResponseDetails}.
 */
public final class Et3ResponseDetailsPage7 {
    private Et3ResponseDetailsPage7() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("7");
        fields.pageLabel("Provide the background and details of your Employer's Contract Claim");
        fields.showCondition("et3ResponseEmployerClaim=\"Yes\"");
        fields.readonly(CaseData::getEt3ResponseEmployerClaimDetailsPreamble);
        fields.mandatory(CaseData::getEt3ResponseEmployerClaimDetails);
        fields.mandatory(CaseData::getEt3ResponseEmployerClaimDocument);
    }
}
