package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 6} of event {@code et3Response}.
 */
public final class Et3ResponsePage6 {
    private Et3ResponsePage6() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("6");
        fields.pageLabel("Your information (as the representative)");
        fields.readonly(CaseData::getEt3RepresentativeInfoFirstWords)
                    .publish(false);
        fields.optional(CaseData::getEt3ResponseContactPreference)
                    .publish(false);
        fields.mandatory(CaseData::getEt3ResponseContactReason)
                    .fieldShowCondition("et3ResponseContactPreference=\"Post\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.optional(CaseData::getEt3ResponseContactLanguage)
                    .publish(false);
        fields.optional(CaseData::getEt3ResponsePhone)
                    .publish(false);
        fields.optional(CaseData::getEt3ResponseAddress)
                    .publish(false);
        fields.optional(CaseData::getEt3ResponseReference)
                    .publish(false);
    }
}
