package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code et3ResponseDetails}.
 */
public final class Et3ResponseDetailsPage3 {
    private Et3ResponseDetailsPage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("3");
        fields.pageLabel("Do you agree with the details given by the claimant about early conciliation with Acas?");
        fields.mandatory(CaseData::getEt3ResponseAcasAgree);
        fields.optional(CaseData::getEt3ResponseAcasAgreeReason)
                    .fieldShowCondition("et3ResponseAcasAgree=\"No\"")
                    .retainHiddenValue();
    }
}
