package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code et3Response}.
 */
public final class Et3ResponsePage1 {
    private Et3ResponsePage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.pageLabel("ET3 - Response to Employment tribunal claim (ET1)");
        fields.optional(CaseData::getEt3ResponseShowInset)
                    .fieldShowCondition("et3StartPagePreamble=\"dummy\"")
                    .publish(false);
        fields.readonly(CaseData::getEt3StartPagePreamble)
                    .publish(false);
        fields.readonly(CaseData::getEt3StartPageInset)
                    .fieldShowCondition("et3ResponseShowInset=\"Yes\"")
                    .publish(false);
        fields.readonly(CaseData::getEt3StartPageMainBody)
                    .publish(false);
    }
}
