package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.DocumentUpload;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 5} of event {@code et3ResponseDetails}.
 */
public final class Et3ResponseDetailsPage5 {
    private Et3ResponseDetailsPage5() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("5");
        fields.pageLabel("Explain why the respondent contests the claim");
        fields.showCondition("et3ResponseRespondentContestClaim=\"Yes\"");
        fields.readonly(CaseData::getEt3ResponseContestClaimPreamble);
        fields.complex(CaseData::getEt3ResponseContestClaimDocument).done();
        fields.complex(CaseData::getEt3ResponseContestClaimDocument, DocumentUpload.class)
                    .optional(DocumentUpload::getUploadedDocument)
                    .eventLabel("Upload a document to your response").done();
        fields.optional(CaseData::getEt3ResponseContestClaimDetails);
    }
}
