package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code et3Response}.
 */
public final class Et3ResponsePage3 {
    private Et3ResponsePage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("3");
        fields.pageLabel("Is this the correct claimant for the claim you're responding to?");
        fields.readonly(CaseData::getEt3ResponseClaimantName)
                    .fieldShowCondition("et3ResponseClaimantNameLabel=\"dummy\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.readonly(CaseData::getEt3ResponseClaimantNameLabel)
                    .publish(false);
        fields.mandatory(CaseData::getEt3ResponseIsClaimantNameCorrect)
                    .publish(false);
        fields.mandatory(CaseData::getEt3ResponseClaimantNameCorrection)
                    .fieldShowCondition("et3ResponseIsClaimantNameCorrect=\"No\"")
                    .retainHiddenValue()
                    .publish(false);
    }
}
