package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 14} of event {@code et3Vetting}.
 */
public final class Et3VettingPage14 {
    private Et3VettingPage14() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("14");
        fields.pageLabel("Page Title");
        fields.showCondition("et3IsThereAnEt3Response=\"Yes\"");
        fields.readonly(CaseData::getEt3HearingDetails)
                    .fieldShowCondition("et3HearingDetailsLabel=\"dummy\"")
                    .publish(false);
        fields.readonly(CaseData::getEt3HearingDetailsLabel)
                    .publish(false);
        fields.mandatory(CaseData::getEt3IsCaseListedForHearing)
                    .publish(false);
        fields.optional(CaseData::getEt3IsCaseListedForHearingDetails)
                    .fieldShowCondition("et3IsCaseListedForHearing=\"No\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.optional(CaseData::getEt3GeneralNotesCaseListed)
                    .publish(false);
    }
}
