package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 11} of event {@code et3Vetting}.
 */
public final class Et3VettingPage11 {
    private Et3VettingPage11() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("11");
        fields.pageLabel("Minimum required information");
        fields.showCondition("et3IsThereAnEt3Response=\"Yes\" AND et3DoWeHaveRespondentsAddress=\"Yes\"");
        fields.readonly(CaseData::getEt3ContactDetailsAddressMismatchLabel)
                    .publish(false);
        fields.readonly(CaseData::getEt3NameAddressRespondentAddressMismatchLabel)
                    .publish(false);
        fields.mandatory(CaseData::getEt3DoesRespondentsAddressMatch)
                    .publish(false);
        fields.mandatory(CaseData::getEt3RespondentAddressMismatchDetails)
                    .fieldShowCondition("et3DoesRespondentsAddressMatch=\"No\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.optional(CaseData::getEt3GeneralNotesAddressMatch)
                    .publish(false);
    }
}
