package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 16} of event {@code et3Vetting}.
 */
public final class Et3VettingPage16 {
    private Et3VettingPage16() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("16");
        fields.pageLabel("Issues identified");
        fields.showCondition("et3IsThereAnEt3Response=\"Yes\"");
        fields.mandatory(CaseData::getEt3Rule26)
                    .publish(false);
        fields.mandatory(CaseData::getEt3Rule26Details)
                    .fieldShowCondition("et3Rule26=\"Yes\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.optional(CaseData::getEt3SuggestedIssues)
                    .publish(false);
        fields.mandatory(CaseData::getEt3SuggestedIssuesStrikeOut)
                    .fieldShowCondition("et3SuggestedIssues CONTAINS \"Applications for strike out or deposit\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.mandatory(CaseData::getEt3SuggestedIssueInterpreters)
                    .fieldShowCondition("et3SuggestedIssues CONTAINS \"Interpreters\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.mandatory(CaseData::getEt3SuggestedIssueJurisdictional)
                    .fieldShowCondition("et3SuggestedIssues CONTAINS \"Jurisdictional issues\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.mandatory(CaseData::getEt3SuggestedIssueAdjustments)
                    .fieldShowCondition("et3SuggestedIssues CONTAINS \"Request for adjustments\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.mandatory(CaseData::getEt3SuggestedIssueRule50)
                    .fieldShowCondition("et3SuggestedIssues CONTAINS \"Rule 50\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.mandatory(CaseData::getEt3SuggestedIssueTimePoints)
                    .fieldShowCondition("et3SuggestedIssues CONTAINS \"Time points\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.optional(CaseData::getEt3GeneralNotesRule26)
                    .publish(false);
    }
}
