package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.ET3Vetting;
import uk.gov.hmcts.et.common.model.ccd.Respondent;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code et3Vetting}.
 */
public final class Et3VettingPage2 {
    private Et3VettingPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.pageLabel("Select Respondent");
        fields.complex(CaseData::getRespondentCollection, false).done()
                    .fieldShowCondition("et3ChooseRespondent=\"dummy\"");
        fields.complex(CaseData::getRespondentCollection, Respondent.class)
                    .complex(Respondent::getEt3Vetting)
                    .optional(ET3Vetting::getEt3ContractClaimSection7)
                    .eventLabel(" ").done()
                    .optional(Respondent::getEt3Vetting)
                    .eventLabel(" ")
                    .complex(Respondent::getEt3Vetting)
                    .optional(ET3Vetting::getEt3IsThereAnEt3Response)
                    .eventLabel(" ").done().done();
        fields.mandatory(CaseData::getEt3ChooseRespondent)
                    .publish(false);
    }
}
