package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 13} of event {@code et3Vetting}.
 */
public final class Et3VettingPage13 {
    private Et3VettingPage13() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("13");
        fields.pageLabel("Minimum required information");
        fields.showCondition("et3IsThereAnEt3Response=\"Yes\"");
        fields.mandatory(CaseData::getEt3ContractClaimSection7)
                    .publish(false);
        fields.optional(CaseData::getEt3ContractClaimSection7Details)
                    .fieldShowCondition("et3ContractClaimSection7=\"Yes\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.optional(CaseData::getEt3GeneralNotesContractClaimSection7)
                    .publish(false);
    }
}
