package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code et3Vetting}.
 */
public final class Et3VettingPage3 {
    private Et3VettingPage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("3");
        fields.pageLabel("Minimum required information");
        fields.optionalNoSummary(CaseData::getNextListedDate)
                    .fieldShowCondition("et3DateLabel=\"dummy\"");
        fields.readonly(CaseData::getEt3Date)
                    .fieldShowCondition("et3DateLabel=\"dummy\"")
                    .publish(false);
        fields.readonly(CaseData::getEt3DateLabel)
                    .publish(false);
        fields.mandatory(CaseData::getEt3IsThereAnEt3Response)
                    .publish(false);
        fields.optional(CaseData::getEt3NoEt3Response)
                    .fieldShowCondition("et3IsThereAnEt3Response=\"No\"")
                    .publish(false);
        fields.optional(CaseData::getEt3GeneralNotes)
                    .publish(false);
    }
}
