package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 15} of event {@code et3Vetting}.
 */
public final class Et3VettingPage15 {
    private Et3VettingPage15() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("15");
        fields.pageLabel("Page Title");
        fields.showCondition("et3IsThereAnEt3Response=\"Yes\"");
        fields.readonly(CaseData::getEt3TribunalLocation)
                    .fieldShowCondition("et3TribunalLocationLabel=\"dummy\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.readonly(CaseData::getEt3TribunalLocationLabel)
                    .publish(false);
        fields.mandatory(CaseData::getEt3IsThisLocationCorrect)
                    .publish(false);
        fields.mandatory(CaseData::getEt3RegionalOffice)
                    .fieldShowCondition("et3IsThisLocationCorrect=\"No - suggest another location\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.mandatory(CaseData::getEt3WhyWeShouldChangeTheOffice)
                    .fieldShowCondition("et3IsThisLocationCorrect=\"No - suggest another location\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.optional(CaseData::getEt3GeneralNotesTransferApplication)
                    .fieldShowCondition("et3IsThisLocationCorrect=\"Yes\"")
                    .publish(false);
    }
}
