package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.IcDocumentUpload;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 4} of event {@code initialConsideration}.
 */
public final class InitialConsiderationPage4 {
    private InitialConsiderationPage4() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("4");
        fields.showCondition("etICCanProceed=\"No\"");
        fields.readonlyNoSummary(CaseData::getInitialConsiderationBeforeYouStartLabel4)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICFurtherInfoRespondentLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICFurtherInfoHearingLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICFurtherInfoJurisdictionCodesLabel)
                    .publish(false);
        fields.optional(CaseData::getEtICFurtherInformation)
                    .publish(false);
        fields.mandatory(CaseData::getEtICFurtherInfoAnswers)
                    .fieldShowCondition("etICFurtherInformation CONTAINS \"Further information required\"")
                    .publish(false);
        fields.mandatory(CaseData::getEtInitialConsiderationRule27)
                    .fieldShowCondition("etICFurtherInformation CONTAINS \"Issue Rule 27 Notice and order\"");
        fields.mandatory(CaseData::getEtInitialConsiderationRule28)
                    .fieldShowCondition("etICFurtherInformation CONTAINS \"Issue Rule 28 Notice and order\"");
        fields.readonlyNoSummary(CaseData::getEtICFurtherInformationHearingAnyOtherDirectionsLabel)
                    .publish(false);
        fields.optional(CaseData::getEtICFurtherInformationHearingAnyOtherDirections)
                    .publish(false);
        fields.complex(CaseData::getIcDocumentCollection3).done();
        fields.complex(CaseData::getIcDocumentCollection3, IcDocumentUpload.class)
                    .mandatory(IcDocumentUpload::getUploadedDocument)
                    .optional(IcDocumentUpload::getShortDescription).done();
    }
}
