package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.EtICHearingNotListedListForFinalHearing;
import uk.gov.hmcts.et.common.model.ccd.EtICHearingNotListedListForFinalHearingUpdated;
import uk.gov.hmcts.et.common.model.ccd.EtICHearingNotListedListForPrelimHearing;
import uk.gov.hmcts.et.common.model.ccd.EtICHearingNotListedListForPrelimHearingUpdated;
import uk.gov.hmcts.et.common.model.ccd.EtICHearingNotListedSeekComments;
import uk.gov.hmcts.et.common.model.ccd.EtICHearingNotListedUDLHearing;
import uk.gov.hmcts.et.common.model.ccd.IcDocumentUpload;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code initialConsideration}.
 */
public final class InitialConsiderationPage2 {
    private InitialConsiderationPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.pageLabel("Rule 27");
        fields.showCondition("etICCanProceed=\"Yes\" AND etICHearingAlreadyListed=\"No\"");
        fields.readonlyNoSummary(CaseData::getInitialConsiderationBeforeYouStartLabel2)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICHearingNotListedRespondentLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICHearingNotListedHearingLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getNotListedHearingPartiesPanelPreferenceLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getNotListedHearingPartiesHearingFormatLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICHearingNotListedJurCodesLabel)
                    .publish(false);
        fields.mandatory(CaseData::getEtICHearingNotListedList)
                    .fieldShowCondition("etICCanProceed=\"dummy\"");
        fields.readonly(CaseData::getEtICHearingNotListedListUpdatedDividerHrLabel);
        fields.mandatory(CaseData::getEtICHearingNotListedListUpdated);
        fields.complex(CaseData::getEtICHearingNotListedSeekComments)
                    .mandatory(EtICHearingNotListedSeekComments::getEtICTypeOfCvpHearing)
                    .eventLabel("Type of Video hearing")
                    .mandatory(EtICHearingNotListedSeekComments::getEtICFinalHearingDetails)
                    .eventLabel("Give details of final hearing")
                    .mandatory(EtICHearingNotListedSeekComments::getEtICPrelimHearingDetails)
                    .eventLabel("Give details of preliminary hearing")
                    .mandatory(EtICHearingNotListedSeekComments::getEtICPrelimHearingYesNo)
                    .eventLabel("Should the case be listed for a private preliminary hearing?").done()
                    .fieldShowCondition("etICHearingNotListedList=\"dummy\"");
        fields.complex(CaseData::getEtICHearingNotListedListForPrelimHearing)
                    .mandatory(EtICHearingNotListedListForPrelimHearing::getEtICTypeOfPreliminaryHearing)
                    .eventLabel("Type of preliminary hearing")
                    .noHintText()
                    .mandatory(EtICHearingNotListedListForPrelimHearing::getEtICPurposeOfPreliminaryHearing)
                    .eventLabel("Purpose of preliminary hearing")
                    .noHintText()
                    .mandatory(EtICHearingNotListedListForPrelimHearing::getEtICGiveDetailsOfHearingNotice)
                    .eventLabel("Give details of hearing notice")
                    .mandatory(EtICHearingNotListedListForPrelimHearing::getPrelimHearingLengthNumType)
                    .eventLabel("Days, Hours or Minutes").done()
                    .fieldShowCondition("etICHearingNotListedList=\"dummy\"");
        fields.complex(CaseData::getEtICHearingNotListedListForPrelimHearingUpdated)
                    .mandatory(EtICHearingNotListedListForPrelimHearingUpdated::getEtICTypeOfPreliminaryHearingV2)
                    .eventLabel("Type of preliminary hearing")
                    .noHintText()
                    .mandatory(EtICHearingNotListedListForPrelimHearingUpdated::getEtICPurposeOfPreliminaryHearingV2)
                    .eventLabel("Purpose of preliminary hearing")
                    .noHintText()
                    .mandatory(EtICHearingNotListedListForPrelimHearingUpdated::getEtICGiveDetailsOfHearingNoticeV2)
                    .eventLabel("Give details of hearing notice")
                    .mandatory(EtICHearingNotListedListForPrelimHearingUpdated::getEtICLengthOfPrelimHearingV2)
                    .eventLabel("Length of hearing")
                    .mandatory(EtICHearingNotListedListForPrelimHearingUpdated::getPrelimHearingLengthNumTypeV2)
                    .eventLabel("Days, Hours or Minutes")
                    .mandatory(EtICHearingNotListedListForPrelimHearingUpdated::getEtICIsPreliminaryHearingWithMembersV2)
                    .eventLabel("Do you consider this preliminary hearing should be listed with members?")
                    .mandatory(EtICHearingNotListedListForPrelimHearingUpdated::getEtICIsPreliminaryHearingWithMembersReasonV2)
                    .eventLabel("Give reasons for requiring members").done()
                    .fieldShowCondition("etICHearingNotListedListUpdated CONTAINS \"List for preliminary hearing\"");
        fields.complex(CaseData::getEtICHearingNotListedListForFinalHearing)
                    .mandatory(EtICHearingNotListedListForFinalHearing::getEtICTypeOfFinalHearing)
                    .eventLabel("Type of final hearing")
                    .noHintText()
                    .mandatory(EtICHearingNotListedListForFinalHearing::getEtICLengthOfFinalHearing)
                    .eventLabel("Length of hearing")
                    .mandatory(EtICHearingNotListedListForFinalHearing::getFinalHearingLengthNumType)
                    .eventLabel("Days, Hours or Minutes").done()
                    .fieldShowCondition("etICHearingNotListedList=\"dummy\"");
        fields.complex(CaseData::getEtICHearingNotListedListForFinalHearingUpdated)
                    .mandatory(EtICHearingNotListedListForFinalHearingUpdated::getEtICTypeOfFinalHearingV2)
                    .eventLabel("Type of final hearing")
                    .noHintText()
                    .mandatory(EtICHearingNotListedListForFinalHearingUpdated::getEtICLengthOfFinalHearingV2)
                    .eventLabel("Length of hearing")
                    .mandatory(EtICHearingNotListedListForFinalHearingUpdated::getFinalHearingLengthNumTypeV2)
                    .eventLabel("Days, Hours or Minutes")
                    .mandatory(EtICHearingNotListedListForFinalHearingUpdated::getEtICFinalHearingIsEJSitAlone)
                    .eventLabel("Do you consider this final hearing should be listed judge alone or with members?")
                    .mandatory(EtICHearingNotListedListForFinalHearingUpdated::getEtICFinalHearingIsEJSitAloneReasonYes)
                    .eventLabel("Reasons for JSA")
                    .noHintText()
                    .mandatory(EtICHearingNotListedListForFinalHearingUpdated::getEtICNoLFinalHearingIsEJSitAloneReasonsJsaOther)
                    .eventLabel("Reason for JSA - Other")
                    .mandatory(EtICHearingNotListedListForFinalHearingUpdated::getEtICFinalHearingIsEJSitAloneReasonNo)
                    .eventLabel("Reasons for Members")
                    .noHintText()
                    .mandatory(EtICHearingNotListedListForFinalHearingUpdated::getEtICNoLFinalHearingIsEJSitAloneReasonsMembersOther)
                    .eventLabel("Reason for Members - Other")
                    .optional(EtICHearingNotListedListForFinalHearingUpdated::getEtICFinalHearingIsEJSitAloneFurtherDetails)
                    .eventLabel("Further details").done()
                    .fieldShowCondition("etICHearingNotListedListUpdated CONTAINS \"List for final hearing\"");
        fields.complex(CaseData::getEtICHearingNotListedUDLHearing)
                    .mandatory(EtICHearingNotListedUDLHearing::getEtICEJSitAlone)
                    .eventLabel("EJ sit alone?")
                    .mandatory(EtICHearingNotListedUDLHearing::getEtICUDLGiveReasons)
                    .eventLabel("Give reasons")
                    .noHintText()
                    .mandatory(EtICHearingNotListedUDLHearing::getEtICUDLDisputeOnFacts)
                    .eventLabel("Likelihood of dispute on facts makes full tribunal desirable")
                    .mandatory(EtICHearingNotListedUDLHearing::getEtICUDLLittleOrNoAgreement)
                    .eventLabel("Little or no agreement on facts")
                    .mandatory(EtICHearingNotListedUDLHearing::getEtICUDLIssueOfLawArising)
                    .eventLabel("Likelihood of issue of law arising makes EJSA desirable")
                    .mandatory(EtICHearingNotListedUDLHearing::getEtICUDLViewsOfParties)
                    .eventLabel("Views of parties")
                    .mandatory(EtICHearingNotListedUDLHearing::getEtICUDLNoViewsExpressedByParties)
                    .eventLabel("No views expressed by parties")
                    .mandatory(EtICHearingNotListedUDLHearing::getEtICUDLConcurrentProceedings)
                    .eventLabel("Concurrent proceedings")
                    .mandatory(EtICHearingNotListedUDLHearing::getEtICUDLOther)
                    .eventLabel("Other")
                    .mandatory(EtICHearingNotListedUDLHearing::getEtICUDLHearFormat)
                    .eventLabel("Hearing format")
                    .mandatory(EtICHearingNotListedUDLHearing::getEtICUDLCVPIssue)
                    .eventLabel("Issue standard Video orders when listed")
                    .mandatory(EtICHearingNotListedUDLHearing::getEtICUDLFinalF2FIssue)
                    .eventLabel("Issue standard orders when listed")
                    .mandatory(EtICHearingNotListedUDLHearing::getEtICBUCheckComplianceOrders)
                    .eventLabel("BU to check compliance with orders?").done()
                    .fieldShowCondition("etICHearingNotListedList=\"dummy\"");
        fields.optional(CaseData::getEtICHearingAlreadyListed)
                    .fieldShowCondition("etICCanProceed=\"dummy\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICAnyOtherDirectionsDividerHrLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICHearingNotListedAnyOtherDirectionsLabel)
                    .publish(false);
        fields.optional(CaseData::getEtICHearingNotListedAnyOtherDirections)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICUploadDocDividerHrLabel)
                    .publish(false);
        fields.complex(CaseData::getIcDocumentCollection1).done();
        fields.complex(CaseData::getIcDocumentCollection1, IcDocumentUpload.class)
                    .mandatory(IcDocumentUpload::getUploadedDocument)
                    .optional(IcDocumentUpload::getShortDescription).done();
        fields.readonlyNoSummary(CaseData::getEtICNavigationButtonsDividerHrLabel)
                    .publish(false);
    }
}
