package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code initialConsideration}.
 */
public final class InitialConsiderationPage1 {
    private InitialConsiderationPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.pageLabel("Before you start");
        fields.readonlyNoSummary(CaseData::getInitialConsiderationBeforeYouStart)
                    .fieldShowCondition("initialConsiderationBeforeYouStartLabel=\"dummy\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getInitialConsiderationBeforeYouStartLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtInitialConsiderationRespondent)
                    .fieldShowCondition("etInitialConsiderationRespondentLabel=\"dummy\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtInitialConsiderationRespondentLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtInitialConsiderationHearing)
                    .fieldShowCondition("etInitialConsiderationHearingLabel=\"dummy\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtInitialConsiderationHearingLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtIcPartiesHearingPanelPreferenceHeader)
                    .fieldShowCondition("etIcPartiesHearingPanelPreferenceHeaderLabel=\"dummy\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtIcPartiesHearingPanelPreferenceHeaderLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtIcPartiesHearingPanelPreference)
                    .fieldShowCondition("etIcPartiesHearingPanelPreferenceLabel=\"dummy\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtIcPartiesHearingPanelPreferenceLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtIcPartiesHearingFormat)
                    .fieldShowCondition("etIcPartiesHearingFormatLabel=\"dummy\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtIcPartiesHearingFormatLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtInitialConsiderationJurisdictionCodes)
                    .fieldShowCondition("etInitialConsiderationJurisdictionCodesLabel=\"dummy\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtInitialConsiderationJurisdictionCodesLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getIcRespondentHearingPanelPreference)
                    .fieldShowCondition("icRespondentHearingPanelPreferenceLabel=\"dummy\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getNextListedDate)
                    .fieldShowCondition("etICJuridictionCodesInvalid=\"dummy\"");
        fields.readonlyNoSummary(CaseData::getIcRespondentHearingPanelPreferenceLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICIssuesArisingFromVettingLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getIcEt1VettingIssuesDetail)
                    .fieldShowCondition("icEt1VettingIssuesDetailLabel=\"dummy\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICMinimumInfoFromVettingLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getIcEt1VettingIssuesDetailLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEt3DoWeHaveRespondentsName)
                    .fieldShowCondition("etICIssuesArisingFromVettingLabel=\"dummy\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEt3DoesRespondentsNameMatch)
                    .fieldShowCondition("et3DoWeHaveRespondentsName=\"dummy\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEt3RespondentNameMismatchDetails)
                    .fieldShowCondition("et3DoesRespondentsNameMatch=\"dummy\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getIcEt3ProcessingIssuesDetailDividerHrLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getIcEt3ProcessingIssuesDetail)
                    .fieldShowCondition("icEt3ProcessingIssuesDetailLabel=\"dummy\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getIcEt3ProcessingIssuesDetailLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getIcEt3ProcessingIssuesBottomDividerHrLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtIcHearingPanelPreferenceLabel)
                    .fieldShowCondition("etIcHearingPanelPreference=\"dummy\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtIcHearingPanelPreference)
                    .fieldShowCondition("etIcHearingPanelPreferenceLabel=\"dummy\"")
                    .publish(false);
        fields.mandatory(CaseData::getEtICJuridictionCodesInvalid)
                    .publish(false);
        fields.mandatory(CaseData::getEtICInvalidDetails)
                    .fieldShowCondition("etICJuridictionCodesInvalid=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getEtICCanProceed);
    }
}
