package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.types.ClaimantHearingPreference;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 9} of event {@code initiateCase}.
 */
public final class InitiateCasePage9 {
    private InitiateCasePage9() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("9");
        fields.complex(CaseData::getClaimantHearingPreference)
                    .mandatory(ClaimantHearingPreference::getHearingPreferences)
                    .eventLabel("What are the claimant's hearing preferences")
                    .mandatory(ClaimantHearingPreference::getHearingAssistance)
                    .eventLabel("Why is the claimant unable to take part in video or phone hearings").done();
    }
}
