package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.Address;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.types.ClaimantType;
import uk.gov.hmcts.et.common.model.ccd.types.ClaimantIndType;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code INITIATE_CASE_DRAFT}.
 */
public final class INITIATECASEDRAFTPage2 {
    private INITIATECASEDRAFTPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.mandatory(CaseData::getClaimantTypeOfClaimant);
        fields.mandatory(CaseData::getClaimantCompany)
                    .fieldShowCondition("claimant_TypeOfClaimant=\"Company\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getClaimantIndType)
                    .optional(ClaimantIndType::getClaimantPreferredTitle)
                    .eventLabel("Title")
                    .optional(ClaimantIndType::getClaimantTitleOther)
                    .eventLabel("Other title")
                    .mandatory(ClaimantIndType::getClaimantFirstNames)
                    .eventLabel("First Name")
                    .mandatory(ClaimantIndType::getClaimantLastName)
                    .eventLabel("Last Name")
                    .optional(ClaimantIndType::getClaimantDateOfBirth)
                    .eventLabel("Date of birth")
                    .optional(ClaimantIndType::getClaimantSex)
                    .eventLabel("Sex")
                    .optional(ClaimantIndType::getClaimantGenderIdentitySame)
                    .eventLabel("Gender Identity")
                    .optional(ClaimantIndType::getClaimantGenderIdentity)
                    .eventLabel("Gender Identity description").done()
                    .fieldShowCondition("claimant_TypeOfClaimant=\"Individual\"");
        fields.complex(CaseData::getClaimantType)
                    .mandatory(ClaimantType::getClaimantAddressUK)
                    .complex(ClaimantType::getClaimantAddressUK)
                    .mandatory(Address::getAddressLine1)
                    .eventLabel("Building and Street").done()
                    .complex(ClaimantType::getClaimantAddressUK)
                    .optional(Address::getAddressLine2).done()
                    .complex(ClaimantType::getClaimantAddressUK)
                    .optional(Address::getAddressLine3).done()
                    .complex(ClaimantType::getClaimantAddressUK)
                    .optional(Address::getPostTown)
                    .eventLabel("Town or City").done()
                    .complex(ClaimantType::getClaimantAddressUK)
                    .optional(Address::getCounty)
                    .eventLabel("County").done()
                    .complex(ClaimantType::getClaimantAddressUK)
                    .optional(Address::getCountry)
                    .eventLabel("Country").done()
                    .complex(ClaimantType::getClaimantAddressUK)
                    .mandatory(Address::getPostCode)
                    .eventLabel("Postcode").done()
                    .optional(ClaimantType::getClaimantPhoneNumber)
                    .eventLabel("Phone number")
                    .optional(ClaimantType::getClaimantMobileNumber)
                    .eventLabel("Alternative number")
                    .optional(ClaimantType::getClaimantEmailAddress)
                    .eventLabel("Email address")
                    .optional(ClaimantType::getClaimantContactPreference)
                    .eventLabel("Contact preference").done();
    }
}
