package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code initiateCase}.
 */
public final class InitiateCasePage1 {
    private InitiateCasePage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.mandatory(CaseData::getReceiptDate)
                    .publish(false);
        fields.optional(CaseData::getFeeGroupReference)
                    .fieldShowCondition("managingOffice=\"dummy\"")
                    .publish(false);
        fields.mandatory(CaseData::getManagingOffice)
                    .publish(false);
        fields.optional(CaseData::getStateAPI)
                    .fieldShowCondition("feeGroupReference=\"dummy\"")
                    .publish(false);
        fields.optional(CaseData::getCaseRefNumberCount)
                    .fieldShowCondition("feeGroupReference=\"dummy\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.optional(CaseData::getStartCaseRefNumber)
                    .fieldShowCondition("feeGroupReference=\"dummy\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.optional(CaseData::getMultipleRefNumber)
                    .fieldShowCondition("feeGroupReference=\"dummy\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.mandatory(CaseData::getEcmCaseType)
                    .fieldShowCondition("feeGroupReference=\"dummy\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.readonly(CaseData::getMultipleReference)
                    .fieldShowCondition("caseType=\"Multiple\"")
                    .publish(false);
        fields.readonly(CaseData::getLeadClaimant)
                    .fieldShowCondition("caseType=\"Multiple\"")
                    .publish(false);
    }
}
