package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.EtICListForFinalHearing;
import uk.gov.hmcts.et.common.model.ccd.EtICListForFinalHearingUpdated;
import uk.gov.hmcts.et.common.model.ccd.EtICListForPreliminaryHearing;
import uk.gov.hmcts.et.common.model.ccd.EtICSeekComments;
import uk.gov.hmcts.et.common.model.ccd.EtIcudlHearing;
import uk.gov.hmcts.et.common.model.ccd.IcDocumentUpload;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code initialConsideration}.
 */
public final class InitialConsiderationPage2 {
    private InitialConsiderationPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.pageLabel("Rule 27");
        fields.showCondition("etICCanProceed=\"Yes\" AND etICHearingAlreadyListed=\"No\"");
        fields.readonlyNoSummary(CaseData::getInitialConsiderationBeforeYouStartLabel2)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICHearingNotListedRespondentLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICHearingNotListedHearingLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getNotListedHearingPartiesPanelPreferenceLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getNotListedHearingPartiesHearingFormatLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICHearingNotListedJurCodesLabel)
                    .publish(false);
        fields.mandatory(CaseData::getEtICHearingNotListedList)
                    .fieldShowCondition("etICCanProceed=\"dummy\"");
        fields.readonly(CaseData::getEtICHearingNotListedListUpdatedDividerHrLabel);
        fields.mandatory(CaseData::getEtICHearingNotListedListUpdated);
        fields.complex(CaseData::getEtICHearingNotListedSeekComments)
                    .mandatory(EtICSeekComments::getEtICTypeOfCvpHearing)
                    .eventLabel("Type of Video hearing")
                    .mandatory(EtICSeekComments::getEtICFinalHearingDetails)
                    .eventLabel("Give details of final hearing")
                    .mandatory(EtICSeekComments::getEtICPrelimHearingDetails)
                    .eventLabel("Give details of preliminary hearing")
                    .mandatory(EtICSeekComments::getEtICPrelimHearingYesNo)
                    .eventLabel("Should the case be listed for a private preliminary hearing?").done()
                    .fieldShowCondition("etICHearingNotListedList=\"dummy\"");
        fields.complex(CaseData::getEtICHearingNotListedListForPrelimHearing)
                    .mandatory(EtICListForPreliminaryHearing::getEtICTypeOfPreliminaryHearing)
                    .eventLabel("Type of preliminary hearing")
                    .noHintText()
                    .mandatory(EtICListForPreliminaryHearing::getEtICPurposeOfPreliminaryHearing)
                    .eventLabel("Purpose of preliminary hearing")
                    .noHintText()
                    .mandatory(EtICListForPreliminaryHearing::getEtICGiveDetailsOfHearingNotice)
                    .eventLabel("Give details of hearing notice")
                    .mandatory(EtICListForPreliminaryHearing::getPrelimHearingLengthNumType)
                    .eventLabel("Days, Hours or Minutes").done()
                    .fieldShowCondition("etICHearingNotListedList=\"dummy\"");
        fields.complex(CaseData::getEtICHearingNotListedListForPrelimHearingUpdated).done()
                    .fieldShowCondition("etICHearingNotListedListUpdated CONTAINS \"List for preliminary hearing\"");
        fields.complex(CaseData::getEtICHearingNotListedListForFinalHearing)
                    .mandatory(EtICListForFinalHearing::getEtICTypeOfFinalHearing)
                    .eventLabel("Type of final hearing")
                    .noHintText()
                    .mandatory(EtICListForFinalHearing::getEtICLengthOfFinalHearing)
                    .eventLabel("Length of hearing")
                    .mandatory(EtICListForFinalHearing::getFinalHearingLengthNumType)
                    .eventLabel("Days, Hours or Minutes").done()
                    .fieldShowCondition("etICHearingNotListedList=\"dummy\"");
        fields.complex(CaseData::getEtICHearingNotListedListForFinalHearingUpdated)
                    .mandatory(EtICListForFinalHearingUpdated::getEtICTypeOfFinalHearing)
                    .eventLabel("Type of final hearing")
                    .noHintText()
                    .mandatory(EtICListForFinalHearingUpdated::getEtICLengthOfFinalHearing)
                    .eventLabel("Length of hearing")
                    .mandatory(EtICListForFinalHearingUpdated::getFinalHearingLengthNumType)
                    .eventLabel("Days, Hours or Minutes")
                    .mandatory(EtICListForFinalHearingUpdated::getEtICFinalHearingIsEJSitAlone)
                    .eventLabel("Do you consider this final hearing should be listed judge alone or with members?")
                    .mandatory(EtICListForFinalHearingUpdated::getEtICFinalHearingIsEJSitAloneReasonYes)
                    .eventLabel("Reasons for JSA")
                    .noHintText()
                    .mandatory(EtICListForFinalHearingUpdated::getEtICNoLFinalHearingIsEJSitAloneReasonsJsaOther)
                    .eventLabel("Reason for JSA - Other")
                    .mandatory(EtICListForFinalHearingUpdated::getEtICFinalHearingIsEJSitAloneReasonNo)
                    .eventLabel("Reasons for Members")
                    .noHintText()
                    .mandatory(EtICListForFinalHearingUpdated::getEtICNoLFinalHearingIsEJSitAloneReasonsMembersOther)
                    .eventLabel("Reason for Members - Other")
                    .optional(EtICListForFinalHearingUpdated::getEtICFinalHearingIsEJSitAloneFurtherDetails)
                    .eventLabel("Further details").done()
                    .fieldShowCondition("etICHearingNotListedListUpdated CONTAINS \"List for final hearing\"");
        fields.complex(CaseData::getEtICHearingNotListedUDLHearing)
                    .mandatory(EtIcudlHearing::getEtIcejSitAlone)
                    .eventLabel("EJ sit alone?")
                    .mandatory(EtIcudlHearing::getEtIcudlGiveReasons)
                    .eventLabel("Give reasons")
                    .noHintText()
                    .mandatory(EtIcudlHearing::getEtIcudlDisputeOnFacts)
                    .eventLabel("Likelihood of dispute on facts makes full tribunal desirable")
                    .mandatory(EtIcudlHearing::getEtIcudlLittleOrNoAgreement)
                    .eventLabel("Little or no agreement on facts")
                    .mandatory(EtIcudlHearing::getEtIcudlIssueOfLawArising)
                    .eventLabel("Likelihood of issue of law arising makes EJSA desirable")
                    .mandatory(EtIcudlHearing::getEtIcudlViewsOfParties)
                    .eventLabel("Views of parties")
                    .mandatory(EtIcudlHearing::getEtIcudlNoViewsExpressedByParties)
                    .eventLabel("No views expressed by parties")
                    .mandatory(EtIcudlHearing::getEtIcudlConcurrentProceedings)
                    .eventLabel("Concurrent proceedings")
                    .mandatory(EtIcudlHearing::getEtIcudlOther)
                    .eventLabel("Other")
                    .mandatory(EtIcudlHearing::getEtIcudlHearFormat)
                    .eventLabel("Hearing format")
                    .mandatory(EtIcudlHearing::getEtIcudlCvpIssue)
                    .eventLabel("Issue standard Video orders when listed")
                    .mandatory(EtIcudlHearing::getEtIcudlFinalF2FIssue)
                    .eventLabel("Issue standard orders when listed")
                    .mandatory(EtIcudlHearing::getEtIcbuCheckComplianceOrders)
                    .eventLabel("BU to check compliance with orders?").done()
                    .fieldShowCondition("etICHearingNotListedList=\"dummy\"");
        fields.optional(CaseData::getEtICHearingAlreadyListed)
                    .fieldShowCondition("etICCanProceed=\"dummy\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICAnyOtherDirectionsDividerHrLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICHearingNotListedAnyOtherDirectionsLabel)
                    .publish(false);
        fields.optional(CaseData::getEtICHearingNotListedAnyOtherDirections)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICUploadDocDividerHrLabel)
                    .publish(false);
        fields.complex(CaseData::getIcDocumentCollection1).done();
        fields.complex(CaseData::getIcDocumentCollection1, IcDocumentUpload.class)
                    .mandatory(IcDocumentUpload::getUploadedDocument)
                    .optional(IcDocumentUpload::getShortDescription).done();
        fields.readonlyNoSummary(CaseData::getEtICNavigationButtonsDividerHrLabel)
                    .publish(false);
    }
}
