package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.EtICHearingListedAnswers;
import uk.gov.hmcts.et.common.model.ccd.IcDocumentUpload;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code initialConsideration}.
 */
public final class InitialConsiderationPage3 {
    private InitialConsiderationPage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("3");
        fields.showCondition("etICCanProceed=\"Yes\" AND etICHearingAlreadyListed=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getInitialConsiderationBeforeYouStartLabel3)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICHearingListedRespondentLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICHearingListedHearingLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getListedHearingPartiesPanelPreferenceLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getListedHearingPartiesHearingFormatLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getEtICHearingListedJurisdictionCodesLabel)
                    .publish(false);
        fields.complex(CaseData::getEtICHearingListedAnswers)
                    .mandatory(EtICHearingListedAnswers::getEtICHearingListed)
                    .mandatory(EtICHearingListedAnswers::getEtICExtendDurationGiveDetails)
                    .mandatory(EtICHearingListedAnswers::getEtICOtherGiveDetails)
                    .mandatory(EtICHearingListedAnswers::getEtICIsHearingWithJudgeOrMembers)
                    .mandatory(EtICHearingListedAnswers::getEtICIsHearingWithJudgeOrMembersReason)
                    .mandatory(EtICHearingListedAnswers::getEtICIsFinalHearingWithJudgeOrMembersJsaReason)
                    .mandatory(EtICHearingListedAnswers::getEtICIsFinalHearingWithJudgeOrMembersReason)
                    .mandatory(EtICHearingListedAnswers::getEtICIsHearingWithJudgeOrMembersReasonOther)
                    .mandatory(EtICHearingListedAnswers::getEtICJsaFinalHearingReasonOther)
                    .mandatory(EtICHearingListedAnswers::getEtICMembersFinalHearingReasonOther)
                    .readonly(EtICHearingListedAnswers::getEtInitialConsiderationListedHearingType)
                    .mandatory(EtICHearingListedAnswers::getEtICIsHearingWithJsa)
                    .mandatory(EtICHearingListedAnswers::getEtICIsHearingWithJsaReasonOther)
                    .mandatory(EtICHearingListedAnswers::getEtICJsaCmPreliminaryHearingReasonOther)
                    .mandatory(EtICHearingListedAnswers::getEtICIsHearingWithMembers)
                    .optional(EtICHearingListedAnswers::getEtICIsHearingWithJudgeOrMembersFurtherDetails)
                    .readonly(EtICHearingListedAnswers::getOtherDirectionsLabel)
                    .optional(EtICHearingListedAnswers::getEtICHearingAnyOtherDirections)
                    .eventLabel(" ").done();
        fields.readonlyNoSummary(CaseData::getEtICUploadDocDividerHrLabel3)
                    .publish(false);
        fields.complex(CaseData::getIcDocumentCollection2).done();
        fields.complex(CaseData::getIcDocumentCollection2, IcDocumentUpload.class)
                    .mandatory(IcDocumentUpload::getUploadedDocument)
                    .optional(IcDocumentUpload::getShortDescription).done();
    }
}
