package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.ReferralDetails;
import uk.gov.hmcts.et.common.model.ccd.ReferralReply;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code replyToReferral}.
 */
public final class ReplyToReferralPage1 {
    private ReplyToReferralPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.pageLabel("Refer to admin, legal officer or judge");
        fields.optionalNoSummary(CaseData::getNextListedDate)
                    .fieldShowCondition("selectReferral=\"dummy\"");
        fields.complex(CaseData::getReferralCollection, false).done()
                    .fieldShowCondition("selectReferral=\"dummy\"");
        fields.complex(CaseData::getReferralCollection, ReferralDetails.class)
                    .optional(ReferralDetails::getReferralSubject)
                    .eventLabel(" ")
                    .optional(ReferralDetails::getReferralSubjectSpecify)
                    .eventLabel(" ")
                    .optional(ReferralDetails::getReferCaseTo)
                    .eventLabel(" ")
                    .readonly(ReferralDetails::getReferralNumber)
                    .eventLabel(" ")
                    .optional(ReferralDetails::getReferralReplyCollection)
                    .eventLabel(" ")
                    .complex(ReferralDetails::getReferralReplyCollection, ReferralReply.class)
                    .optional(ReferralReply::getDirectionTo)
                    .eventLabel(" ").done()
                    .complex(ReferralDetails::getReferralReplyCollection, ReferralReply.class)
                    .optional(ReferralReply::getIsUrgentReply)
                    .eventLabel(" ").done()
                    .complex(ReferralDetails::getReferralReplyCollection, ReferralReply.class)
                    .optional(ReferralReply::getReplyDateTime)
                    .eventLabel(" ").done()
                    .complex(ReferralDetails::getReferralReplyCollection, ReferralReply.class)
                    .optional(ReferralReply::getReferralSubject)
                    .eventLabel(" ").done()
                    .complex(ReferralDetails::getReferralReplyCollection, ReferralReply.class)
                    .optional(ReferralReply::getReferralNumber)
                    .eventLabel(" ").done().done();
        fields.mandatory(CaseData::getSelectReferral)
                    .publish(false);
        fields.readonly(CaseData::getIsJudge)
                    .fieldShowCondition("selectReferral=\"dummy\"")
                    .publish(false);
    }
}
