package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 6} of event {@code respondentTSE}.
 */
public final class RespondentTSEPage6 {
    private RespondentTSEPage6() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("6");
        fields.pageLabel("Consider a decision afresh");
        fields.showCondition("resTseSelectApplication=\"Consider a decision afresh\"");
        fields.readonly(CaseData::getResTseGuidanceLabel4)
                    .publish(false);
        fields.optional(CaseData::getResTseDocument4)
                    .publish(false);
        fields.optional(CaseData::getResTseTextBox4)
                    .publish(false);
    }
}
