package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 12} of event {@code respondentTSE}.
 */
public final class RespondentTSEPage12 {
    private RespondentTSEPage12() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("12");
        fields.pageLabel("Restrict publicity");
        fields.showCondition("resTseSelectApplication=\"Restrict publicity\"");
        fields.readonly(CaseData::getResTseGuidanceLabel10)
                    .publish(false);
        fields.optional(CaseData::getResTseDocument10)
                    .publish(false);
        fields.optional(CaseData::getResTseTextBox10)
                    .publish(false);
    }
}
