package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.DocumentUpload;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code respondNotification}.
 */
public final class RespondNotificationPage2 {
    private RespondNotificationPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.pageLabel("Respond to a notification");
        fields.mandatory(CaseData::getRespondNotificationTitle)
                    .publish(false);
        fields.optional(CaseData::getRespondNotificationAdditionalInfo)
                    .publish(false);
        fields.complex(CaseData::getRespondNotificationUploadDocument).done();
        fields.complex(CaseData::getRespondNotificationUploadDocument, DocumentUpload.class)
                    .optional(DocumentUpload::getShortDescription)
                    .eventLabel("Short description")
                    .mandatory(DocumentUpload::getUploadedDocument)
                    .eventLabel("Document").done();
        fields.mandatory(CaseData::getRespondNotificationResponseRequired)
                    .fieldShowCondition("respondNotificationCmoOrRequest=\"Case management order\" OR respondNotificationCmoOrRequest=\"Request\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.mandatory(CaseData::getRespondNotificationWhoRespond)
                    .fieldShowCondition("respondNotificationResponseRequired=\"Yes\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.readonly(CaseData::getNotificationMarkdown)
                    .fieldShowCondition("notificationMarkdownLabel=\"dummy\"")
                    .publish(false);
        fields.readonly(CaseData::getNotificationMarkdownLabel)
                    .publish(false);
        fields.mandatory(CaseData::getRespondNotificationPartyToNotify)
                    .publish(false);
        fields.mandatory(CaseData::getRespondNotificationCaseManagementMadeBy)
                    .fieldShowCondition("respondNotificationCmoOrRequest=\"Case management order\"")
                    .publish(false);
        fields.mandatory(CaseData::getRespondNotificationFullName)
                    .fieldShowCondition("respondNotificationCmoOrRequest=\"Case management order\" OR respondNotificationCmoOrRequest=\"Request\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.mandatory(CaseData::getRespondNotificationCmoOrRequest)
                    .publish(false);
        fields.mandatory(CaseData::getRespondNotificationRequestMadeBy)
                    .fieldShowCondition("respondNotificationCmoOrRequest=\"Request\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.readonly(CaseData::getRespondNotificationDate)
                    .fieldShowCondition("respondNotificationCmoOrRequest=\"dummy\"")
                    .retainHiddenValue()
                    .publish(false);
    }
}
