package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 7} of event {@code respondentTSE}.
 */
public final class RespondentTSEPage7 {
    private RespondentTSEPage7() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("7");
        fields.pageLabel("Contact the tribunal");
        fields.showCondition("resTseSelectApplication=\"Contact the tribunal\"");
        fields.readonly(CaseData::getResTseGuidanceLabel5)
                    .publish(false);
        fields.optional(CaseData::getResTseDocument5)
                    .publish(false);
        fields.optional(CaseData::getResTseTextBox5)
                    .publish(false);
    }
}
