package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 13} of event {@code respondentTSE}.
 */
public final class RespondentTSEPage13 {
    private RespondentTSEPage13() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("13");
        fields.pageLabel("Strike out all or part of a claim");
        fields.showCondition("resTseSelectApplication=\"Strike out all or part of a claim\"");
        fields.readonly(CaseData::getResTseGuidanceLabel11)
                    .publish(false);
        fields.optional(CaseData::getResTseDocument11)
                    .publish(false);
        fields.optional(CaseData::getResTseTextBox11)
                    .publish(false);
    }
}
