package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.DocumentUpload;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code tseAdmin}.
 */
public final class TseAdminPage2 {
    private TseAdminPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.pageLabel("Record a decision");
        fields.readonly(CaseData::getTseAdminTableMarkUp)
                    .fieldShowCondition("tseAdminTableLabel=\"dummy\"");
        fields.readonly(CaseData::getTseAdminTableLabel);
        fields.mandatory(CaseData::getTseAdminEnterNotificationTitle);
        fields.mandatory(CaseData::getTseAdminDecision);
        fields.mandatory(CaseData::getTseAdminDecisionDetails)
                    .fieldShowCondition("tseAdminDecision=\"Other\"");
        fields.mandatory(CaseData::getTseAdminTypeOfDecision);
        fields.mandatory(CaseData::getTseAdminIsResponseRequired)
                    .fieldShowCondition("tseAdminTypeOfDecision=\"Case management order\"");
        fields.mandatory(CaseData::getTseAdminSelectPartyRespond)
                    .fieldShowCondition("tseAdminTypeOfDecision=\"Case management order\" AND tseAdminIsResponseRequired=\"Yes\"");
        fields.optional(CaseData::getTseAdminAdditionalInformation);
        fields.complex(CaseData::getTseAdminResponseRequiredYesDoc).done()
                    .fieldShowCondition("tseAdminTypeOfDecision=\"Case management order\" AND tseAdminIsResponseRequired=\"Yes\"");
        fields.complex(CaseData::getTseAdminResponseRequiredYesDoc, DocumentUpload.class)
                    .mandatory(DocumentUpload::getUploadedDocument)
                    .eventLabel("Document")
                    .optional(DocumentUpload::getShortDescription)
                    .eventLabel("Short description").done();
        fields.complex(CaseData::getTseAdminResponseRequiredNoDoc).done()
                    .fieldShowCondition("tseAdminTypeOfDecision=\"Judgment\" OR tseAdminIsResponseRequired=\"No\"");
        fields.complex(CaseData::getTseAdminResponseRequiredNoDoc, DocumentUpload.class)
                    .optional(DocumentUpload::getShortDescription)
                    .eventLabel("Short description")
                    .mandatory(DocumentUpload::getUploadedDocument)
                    .eventLabel("Document").done();
        fields.mandatory(CaseData::getTseAdminDecisionMadeBy);
        fields.mandatory(CaseData::getTseAdminDecisionMadeByFullName)
                    .fieldShowCondition("tseAdminDecisionMadeBy=\"Legal officer\" OR tseAdminDecisionMadeBy=\"Judge\"");
        fields.mandatory(CaseData::getTseAdminSelectPartyNotify);
    }
}
