package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.GenericTseDetails;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.TseReply;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code tseRespond}.
 */
public final class TseRespondPage2 {
    private TseRespondPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.pageLabel("Select an application");
        fields.optionalNoSummary(CaseData::getNextListedDate)
                    .fieldShowCondition("tseRespondSelectApplication=\"dummy\"");
        fields.complex(CaseData::getGenericTseApplicationCollection, false).done()
                    .fieldShowCondition("tseRespondSelectApplication=\"dummy\"");
        fields.complex(CaseData::getGenericTseApplicationCollection, GenericTseDetails.class)
                    .optional(GenericTseDetails::getType)
                    .eventLabel(" ")
                    .optional(GenericTseDetails::getNumber)
                    .eventLabel(" ")
                    .optional(GenericTseDetails::getRespondCollection)
                    .eventLabel(" ")
                    .complex(GenericTseDetails::getRespondCollection, TseReply.class)
                    .optional(TseReply::getFrom)
                    .eventLabel(" ").done()
                    .complex(GenericTseDetails::getRespondCollection, TseReply.class)
                    .optional(TseReply::getDateTime)
                    .eventLabel(" ").done()
                    .complex(GenericTseDetails::getRespondCollection, TseReply.class)
                    .optional(TseReply::getApplicationType)
                    .eventLabel(" ").done().done();
        fields.mandatory(CaseData::getTseRespondSelectApplication)
                    .publish(false);
    }
}
