package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.DocumentUpload;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code updateReferral}.
 */
public final class UpdateReferralPage2 {
    private UpdateReferralPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.pageLabel("Refer to admin, legal officer or judge");
        fields.optional(CaseData::getUpdateReferentEmail)
                    .publish(false);
        fields.readonly(CaseData::getReferralHearingDetails)
                    .fieldShowCondition("referralHearingDetailsLabel=\"dummy\"")
                    .publish(false);
        fields.readonly(CaseData::getReferralHearingDetailsLabel)
                    .publish(false);
        fields.mandatory(CaseData::getUpdateReferCaseTo)
                    .publish(false);
        fields.mandatory(CaseData::getUpdateIsUrgent)
                    .publish(false);
        fields.mandatory(CaseData::getUpdateReferralSubject)
                    .publish(false);
        fields.mandatory(CaseData::getUpdateReferralDetails)
                    .publish(false);
        fields.complex(CaseData::getUpdateReferralDocument).done();
        fields.complex(CaseData::getUpdateReferralDocument, DocumentUpload.class)
                    .optional(DocumentUpload::getUploadedDocument)
                    .eventLabel("Document")
                    .optional(DocumentUpload::getShortDescription)
                    .eventLabel("Short description of document").done();
        fields.mandatory(CaseData::getUpdateReferralSubjectSpecify)
                    .fieldShowCondition("updateReferralSubject =\"Other\"")
                    .publish(false);
        fields.optional(CaseData::getUpdateReferralInstruction)
                    .publish(false);
    }
}
