package uk.gov.hmcts.et.common.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;
import uk.gov.hmcts.et.common.model.ccd.types.HearingDetailType;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code updateHearing}.
 */
public final class UpdateHearingPage2 {
    private UpdateHearingPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.optional(CaseData::getUploadHearingNotesDocument)
                    .publish(false);
        fields.optional(CaseData::getDoesHearingNotesDocExist)
                    .fieldShowCondition("uploadHearingNotesDocument=\"dummy\"")
                    .publish(false);
        fields.optional(CaseData::getRemoveHearingNotesDocument)
                    .fieldShowCondition("doesHearingNotesDocExist=\"Yes\"")
                    .publish(false);
        fields.complex(CaseData::getHearingDetailsCollection).done();
        fields.complex(CaseData::getHearingDetailsCollection, HearingDetailType.class)
                    .mandatory(HearingDetailType::getHearingDetailsStatus)
                    .eventLabel("Hearing Status")
                    .readonly(HearingDetailType::getHearingDetailsDate)
                    .eventLabel("Hearing Date")
                    .mandatory(HearingDetailType::getHearingDetailsPostponedBy)
                    .eventLabel("Postponed by")
                    .mandatory(HearingDetailType::getHearingDetailsCaseDisposed)
                    .eventLabel("Has the case or part of the case been disposed?")
                    .optional(HearingDetailType::getHearingDetailsPartHeard)
                    .eventLabel("Has the hearing been part heard?")
                    .optional(HearingDetailType::getHearingDetailsReservedJudgment)
                    .eventLabel("Is there a reserved Judgment?")
                    .optional(HearingDetailType::getHearingDetailsAttendeeClaimant)
                    .eventLabel("Attendees (Claimant)")
                    .optional(HearingDetailType::getHearingDetailsAttendeeNonAttendees)
                    .eventLabel("Number of Non Attendees (Respondent) ")
                    .optional(HearingDetailType::getHearingDetailsAttendeeRespNoRep)
                    .eventLabel("Respondent Attended - No Representative")
                    .optional(HearingDetailType::getHearingDetailsAttendeeRespAndRep)
                    .eventLabel("Respondent and Representative Attended")
                    .optional(HearingDetailType::getHearingDetailsAttendeeRepOnly)
                    .eventLabel("Respondent representative only attended")
                    .optional(HearingDetailType::getHearingDetailsTimingStart)
                    .eventLabel("Start Time")
                    .optional(HearingDetailType::getHearingDetailsTimingBreak)
                    .eventLabel("Break")
                    .optional(HearingDetailType::getHearingDetailsTimingResume)
                    .eventLabel("Resume")
                    .optional(HearingDetailType::getHearingDetailsTimingFinish)
                    .eventLabel("Finish")
                    .optional(HearingDetailType::getHearingDetailsTimingDuration)
                    .eventLabel("Duration")
                    .optional(HearingDetailType::getHearingDetailsHearingNotes2)
                    .eventLabel("Hearing Notes").done();
    }
}
