package uk.gov.hmcts.et.common.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
public class SOLICITORACuPlus9RolesXrnczvAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.SOLICITORA, Permission.C);
        grants.put(UserRole.SOLICITORA, Permission.U);
        grants.put(UserRole.SOLICITORB, Permission.C);
        grants.put(UserRole.SOLICITORB, Permission.U);
        grants.put(UserRole.SOLICITORC, Permission.C);
        grants.put(UserRole.SOLICITORC, Permission.U);
        grants.put(UserRole.SOLICITORD, Permission.C);
        grants.put(UserRole.SOLICITORD, Permission.U);
        grants.put(UserRole.SOLICITORE, Permission.C);
        grants.put(UserRole.SOLICITORE, Permission.U);
        grants.put(UserRole.SOLICITORF, Permission.C);
        grants.put(UserRole.SOLICITORF, Permission.U);
        grants.put(UserRole.SOLICITORG, Permission.C);
        grants.put(UserRole.SOLICITORG, Permission.U);
        grants.put(UserRole.SOLICITORH, Permission.C);
        grants.put(UserRole.SOLICITORH, Permission.U);
        grants.put(UserRole.SOLICITORI, Permission.C);
        grants.put(UserRole.SOLICITORI, Permission.U);
        grants.put(UserRole.SOLICITORJ, Permission.C);
        grants.put(UserRole.SOLICITORJ, Permission.U);
        return grants;
    }
}
