package uk.gov.hmcts.et.common.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
public class SOLICITORACruPlus13RolesJweikaAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.SOLICITORA, Permission.C);
        grants.put(UserRole.SOLICITORA, Permission.R);
        grants.put(UserRole.SOLICITORA, Permission.U);
        grants.put(UserRole.SOLICITORB, Permission.C);
        grants.put(UserRole.SOLICITORB, Permission.R);
        grants.put(UserRole.SOLICITORB, Permission.U);
        grants.put(UserRole.SOLICITORC, Permission.C);
        grants.put(UserRole.SOLICITORC, Permission.R);
        grants.put(UserRole.SOLICITORC, Permission.U);
        grants.put(UserRole.SOLICITORD, Permission.C);
        grants.put(UserRole.SOLICITORD, Permission.R);
        grants.put(UserRole.SOLICITORD, Permission.U);
        grants.put(UserRole.SOLICITORE, Permission.C);
        grants.put(UserRole.SOLICITORE, Permission.R);
        grants.put(UserRole.SOLICITORE, Permission.U);
        grants.put(UserRole.SOLICITORF, Permission.C);
        grants.put(UserRole.SOLICITORF, Permission.R);
        grants.put(UserRole.SOLICITORF, Permission.U);
        grants.put(UserRole.SOLICITORG, Permission.C);
        grants.put(UserRole.SOLICITORG, Permission.R);
        grants.put(UserRole.SOLICITORG, Permission.U);
        grants.put(UserRole.SOLICITORH, Permission.C);
        grants.put(UserRole.SOLICITORH, Permission.R);
        grants.put(UserRole.SOLICITORH, Permission.U);
        grants.put(UserRole.SOLICITORI, Permission.C);
        grants.put(UserRole.SOLICITORI, Permission.R);
        grants.put(UserRole.SOLICITORI, Permission.U);
        grants.put(UserRole.SOLICITORJ, Permission.C);
        grants.put(UserRole.SOLICITORJ, Permission.R);
        grants.put(UserRole.SOLICITORJ, Permission.U);
        grants.put(UserRole.CASEWORKER_EMPLOYMENT_API, Permission.C);
        grants.put(UserRole.CASEWORKER_EMPLOYMENT_API, Permission.R);
        grants.put(UserRole.CASEWORKER_EMPLOYMENT_API, Permission.U);
        grants.put(UserRole.CASEWORKER_EMPLOYMENT_API, Permission.D);
        grants.put(UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, Permission.C);
        grants.put(UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, Permission.R);
        grants.put(UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, Permission.U);
        grants.put(UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES, Permission.C);
        grants.put(UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES, Permission.R);
        grants.put(UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES, Permission.U);
        grants.put(UserRole.ET_ACAS_API, Permission.R);
        return grants;
    }
}
