package uk.gov.hmcts.et.common.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 */
public class TTLProfileCrudAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.TTL_PROFILE, Permission.C);
        grants.put(UserRole.TTL_PROFILE, Permission.R);
        grants.put(UserRole.TTL_PROFILE, Permission.U);
        grants.put(UserRole.TTL_PROFILE, Permission.D);
        return grants;
    }
}
