server {
  listen 5062;
  server_name _;

  location / {
    proxy_pass http://host.docker.internal:5062;
    proxy_set_header Host host.docker.internal;
    proxy_set_header Accept-Encoding "";
    proxy_redirect off;
    sub_filter_once off;
    sub_filter_types application/json text/plain;
    sub_filter "http://localhost:5062" "http://rd-idam-simulator-proxy:5062";
  }
}
