package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code acceptRejectedCase} for case type {@code ET_EnglandWales}.
 */
@Component
public class AcceptRejectedCase implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ACCEPT_REJECTED_CASE = "acceptRejectedCase";

    /**
     * Registers event {@code acceptRejectedCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ACCEPT_REJECTED_CASE)
            .forStateTransition(State.Rejected, State.Accepted)
            .name("Accept Case")
            .displayOrder(10)
            .showCondition("caseType =\"dummy\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.pageLabel("Pre-Acceptance");
        fields.mandatory(CaseData::getPreAcceptCase);
    }
}
