package uk.gov.hmcts.et.common.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.Judgment;
import uk.gov.hmcts.et.common.model.ccd.JudgmentCosts;
import uk.gov.hmcts.et.common.model.ccd.JudgmentDetails;
import uk.gov.hmcts.et.common.model.ccd.JudgmentReconsideration;
import uk.gov.hmcts.et.common.model.ccd.Jurisdiction;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code addAmendJudgment} for case type {@code ET_EnglandWales}.
 */
@Component
public class AddAmendJudgment implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADD_AMEND_JUDGMENT = "addAmendJudgment";

    /**
     * Registers event {@code addAmendJudgment}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ADD_AMEND_JUDGMENT)
            .forStateTransition(EnumSet.of(State.Accepted, State.Rejected), State.Accepted)
            .name("Judgment")
            .description("Add or Amend a Judgment")
            .displayOrder(26)
            .showCondition("managingOffice !=\"Unassigned\"")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getJudgementCollection).done();
        fields.complex(CaseData::getJudgementCollection, Judgment.class)
                    .mandatory(Judgment::getNon_hearing_judgment)
                    .eventLabel("Non Hearing Judgment?")
                    .mandatory(Judgment::getDynamicJudgementHearing)
                    .eventLabel("Hearing Details")
                    .mandatory(Judgment::getJudgement_type)
                    .eventLabel("Judgment Type")
                    .optional(Judgment::getLiability_optional)
                    .eventLabel("Liability")
                    .mandatory(Judgment::getJurisdictionCodes)
                    .eventLabel("Jurisdiction")
                    .complex(Judgment::getJurisdictionCodes, Jurisdiction.class)
                    .mandatory(Jurisdiction::getJuridictionCodesList)
                    .eventLabel("Jurisdiction").done()
                    .mandatory(Judgment::getDate_judgment_made)
                    .eventLabel("Date Judgment made")
                    .mandatory(Judgment::getDate_judgment_sent)
                    .eventLabel("Date Judgment sent")
                    .optional(Judgment::getJudgment_notes)
                    .eventLabel("Judgment Notes")
                    .optional(Judgment::getJudgement_outcome_doc)
                    .eventLabel("Upload outcome of Judgment")
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getReasons_given)
                    .eventLabel("Reasons given").done()
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getDate_reasons_issued)
                    .eventLabel("Date reasons issued").done()
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getAwardMade)
                    .eventLabel("Award made?").done()
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getFinancialAwardMade)
                    .eventLabel("Financial award made?").done()
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getTotal_award)
                    .eventLabel("Total award £").done()
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getAdjustment)
                    .eventLabel("Adjustment (Old Regs) / ACAS Code Adj (New Regs) ").done()
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getAdjustmentPercentage)
                    .eventLabel("Adjustment % (New Regs)")
                    .noHintText().done()
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getNon_financial_award)
                    .eventLabel("Non-financial award").done()
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getRemedy_left_to_parties)
                    .eventLabel("Remedy left to parties").done()
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getReinstate_reengage_order)
                    .eventLabel("Reinstate / reengage order").done()
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getReinstated_reengaged)
                    .eventLabel("Reinstated / reengaged").done()
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getCertificateOfCorrection)
                    .eventLabel("Certificate of Correction Issued?").done()
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getCert_of_correction_date)
                    .eventLabel("Cert. of correction date").done()
                    .complex(Judgment::getJudgement_details)
                    .optional(JudgmentDetails::getCert_of_correction_sent)
                    .eventLabel("Cert. of correction sent").done()
                    .complex(Judgment::getJudgement_costs)
                    .optional(JudgmentCosts::getCosts_question)
                    .eventLabel("Have costs been awarded?").done()
                    .complex(Judgment::getJudgement_costs)
                    .optional(JudgmentCosts::getCosts_expenses_awarded_to)
                    .eventLabel("Costs/Expenses awarded to").done()
                    .complex(Judgment::getJudgement_costs)
                    .optional(JudgmentCosts::getCosts_expenses_awarded_against)
                    .eventLabel("Costs/Expenses awarded against").done()
                    .complex(Judgment::getJudgement_costs)
                    .optional(JudgmentCosts::getCosts_expenses_awarded_amount)
                    .eventLabel("Costs/Expenses amount awarded").done()
                    .complex(Judgment::getJudgement_costs)
                    .optional(JudgmentCosts::getPreparation_of_time_awarded_to)
                    .eventLabel("Preparation of time awarded to").done()
                    .complex(Judgment::getJudgement_costs)
                    .optional(JudgmentCosts::getPreparation_of_time_awarded_against)
                    .eventLabel("Preparation of time awarded against").done()
                    .complex(Judgment::getJudgement_costs)
                    .optional(JudgmentCosts::getPreparation_of_time_amount_awarded)
                    .eventLabel("Preparation of time amount awarded").done()
                    .complex(Judgment::getJudgement_costs)
                    .optional(JudgmentCosts::getWasted_cost_awarded_to)
                    .eventLabel("Wasted cost awarded to").done()
                    .complex(Judgment::getJudgement_costs)
                    .optional(JudgmentCosts::getWasted_cost_awarded_against)
                    .eventLabel("Wasted cost awarded against").done()
                    .complex(Judgment::getJudgement_costs)
                    .optional(JudgmentCosts::getWasted_cost_amount_awarded)
                    .eventLabel("Wasted cost amount awarded").done()
                    .complex(Judgment::getJudgement_costs)
                    .optional(JudgmentCosts::getPro_bono_costs_awarded_to)
                    .eventLabel("Pro Bono costs awarded to").done()
                    .complex(Judgment::getJudgement_costs)
                    .optional(JudgmentCosts::getPro_bono_costs_awarded_against)
                    .eventLabel("Pro Bono costs awarded against").done()
                    .complex(Judgment::getJudgement_costs)
                    .optional(JudgmentCosts::getPro_bono_costs_amount_awarded)
                    .eventLabel("Pro Bono costs amount awarded").done()
                    .complex(Judgment::getReconsiderations)
                    .optional(JudgmentReconsideration::getReconsideration)
                    .eventLabel("Has a reconsideration application been made?").done()
                    .complex(Judgment::getReconsiderations)
                    .mandatory(JudgmentReconsideration::getReconsiderationDate)
                    .eventLabel("Date of application for reconsideration").done()
                    .complex(Judgment::getReconsiderations)
                    .mandatory(JudgmentReconsideration::getReconsiderationOwnInitiative)
                    .eventLabel("Did the Tribunal reconsider the Judgment on its own initiative").done()
                    .complex(Judgment::getReconsiderations)
                    .optional(JudgmentReconsideration::getReconsiderationPartyInitiative)
                    .eventLabel("Who applied for reconsideration?").done()
                    .complex(Judgment::getReconsiderations)
                    .mandatory(JudgmentReconsideration::getReconsiderationDirection)
                    .eventLabel("Employment Judge's direction").done()
                    .complex(Judgment::getReconsiderations)
                    .optional(JudgmentReconsideration::getReconsiderationDecision)
                    .eventLabel("Employment Judge's decision").done().done();
    }
}
