package uk.gov.hmcts.et.common.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;
import uk.gov.hmcts.et.common.model.ccd.types.CostsType;
import uk.gov.hmcts.et.common.model.ccd.types.JudgementDetailsType;
import uk.gov.hmcts.et.common.model.ccd.types.JudgementType;
import uk.gov.hmcts.et.common.model.ccd.types.JudgmentReconsiderationType;
import uk.gov.hmcts.et.common.model.ccd.types.JurCodesType;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code addAmendJudgment} for case type {@code ET_EnglandWales}.
 */
@Component
public class AddAmendJudgment implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADD_AMEND_JUDGMENT = "addAmendJudgment";

    /**
     * Registers event {@code addAmendJudgment}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ADD_AMEND_JUDGMENT)
            .forStateTransition(EnumSet.of(State.Accepted, State.Rejected), State.Accepted)
            .name("Judgment")
            .description("Add or Amend a Judgment")
            .displayOrder(26)
            .showCondition("managingOffice !=\"Unassigned\"")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getJudgementCollection).done();
        fields.complex(CaseData::getJudgementCollection, JudgementType.class)
                    .mandatory(JudgementType::getNonHearingJudgment)
                    .eventLabel("Non Hearing Judgment?")
                    .mandatory(JudgementType::getDynamicJudgementHearing)
                    .eventLabel("Hearing Details")
                    .mandatory(JudgementType::getJudgementType)
                    .eventLabel("Judgment Type")
                    .optional(JudgementType::getLiabilityOptional)
                    .eventLabel("Liability")
                    .mandatory(JudgementType::getJurisdictionCodes)
                    .eventLabel("Jurisdiction")
                    .complex(JudgementType::getJurisdictionCodes, JurCodesType.class)
                    .mandatory(JurCodesType::getJuridictionCodesList)
                    .eventLabel("Jurisdiction").done()
                    .mandatory(JudgementType::getDateJudgmentMade)
                    .eventLabel("Date Judgment made")
                    .mandatory(JudgementType::getDateJudgmentSent)
                    .eventLabel("Date Judgment sent")
                    .optional(JudgementType::getJudgmentNotes)
                    .eventLabel("Judgment Notes")
                    .optional(JudgementType::getJudgementOutcomeDoc)
                    .eventLabel("Upload outcome of Judgment")
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getReasonsGiven)
                    .eventLabel("Reasons given").done()
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getDateReasonsIssued)
                    .eventLabel("Date reasons issued").done()
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getAwardMade)
                    .eventLabel("Award made?").done()
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getFinancialAwardMade)
                    .eventLabel("Financial award made?").done()
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getTotalAward)
                    .eventLabel("Total award £").done()
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getAdjustment)
                    .eventLabel("Adjustment (Old Regs) / ACAS Code Adj (New Regs) ").done()
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getAdjustmentPercentage)
                    .eventLabel("Adjustment % (New Regs)").done()
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getNonFinancialAward)
                    .eventLabel("Non-financial award").done()
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getRemedyLeftToParties)
                    .eventLabel("Remedy left to parties").done()
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getReinstateReengageOrder)
                    .eventLabel("Reinstate / reengage order").done()
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getReinstatedReengaged)
                    .eventLabel("Reinstated / reengaged").done()
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getCertificateOfCorrection)
                    .eventLabel("Certificate of Correction Issued?").done()
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getCertOfCorrectionDate)
                    .eventLabel("Cert. of correction date").done()
                    .complex(JudgementType::getJudgementDetails)
                    .optional(JudgementDetailsType::getCertOfCorrectionSent)
                    .eventLabel("Cert. of correction sent").done()
                    .complex(JudgementType::getJudgementCosts)
                    .optional(CostsType::getCostsQuestion)
                    .eventLabel("Have costs been awarded?").done()
                    .complex(JudgementType::getJudgementCosts)
                    .optional(CostsType::getCostsExpensesAwardedTo)
                    .eventLabel("Costs/Expenses awarded to").done()
                    .complex(JudgementType::getJudgementCosts)
                    .optional(CostsType::getCostExpensesAwardedAgainst)
                    .eventLabel("Costs/Expenses awarded against").done()
                    .complex(JudgementType::getJudgementCosts)
                    .optional(CostsType::getCostsExpensesAwardedAmount)
                    .eventLabel("Costs/Expenses amount awarded").done()
                    .complex(JudgementType::getJudgementCosts)
                    .optional(CostsType::getPreparationOfTimeAwardedTo)
                    .eventLabel("Preparation of time awarded to").done()
                    .complex(JudgementType::getJudgementCosts)
                    .optional(CostsType::getPreparationOfTimeAwardedAgainst)
                    .eventLabel("Preparation of time awarded against").done()
                    .complex(JudgementType::getJudgementCosts)
                    .optional(CostsType::getPreparationOfTimeAmountAwarded)
                    .eventLabel("Preparation of time amount awarded").done()
                    .complex(JudgementType::getJudgementCosts)
                    .optional(CostsType::getWastedCostAwardedTo)
                    .eventLabel("Wasted cost awarded to").done()
                    .complex(JudgementType::getJudgementCosts)
                    .optional(CostsType::getWastedCostAwardedAgainst)
                    .eventLabel("Wasted cost awarded against").done()
                    .complex(JudgementType::getJudgementCosts)
                    .optional(CostsType::getWastedCostAmountAwarded)
                    .eventLabel("Wasted cost amount awarded").done()
                    .complex(JudgementType::getJudgementCosts)
                    .optional(CostsType::getProBonoCostsAwardedTo)
                    .eventLabel("Pro Bono costs awarded to")
                    .retainHiddenValue().done()
                    .complex(JudgementType::getJudgementCosts)
                    .optional(CostsType::getProBonoCostsAwardedAgainst)
                    .eventLabel("Pro Bono costs awarded against")
                    .retainHiddenValue().done()
                    .complex(JudgementType::getJudgementCosts)
                    .optional(CostsType::getProBonoCostsAmountAwarded)
                    .eventLabel("Pro Bono costs amount awarded")
                    .retainHiddenValue().done()
                    .complex(JudgementType::getJudgementReconsiderations)
                    .optional(JudgmentReconsiderationType::getReconsideration)
                    .eventLabel("Has a reconsideration application been made?").done()
                    .complex(JudgementType::getJudgementReconsiderations)
                    .mandatory(JudgmentReconsiderationType::getReconsiderationDate)
                    .eventLabel("Date of application for reconsideration").done()
                    .complex(JudgementType::getJudgementReconsiderations)
                    .mandatory(JudgmentReconsiderationType::getReconsiderationOwnInitiative)
                    .eventLabel("Did the Tribunal reconsider the Judgment on its own initiative").done()
                    .complex(JudgementType::getJudgementReconsiderations)
                    .optional(JudgmentReconsiderationType::getReconsiderationPartyInitiative)
                    .eventLabel("Who applied for reconsideration?").done()
                    .complex(JudgementType::getJudgementReconsiderations)
                    .mandatory(JudgmentReconsiderationType::getReconsiderationDirection)
                    .eventLabel("Employment Judge's direction").done()
                    .complex(JudgementType::getJudgementReconsiderations)
                    .optional(JudgmentReconsiderationType::getReconsiderationDecision)
                    .eventLabel("Employment Judge's decision").done().done();
    }
}
