package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.Address;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.EnvironmentFlags;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;
import uk.gov.hmcts.et.common.model.ccd.types.Organisation;
import uk.gov.hmcts.et.common.model.ccd.types.RepresentedTypeC;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code addAmendClaimantRepresentative} for case type {@code ET_EnglandWales}.
 */
@Component
public class AddAmendClaimantRepresentativeProd implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADD_AMEND_CLAIMANT_REPRESENTATIVE = "addAmendClaimantRepresentative";

    /**
     * Registers overlay event {@code addAmendClaimantRepresentative} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        if (!EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(ADD_AMEND_CLAIMANT_REPRESENTATIVE)
            .forStates(State.Accepted, State.Rejected, State.Closed)
            .name("Claimant Representative")
            .description("Add or Amend a Claimant Representative")
            .displayOrder(14)
            .showCondition("managingOffice !=\"Unassigned\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.optional(CaseData::getClaimantRepresentedQuestion);
        fields.complex(CaseData::getRepresentativeClaimantType)
                    .complex(RepresentedTypeC::getMyHmctsOrganisation)
                    .optional(Organisation::getOrganisationID).done()
                    .complex(RepresentedTypeC::getMyHmctsOrganisation)
                    .optional(Organisation::getOrganisationName).done()
                    .mandatory(RepresentedTypeC::getNameOfRepresentative)
                    .eventLabel("Name of representative")
                    .optional(RepresentedTypeC::getNameOfOrganisation)
                    .eventLabel("Name of Organisation")
                    .optional(RepresentedTypeC::getRepresentativeOccupation)
                    .eventLabel("Occupation")
                    .optional(RepresentedTypeC::getRepresentativeReference)
                    .eventLabel("Reference")
                    .optional(RepresentedTypeC::getRepresentativeOccupationOther)
                    .eventLabel("What is the Representative's occupation?")
                    .complex(RepresentedTypeC::getRepresentativeAddress)
                    .mandatory(Address::getAddressLine1)
                    .eventLabel("Building and Street").done()
                    .complex(RepresentedTypeC::getRepresentativeAddress)
                    .optional(Address::getAddressLine2).done()
                    .complex(RepresentedTypeC::getRepresentativeAddress)
                    .optional(Address::getAddressLine3).done()
                    .complex(RepresentedTypeC::getRepresentativeAddress)
                    .optional(Address::getPostTown)
                    .eventLabel("Town or City").done()
                    .complex(RepresentedTypeC::getRepresentativeAddress)
                    .optional(Address::getCounty)
                    .eventLabel("County").done()
                    .complex(RepresentedTypeC::getRepresentativeAddress)
                    .optional(Address::getCountry)
                    .eventLabel("Country").done()
                    .complex(RepresentedTypeC::getRepresentativeAddress)
                    .mandatory(Address::getPostCode)
                    .eventLabel("Postcode").done()
                    .optional(RepresentedTypeC::getRepresentativePhoneNumber)
                    .eventLabel("Phone number")
                    .optional(RepresentedTypeC::getRepresentativeMobileNumber)
                    .eventLabel("Alternative number")
                    .optional(RepresentedTypeC::getRepresentativeEmailAddress)
                    .eventLabel("Email address")
                    .optional(RepresentedTypeC::getRepresentativePreference)
                    .eventLabel("Contact preference").done()
                    .fieldShowCondition("claimantRepresentedQuestion=\"Yes\"");
    }
}
