package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.AmendRepresentativeContactPage1;
import uk.gov.hmcts.et.common.ccd.event.page.AmendRepresentativeContactPage2;
import uk.gov.hmcts.et.common.ccd.event.page.AmendRepresentativeContactPage3;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code amendRepresentativeContact} for case type {@code ET_EnglandWales}.
 */
@Component
public class AmendRepresentativeContact implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_REPRESENTATIVE_CONTACT = "amendRepresentativeContact";

    /**
     * Registers event {@code amendRepresentativeContact}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(AMEND_REPRESENTATIVE_CONTACT)
            .forState(State.Accepted)
            .name("Amend contact details")
            .displayOrder(53)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.SOLICITORA, UserRole.SOLICITORB, UserRole.SOLICITORC, UserRole.SOLICITORD, UserRole.SOLICITORE, UserRole.SOLICITORF, UserRole.SOLICITORG, UserRole.SOLICITORH, UserRole.SOLICITORI, UserRole.SOLICITORJ)
            .fields();
        AmendRepresentativeContactPage1.apply(fields);
        AmendRepresentativeContactPage2.apply(fields);
        AmendRepresentativeContactPage3.apply(fields);
    }
}
