package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.AmendClaimantRepresentativeContactPage1;
import uk.gov.hmcts.et.common.ccd.event.page.AmendClaimantRepresentativeContactPage2;
import uk.gov.hmcts.et.common.ccd.event.page.AmendClaimantRepresentativeContactPage3;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code amendClaimantRepresentativeContact} for case type {@code ET_EnglandWales}.
 */
@Component
public class AmendClaimantRepresentativeContact implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_CLAIMANT_REPRESENTATIVE_CONTACT = "amendClaimantRepresentativeContact";

    /**
     * Registers event {@code amendClaimantRepresentativeContact}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(AMEND_CLAIMANT_REPRESENTATIVE_CONTACT)
            .forStates(State.Submitted, State.Vetted, State.Accepted, State.Rejected)
            .name("Amend contact details")
            .description("Claimant - Amend Contact Details")
            .displayOrder(62)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.CLAIMANTSOLICITOR)
            .fields();
        AmendClaimantRepresentativeContactPage1.apply(fields);
        AmendClaimantRepresentativeContactPage2.apply(fields);
        AmendClaimantRepresentativeContactPage3.apply(fields);
    }
}
