package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.Address;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;
import uk.gov.hmcts.et.common.model.ccd.types.Organisation;
import uk.gov.hmcts.et.common.model.ccd.types.RepresentedTypeR;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code amendRespondentRepresentative} for case type {@code ET_EnglandWales}.
 */
@Component
public class AmendRespondentRepresentative implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_RESPONDENT_REPRESENTATIVE = "amendRespondentRepresentative";

    /**
     * Registers event {@code amendRespondentRepresentative}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(AMEND_RESPONDENT_REPRESENTATIVE)
            .forStates(State.Accepted, State.Closed)
            .name("Respondent Representative")
            .description("Add or Amend a Respondent Representative")
            .displayOrder(17)
            .showCondition("managingOffice !=\"Unassigned\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getRepCollection).done();
        fields.complex(CaseData::getRepCollection, RepresentedTypeR.class)
                    .mandatory(RepresentedTypeR::getDynamicRespRepName)
                    .eventLabel("Respondent who is being represented")
                    .mandatory(RepresentedTypeR::getNameOfRepresentative)
                    .eventLabel("Name of representative")
                    .optional(RepresentedTypeR::getRepresentativePhoneNumber)
                    .eventLabel("Phone number")
                    .optional(RepresentedTypeR::getRepresentativeMobileNumber)
                    .eventLabel("Alternative number")
                    .optional(RepresentedTypeR::getRepresentativeEmailAddress)
                    .eventLabel("Email address")
                    .optional(RepresentedTypeR::getRepresentativePreference)
                    .eventLabel("Contact preference")
                    .optional(RepresentedTypeR::getMyHmctsYesNo)
                    .eventLabel("Does the representative have a MyHMCTS account?")
                    .complex(RepresentedTypeR::getRespondentOrganisation)
                    .optional(Organisation::getOrganisationID).done()
                    .complex(RepresentedTypeR::getRespondentOrganisation)
                    .optional(Organisation::getOrganisationName).done()
                    .optional(RepresentedTypeR::getNameOfOrganisation)
                    .eventLabel("Name of Organisation")
                    .optional(RepresentedTypeR::getRepresentativeReference)
                    .eventLabel("Reference")
                    .complex(RepresentedTypeR::getRepresentativeAddress)
                    .optional(Address::getAddressLine1)
                    .eventLabel("Building and Street").done()
                    .complex(RepresentedTypeR::getRepresentativeAddress)
                    .optional(Address::getAddressLine2).done()
                    .complex(RepresentedTypeR::getRepresentativeAddress)
                    .optional(Address::getAddressLine3).done()
                    .complex(RepresentedTypeR::getRepresentativeAddress)
                    .optional(Address::getPostTown)
                    .eventLabel("Town or City").done()
                    .complex(RepresentedTypeR::getRepresentativeAddress)
                    .optional(Address::getCounty)
                    .eventLabel("County").done()
                    .complex(RepresentedTypeR::getRepresentativeAddress)
                    .optional(Address::getCountry)
                    .eventLabel("Country").done()
                    .complex(RepresentedTypeR::getRepresentativeAddress)
                    .optional(Address::getPostCode)
                    .eventLabel("Postcode").done()
                    .optional(RepresentedTypeR::getRepresentativeOccupation)
                    .eventLabel("Occupation")
                    .optional(RepresentedTypeR::getRepresentativeOccupationOther)
                    .eventLabel("What is the Representative's occupation?").done();
    }
}
