package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.AmendClaimantDetailsPage1;
import uk.gov.hmcts.et.common.ccd.event.page.AmendClaimantDetailsPage2;
import uk.gov.hmcts.et.common.ccd.event.page.AmendClaimantDetailsPage3;
import uk.gov.hmcts.et.common.ccd.event.page.AmendClaimantDetailsPage4;
import uk.gov.hmcts.et.common.ccd.event.page.AmendClaimantDetailsPage5;
import uk.gov.hmcts.et.common.ccd.event.page.AmendClaimantDetailsPage6;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code amendClaimantDetails} for case type {@code ET_EnglandWales}.
 */
@Component
public class AmendClaimantDetails implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_CLAIMANT_DETAILS = "amendClaimantDetails";

    /**
     * Registers event {@code amendClaimantDetails}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(AMEND_CLAIMANT_DETAILS)
            .forStates(State.Accepted, State.Rejected, State.Closed)
            .name("Claimant Details")
            .description("Amend Claimant Details")
            .displayOrder(13)
            .showCondition("managingOffice !=\"Unassigned\"")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        AmendClaimantDetailsPage1.apply(fields);
        AmendClaimantDetailsPage2.apply(fields);
        AmendClaimantDetailsPage3.apply(fields);
        AmendClaimantDetailsPage4.apply(fields);
        AmendClaimantDetailsPage5.apply(fields);
        AmendClaimantDetailsPage6.apply(fields);
    }
}
