package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code asyncStitchingComplete} for case type {@code ET_EnglandWales}.
 */
@Component
public class AsyncStitchingComplete implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ASYNC_STITCHING_COMPLETE = "asyncStitchingComplete";

    /**
     * Registers event {@code asyncStitchingComplete}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(ASYNC_STITCHING_COMPLETE)
            .forAllStates()
            .name("Stitching bundle complete")
            .displayOrder(9000)
            .showCondition("caseType=\"dummy\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API);
    }
}
