package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.BFActions;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code broughtForward} for case type {@code ET_EnglandWales}.
 */
@Component
public class BroughtForward implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BROUGHT_FORWARD = "broughtForward";

    /**
     * Registers event {@code broughtForward}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BROUGHT_FORWARD)
            .forStates(State.Accepted, State.Rejected, State.Submitted, State.Vetted)
            .name("B/F Action")
            .displayOrder(27)
            .showCondition("managingOffice !=\"Unassigned\"")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getBfActions).done();
        fields.complex(CaseData::getBfActions, BFActions.class)
                    .mandatory(BFActions::getCwActions)
                    .eventLabel("Description")
                    .readonly(BFActions::getAllActions)
                    .eventLabel("Action")
                    .mandatory(BFActions::getBfDate)
                    .eventLabel("B/F Date")
                    .optional(BFActions::getCleared)
                    .eventLabel("Date Cleared")
                    .optional(BFActions::getNotes)
                    .eventLabel("Comments").done();
    }
}
