package uk.gov.hmcts.et.common.ccd.event;

import java.util.EnumSet;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code caseTransferMultiple} for case type {@code ET_EnglandWales}.
 */
@Component
public class CaseTransferMultiple implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CASE_TRANSFER_MULTIPLE = "caseTransferMultiple";

    /**
     * Registers event {@code caseTransferMultiple}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(CASE_TRANSFER_MULTIPLE)
            .forStateTransition(EnumSet.allOf(State.class), State.Transferred)
            .name("Case Transfer (Multiples)")
            .description("Transfer case to another office (API/Multiples)")
            .displayOrder(36)
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API);
    }
}
