package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code caseTransferSameCountry} for case type {@code ET_EnglandWales}.
 */
@Component
public class CaseTransferSameCountry implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CASE_TRANSFER_SAME_COUNTRY = "caseTransferSameCountry";

    /**
     * Registers event {@code caseTransferSameCountry}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CASE_TRANSFER_SAME_COUNTRY)
            .forStates(State.Submitted, State.Vetted, State.Accepted)
            .name("Case Transfer (Eng/Wales)")
            .description("Transfer cases to another office within England/Wales")
            .displayOrder(33)
            .showCondition("caseType !=\"Multiple\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.mandatory(CaseData::getOfficeCT)
                    .publish(false);
        fields.mandatory(CaseData::getReasonForCT)
                    .publish(false);
    }
}
