package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code caseTransferSameCountryEccLinkedCase} for case type {@code ET_EnglandWales}.
 */
@Component
public class CaseTransferSameCountryEccLinkedCase implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CASE_TRANSFER_SAME_COUNTRY_ECC_LINKED_CASE = "caseTransferSameCountryEccLinkedCase";

    /**
     * Registers event {@code caseTransferSameCountryEccLinkedCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(CASE_TRANSFER_SAME_COUNTRY_ECC_LINKED_CASE)
            .forStates(State.Submitted, State.Vetted, State.Accepted)
            .name("Case Transfer (Eng/Wales)")
            .description("Transfer ECC linked case to another office within England/Wales (API)")
            .displayOrder(34)
            .showCondition("caseType !=\"Multiple\"")
            .showSummary()
            .endButtonLabel("Transfer Case")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API);
    }
}
