package uk.gov.hmcts.et.common.ccd.event;

import java.util.EnumSet;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code caseTransferECM} for case type {@code ET_EnglandWales}.
 */
@Component
public class CaseTransferECM implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CASE_TRANSFER_ECM = "caseTransferECM";

    /**
     * Registers event {@code caseTransferECM}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CASE_TRANSFER_ECM)
            .forStateTransition(EnumSet.of(State.Submitted, State.AWAITING_SUBMISSION_TO_HMCTS, State.Vetted, State.Accepted, State.Closed, State.Rejected), State.Transferred)
            .name("Case Transfer to ECM")
            .description("Transfer case to ECM system")
            .displayOrder(39)
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .fields();
        fields.page("1");
        fields.mandatory(CaseData::getEcmOfficeCT)
                    .publish(false);
        fields.mandatory(CaseData::getReasonForCT)
                    .publish(false);
    }
}
