package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code claimantTransferredCaseAccess} for case type {@code ET_EnglandWales}.
 */
@Component
public class ClaimantTransferredCaseAccess implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CLAIMANT_TRANSFERRED_CASE_ACCESS = "claimantTransferredCaseAccess";

    /**
     * Registers event {@code claimantTransferredCaseAccess}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(CLAIMANT_TRANSFERRED_CASE_ACCESS)
            .forAllStates()
            .name("Assign Claimant Access to Case")
            .description("Give the claimant access back to the case after it's been transferred")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES);
    }
}
