package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code claimantViewAllNotifications} for case type {@code ET_EnglandWales}.
 */
@Component
public class ClaimantViewAllNotifications implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CLAIMANT_VIEW_ALL_NOTIFICATIONS = "claimantViewAllNotifications";

    /**
     * Registers event {@code claimantViewAllNotifications}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CLAIMANT_VIEW_ALL_NOTIFICATIONS)
            .forAllStates()
            .name("View All Notifications")
            .description("View Notification")
            .displayOrder(60)
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CLAIMANTSOLICITOR)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.pageLabel("All judgments, orders and notifications");
        fields.readonly(CaseData::getPseViewNotifications)
                    .fieldShowCondition("pseViewNotificationsLabel=\"dummy\"");
        fields.readonly(CaseData::getPseViewNotificationsLabel);
    }
}
