package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage1;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage10;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage11;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage12;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage13;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage14;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage15;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage2;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage3;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage4;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage5;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage6;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage7;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage8;
import uk.gov.hmcts.et.common.ccd.event.page.ClaimantTSEPage9;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code claimantTSE} for case type {@code ET_EnglandWales}.
 */
@Component
public class ClaimantTSE implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CLAIMANT_TSE = "claimantTSE";

    /**
     * Registers event {@code claimantTSE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CLAIMANT_TSE)
            .forStates(State.Submitted, State.Vetted, State.Rejected, State.Accepted, State.Closed)
            .name("Make an Application")
            .description("Claimant Tell Something Else")
            .showCondition("caseType=\"dummy\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_WA_TASK_CONFIGURATION, UserRole.CLAIMANTSOLICITOR)
            .fields();
        ClaimantTSEPage1.apply(fields);
        ClaimantTSEPage2.apply(fields);
        ClaimantTSEPage3.apply(fields);
        ClaimantTSEPage4.apply(fields);
        ClaimantTSEPage5.apply(fields);
        ClaimantTSEPage6.apply(fields);
        ClaimantTSEPage7.apply(fields);
        ClaimantTSEPage8.apply(fields);
        ClaimantTSEPage9.apply(fields);
        ClaimantTSEPage10.apply(fields);
        ClaimantTSEPage11.apply(fields);
        ClaimantTSEPage12.apply(fields);
        ClaimantTSEPage13.apply(fields);
        ClaimantTSEPage14.apply(fields);
        ClaimantTSEPage15.apply(fields);
    }
}
