package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code createDraftEt1} for case type {@code ET_EnglandWales}.
 */
@Component
public class CreateDraftEt1 implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_DRAFT_ET1 = "createDraftEt1";

    /**
     * Registers event {@code createDraftEt1}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CREATE_DRAFT_ET1)
            .forState(State.AWAITING_SUBMISSION_TO_HMCTS)
            .name("Download draft ET1 Form")
            .description("Download draft ET1 form")
            .displayOrder(58)
            .showCondition("et1ReppedSectionOne = \"Yes\" OR et1ReppedSectionTwo = \"Yes\" OR et1ReppedSectionThree = \"Yes\"")
            .showSummary(false)
            .endButtonLabel("Download draft ET1")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .grant(Permission.CRU, UserRole.CLAIMANTSOLICITOR)
            .fields();
        fields.page("1");
        fields.readonly(CaseData::getEt1DoNotSubmitDraftMessage);
    }
}
