package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;
import uk.gov.hmcts.et.common.model.ccd.types.DocumentType;
import uk.gov.hmcts.et.common.model.ccd.types.ReferralType;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code createReferral} for case type {@code ET_EnglandWales}.
 */
@Component
public class CreateReferral implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_REFERRAL = "createReferral";

    /**
     * Registers event {@code createReferral}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CREATE_REFERRAL)
            .forAllStates()
            .name("Create Referral")
            .displayOrder(48)
            .showCondition("caseType =\"dummy\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.pageLabel("Refer to admin, legal officer or judge");
        fields.optionalNoSummary(CaseData::getNextListedDate)
                    .fieldShowCondition("referralHearingDetailsLabel=\"dummy\"");
        fields.complex(CaseData::getReferralCollection, false).done()
                    .fieldShowCondition("referralHearingDetailsLabel=\"dummy\"");
        fields.complex(CaseData::getReferralCollection, ReferralType.class)
                    .optional(ReferralType::getReferCaseTo)
                    .eventLabel(" ")
                    .optional(ReferralType::getReferralSubject)
                    .eventLabel(" ")
                    .optional(ReferralType::getReferralSubjectSpecify)
                    .eventLabel(" ")
                    .optional(ReferralType::getIsUrgent)
                    .eventLabel(" ")
                    .optional(ReferralType::getReferralNumber)
                    .eventLabel(" ").done();
        fields.optional(CaseData::getReferentEmail)
                    .publish(false);
        fields.readonly(CaseData::getReferralHearingDetails)
                    .fieldShowCondition("referralHearingDetailsLabel=\"dummy\"")
                    .publish(false);
        fields.readonly(CaseData::getReferralHearingDetailsLabel)
                    .publish(false);
        fields.mandatory(CaseData::getReferCaseTo)
                    .publish(false);
        fields.mandatory(CaseData::getIsUrgent)
                    .publish(false);
        fields.mandatory(CaseData::getReferralSubject)
                    .publish(false);
        fields.mandatory(CaseData::getReferralSubjectSpecify)
                    .fieldShowCondition("referralSubject =\"Other\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.mandatory(CaseData::getReferralDetails)
                    .publish(false);
        fields.complex(CaseData::getReferralDocument).done();
        fields.complex(CaseData::getReferralDocument, DocumentType.class)
                    .optional(DocumentType::getUploadedDocument)
                    .eventLabel("Document")
                    .optional(DocumentType::getShortDescription)
                    .eventLabel("Short description of document").done();
        fields.optional(CaseData::getReferralInstruction)
                    .publish(false);
    }
}
