package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code createCaseLink} for case type {@code ET_EnglandWales}.
 */
@Component
public class CreateCaseLink implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_CASE_LINK = "createCaseLink";

    /**
     * Registers event {@code createCaseLink}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CREATE_CASE_LINK)
            .forAllStates()
            .name("Link cases")
            .description("To link related cases")
            .displayOrder(63)
            .showSummary(false)
            .endButtonLabel("Create Case Link")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES)
            .fields();
        fields.page("createCaseLink");
        fields.optional(CaseData::getCaseLinks)
                    .fieldShowCondition("LinkedCasesComponentLauncher = \"DO_NOT_SHOW\"")
                    .retainHiddenValue();
        fields.optionalNoSummary(CaseData::getLinkedCasesComponentLauncher)
                    .displayContextParameter("#ARGUMENT(CREATE,LinkedCases)");
    }
}
