package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code DELETE_DRAFT_CASE} for case type {@code ET_EnglandWales}.
 */
@Component
public class DELETEDRAFTCASE implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DELETE_DRAFT_CASE = "DELETE_DRAFT_CASE";

    /**
     * Registers event {@code DELETE_DRAFT_CASE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(DELETE_DRAFT_CASE)
            .forStateTransition(State.AWAITING_SUBMISSION_TO_HMCTS, State.Delete)
            .name("Delete draft case")
            .description("Delete draft cases as a claimant")
            .displayOrder(1000)
            .showSummary(false)
            .significant()
            .ttlIncrement(0)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.CREATOR);
    }
}
