package uk.gov.hmcts.et.common.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.EnvironmentFlags;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code disposeCase} for case type {@code ET_EnglandWales}.
 */
@Component
public class DisposeCaseNonprod implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DISPOSE_CASE = "disposeCase";

    /**
     * Registers overlay event {@code disposeCase} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(DISPOSE_CASE)
            .forStateTransition(EnumSet.of(State.Accepted, State.Rejected), State.Closed)
            .name("Close Case")
            .displayOrder(40)
            .showSummary()
            .publishToCamunda()
            .significant()
            .ttlIncrement(365)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.optional(CaseData::getAdditionalCaseInfoType)
                    .fieldShowCondition("positionType =\"dummy\"")
                    .publish(false);
        fields.complex(CaseData::getTtl).done()
                    .fieldShowCondition("additionalCaseInfo.additional_live_appeal=\"Yes\" OR additionalCaseInfo.interventionRequired=\"Yes\"");
        fields.readonly(CaseData::getPositionType)
                    .publish(false);
        fields.mandatory(CaseData::getClerkResponsible)
                    .publish(false);
        fields.optional(CaseData::getFileLocation)
                    .publish(false);
        fields.optional(CaseData::getCaseNotes)
                    .publish(false);
        fields.readonly(CaseData::getCurrentPosition)
                    .fieldShowCondition("positionType =\"dummy\"")
                    .publish(false);
    }
}
