package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code downloadDraftEt3} for case type {@code ET_EnglandWales}.
 */
@Component
public class DownloadDraftEt3 implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DOWNLOAD_DRAFT_ET3 = "downloadDraftEt3";

    /**
     * Registers event {@code downloadDraftEt3}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(DOWNLOAD_DRAFT_ET3)
            .forState(State.Accepted)
            .name("Download draft ET3 Form")
            .displayOrder(46)
            .showSummary(false)
            .endButtonLabel("Download draft ET3 form")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.SOLICITORA, UserRole.SOLICITORB, UserRole.SOLICITORC, UserRole.SOLICITORD, UserRole.SOLICITORE, UserRole.SOLICITORF, UserRole.SOLICITORG, UserRole.SOLICITORH, UserRole.SOLICITORI, UserRole.SOLICITORJ)
            .fields();
        fields.page("1");
        fields.readonly(CaseData::getDownloadDraftEt3Label);
        fields.mandatory(CaseData::getSubmitEt3Respondent);
    }
}
