package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage1;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage10;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage11;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage12;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage13;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage14;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage15;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage16;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage17;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage19;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage2;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage3;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage4;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage5;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage6;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage7;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage8;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionTwoPage9;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code et1SectionTwo} for case type {@code ET_EnglandWales}.
 */
@Component
public class Et1SectionTwo implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ET1_SECTION_TWO = "et1SectionTwo";

    /**
     * Registers event {@code et1SectionTwo}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ET1_SECTION_TWO)
            .forState(State.AWAITING_SUBMISSION_TO_HMCTS)
            .name("Employment & Respondent Detail")
            .displayOrder(56)
            .showSummary()
            .endButtonLabel("Save as draft")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .grant(Permission.CRU, UserRole.CLAIMANTSOLICITOR)
            .fields();
        Et1SectionTwoPage1.apply(fields);
        Et1SectionTwoPage2.apply(fields);
        Et1SectionTwoPage3.apply(fields);
        Et1SectionTwoPage4.apply(fields);
        Et1SectionTwoPage5.apply(fields);
        Et1SectionTwoPage6.apply(fields);
        Et1SectionTwoPage7.apply(fields);
        Et1SectionTwoPage8.apply(fields);
        Et1SectionTwoPage9.apply(fields);
        Et1SectionTwoPage10.apply(fields);
        Et1SectionTwoPage11.apply(fields);
        Et1SectionTwoPage12.apply(fields);
        Et1SectionTwoPage13.apply(fields);
        Et1SectionTwoPage14.apply(fields);
        Et1SectionTwoPage15.apply(fields);
        Et1SectionTwoPage16.apply(fields);
        Et1SectionTwoPage17.apply(fields);
        Et1SectionTwoPage19.apply(fields);
    }
}
