package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionOnePage1;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionOnePage2;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionOnePage3;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionOnePage4;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionOnePage5;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionOnePage6;
import uk.gov.hmcts.et.common.ccd.event.page.Et1SectionOnePage7;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code et1SectionOne} for case type {@code ET_EnglandWales}.
 */
@Component
public class Et1SectionOne implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ET1_SECTION_ONE = "et1SectionOne";

    /**
     * Registers event {@code et1SectionOne}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ET1_SECTION_ONE)
            .forState(State.AWAITING_SUBMISSION_TO_HMCTS)
            .name("ET1 - Claimant details")
            .description("Claimant details")
            .displayOrder(55)
            .showSummary()
            .endButtonLabel("Save as draft")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .grant(Permission.CRU, UserRole.CLAIMANTSOLICITOR)
            .fields();
        Et1SectionOnePage1.apply(fields);
        Et1SectionOnePage2.apply(fields);
        Et1SectionOnePage3.apply(fields);
        Et1SectionOnePage4.apply(fields);
        Et1SectionOnePage5.apply(fields);
        Et1SectionOnePage6.apply(fields);
        Et1SectionOnePage7.apply(fields);
    }
}
