package uk.gov.hmcts.et.common.ccd.event;

import java.util.EnumSet;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code fixCaseAPI} for case type {@code ET_EnglandWales}.
 */
@Component
public class FixCaseAPI implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FIX_CASE_API = "fixCaseAPI";

    /**
     * Registers event {@code fixCaseAPI}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(FIX_CASE_API)
            .forStateTransition(EnumSet.allOf(State.class), State.Submitted)
            .name("Fix Case API")
            .displayOrder(1)
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.optional(CaseData::getMultipleFlag);
        fields.optional(CaseData::getEcmCaseType);
        fields.optional(CaseData::getMultipleReference);
        fields.optional(CaseData::getPositionType);
        fields.optional(CaseData::getReasonForCT);
        fields.optional(CaseData::getEthosCaseReference);
        fields.optional(CaseData::getJurCodesCollection);
        fields.optional(CaseData::getPreAcceptCase);
        fields.optional(CaseData::getStateAPI);
        fields.optional(CaseData::getJudgementCollection);
        fields.optional(CaseData::getSendNotificationCollection);
    }
}
