package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code generateEt1Documents} for case type {@code ET_EnglandWales}.
 */
@Component
public class GenerateEt1Documents implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String GENERATE_ET1_DOCUMENTS = "generateEt1Documents";

    /**
     * Registers event {@code generateEt1Documents}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(GENERATE_ET1_DOCUMENTS)
            .forAllStates()
            .name("generateEt1Documents")
            .description("Generate ET1 docs in the background")
            .displayOrder(58)
            .showCondition("caseType = \"dummy\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API);
    }
}
