package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code legalrepDocuments} for case type {@code ET_EnglandWales}.
 */
@Component
public class LegalrepDocuments implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String LEGALREP_DOCUMENTS = "legalrepDocuments";

    /**
     * Registers event {@code legalrepDocuments}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(LEGALREP_DOCUMENTS)
            .forAllStates()
            .name("Case Documents")
            .description("View case documents")
            .displayOrder(42)
            .showCondition("[STATE]!=\"AWAITING_SUBMISSION_TO_HMCTS\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.ET_ACAS_API)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR)
            .fields();
        fields.page("1");
        fields.pageLabel("Case Documents");
        fields.optional(CaseData::getLegalRepDocumentsMarkdown)
                    .fieldShowCondition("legalRepDocumentsMarkdownLabel=\"dummy\"");
        fields.readonly(CaseData::getLegalRepDocumentsMarkdownLabel);
    }
}
