package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.ManageTelephoneNotePage1;
import uk.gov.hmcts.et.common.ccd.event.page.ManageTelephoneNotePage2;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code manageTelephoneNote} for case type {@code ET_EnglandWales}.
 */
@Component
public class ManageTelephoneNote implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_TELEPHONE_NOTE = "manageTelephoneNote";

    /**
     * Registers event {@code manageTelephoneNote}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(MANAGE_TELEPHONE_NOTE)
            .forAllStates()
            .name("Manage Telephone Note")
            .description("Edit or delete telephone note")
            .displayOrder(56)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .fields();
        ManageTelephoneNotePage1.apply(fields);
        ManageTelephoneNotePage2.apply(fields);
    }
}
