package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code manageFlags} for case type {@code ET_EnglandWales}.
 */
@Component
public class ManageFlags implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_FLAGS = "manageFlags";

    /**
     * Registers event {@code manageFlags}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(MANAGE_FLAGS)
            .forAllStates()
            .name("Manage case flags")
            .description("Manage Flags")
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES)
            .fields();
        fields.page("1");
        fields.optional(CaseData::getCaseFlags)
                    .fieldShowCondition("flagLauncher=\"hidden\"")
                    .retainHiddenValue();
        fields.optional(CaseData::getClaimantFlags)
                    .fieldShowCondition("flagLauncher=\"hidden\"")
                    .retainHiddenValue();
        fields.optional(CaseData::getFlagLauncher)
                    .displayContextParameter("#ARGUMENT(UPDATE)");
        fields.optional(CaseData::getRespondentFlags)
                    .fieldShowCondition("flagLauncher=\"hidden\"")
                    .retainHiddenValue();
    }
}
