package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code migrateCaseLinkDetails} for case type {@code ET_EnglandWales}.
 */
@Component
public class MigrateCaseLinkDetails implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MIGRATE_CASE_LINK_DETAILS = "migrateCaseLinkDetails";

    /**
     * Registers event {@code migrateCaseLinkDetails}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(MIGRATE_CASE_LINK_DETAILS)
            .forAllStates()
            .name("Migrate Case Link Details")
            .description("Migrate Transferred Case Link")
            .displayOrder(111)
            .showCondition("managingOffice !=\"Unassigned\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.optional(CaseData::getTransferredCaseLink);
    }
}
