package uk.gov.hmcts.et.common.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.PartyUnavailabilityNonprodPage1;
import uk.gov.hmcts.et.common.ccd.event.page.PartyUnavailabilityNonprodPage2;
import uk.gov.hmcts.et.common.ccd.event.page.PartyUnavailabilityNonprodPage3;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.EnvironmentFlags;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code partyUnavailability} for case type {@code ET_EnglandWales}.
 */
@Component
public class PartyUnavailabilityNonprod implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String PARTY_UNAVAILABILITY = "partyUnavailability";

    /**
     * Registers overlay event {@code partyUnavailability} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(PARTY_UNAVAILABILITY)
            .forStateTransition(EnumSet.of(State.Accepted, State.Rejected), State.Accepted)
            .name("Hearings: Unavailability dates")
            .description("party unavailability date ranges for hearing request")
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE, UserRole.ET_ACAS_API)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .fields();
        PartyUnavailabilityNonprodPage2.apply(fields);
        PartyUnavailabilityNonprodPage1.apply(fields);
        PartyUnavailabilityNonprodPage3.apply(fields);
    }
}
