package uk.gov.hmcts.et.common.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.PrintHearingPage1;
import uk.gov.hmcts.et.common.ccd.event.page.PrintHearingPage2;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code printHearing} for case type {@code ET_EnglandWales}.
 */
@Component
public class PrintHearing implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String PRINT_HEARING = "printHearing";

    /**
     * Registers event {@code printHearing}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(PRINT_HEARING)
            .forStateTransition(EnumSet.of(State.Accepted, State.Rejected), State.Accepted)
            .name("Print Hearing lists")
            .description("Print Hearing documents")
            .displayOrder(25)
            .showCondition("managingOffice !=\"Unassigned\"")
            .showSummary(false)
            .endButtonLabel("Print List")
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        PrintHearingPage1.apply(fields);
        PrintHearingPage2.apply(fields);
    }
}
