package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.PseRespondentViewNotificationPage1;
import uk.gov.hmcts.et.common.ccd.event.page.PseRespondentViewNotificationPage2;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code pseRespondentViewNotification} for case type {@code ET_EnglandWales}.
 */
@Component
public class PseRespondentViewNotification implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String PSE_RESPONDENT_VIEW_NOTIFICATION = "pseRespondentViewNotification";

    /**
     * Registers event {@code pseRespondentViewNotification}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(PSE_RESPONDENT_VIEW_NOTIFICATION)
            .forAllStates()
            .name("Judgment, Order, Notification")
            .description("View a judgment, order or notification")
            .showCondition("caseType=\"dummy\"")
            .showSummary(false)
            .endButtonLabel("Close and return to case details")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.SOLICITORA, UserRole.SOLICITORB, UserRole.SOLICITORC, UserRole.SOLICITORD, UserRole.SOLICITORE, UserRole.SOLICITORF, UserRole.SOLICITORG, UserRole.SOLICITORH, UserRole.SOLICITORI, UserRole.SOLICITORJ)
            .grant(Set.of(Permission.D), UserRole.CLAIMANTSOLICITOR)
            .fields();
        PseRespondentViewNotificationPage1.apply(fields);
        PseRespondentViewNotificationPage2.apply(fields);
    }
}
