package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;
import uk.gov.hmcts.et.common.model.ccd.types.DepositType;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code recordDeposit} for case type {@code ET_EnglandWales}.
 */
@Component
public class RecordDeposit implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RECORD_DEPOSIT = "recordDeposit";

    /**
     * Registers event {@code recordDeposit}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(RECORD_DEPOSIT)
            .forState(State.Accepted)
            .name("Deposit Order")
            .description("Record a Deposit")
            .displayOrder(28)
            .showCondition("managingOffice !=\"Unassigned\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getDepositCollection).done();
        fields.complex(CaseData::getDepositCollection, DepositType.class)
                    .mandatory(DepositType::getDepositAmount)
                    .eventLabel("Deposit amount (£)")
                    .optional(DepositType::getDepositOrderAgainst)
                    .eventLabel("Deposit ordered against")
                    .mandatory(DepositType::getDynamicDepositOrderAgainst)
                    .eventLabel("Deposit ordered against")
                    .optional(DepositType::getDepositRequestedBy)
                    .eventLabel("Deposit requested by")
                    .mandatory(DepositType::getDynamicDepositRequestedBy)
                    .eventLabel("Deposit requested by")
                    .mandatory(DepositType::getDepositCovers)
                    .eventLabel("Deposit covers")
                    .mandatory(DepositType::getDepositOrderSent)
                    .eventLabel("Deposit order sent")
                    .mandatory(DepositType::getDepositDue)
                    .eventLabel("Deposit due")
                    .optional(DepositType::getDepositTimeExt)
                    .eventLabel("Deposit time extension")
                    .mandatory(DepositType::getDepositTimeExtDue)
                    .eventLabel("Deposit time extension due")
                    .optional(DepositType::getDepositReceived)
                    .eventLabel("Deposit received")
                    .mandatory(DepositType::getDepositReceivedDate)
                    .eventLabel("Date deposit received")
                    .optional(DepositType::getDepositRefund)
                    .eventLabel("Deposit refund")
                    .mandatory(DepositType::getDepositAmountRefunded)
                    .eventLabel("Amount Refunded")
                    .mandatory(DepositType::getDepositRefundDate)
                    .eventLabel("Deposit refund date")
                    .optional(DepositType::getDepositRefundedTo)
                    .eventLabel("Deposit refunded to")
                    .optional(DepositType::getDynamicDepositRefundedTo)
                    .eventLabel("Deposit refunded to")
                    .optional(DepositType::getDepositNotes)
                    .eventLabel("Notes")
                    .optional(DepositType::getDepositDoc)
                    .eventLabel("Document Upload").done();
    }
}
