package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code refreshSharedUsers} for case type {@code ET_EnglandWales}.
 */
@Component
public class RefreshSharedUsers implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REFRESH_SHARED_USERS = "refreshSharedUsers";

    /**
     * Registers event {@code refreshSharedUsers}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(REFRESH_SHARED_USERS)
            .forStates(State.Submitted, State.Vetted, State.Accepted, State.Rejected, State.Closed)
            .name("Refresh Shared Users")
            .displayOrder(72)
            .showCondition("managingOffice !=\"Unassigned\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_LEGALREP_SOLICITOR)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API);
    }
}
