package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.EnvironmentFlags;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;
import uk.gov.hmcts.et.common.model.ccd.types.CasePreAcceptType;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code reinstateClosedCase} for case type {@code ET_EnglandWales}.
 */
@Component
public class ReinstateClosedCaseNonprod implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REINSTATE_CLOSED_CASE = "reinstateClosedCase";

    /**
     * Registers overlay event {@code reinstateClosedCase} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(REINSTATE_CLOSED_CASE)
            .forStateTransition(State.Closed, State.Accepted)
            .name("Reinstate Case")
            .displayOrder(41)
            .showSummary(false)
            .significant()
            .ttlIncrement(36524)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.mandatory(CaseData::getPositionType);
        fields.complex(CaseData::getPreAcceptCase)
                    .readonly(CasePreAcceptType::getDateAccepted)
                    .eventLabel("Date Accepted")
                    .readonly(CasePreAcceptType::getDateRejected)
                    .eventLabel("Date Rejected")
                    .readonly(CasePreAcceptType::getRejectReason)
                    .eventLabel("Reason for the rejection").done()
                    .fieldShowCondition("positionType !=\"Case closed\"");
    }
}
