package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code REMOVE_OWN_REP_AS_CLAIMANT} for case type {@code ET_EnglandWales}.
 */
@Component
public class REMOVEOWNREPASCLAIMANT implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REMOVE_OWN_REP_AS_CLAIMANT = "REMOVE_OWN_REP_AS_CLAIMANT";

    /**
     * Registers event {@code REMOVE_OWN_REP_AS_CLAIMANT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(REMOVE_OWN_REP_AS_CLAIMANT)
            .forAllStates()
            .name("REMOVE_OWN_REP_AS_CLAIMANT")
            .description("enables claimant citizen to remove his/her own representative via et-sya-frontend project")
            .displayOrder(6)
            .showCondition("caseType =\"dummy\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.CREATOR);
    }
}
