package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code respondentTseAllApplications} for case type {@code ET_EnglandWales}.
 */
@Component
public class RespondentTseAllApplications implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RESPONDENT_TSE_ALL_APPLICATIONS = "respondentTseAllApplications";

    /**
     * Registers event {@code respondentTseAllApplications}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(RESPONDENT_TSE_ALL_APPLICATIONS)
            .forAllStates()
            .name("All applications")
            .description(" ")
            .displayOrder(55)
            .showCondition("caseType =\"dummy\"")
            .endButtonLabel("Close and return to case details")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.SOLICITORA, UserRole.SOLICITORB, UserRole.SOLICITORC, UserRole.SOLICITORD, UserRole.SOLICITORE, UserRole.SOLICITORF, UserRole.SOLICITORG, UserRole.SOLICITORH, UserRole.SOLICITORI, UserRole.SOLICITORJ)
            .grant(Set.of(Permission.D), UserRole.CLAIMANTSOLICITOR)
            .grant(Set.of(Permission.R), UserRole.ET_ACAS_API)
            .fields();
        fields.page("1");
        fields.pageLabel(" ");
        fields.readonly(CaseData::getResTseAllApplicationsLabel);
        fields.readonly(CaseData::getResTseTableMarkUp)
                    .fieldShowCondition("resTseAllApplicationsLabel=\"dummy\"");
        fields.readonly(CaseData::getResTseTableLabel);
    }
}
