package uk.gov.hmcts.et.common.ccd.event;

import java.util.EnumSet;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code rollbackMigrateCase} for case type {@code ET_EnglandWales}.
 */
@Component
public class RollbackMigrateCase implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ROLLBACK_MIGRATE_CASE = "rollbackMigrateCase";

    /**
     * Registers event {@code rollbackMigrateCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(ROLLBACK_MIGRATE_CASE)
            .forStateTransition(EnumSet.allOf(State.class), State.Delete)
            .name("Rollback Migrate Case")
            .displayOrder(37)
            .showSummary(false)
            .publishToCamunda()
            .significant()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.CASEWORKER_WA_TASK_CONFIGURATION);
    }
}
