package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.DocumentUpload;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code sendNotification} for case type {@code ET_EnglandWales}.
 */
@Component
public class SendNotification implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_NOTIFICATION = "sendNotification";

    /**
     * Registers event {@code sendNotification}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SEND_NOTIFICATION)
            .forAllStates()
            .name("Send a notification")
            .showCondition("caseType=\"dummy\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE, UserRole.CASEWORKER_WA_TASK_CONFIGURATION, UserRole.ET_ACAS_API)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .fields();
        fields.page("1");
        fields.pageLabel("Send a notification");
        fields.readonly(CaseData::getSendNotificationInfo)
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationLetter)
                    .publish(false);
        fields.complex(CaseData::getSendNotificationUploadDocument).done()
                    .fieldShowCondition("sendNotificationLetter=\"Yes\"");
        fields.complex(CaseData::getSendNotificationUploadDocument, DocumentUpload.class)
                    .mandatory(DocumentUpload::getUploadedDocument)
                    .mandatory(DocumentUpload::getShortDescription)
                    .eventLabel("Short description of document").done();
        fields.mandatory(CaseData::getSendNotificationSubject)
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationSelectHearing)
                    .fieldShowCondition("sendNotificationSubject CONTAINS \"Hearing\"")
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationCaseManagement)
                    .fieldShowCondition("sendNotificationSubject CONTAINS \"Case management orders / requests\"")
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationResponseTribunal)
                    .fieldShowCondition("sendNotificationSubject CONTAINS \"Case management orders / requests\" OR sendNotificationSubject CONTAINS \"Employer Contract Claim\"")
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationWhoCaseOrder)
                    .fieldShowCondition("sendNotificationSubject CONTAINS \"Case management orders / requests\" AND sendNotificationCaseManagement=\"Case management order\"")
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationFullName)
                    .fieldShowCondition("sendNotificationSubject CONTAINS \"Case management orders / requests\" AND sendNotificationCaseManagement!=\"\"")
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationSelectParties)
                    .fieldShowCondition("sendNotificationSubject CONTAINS \"Case management orders / requests\" OR sendNotificationSubject CONTAINS \"Employer Contract Claim\" AND sendNotificationResponseTribunal=\"Yes - view document for details\"")
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationTitle)
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationWhoMadeJudgement)
                    .fieldShowCondition("sendNotificationSubject CONTAINS \"Judgment\"")
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationFullName2)
                    .fieldShowCondition("sendNotificationSubject CONTAINS \"Judgment\" AND sendNotificationWhoMadeJudgement!=\"\"")
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationDecision)
                    .fieldShowCondition("sendNotificationSubject CONTAINS \"Judgment\"")
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationEccQuestion)
                    .fieldShowCondition("sendNotificationSubject CONTAINS \"Employer Contract Claim\"")
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationNotify)
                    .publish(false);
        fields.optional(CaseData::getSendNotificationAdditionalInfo)
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationDetails)
                    .fieldShowCondition("sendNotificationDecision=\"Other\" AND sendNotificationSubject CONTAINS \"Judgment\"")
                    .publish(false);
        fields.mandatory(CaseData::getSendNotificationRequestMadeBy)
                    .fieldShowCondition("sendNotificationSubject CONTAINS \"Case management orders / requests\" AND sendNotificationCaseManagement=\"Request\"")
                    .publish(false);
    }
}
