package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code STORE_CLAIMANT_TSE_RESPOND} for case type {@code ET_EnglandWales}.
 */
@Component
public class STORECLAIMANTTSERESPOND implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String STORE_CLAIMANT_TSE_RESPOND = "STORE_CLAIMANT_TSE_RESPOND";

    /**
     * Registers event {@code STORE_CLAIMANT_TSE_RESPOND}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(STORE_CLAIMANT_TSE_RESPOND)
            .forAllStates()
            .name("Store response to application")
            .description("Store a response to an application")
            .showCondition("caseType=\"dummy\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CREATOR);
    }
}
