package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code STORE_RESPONDENT_TSE} for case type {@code ET_EnglandWales}.
 */
@Component
public class STORERESPONDENTTSE implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String STORE_RESPONDENT_TSE = "STORE_RESPONDENT_TSE";

    /**
     * Registers event {@code STORE_RESPONDENT_TSE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(STORE_RESPONDENT_TSE)
            .forAllStates()
            .name("Store respondent application")
            .showCondition("caseType=\"dummy\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.DEFENDANT);
    }
}
