package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.SubmitEt3Page1;
import uk.gov.hmcts.et.common.ccd.event.page.SubmitEt3Page2;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code submitEt3} for case type {@code ET_EnglandWales}.
 */
@Component
public class SubmitEt3 implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SUBMIT_ET3 = "submitEt3";

    /**
     * Registers event {@code submitEt3}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SUBMIT_ET3)
            .forState(State.Accepted)
            .name("Submit ET3 Form")
            .displayOrder(46)
            .showSummary()
            .endButtonLabel("Submit ET3 to Tribunal")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.SOLICITORA, UserRole.SOLICITORB, UserRole.SOLICITORC, UserRole.SOLICITORD, UserRole.SOLICITORE, UserRole.SOLICITORF, UserRole.SOLICITORG, UserRole.SOLICITORH, UserRole.SOLICITORI, UserRole.SOLICITORJ)
            .grant(Set.of(Permission.D), UserRole.CLAIMANTSOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES, UserRole.ET_ACAS_API)
            .fields();
        SubmitEt3Page1.apply(fields);
        SubmitEt3Page2.apply(fields);
    }
}
