package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;
import uk.gov.hmcts.et.common.model.ccd.types.PseResponseType;
import uk.gov.hmcts.et.common.model.ccd.types.SendNotificationType;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code SUBMIT_STORED_PSE_RESPONSE} for case type {@code ET_EnglandWales}.
 */
@Component
public class SUBMITSTOREDPSERESPONSE implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SUBMIT_STORED_PSE_RESPONSE = "SUBMIT_STORED_PSE_RESPONSE";

    /**
     * Registers event {@code SUBMIT_STORED_PSE_RESPONSE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SUBMIT_STORED_PSE_RESPONSE)
            .forAllStates()
            .name("Submit stored pse response")
            .description("Submit stored notification response")
            .showCondition("caseType=\"Dummy\"")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_WA_TASK_CONFIGURATION, UserRole.CREATOR)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getSendNotificationCollection).done();
        fields.complex(CaseData::getSendNotificationCollection, SendNotificationType.class)
                    .optional(SendNotificationType::getSendNotificationResponsesCount)
                    .eventLabel(" ")
                    .optional(SendNotificationType::getRespondCollection)
                    .eventLabel(" ")
                    .complex(SendNotificationType::getRespondCollection, PseResponseType.class)
                    .optional(PseResponseType::getFrom)
                    .eventLabel(" ").done()
                    .complex(SendNotificationType::getRespondCollection, PseResponseType.class)
                    .optional(PseResponseType::getDateTime)
                    .eventLabel(" ").done()
                    .complex(SendNotificationType::getRespondCollection, PseResponseType.class)
                    .optional(PseResponseType::getIsECC)
                    .eventLabel(" ").done().done();
    }
}
