package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code submitEt1Draft} for case type {@code ET_EnglandWales}.
 */
@Component
public class SubmitEt1Draft implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SUBMIT_ET1_DRAFT = "submitEt1Draft";

    /**
     * Registers event {@code submitEt1Draft}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SUBMIT_ET1_DRAFT)
            .forStateTransition(State.AWAITING_SUBMISSION_TO_HMCTS, State.Submitted)
            .name("Submit ET1 Claim")
            .displayOrder(57)
            .showCondition("et1ReppedSectionOne = \"Yes\" AND et1ReppedSectionTwo = \"Yes\" AND et1ReppedSectionThree = \"Yes\"")
            .showSummary(false)
            .endButtonLabel("Submit ET1")
            .publishToCamunda()
            .significant()
            .ttlIncrement(36524)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .grant(Permission.CRU, UserRole.CLAIMANTSOLICITOR)
            .fields();
        fields.page("1");
        fields.readonly(CaseData::getSubmitEt1Preamble)
                    .publish(false);
        fields.mandatory(CaseData::getSubmitEt1Confirmation)
                    .publish(false);
    }
}
