package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.TseAdminCloseAnApplicationPage1;
import uk.gov.hmcts.et.common.ccd.event.page.TseAdminCloseAnApplicationPage2;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code tseAdminCloseAnApplication} for case type {@code ET_EnglandWales}.
 */
@Component
public class TseAdminCloseAnApplication implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String TSE_ADMIN_CLOSE_AN_APPLICATION = "tseAdminCloseAnApplication";

    /**
     * Registers event {@code tseAdminCloseAnApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(TSE_ADMIN_CLOSE_AN_APPLICATION)
            .forAllStates()
            .name("Close an application")
            .showCondition("caseType=\"dummy\"")
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE, UserRole.ET_ACAS_API)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .fields();
        TseAdminCloseAnApplicationPage1.apply(fields);
        TseAdminCloseAnApplicationPage2.apply(fields);
    }
}
