package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.TseAdminPage1;
import uk.gov.hmcts.et.common.ccd.event.page.TseAdminPage2;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code tseAdmin} for case type {@code ET_EnglandWales}.
 */
@Component
public class TseAdmin implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String TSE_ADMIN = "tseAdmin";

    /**
     * Registers event {@code tseAdmin}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(TSE_ADMIN)
            .forAllStates()
            .name("Record a decision")
            .displayOrder(63)
            .showCondition("caseType=\"dummy\"")
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE, UserRole.ET_ACAS_API)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .fields();
        TseAdminPage1.apply(fields);
        TseAdminPage2.apply(fields);
    }
}
