package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.TseClaimantRepResponsePage1;
import uk.gov.hmcts.et.common.ccd.event.page.TseClaimantRepResponsePage2;
import uk.gov.hmcts.et.common.ccd.event.page.TseClaimantRepResponsePage3;
import uk.gov.hmcts.et.common.ccd.event.page.TseClaimantRepResponsePage4;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code tseClaimantRepResponse} for case type {@code ET_EnglandWales}.
 */
@Component
public class TseClaimantRepResponse implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String TSE_CLAIMANT_REP_RESPONSE = "tseClaimantRepResponse";

    /**
     * Registers event {@code tseClaimantRepResponse}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(TSE_CLAIMANT_REP_RESPONSE)
            .forAllStates()
            .name("Respond to an application")
            .displayOrder(62)
            .showCondition("caseType=\"dummy\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CLAIMANTSOLICITOR)
            .grant(Permission.CRU, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .fields();
        TseClaimantRepResponsePage2.apply(fields);
        TseClaimantRepResponsePage1.apply(fields);
        TseClaimantRepResponsePage3.apply(fields);
        TseClaimantRepResponsePage4.apply(fields);
    }
}
