package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.TseRespondPage1;
import uk.gov.hmcts.et.common.ccd.event.page.TseRespondPage2;
import uk.gov.hmcts.et.common.ccd.event.page.TseRespondPage3;
import uk.gov.hmcts.et.common.ccd.event.page.TseRespondPage4;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code tseRespond} for case type {@code ET_EnglandWales}.
 */
@Component
public class TseRespond implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String TSE_RESPOND = "tseRespond";

    /**
     * Registers event {@code tseRespond}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(TSE_RESPOND)
            .forAllStates()
            .name("Respond to an application")
            .displayOrder(62)
            .showCondition("caseType=\"dummy\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.CASEWORKER_WA_TASK_CONFIGURATION, UserRole.SOLICITORA, UserRole.SOLICITORB, UserRole.SOLICITORC, UserRole.SOLICITORD, UserRole.SOLICITORE, UserRole.SOLICITORF, UserRole.SOLICITORG, UserRole.SOLICITORH, UserRole.SOLICITORI, UserRole.SOLICITORJ)
            .grant(Set.of(Permission.D), UserRole.CLAIMANTSOLICITOR)
            .fields();
        TseRespondPage2.apply(fields);
        TseRespondPage1.apply(fields);
        TseRespondPage3.apply(fields);
        TseRespondPage4.apply(fields);
    }
}
