package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code UPDATE_CASE_SUBMITTED} for case type {@code ET_EnglandWales}.
 */
@Component
public class UPDATECASESUBMITTED implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPDATE_CASE_SUBMITTED = "UPDATE_CASE_SUBMITTED";

    /**
     * Registers event {@code UPDATE_CASE_SUBMITTED}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPDATE_CASE_SUBMITTED)
            .forAllStates()
            .name("UPDATE_CASE_SUBMITTED")
            .description("Update a submitted case")
            .displayOrder(5)
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.CITIZEN)
            .fields();
        fields.page("1");
        fields.mandatory(CaseData::getHubLinksStatuses);
        fields.mandatory(CaseData::getEt1OnlineSubmission);
    }
}
