package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.UPDATECASEDRAFTPage1;
import uk.gov.hmcts.et.common.ccd.event.page.UPDATECASEDRAFTPage10;
import uk.gov.hmcts.et.common.ccd.event.page.UPDATECASEDRAFTPage2;
import uk.gov.hmcts.et.common.ccd.event.page.UPDATECASEDRAFTPage3;
import uk.gov.hmcts.et.common.ccd.event.page.UPDATECASEDRAFTPage4;
import uk.gov.hmcts.et.common.ccd.event.page.UPDATECASEDRAFTPage5;
import uk.gov.hmcts.et.common.ccd.event.page.UPDATECASEDRAFTPage6;
import uk.gov.hmcts.et.common.ccd.event.page.UPDATECASEDRAFTPage7;
import uk.gov.hmcts.et.common.ccd.event.page.UPDATECASEDRAFTPage8;
import uk.gov.hmcts.et.common.ccd.event.page.UPDATECASEDRAFTPage9;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code UPDATE_CASE_DRAFT} for case type {@code ET_EnglandWales}.
 */
@Component
public class UPDATECASEDRAFT implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPDATE_CASE_DRAFT = "UPDATE_CASE_DRAFT";

    /**
     * Registers event {@code UPDATE_CASE_DRAFT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPDATE_CASE_DRAFT)
            .forState(State.AWAITING_SUBMISSION_TO_HMCTS)
            .name("Update Draft Case")
            .description("Maintain this state till case submission")
            .displayOrder(4)
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.CREATOR)
            .fields();
        UPDATECASEDRAFTPage1.apply(fields);
        UPDATECASEDRAFTPage2.apply(fields);
        UPDATECASEDRAFTPage3.apply(fields);
        UPDATECASEDRAFTPage4.apply(fields);
        UPDATECASEDRAFTPage5.apply(fields);
        UPDATECASEDRAFTPage6.apply(fields);
        UPDATECASEDRAFTPage7.apply(fields);
        UPDATECASEDRAFTPage8.apply(fields);
        UPDATECASEDRAFTPage9.apply(fields);
        UPDATECASEDRAFTPage10.apply(fields);
    }
}
