package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.PseRespondCollection;
import uk.gov.hmcts.et.common.model.ccd.SendNotificationCollection;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code UPDATE_NOTIFICATION_RESPONSE} for case type {@code ET_EnglandWales}.
 */
@Component
public class UPDATENOTIFICATIONRESPONSE implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPDATE_NOTIFICATION_RESPONSE = "UPDATE_NOTIFICATION_RESPONSE";

    /**
     * Registers event {@code UPDATE_NOTIFICATION_RESPONSE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPDATE_NOTIFICATION_RESPONSE)
            .forAllStates()
            .name("UPDATE_NOTIFICATION_RESPONSE")
            .description("")
            .displayOrder(9001)
            .showCondition("caseType=\"Dummy\"")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .grant(Permission.CRU, UserRole.CITIZEN)
            .fields();
        fields.page("1");
        fields.optionalNoSummary(CaseData::getNextListedDate);
        fields.complex(CaseData::getSendNotificationCollection).done();
        fields.complex(CaseData::getSendNotificationCollection, SendNotificationCollection.class)
                    .optional(SendNotificationCollection::getSendNotificationResponsesCount)
                    .eventLabel(" ")
                    .optional(SendNotificationCollection::getRespondCollection)
                    .eventLabel(" ")
                    .complex(SendNotificationCollection::getRespondCollection, PseRespondCollection.class)
                    .optional(PseRespondCollection::getFrom)
                    .eventLabel(" ").done()
                    .complex(SendNotificationCollection::getRespondCollection, PseRespondCollection.class)
                    .optional(PseRespondCollection::getDateTime)
                    .eventLabel(" ").done()
                    .complex(SendNotificationCollection::getRespondCollection, PseRespondCollection.class)
                    .optional(PseRespondCollection::getIsECC)
                    .eventLabel(" ").done().done();
    }
}
