package uk.gov.hmcts.et.common.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code UPDATE_APPLICATION_STATE} for case type {@code ET_EnglandWales}.
 */
@Component
public class UPDATEAPPLICATIONSTATE implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPDATE_APPLICATION_STATE = "UPDATE_APPLICATION_STATE";

    /**
     * Registers event {@code UPDATE_APPLICATION_STATE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(UPDATE_APPLICATION_STATE)
            .forAllStates()
            .name("View an application")
            .displayOrder(59)
            .showCondition("caseType=\"dummy\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CITIZEN);
    }
}
