package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.DocumentUpload;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code uploadDocument} for case type {@code ET_EnglandWales}.
 */
@Component
public class UploadDocument implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPLOAD_DOCUMENT = "uploadDocument";

    /**
     * Registers event {@code uploadDocument}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPLOAD_DOCUMENT)
            .forStates(State.Submitted, State.Vetted, State.Accepted, State.Rejected, State.Closed)
            .name("Upload Document")
            .description("Upload a Document")
            .displayOrder(29)
            .showCondition("managingOffice !=\"Unassigned\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_EMPLOYMENT, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_EMPLOYMENT_ENGLANDWALES, UserRole.CASEWORKER_EMPLOYMENT_ETJUDGE_ENGLANDWALES)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getDocumentCollection).done();
        fields.complex(CaseData::getDocumentCollection, DocumentUpload.class)
                    .optional(DocumentUpload::getExcludeFromDcf)
                    .eventLabel("Do you want to exclude this document from the DCF?")
                    .mandatory(DocumentUpload::getTopLevelDocuments)
                    .eventLabel("Document Category")
                    .mandatory(DocumentUpload::getStartingClaimDocuments)
                    .eventLabel("Starting a Claim")
                    .mandatory(DocumentUpload::getResponseClaimDocuments)
                    .eventLabel("Response to a Claim")
                    .mandatory(DocumentUpload::getInitialConsiderationDocuments)
                    .eventLabel("Initial Consideration")
                    .mandatory(DocumentUpload::getCaseManagementDocuments)
                    .eventLabel("Case Management")
                    .mandatory(DocumentUpload::getEccDocuments)
                    .eventLabel("Employer Contract Claim")
                    .mandatory(DocumentUpload::getWithdrawalSettledDocuments)
                    .eventLabel("Withdrawal/Settled")
                    .mandatory(DocumentUpload::getHearingsDocuments)
                    .eventLabel("Hearings")
                    .mandatory(DocumentUpload::getJudgmentAndReasonsDocuments)
                    .eventLabel("Judgment and Reasons")
                    .mandatory(DocumentUpload::getReconsiderationDocuments)
                    .eventLabel("Reconsideration")
                    .mandatory(DocumentUpload::getMiscDocuments)
                    .eventLabel("Misc")
                    .mandatory(DocumentUpload::getTypeOfDocument)
                    .eventLabel("Type of Document")
                    .mandatory(DocumentUpload::getUploadedDocument)
                    .eventLabel("Document")
                    .optional(DocumentUpload::getShortDescription)
                    .eventLabel("Short Description")
                    .optional(DocumentUpload::getDateOfCorrespondence)
                    .eventLabel("Date of Correspondence").done();
    }
}
