package uk.gov.hmcts.et.common.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.ccd.event.page.ViewClaimantTSEApplicationsPage1;
import uk.gov.hmcts.et.common.ccd.event.page.ViewClaimantTSEApplicationsPage2;
import uk.gov.hmcts.et.common.ccd.event.page.ViewClaimantTSEApplicationsPage3;
import uk.gov.hmcts.et.common.model.ccd.CaseData;
import uk.gov.hmcts.et.common.model.ccd.State;
import uk.gov.hmcts.et.common.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from ET_EnglandWales on migration; owned by this service team.
 *
 * <p>Event {@code viewClaimantTSEApplications} for case type {@code ET_EnglandWales}.
 */
@Component
public class ViewClaimantTSEApplications implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String VIEW_CLAIMANT_TSEAPPLICATIONS = "viewClaimantTSEApplications";

    /**
     * Registers event {@code viewClaimantTSEApplications}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(VIEW_CLAIMANT_TSEAPPLICATIONS)
            .forAllStates()
            .name("View application")
            .description(" ")
            .displayOrder(56)
            .showCondition("caseType=\"dummy\"")
            .endButtonLabel("Close and return to case details")
            .explicitGrants()
            .grant(Set.of(Permission.D), UserRole.SOLICITORA, UserRole.SOLICITORB, UserRole.SOLICITORC, UserRole.SOLICITORD, UserRole.SOLICITORE, UserRole.SOLICITORF, UserRole.SOLICITORG, UserRole.SOLICITORH, UserRole.SOLICITORI, UserRole.SOLICITORJ)
            .grant(Permission.CRUD, UserRole.CASEWORKER_EMPLOYMENT_API, UserRole.CLAIMANTSOLICITOR)
            .fields();
        ViewClaimantTSEApplicationsPage1.apply(fields);
        ViewClaimantTSEApplicationsPage2.apply(fields);
        ViewClaimantTSEApplicationsPage3.apply(fields);
    }
}
