package uk.gov.hmcts.ethos.replacement.docmosis.ccd;

import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.Field;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;

public abstract class Et1ReppedSectionsConfig<T extends CaseData> implements CCDConfig<T, EtState, EtUserRole> {

    private static final String PAGE_COLUMN_NUMBER = "PageColumnNumber";
    private static final String PAGE_DISPLAY_ORDER = "PageDisplayOrder";
    private static final String PAGE_FIELD_DISPLAY_ORDER = "PageFieldDisplayOrder";
    private static final String PAGE_LABEL = "PageLabel";

    private final boolean includeLanguageFields;

    protected Et1ReppedSectionsConfig(boolean includeLanguageFields) {
        this.includeLanguageFields = includeLanguageFields;
    }

    @Override
    public void configure(ConfigBuilder<T, EtState, EtUserRole> configBuilder) {
        et1SectionOneFields(et1SectionEvent(
            configBuilder,
            "et1SectionOne",
            "ET1 - Claimant details",
            "Claimant details",
            55
        ));
        et1SectionTwoFields(et1SectionEvent(
            configBuilder,
            "et1SectionTwo",
            "Employment & Respondent Detail",
            "Employment & Respondent Detail",
            56
        ));
        et1SectionThreeFields(et1SectionEvent(configBuilder, "et1SectionThree", "Claim Details", "Claim Details", 57));
    }

    private Event.EventBuilder<T, EtUserRole, EtState> et1SectionEvent(
        ConfigBuilder<T, EtState, EtUserRole> configBuilder,
        String eventId,
        String name,
        String description,
        int displayOrder
    ) {
        return configBuilder.event(eventId)
            .forStateTransition(
                EtState.AWAITING_SUBMISSION_TO_HMCTS,
                EtState.AWAITING_SUBMISSION_TO_HMCTS
            )
            .name(name)
            .description(description)
            .displayOrder(displayOrder)
            .showSummary()
            .aboutToSubmitCallbackUrl("${ET_COS_URL}/et1Repped/aboutToSubmitSection")
            .submittedCallbackUrl("${ET_COS_URL}/et1Repped/sectionCompleted")
            .endButtonLabel("Save as draft")
            .grant(Permission.CRUD, EtUserRole.CASEWORKER_EMPLOYMENT_API)
            .grant(Permission.CRU, EtUserRole.CLAIMANT_SOLICITOR);
    }

    private Event.EventBuilder<T, EtUserRole, EtState> et1SectionOneFields(
        Event.EventBuilder<T, EtUserRole, EtState> event
    ) {
        var fields = event.fields()
            .page("1")
            .pageLabel("Make a claim to an employment tribunal")
            .field("et1Section1PreambleLabel")
            .readOnly()
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("2")
            .pageLabel("Claimant details")
            .field(CaseData::getClaimantFirstName)
            .mandatory()
            .showSummary()
            .caseEventColumn(PAGE_COLUMN_NUMBER, 1)
            .done()
            .field(CaseData::getClaimantLastName)
            .mandatory()
            .showSummary()
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, 1)
            .done()
            .field(CaseData::getClaimantDateOfBirth)
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, 1)
            .done()
            .page("3")
            .pageLabel("Claimant details")
            .field(CaseData::getClaimantSex)
            .optional()
            .showSummary()
            .caseEventColumn("CallBackURLMidEvent", "${ET_COS_URL}/et1Repped/sectionOne/validateClaimantSex")
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getClaimantPreferredTitle)
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("4")
            .pageLabel("Claimant contact address")
            .field(CaseData::getClaimantContactAddress)
            .mandatory()
            .showSummary()
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("5")
            .pageLabel("Hearing format")
            .field("hearingFormatPreamble")
            .readOnly()
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getRepresentativeAttendHearing)
            .optional()
            .showSummary()
            .caseEventColumn(
                "CallBackURLMidEvent",
                "${ET_COS_URL}/et1Repped/sectionOne/validateHearingPreferences"
            )
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done();

        if (includeLanguageFields) {
            fields
                .field(CaseData::getHearingContactLanguage)
                .optional()
                .showSummary()
                .caseEventColumn(PAGE_LABEL, null)
                .caseEventColumn(PAGE_COLUMN_NUMBER, null)
                .done();
        }

        fields
            .field(CaseData::getClaimantAttendHearing)
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done();

        if (includeLanguageFields) {
            fields
                .field(CaseData::getClaimantHearingContactLanguage)
                .optional()
                .showSummary()
                .caseEventColumn(PAGE_LABEL, null)
                .caseEventColumn(PAGE_COLUMN_NUMBER, null)
                .done();
        }

        fields
            .page("6")
            .pageLabel("In the claimant party - are you aware of any physical, mental or learning disability or health "
                           + "condition which requires support?")
            .field(CaseData::getClaimantSupportQuestion)
            .optional()
            .showSummary()
            .caseEventColumn(
                "CallBackURLMidEvent",
                "${ET_COS_URL}/et1Repped/sectionOne/validateClaimantSupport"
            )
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getClaimantSupportQuestionReason)
            .optional()
            .showCondition("claimantSupportQuestion CONTAINS \"Yes\"")
            .showSummary()
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("7")
            .pageLabel("Your information (as the representative)")
            .field("representativeInformationPreamble")
            .readOnly()
            .caseEventColumn(
                "CallBackURLMidEvent",
                "${ET_COS_URL}/et1Repped/sectionOne/validateRepresentativeInformation"
            )
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getRepresentativeContactPreference)
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getContactPreferencePostReason)
            .optional()
            .showCondition("representativeContactPreference CONTAINS \"Post\"")
            .showSummary()
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done();

        if (includeLanguageFields) {
            fields
                .field(CaseData::getContactLanguageQuestion)
                .optional()
                .showSummary()
                .caseEventColumn(PAGE_LABEL, null)
                .caseEventColumn(PAGE_COLUMN_NUMBER, null)
                .done();
        }

        return fields
            .field(CaseData::getRepresentativeAddress)
            .optional()
            .showSummary()
            .caseEventColumn("PageFieldDisplayOrder", 5)
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getRepresentativePhoneNumber)
            .optional()
            .showSummary()
            .caseEventColumn("PageFieldDisplayOrder", 6)
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getRepresentativeReferenceNumber)
            .optional()
            .showSummary()
            .caseEventColumn("PageFieldDisplayOrder", 7)
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .done();
    }

    private Event.EventBuilder<T, EtUserRole, EtState> et1SectionTwoFields(
        Event.EventBuilder<T, EtUserRole, EtState> event
    ) {
        var fields = event.fields();

        return ordered(fields.page("1").field("et1Section2PreambleLabel").readOnly(), 1, 1)
            .caseEventColumn(PAGE_LABEL, "Section 2 - Employment and respondent details")
            .done()
            .page("2")
            .field("didClaimantWorkForOrg")
            .optional()
            .showSummary()
            .caseEventColumn("CallBackURLMidEvent", "${ET_COS_URL}/et1Repped/sectionTwo/validateClaimantWorked")
            .caseEventColumn(PAGE_LABEL, "Did the claimant work for the respondent the claim is being made against? "
                                 + "(Optional)")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("3")
            .field("claimantStillWorking")
            .optional()
            .showSummary()
            .caseEventColumn("PageShowCondition", "didClaimantWorkForOrg CONTAINS \"Yes\"")
            .caseEventColumn("CallBackURLMidEvent", "${ET_COS_URL}/et1Repped/sectionTwo/validateClaimantWorking")
            .caseEventColumn(PAGE_LABEL, "Is the claimant still working for the respondent the claim is being made "
                                 + "against? (Optional)")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("4")
            .field("claimantJobTitle")
            .optional()
            .showSummary()
            .caseEventColumn("PageShowCondition", "didClaimantWorkForOrg CONTAINS \"Yes\"")
            .caseEventColumn(PAGE_LABEL, "Claimant employment details")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantStartDate")
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantEndDate")
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("5")
            .field("claimantStillWorkingNoticePeriod")
            .optional()
            .showSummary()
            .caseEventColumn("PageShowCondition", "claimantStillWorking CONTAINS \"Working\"")
            .caseEventColumn(
                "CallBackURLMidEvent",
                "${ET_COS_URL}/et1Repped/sectionTwo/validateClaimantWrittenNoticePeriod"
            )
            .caseEventColumn(PAGE_LABEL, "Does the claimant have a written contract with \r\na notice period? "
                                 + "(Optional)")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 5)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantStillWorkingNoticePeriodMonths")
            .optional()
            .showSummary()
            .showCondition("claimantStillWorkingNoticePeriod CONTAINS \"Months\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 5)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantStillWorkingNoticePeriodWeeks")
            .optional()
            .showSummary()
            .showCondition("claimantStillWorkingNoticePeriod CONTAINS \"Weeks\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 5)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("6")
            .field("claimantWorkingNoticePeriod")
            .optional()
            .showSummary()
            .caseEventColumn("PageShowCondition", "claimantStillWorking CONTAINS \"Notice\"")
            .caseEventColumn(
                "CallBackURLMidEvent",
                "${ET_COS_URL}/et1Repped/sectionTwo/validateClaimantWorkingNoticePeriod"
            )
            .caseEventColumn(PAGE_LABEL, "Is the notice period in months or weeks? (Optional)")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 6)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantWorkingNoticePeriodMonths")
            .optional()
            .showSummary()
            .showCondition("claimantWorkingNoticePeriod CONTAINS \"Months\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 6)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantWorkingNoticePeriodWeeks")
            .optional()
            .showSummary()
            .showCondition("claimantWorkingNoticePeriod CONTAINS \"Weeks\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 6)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantWorkingNoticePeriodEndDate")
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 6)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("7")
            .field("claimantNoLongerWorkingQuestion")
            .optional()
            .showSummary()
            .caseEventColumn("PageShowCondition", "claimantStillWorking CONTAINS \"No longer working\"")
            .caseEventColumn(
                "CallBackURLMidEvent",
                "${ET_COS_URL}/et1Repped/sectionTwo/validateClaimantNoLongerWorking"
            )
            .caseEventColumn(PAGE_LABEL, "Did the claimant work or get paid for a notice period? (Optional)")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 7)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantNoLongerWorking")
            .optional()
            .showSummary()
            .showCondition("claimantNoLongerWorkingQuestion CONTAINS \"Worked\" "
                               + "OR claimantNoLongerWorkingQuestion CONTAINS \"Paid\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 7)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantNoLongerWorkingMonths")
            .optional()
            .showSummary()
            .showCondition("claimantNoLongerWorking CONTAINS \"Months\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 7)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantNoLongerWorkingWeeks")
            .optional()
            .showSummary()
            .showCondition("claimantNoLongerWorking CONTAINS \"Weeks\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 7)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("8")
            .field("claimantAverageWeeklyWorkHoursPreamble")
            .readOnly()
            .caseEventColumn("PageShowCondition", "didClaimantWorkForOrg CONTAINS \"Yes\"")
            .caseEventColumn(PAGE_LABEL, "Average weekly work hours")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 8)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantAverageWeeklyWorkHours")
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 8)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("9")
            .field("claimantPayPreamble")
            .readOnly()
            .caseEventColumn("PageShowCondition", "didClaimantWorkForOrg CONTAINS \"Yes\"")
            .caseEventColumn("CallBackURLMidEvent", "${ET_COS_URL}/et1Repped/sectionTwo/validateClaimantPay")
            .caseEventColumn(PAGE_LABEL, "Pay details")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 9)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantPayBeforeTax")
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 9)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantPayAfterTax")
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 9)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantPayType")
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 9)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("10")
            .field("claimantPensionContribution")
            .optional()
            .showSummary()
            .caseEventColumn("PageShowCondition", "didClaimantWorkForOrg CONTAINS \"Yes\"")
            .caseEventColumn(
                "CallBackURLMidEvent",
                "${ET_COS_URL}/et1Repped/sectionTwo/validateClaimantPensionBenefits"
            )
            .caseEventColumn(PAGE_LABEL, "Pensions and benefits")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 10)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantWeeklyPension")
            .optional()
            .showSummary()
            .showCondition("claimantPensionContribution CONTAINS \"Yes\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 10)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantEmployeeBenefits")
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 10)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantBenefits")
            .optional()
            .showSummary()
            .showCondition("claimantEmployeeBenefits CONTAINS \"Yes\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 10)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("11")
            .field("claimantNewJob")
            .optional()
            .showSummary()
            .caseEventColumn("PageShowCondition", "didClaimantWorkForOrg CONTAINS \"Yes\" "
                                                + "AND claimantStillWorking CONTAINS \"No longer working\"")
            .caseEventColumn("CallBackURLMidEvent", "${ET_COS_URL}/et1Repped/sectionTwo/validateClaimantNewJob")
            .caseEventColumn(PAGE_LABEL, "Claimant new job (Optional)")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 11)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantNewJobStartDate")
            .optional()
            .showSummary()
            .showCondition("claimantNewJob CONTAINS \"Yes\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 11)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("12")
            .field("claimantNewJobPayPreamble")
            .readOnly()
            .caseEventColumn("PageShowCondition", "didClaimantWorkForOrg CONTAINS \"Yes\" "
                                                + "AND claimantStillWorking CONTAINS \"No longer working\" "
                                                + "AND claimantNewJob CONTAINS \"Yes\"")
            .caseEventColumn("CallBackURLMidEvent", "${ET_COS_URL}/et1Repped/sectionTwo/validateClaimantNewJobPay")
            .caseEventColumn(PAGE_LABEL, "New job pay details")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 12)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantNewJobPayBeforeTax")
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 12)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantNewJobPayPeriod")
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 12)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("13")
            .field("respondentNamePreamble")
            .readOnly()
            .caseEventColumn(
                "CallBackURLMidEvent",
                "${ET_COS_URL}/et1Repped/sectionTwo/generateRespondentPreamble"
            )
            .caseEventColumn(PAGE_LABEL, "Respondent Name")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 13)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("respondentType")
            .mandatory()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 13)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("respondentOrganisationName")
            .mandatory()
            .showSummary()
            .showCondition("respondentType = \"Organisation\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 13)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("respondentFirstName")
            .mandatory()
            .showSummary()
            .showCondition("respondentType = \"Individual\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 13)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("respondentLastName")
            .mandatory()
            .showSummary()
            .showCondition("respondentType = \"Individual\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 13)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 5)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("respondentEndLabel")
            .readOnly()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 13)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 6)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("14")
            .field("respondentAddress")
            .mandatory()
            .showSummary()
            .caseEventColumn(
                "CallBackURLMidEvent",
                "${ET_COS_URL}/et1Repped/sectionTwo/generateWorkAddressLabel"
            )
            .caseEventColumn(PAGE_LABEL, "Respondent address")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 14)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("15")
            .field("didClaimantWorkAtSameAddressPreamble")
            .optional()
            .showCondition("didClaimantWorkAtSameAddress = \"dummy\"")
            .caseEventColumn("PageShowCondition", "didClaimantWorkForOrg CONTAINS \"Yes\"")
            .caseEventColumn(PAGE_LABEL, "Claimant work address")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 15)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("didClaimantWorkAtSameAddressPreambleLabel")
            .readOnly()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 15)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("didClaimantWorkAtSameAddress")
            .mandatory()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 15)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("16")
            .field("claimantWorkAddress")
            .showSummary()
            .caseEventColumn("PageShowCondition", "didClaimantWorkAtSameAddress = \"No\"")
            .caseEventColumn(PAGE_LABEL, "What address did the claimant work at? ")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 16)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("17")
            .field("respondentAcasYesNo")
            .mandatory()
            .showSummary()
            .caseEventColumn(PAGE_LABEL, "Acas certificate for the respondent")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 17)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("respondentAcasNumber")
            .mandatory()
            .showSummary()
            .showCondition("respondentAcasYesNo = \"Yes\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 17)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("respondentNoAcasCertificateReason")
            .mandatory()
            .showSummary()
            .showCondition("respondentAcasYesNo = \"No\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 17)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("19")
            .field("addAdditionalRespondentPreamble")
            .optional()
            .showCondition("addAdditionalRespondent = \"dummy\"")
            .caseEventColumn(PAGE_LABEL, "Do you want to add another respondent?")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 19)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("addAdditionalRespondentPreambleLabel")
            .readOnly()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 19)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("addAdditionalRespondent")
            .mandatory()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 19)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("et1ReppedRespondentCollection")
            .mandatory()
            .showSummary()
            .showCondition("addAdditionalRespondent=\"Yes\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 19)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .done();
    }

    private Event.EventBuilder<T, EtUserRole, EtState> et1SectionThreeFields(
        Event.EventBuilder<T, EtUserRole, EtState> event
    ) {
        return event.fields()
            .page("1")
            .field("et1SectionThreePreamble")
            .readOnly()
            .caseEventColumn(PAGE_COLUMN_NUMBER, 1)
            .done()
            .page("2")
            .pageLabel("Details of the claim")
            .field("et1SectionThreeDetailsPreamble")
            .readOnly()
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getEt1SectionThreeDocumentUpload)
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getEt1SectionThreeClaimDetails)
            .optional()
            .showSummary()
            .caseEventColumn("CallBackURLMidEvent", "${ET_COS_URL}/et1Repped/validateGrounds")
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("3")
            .pageLabel("What type of claim is this?")
            .field(CaseData::getEt1SectionThreeTypeOfClaim)
            .mandatory()
            .showSummary()
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getDiscriminationTypesOfClaim)
            .mandatory()
            .showCondition("et1SectionThreeTypeOfClaim CONTAINS \"discrimination\"")
            .showSummary()
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getPayTypesOfClaim)
            .mandatory()
            .showCondition("et1SectionThreeTypeOfClaim CONTAINS \"payRelated\"")
            .showSummary()
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getWhistleblowingYesNo)
            .optional()
            .showCondition("et1SectionThreeTypeOfClaim CONTAINS \"whistleBlowing\"")
            .showSummary()
            .caseEventColumn(
                "CallBackURLMidEvent",
                "${ET_COS_URL}/et1Repped/sectionThree/validateWhistleblowing"
            )
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getWhistleblowingRegulator)
            .mandatory()
            .showCondition("et1SectionThreeTypeOfClaim CONTAINS \"whistleBlowing\" AND whistleblowingYesNo = \"Yes\"")
            .showSummary()
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getOtherTypeOfClaimDetails)
            .mandatory()
            .showCondition("et1SectionThreeTypeOfClaim CONTAINS \"otherTypesOfClaims\"")
            .showSummary()
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("4")
            .pageLabel("What does the claimant want if their claim is successful? (Optional)")
            .field(CaseData::getClaimSuccessful)
            .optional()
            .showSummary()
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getCompensationDetails)
            .optional()
            .showCondition("claimSuccessful CONTAINS \"compensation\"")
            .showSummary()
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getTribunalRecommendationDetails)
            .optional()
            .showCondition("claimSuccessful CONTAINS \"tribunal\"")
            .showSummary()
            .caseEventColumn("PageFieldDisplayOrder", 4)
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("5")
            .pageLabel("Linked cases")
            .field("linkedCasesPreamble")
            .readOnly()
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getLinkedCasesYesNo)
            .optional()
            .showSummary()
            .caseEventColumn(
                "CallBackURLMidEvent",
                "${ET_COS_URL}/et1Repped/sectionThree/validateLinkedCases"
            )
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field(CaseData::getLinkedCasesDetails)
            .optional()
            .showCondition("linkedCasesYesNo CONTAINS \"Yes\"")
            .showSummary()
            .caseEventColumn(PAGE_LABEL, null)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .done();
    }

    private static <F, S, P, G> Field.FieldBuilder<F, S, P, G> ordered(
        Field.FieldBuilder<F, S, P, G> field,
        int pageDisplayOrder,
        int pageFieldDisplayOrder
    ) {
        return field
            .caseEventColumn(PAGE_DISPLAY_ORDER, pageDisplayOrder)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, pageFieldDisplayOrder)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null);
    }
}
