package uk.gov.hmcts.ethos.replacement.docmosis.ccd;

import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.et.common.model.ccd.CaseData;

public abstract class TseResponseConfig<T extends CaseData> implements CCDConfig<T, EtState, EtUserRole> {

    private static final String PAGE_COLUMN_NUMBER = "PageColumnNumber";
    private static final String PAGE_DISPLAY_ORDER = "PageDisplayOrder";
    private static final String PAGE_FIELD_DISPLAY_ORDER = "PageFieldDisplayOrder";
    private static final String PAGE_LABEL = "PageLabel";
    private static final String PUBLISH = "Publish";
    private static final String RETAIN_HIDDEN_VALUE = "RetainHiddenValue";

    @Override
    public void configure(ConfigBuilder<T, EtState, EtUserRole> configBuilder) {
        claimantRepResponseFields(
            configBuilder.event("tseClaimantRepResponse")
                .forAllStates()
                .name("Respond to an application")
                .description("Respond to an application")
                .displayOrder(62)
                .showSummary()
                .showCondition("caseType=\"dummy\"")
                .caseEventColumn(PUBLISH, "Y")
                .aboutToStartCallbackUrl("${ET_COS_URL}/tseClaimantRepResponse/aboutToStart")
                .aboutToSubmitCallbackUrl("${ET_COS_URL}/tseClaimantRepResponse/aboutToSubmit")
                .submittedCallbackUrl("${ET_COS_URL}/tseClaimantRepResponse/submitted")
        )
            .grant(Permission.CRUD, EtUserRole.CLAIMANT_SOLICITOR)
            .grant(Permission.CRU, EtUserRole.CASEWORKER_WA_TASK_CONFIGURATION);
    }

    private Event.EventBuilder<T, EtUserRole, EtState> claimantRepResponseFields(
        Event.EventBuilder<T, EtUserRole, EtState> event
    ) {
        return event.fields()
            .page("2")
            .field("genericTseApplicationCollection")
            .showCondition("claimantRepRespondSelectApplication=\"dummy\"")
            .caseEventColumn("DisplayContext", "COMPLEX")
            .caseEventColumn("ShowSummaryChangeOption", "N")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, 1)
            .done()
            .page("1")
            .field("claimantTseRespNotAvailable")
            .readOnly()
            .showCondition("claimantRepRespondSelectApplication=\"dummy\"")
            .caseEventColumn("CallBackURLMidEvent", "${ET_COS_URL}/tseClaimantRepResponse/showError")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, 1)
            .done()
            .field("tseRespondNotAvailableWarningLabel")
            .readOnly()
            .showSummary()
            .showCondition("claimantTseRespNotAvailable=\"Yes\"")
            .caseEventColumn("PageShowCondition", "claimantTseRespNotAvailable=\"Yes\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, null)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, 1)
            .done()
            .page("2")
            .field("claimantRepRespondSelectApplication")
            .mandatory()
            .showSummary()
            .caseEventColumn("CallBackURLMidEvent", "${ET_COS_URL}/tseClaimantRepResponse/midPopulateReply")
            .caseEventColumn(PAGE_LABEL, "Select an application")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("3")
            .field("claimantRepResponseIntro")
            .readOnly()
            .showSummary()
            .showCondition("claimantRepTseRespIntroLabel=\"dummy\"")
            .caseEventColumn(RETAIN_HIDDEN_VALUE, "No")
            .caseEventColumn("CallBackURLMidEvent", "${ET_COS_URL}/tseClaimantRepResponse/midValidateInput")
            .caseEventColumn(PAGE_LABEL, "Your response")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantRepTseRespIntroLabel")
            .readOnly()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantRepResponseTable")
            .readOnly()
            .showCondition("claimantRepResponseTableLabel=\"dummy\"")
            .caseEventColumn(RETAIN_HIDDEN_VALUE, "No")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantRepResponseTableLabel")
            .readOnly()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("tseResponseConsider")
            .readOnly()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 5)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantRepResToTribunal")
            .readOnly()
            .showCondition("claimantRepResponseTable=\"dummy\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 6)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantRepResponseText")
            .optional()
            .showSummary()
            .showCondition("claimantRepResToTribunal!=\"Yes\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 7)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantRepResToTribunalText")
            .optional()
            .showSummary()
            .showCondition("claimantRepResToTribunal=\"Yes\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 8)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantRepResponseHasSupportingMaterial")
            .mandatory()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 9)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("tseResponseConsiderMaterial")
            .readOnly()
            .showCondition("claimantRepResponseHasSupportingMaterial=\"Yes\"")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 10)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantRepResSupportingMaterial")
            .showSummary()
            .showCondition("claimantRepResponseHasSupportingMaterial=\"Yes\"")
            .caseEventColumn("DisplayContext", "COMPLEX")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 11)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .page("4")
            .field("tseRespondCopyPartyIntro")
            .readOnly()
            .caseEventColumn(PAGE_LABEL, "Copy this correspondence to the other party")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 1)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantRepResponseCopyToOtherParty")
            .mandatory()
            .showSummary()
            .caseEventColumn(PAGE_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 2)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .field("claimantRepResponseCopyNoGiveDetails")
            .mandatory()
            .showSummary()
            .showCondition("claimantRepResponseCopyToOtherParty=\"No\"")
            .caseEventColumn(RETAIN_HIDDEN_VALUE, "Yes")
            .caseEventColumn(PAGE_DISPLAY_ORDER, 4)
            .caseEventColumn(PAGE_FIELD_DISPLAY_ORDER, 3)
            .caseEventColumn(PAGE_COLUMN_NUMBER, null)
            .done()
            .done();
    }
}
