java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    ET_COS_DB_HOST: "{{ .Release.Name }}-postgresql"
    ET_COS_DB_NAME: "{{ .Values.postgresql.auth.database}}"
    ET_COS_DB_USER_NAME: "{{ .Values.postgresql.auth.username}}"
    ET_COS_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    ET_COS_DB_CONN_OPTIONS: ""
    REFERRAL_TEMPLATE_ID: 6ad8c05b-5c0b-4d10-a5e3-f39fdea4647e
    REJECTED_TEMPLATE_ID: 3f932a27-3960-4135-9ef5-5f2b9ec35da0
    ET1SERVING_TEMPLATE_ID: 43477bad-e63f-44a7-a0e5-39e984987044
    ET1SERVING_RESPONDENT_TEMPLATE_ID: bf00082e-2709-472a-b0e8-11e53473741e
    ET3RESPONSE_NOTIFICATION_TRIBUNAL_TEMPLATE_ID: 34e5ed0e-e39d-4ea7-acd7-751a1d7fb467
    ET3NOTIFICATION_TEMPLATE_MYHMCTS_ID: 6983b7cf-a492-46da-8eaf-9751191eb736
    ET3NOTIFICATION_TEMPLATE_CITIZEN_ID: dd211d08-ba0a-4e9e-8502-31b4ed5515e9
    NOC_NOTIFICATION_TEMPLATE_RESPONDENT_ID: a3539d79-65c0-491c-b578-b58cf321f83e
    NOC_NOTIFICATION_TEMPLATE_CLAIMANT_ID: 3d0c5784-0055-4863-9c03-7d37d9b2ad8d
    NOC_NOTIFICATION_TEMPLATE_OLD_REP_ID: fe52b39f-852c-43ca-a42a-b9a27c43b130
    NOC_NOTIFICATION_TEMPLATE_NEW_REP_ID: 8fe52f24-40b2-4986-8f86-4dd1af311cbd
    NOC_NOTIFICATION_TEMPLATE_TRIBUNAL_ID: 1d5efcbd-1971-4ebe-bfe8-72ba36b5abac
    TSE_RESPONDENT_RESPONSE_TEMPLATE_ID: dec79c11-2c02-481d-aed8-6f013667cdf5
    TSE_RESPONDENT_TO_CLAIMANT_TEMPLATE_ID: 5d014e5a-9528-4d02-bd31-8eca98cfba19
    TSE_RESPONDENT_TO_RESPONDENT_TEMPLATE_ID: c0b393f6-daf0-46fc-8995-d5e98149326f
    TSE_ADMIN_RECORD_A_DECISION_CLAIMANT_TEMPLATE_ID: 615827dc-d21b-46ae-8c66-91a635d82504
    TSE_ADMIN_RECORD_A_DECISION_RESPONDENT_TEMPLATE_ID: ca1a1dd2-13c9-435d-b63e-0ca07abe937d
    TSE_ADMIN_REPLY_CLAIMANT_TEMPLATE_ID: 52b14d5d-038e-48c7-8f9c-3f1193660608
    TSE_ADMIN_REPLY_RESPONDENT_TEMPLATE_ID: 46872d50-cb92-4fee-a460-cc35bd836025
    TSE_RESPONDENT_ACKNOWLEDGEMENT_NO_TEMPLATE_ID: d647a4c5-5859-42f6-96a6-30d57c0e98c2
    TSE_RESPONDENT_ACKNOWLEDGEMENT_YES_TEMPLATE_ID: 232f1fbe-3a7f-44cd-926b-bfa192c25ac4
    TSE_RESPONDENT_REPLY_TO_TRIB_TO_TRIB: c2f72be8-541c-4bcc-b213-42557976dc39
    TSE_RESPONDENT_REPLY_TO_TRIB_TO_CLAIMANT: 5d014e5a-9528-4d02-bd31-8eca98cfba19
    TSE_RESPONDENT_REPLY_TO_TRIB_TO_RES_RULE92_YES: f75316e7-29b4-49e1-b04e-02241f69b649
    TSE_RESPONDENT_REPLY_TO_TRIB_TO_RES_RULE92_NO: 376fb37d-d563-42f2-89f0-3165a4777447
    EXUI_CASE_DETAILS_URL: "https://manage-case.preview.platform.hmcts.net/cases/case-details/"
    CITIZEN_CASE_DETAILS_URL: "https://et-sya.preview.platform.hmcts.net/citizen-hub/"

  keyVaults:
    et-cos:
      secrets:
        - name: et-cos-s2s-secret
          alias: ET_COS_S2S_SECRET
        - name: cos-system-user
          alias: ET_COS_SYSTEM_USER
        - name: cos-system-user-password
          alias: ET_COS_SYSTEM_USER_PASSWORD
        - name: idam-client-secret
          alias: IDAM_CLIENT_SECRET
    et:
      secrets:
        - name: create-updates-queue-send-connection-string
          alias: CREATE_UPDATES_QUEUE_SEND_CONNECTION_STRING
        - name: tornado-access-key
          alias: TORNADO_ACCESS_KEY
        - name: gov-notify-api-key
          alias: GOV_NOTIFY_API_KEY
  postgresql:
    enabled: true
