java:
  image: 'hmctspublic.azurecr.io/et/et-cos:latest'
  applicationPort: 8081
  ingressHost: et-cos-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: et
  keyVaults:
    et-cos:
      secrets:
        - name: cos-POSTGRES-PASS
          alias: ET_COS_DB_PASSWORD
        - name: et-cos-s2s-secret
          alias: ET_COS_S2S_SECRET
    et:
      secrets:
        - name: create-updates-queue-send-connection-string
          alias: CREATE_UPDATES_QUEUE_SEND_CONNECTION_STRING
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: tornado-access-key
          alias: TORNADO_ACCESS_KEY
        - name: gov-notify-api-key
          alias: GOV_NOTIFY_API_KEY
  environment:
    SERVER_PORT: 8081
    REFORM_TEAM: et
    REFORM_SERVICE_NAME: et-cos
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
    ET_COS_URL: "http://et-cos-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    TORNADO_URL: "https://docmosis.{{ .Values.global.environment }}.platform.hmcts.net/rs/render"
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    IDAM_API_JWK_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/jwks"
    CCD_DATA_STORE_API_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    DOCUMENT_MANAGEMENT_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    SERVICE_AUTH_PROVIDER_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_GATEWAY_BASE_URL: "https://manage-case.{{ .Values.global.environment }}.platform.hmcts.net"
    MICRO_SERVICE: "et_cos"
    ET_COS_DB_CONN_OPTIONS: ?sslmode=require
    ET_COS_DB_HOST: et-cos-{{ .Values.global.environment }}.postgres.database.azure.com
    ET_COS_DB_NAME: et_cos
    ET_COS_DB_PORT: '5432'
    ET_COS_DB_USER_NAME: et_cos@et-cos-{{ .Values.global.environment }}
    CASE_DOCUMENT_AM_URL: http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SECURE_DOC_STORE_FEATURE: true
    REFERRAL_TEMPLATE_ID: 6ad8c05b-5c0b-4d10-a5e3-f39fdea4647e
    REJECTED_TEMPLATE_ID: 3f932a27-3960-4135-9ef5-5f2b9ec35da0
    ET1SERVING_TEMPLATE_ID: 43477bad-e63f-44a7-a0e5-39e984987044
    ET1SERVING_RESPONDENT_TEMPLATE_ID: bf00082e-2709-472a-b0e8-11e53473741e
    ET3NOTIFICATION_TEMPLATE_MYHMCTS_ID: 6983b7cf-a492-46da-8eaf-9751191eb736
    ET3NOTIFICATION_TEMPLATE_CITIZEN_ID: dd211d08-ba0a-4e9e-8502-31b4ed5515e9
