tags:
  ccd-idam-pr: true

java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    ET_COS_DB_HOST: "{{ .Release.Name }}-postgresql"
    ET_COS_DB_NAME: "{{ .Values.postgresql.auth.database}}"
    ET_COS_DB_USER_NAME: "{{ .Values.postgresql.auth.username}}"
    ET_COS_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    ET_COS_DB_CONN_OPTIONS: ""
    REFERRAL_TEMPLATE_ID: 6ad8c05b-5c0b-4d10-a5e3-f39fdea4647e
    REJECTED_TEMPLATE_ID: 3f932a27-3960-4135-9ef5-5f2b9ec35da0
    ET1SERVING_TEMPLATE_ID: 2d839d00-88f0-4136-a65e-364da046c6f8
    ET3NOTIFICATION_TEMPLATE_ID: 5b801bd7-cfb3-4249-b99d-a3f5af96c253
  keyVaults:
    et-cos:
      secrets:
        - name: et-cos-s2s-secret
          alias: ET_COS_S2S_SECRET
    et:
      secrets:
        - name: create-updates-queue-send-connection-string
          alias: CREATE_UPDATES_QUEUE_SEND_CONNECTION_STRING
        - name: tornado-access-key
          alias: TORNADO_ACCESS_KEY
        - name: gov-notify-api-key
          alias: GOV_NOTIFY_API_KEY
  postgresql:
    enabled: true

et-sya:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    image: hmctspublic.azurecr.io/et/sya:latest # or pr
    releaseNameOverride: ${SERVICE_NAME}-et-sya
    ingressHost: et-sya-${SERVICE_FQDN}
    keyVaults:
      et:
        resourceGroup: et
        secrets:
          - AppInsightsInstrumentationKey
          - idam-secret
          - redis-access-key
          - os-places-token
          - pcq-token-key
    environment:
      IDAM_WEB_URL: https://idam-web-public.aat.platform.hmcts.net/login
      IDAM_API_URL: https://idam-api.aat.platform.hmcts.net/o/token
      REDIS_HOST: et-sya-session-storage-aat.redis.cache.windows.net
      ET_SYA_API_HOST: http://{{ .Release.Name }}-et-sya-api
      PCQ_ENABLED: true

et-sya-api:
  enabled: true
  java:
    imagePullPolicy: Always
    image: hmctspublic.azurecr.io/et/sya-api:latest # or pr
    releaseNameOverride: ${SERVICE_NAME}-et-sya-api
    ingressHost: et-sya-api-${SERVICE_FQDN}
    keyVaults:
      et-sya-api:
        secrets:
          - name: et-sya-api-s2s-secret
            alias: ET_SYA_S2S_SECRET
          - name: Ocp-Apim-Subscription-Key
            alias: ACAS_KEY
      et:
        secrets:
          - AppInsightsInstrumentationKey
          - name: tornado-access-key
            alias: TORNADO_ACCESS_KEY
          - gov-notify-api-key
    environment:
      IDAM_API_BASEURL: https://idam-api.aat.platform.hmcts.net
      IDAM_JWKS_BASEURL: https://idam-api.aat.platform.hmcts.net/o/jwks
      CASE_DATA_STORE_BASEURL: http://{{ .Release.Name }}-ccd-data-store-api
      SERVICE_AUTH_PROVIDER_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      ACAS_URL: https://api-dev-acas-01.azure-api.net/ECCLDev
      MICRO_SERVICE: et_sya_api
      TORNADO_URL: https://docmosis.aat.platform.hmcts.net/rs/render
      CASE_DOCUMENT_AM_URL: http://ccd-case-document-am-api-aat.service.core-compute-aat.internal

ccd:
  ccd:
    definitionImporter:
      enabled: false
    apiGatewayWeb:
      enabled: true
    s2s:
      enabled: false
    elastic:
      enabled: true

  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}

  global:
    idamApiUrl: https://idam-api.aat.platform.hmcts.net
    idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
    dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
    ccdAdminWebIngress: admin-web-${SERVICE_FQDN}
    ccdApiGatewayIngress: gateway-${SERVICE_FQDN}
    postgresUsername: hmcts
    postgresPassword: hmcts
    s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal

  ccd-api-gateway-web:
    nodejs:
      imagePullPolicy: Always
      environment:
        ADDRESS_LOOKUP_TOKEN: ${ADDRESS_LOOKUP_TOKEN}
        IDAM_SERVICE_KEY: ${CCD_API_GATEWAY_S2S_KEY}
        IDAM_OAUTH2_CLIENT_SECRET: ${CCD_API_GATEWAY_OAUTH2_CLIENT_SECRET}
        PROXY_DOCUMENT_MANAGEMENT: http://dm-store-aat.service.core-compute-aat.internal
      ingressHost: gateway-${SERVICE_FQDN}
      ingressIP: ${INGRESS_IP}
      keyVaults: []
  ccd-data-store-api:
    java:
      imagePullPolicy: Always
      environment:
        DATA_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DATA_STORE_IDAM_KEY: ${DATA_STORE_S2S_KEY}
        DATA_STORE_DEFAULT_LOG_LEVEL: info
        DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,ccd_gateway,ccd_data,aac_manage_case_assignment,xui_webapp,ccd_case_document_am_api,divorce_frontend,nfdiv_case_api
        CCD_S2S_AUTHORISED_SERVICES_CASE_USER_ROLES: aac_manage_case_assignment,fpl_case_service,finrem_case_orchestration,iac,divorce_frontend,civil_service,nfdiv_case_api
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOSTS: ${SERVICE_NAME}-es-master:9200
        ELASTIC_SEARCH_DATA_NODES_HOSTS: http://${SERVICE_NAME}-es-master:9200
        CCD_DM_DOMAIN: http://dm-store-aat.service.core-compute-aat.internal
        CCD_DOCUMENT_URL_PATTERN: ^https?://(((?:api-gateway\.preprod\.dm\.reform\.hmcts\.net|dm-store-aat\.service\.core-compute-aat\.internal(?::\d+)?)\/documents\/[A-Za-z0-9-]+(?:\/binary)?)|(em-hrs-api-aat\.service\.core-compute-aat\.internal(?::\d+)?\/hearing-recordings\/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\/segments\/[0-9]))
        IDAM_API_BASE_URL: https://idam-api.aat.platform.hmcts.net
        IDAM_OIDC_URL: https://idam-web-public.aat.platform.hmcts.net
        CASE_DOCUMENT_AM_URL: http://ccd-case-document-am-api-aat.service.core-compute-aat.internal
        IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET: ${IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET}
        IDAM_DATA_STORE_SYSTEM_USER_USERNAME: ${IDAM_DATA_STORE_SYSTEM_USER_USERNAME}
        IDAM_DATA_STORE_SYSTEM_USER_PASSWORD: ${IDAM_DATA_STORE_SYSTEM_USER_PASSWORD}
      keyVaults: []
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}
  am-role-assignment-service:
    java:
      environment:
        CCD_DATA_STORE_URL: http://${SERVICE_NAME}-ccd-data-store-api
        RUN_LD_ON_STARTUP: false
      keyVaults: []

  ccd-definition-store-api:
    java:
      imagePullPolicy: Always
      environment:
        DEFINITION_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DEFINITION_STORE_IDAM_KEY: ${DEFINITION_STORE_S2S_KEY}
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOST: ${SERVICE_NAME}-es-master
      keyVaults: []
      ingressHost: ccd-definition-store-${SERVICE_FQDN}
  ccd-user-profile-api:
    java:
      imagePullPolicy: Always
      enviroment:
        USER_PROFILE_DB_HOST: ${SERVICE_NAME}-postgresql
      keyVaults: []
      ingressHost: ccd-user-profile-api-${SERVICE_FQDN}

  ccd-admin-web:
    nodejs:
      image: hmctspublic.azurecr.io/ccd/admin-web:latest
      ingressHost: admin-web-${SERVICE_FQDN}
      keyVaults: []
      environment:
        USER_PROFILE_DB_HOST: ${SERVICE_NAME}-postgresql
        IDAM_ADMIN_WEB_SERVICE_KEY: ${ADMIN_S2S_KEY}
        IDAM_OAUTH2_AW_CLIENT_SECRET: ${ADMIN_WEB_IDAM_SECRET}
elasticsearch:
  nameOverride: ${SERVICE_NAME}-es
  clusterName: "es"
  imageTag: "7.17.0"
  replicas: 1
  initResources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "25m"
      memory: "512Mi"
  minimumMasterNodes: 1
  antiAffinity: "soft"
  esJavaOpts: "-Xmx512m -Xms512m"
  extraEnvs:
    - name: discovery.type
      value: single-node
    - name: cluster.initial_master_nodes
      value: ""
    - name: action.auto_create_index
      value: .security*,.watches,.triggered_watches,.watcher-history-*,.logstash_dead_letter,.ml*
  persistence:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    path: /
    hosts:
      - es-${SERVICE_FQDN}

  logstash:
    image:
      repository: hmctspublic.azurecr.io/ccd/logstash
      tag: ccd-divorce-logstash-latest
      pullPolicy: Always
    logstashJavaOpts: -Xmx1g -Xms512M
    persistence:
      enabled: false
    volumeMounts:
      - name: pipeline
        mountPath: /usr/share/logstash/files
    elasticsearch:
      host: ${SERVICE_NAME}-es-master
      port: 9200
    configTpl:
      xpack.monitoring.enabled: "false"
      db.url: jdbc:postgresql://${SERVICE_NAME}-postgresql:5432/data-store?ssl=disable&stringtype=unspecified
      db.user: hmcts
      db.pwd: hmcts
      es.data.nodes.url: http://${SERVICE_NAME}-es-master:9200
    livenessProbe:
      initialDelaySeconds: 90


xui-webapp:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-xui-webapp
    image: hmctspublic.azurecr.io/xui/webapp:latest
    ingressHost: xui-${SERVICE_FQDN}
    devcpuRequests: 250m
    devmemoryRequests: 1024Mi
    devmemoryLimits: 1024Mi
    environment:
      SERVICES_CCD_COMPONENT_API: http://{{ .Release.Name }}-ccd-api-gw
      SERVICES_CCD_DATA_STORE_API: http://${SERVICE_NAME}-ccd-data-store-api
      SERVICES_DOCUMENTS_API_V2: http://ccd-case-document-am-api-aat.service.core-compute-aat.internal
      SERVICES_CCD_CASE_ASSIGNMENT_API: http://{{ .Release.Name }}-aac-manage-case-assignment
      JURISDICTIONS: DIVORCE
      FEATURE_REDIS_ENABLED: false
      NODE_OPTIONS: --max-old-space-size=900

idam-pr:
  enabled: true
  releaseNameOverride: ${SERVICE_NAME}-idam-pr