const testConfig = require('../../../config');
const commonConfig = require('../../../data/commonConfig.json');
const { I } = inject();

function verifyCheckYourAnswers() {

    I.waitForText('Additional Information', testConfig.TestTimeToWaitForText);
    I.see('ET1 case vetting');
    I.see('Case Number:');
    I.see('Check your answers');
    I.see('Check the information below carefully.');
    I.see('Contact Details');
    I.see('Can we serve the claim with these contact details?');
    I.see('Yes');
    I.see('General notes');
    I.see('ET1 Vetting can be served for this Customer...');
    I.see('Is there an Acas certificate?');
    I.see('Yes');
    I.see('Possible substantive defects');
    I.see('The tribunal has no jurisdiction to consider - Rule 12(1)(a)');
    I.see('Is in a form which cannot sensibly be responded to or otherwise an abuse of process - Rule 12 (1)(b)');
    I.see('Has neither an EC number nor claims one of the EC exemptions - Rule 12 (1)(c)');
    I.see('States that one of the EC exceptions applies but it might not - Rule 12 (1)(d)');
    I.see('Institutes relevant proceedings and the EC number on the claim form does not match the EC number on the Acas certificate - Rule 12 (1)(da)');
    I.see('Has a different claimant name on the ET1 to the claimant name on the Acas certificate - Rule 12 (1)(e)');
    I.see('Has a different respondent name on the ET1 to the respondent name on the Acas certificate - Rule 12 (1)(f)');
    I.see('The tribunal has no jurisdiction to consider');
    I.see('Rule 121 a - Give Details Text');
    I.see('Is in a form which cannot sensibly be responded to or otherwise an abuse of process');
    I.see('Rule 121 b - Give Details Text');
    I.see('Has neither an EC number nor claims one of the EC exemptions');
    I.see('Rule 121 c - Give Details Text');
    I.see('States that one of the EC exceptions applies but it might not');
    I.see('Rule 121 d - Give Details Text');
    I.see('Institutes relevant proceedings and the EC number on the claim form does not match the EC number on the Acas certificate');
    I.see('Rule 121 da - Give Details Text');
    I.see('Has a different claimant name on the ET1 to the claimant name on the Acas certificate');
    I.see('Rule 121 e - Give Details Text');
    I.see('Has a different respondent name on the ET1 to the respondent name on the Acas certificate');
    I.see('Rule 121 f - Give Details Text');
    I.see('General notes');
    I.see('General Notes for Possible substantive defects');
    I.see('Are these codes correct?');
    I.see('Yes');
    I.see('General Notes');
    I.see('General Notes for Jurisdiction Codes');
    I.see('Is the track allocation correct?');
    I.see('Yes');
    I.see('General Notes');
    I.see('General Notes for Track Allocation');
    I.see('Is this location correct?');
    I.see('Yes');
    I.see('General Notes');
    I.see('General Notes for Tribunal Location');
    I.see('Do you want to suggest a hearing venue?');
    I.see('Yes');
    I.see('Hearing venue selected');
    I.see('Hull');
    I.see('Is the respondent a government agency or a major employer?');
    I.see('Yes');
    I.see('Are reasonable adjustments required?');
    I.see('Yes');
    I.see('Give details');
    I.see('Reasonable adjustments are required');
    I.see('Can the claimant attend a video hearing?');
    I.see('No');
    I.see('Give details');
    I.see('Video Hearing Required');
    I.see('General notes');
    I.see('General Notes for Further Questions....');
    I.see('Possible referral to a judge or legal officer');
    I.see('A claim of interim relief');
    I.see('A statutory appeal');
    I.see('An allegation of commission of sexual offence');
    I.see('Insolvency');
    I.see('Jurisdictions unclear');
    I.see('Length of service');
    I.see('Potentially linked cases in the ECM');
    I.see('Rule 50 issues');
    I.see('Internal Releief - Give Details Notes...');
    I.see('Statutory Appeal - Give Details Notes...');
    I.see('Allegation Commission of Sexual Offence - Give Details Notes...');
    I.see('Insolvency - Give Details Notes...');
    I.see('Jurisdiction Unclear - Give Details Notes...');
    I.see('Length of Service - Give Details Notes...');
    I.see('Potentially Linked Cases - Give Details Notes...');
    I.see('Rule 50 Issues -  Give Details Notes...');
    I.see('Another reason for Judicial Referall -  Give Details Notes...');
    I.see('General Notes for Possible referral to a judge or legal officer');
    I.see('Possible referral to Regional Employment Judge or Vice-President');
    I.see('A claimant covered by vexatious litigant order');
    I.see('A national security issue');
    I.see('A part of national multiple / covered by Presidential case management order');
    I.see('A request for transfer to another ET region');
    I.see('A request for service abroad');
    I.see('A sensitive issue which may attract publicity or need early allocation to a specific judge');
    I.see('Any potential conflict involving judge, non-legal member or HMCTS staff member');
    I.see('Another reason for Regional Employment Judge / Vice-President referral');
    I.see('Another reason for Regional Employment Judge / Vice-President referral');
    I.see('Does the claim include any other factors');
    I.see('The whole or any part of the claim is out of time');
    I.see('The claim is part of a multiple claim');
    I.see('The claim has a potential issue about employment status');
    I.see('The claim has PID jurisdiction and claimant wants it forwarded to relevant regulator - Box 10.1');
    I.see('The claimant prefers a video hearing');
    I.see('The claim has Rule 50 issues');
    I.see('The claim has other relevant factors for judicial referral');
    I.see('Claim out of time - Give Details Notes...');
    I.see('Multiple - Give Details Notes...');
    I.see('Employment Status Issues - Give Details Notes.....');
    I.see('PID Jurisdiction - Give Details Notes...');
    I.see('Video Hearing - Give Details Notes...');
    I.see('Another reason for other - Give Details Notes...');
    I.see('Vetting Additional Information - Give Details Notes...');
    I.click('Submit');

}
module.exports = { verifyCheckYourAnswers };
