module.exports = {
    TestUrl: process.env.TEST_E2E_URL || 'https://manage-case.aat.platform.hmcts.net',
    IdamBaseUrl: process.env.IDAM_URL || 'https://idam-api.aat.platform.hmcts.net',
    RedirectUri: process.env.REDIRECT_URI || `https://manage-case.aat.platform.hmcts.net/oauth2/callback`,
    TestEnv: process.env.RUNNING_ENV || 'aat',
    TestShowBrowserWindow: process.env.SHOW_BROWSER_WINDOW || false,
    TestRetryFeatures: process.env.RETRY_FEATURES || 0,
    TestRetryScenarios: process.env.RETRY_SCENARIOS || 2,
    TestPathToRun: process.env.E2E_TEST_PATH || './paths/**/*.js',
    TestOutputDir: process.env.E2E_OUTPUT_DIR || './functional-output',
    TestTimeToWaitForText: parseInt(process.env.E2E_TEST_TIME_TO_WAIT_FOR_TEXT || 30),
    TestEnvCWUser: process.env.ET_CCD_CASEWORKER_USER_NAME || 'et.caseworker.5@hmcts.net',
    TestEnvCWPassword: process.env.ET_CCD_CASEWORKER_PASSWORD || 'h8$w%vWk',
    TestEnvEtCWUser: process.env.ET_CASEWORKER_USER_NAME || 'et.caseworker.5@hmcts.net',
    TestEnvEtCWPwd: process.env.ET_CASEWORKER_PASSWORD || 'h8$w%vWk',
    TestEnvEtJudgeUser: process.env.ET_JUDGE_4_USER_NAME || 'et.judge.4@hmcts.net',
    TestEnvEtJudgePwd: process.env.ET_JUDGE_4_PASSWORD || 't!Pf%32I',
    TestForXUI: process.env.TESTS_FOR_XUI_SERVICE === 'true',
    TestAutoDelayEnabled: process.env.E2E_AUTO_DELAY_ENABLED === 'true',
    TestForAccessibility: process.env.TESTS_FOR_ACCESSIBILITY === 'true',
    TestForCrossBrowser: process.env.TESTS_FOR_CROSS_BROWSER === 'true',
    TestIdamClientSecret: process.env.IDAM_CLIENT_SECRET || '',
    TestCcdGwSecret: process.env.MICROSERVICE_CCD_GW || '',
    oneTimePassword: process.env.ONE_TIME_PASSWORD || '',
};
